### ISSUE TITLE
[Suggestion] Adding {target_player}

### ISSUE THREAD

**Issue by dotheflopboy** [PluginBugs/Issues-ItemsAdder#1031]
My suggestion is to add {target_player} variables, for example to ban a player when attacking:

```YAML
attack:
  execute_commands:
    cmd1:
      command: 'ban {target_player} reason'
      as_console: true
      delay: 0
```

**Comment by LoneDev6** [comment]
After the update you'll be able to do this:
```yml
    events:
      interact:
        entity:
          execute_commands:
            change_me_1:
              command: tell {target-player} Hello {target-player}, your coords are {target-x} {target-y} {target-z}
              as_console: false
```
