### ISSUE TITLE
[Suggestion] Set different mining speeds for each tool

### ISSUE THREAD

**Issue by qwer2415wy** [PluginBugs/Issues-ItemsAdder#1033]
**I hope can add different mining speeds in itemsadder. Because now only able set one hardness, this will cause every tools break blocks in same time, so I hope can add different hardness for different tools.**

Picture:

![image](https://user-images.githubusercontent.com/70427269/125427213-6c2973ab-3d0e-47d9-ab56-23912b3632f5.png)

**Comment by LoneDev6** [comment]
You may add fast digging effect, this is the best way

```yml
    events:
      held:
        potion_effect:
          type: FAST_DIGGING
          duration: 1000000
          amplifier: 0
      unheld:
        remove_potion_effect:
          type: FAST_DIGGING
```

**Comment by qwer2415wy** [comment]
This will only for one thing? Can you give me for example wooden pickaxe and diamond pickaxe?

**Comment by qwer2415wy** [comment]
If a feature could be added allowing you to decide how long it takes each vanilla tool to break a custom block

**Comment by LoneDev6** [comment]
> 
> 
> This will only for one thing? Can you give me for example wooden pickaxe and diamond pickaxe?

This applies to any item.

If you want to make it mine slower you have to set SLOW_DIGGING potion effect instead of FAST_DIGGING.
It's a potion effect, look in the wiki 
https://minecraft.fandom.com/wiki/Mining_Fatigue
https://minecraft.fandom.com/wiki/Haste

**Comment by qwer2415wy** [comment]
https://youtu.be/BUBErWxsOug

**Comment by qwer2415wy** [comment]
This is my setting
```
bronze_block:
    display_name: 青銅磚
    permission: comet.blocks
    resource:
      material: PAPER
      generate: false
      model_path: blocks/bronze
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
        hardness: 2
```

**Comment by LoneDev6** [comment]
```yml
items:
  diamond_pick_test:
    display_name: Test
    resource:
      material: DIAMOND_PICKAXE
      generate: true
      textures:
        - item/my_custom_diamond_pick.png
    events:
      held:
        potion_effect:
          type: FAST_DIGGING
          duration: 1000000
          amplifier: 2
      unheld:
        remove_potion_effect:
          type: FAST_DIGGING
  wooden_pick_test:
    display_name: Test
    resource:
      material: WOODEN_PICKAXE
      generate: true
      textures:
        - item/my_custom_wooden_pick.png
    events:
      held:
        potion_effect:
          type: SLOW_DIGGING
          duration: 1000000
          amplifier: 2
      unheld:
        remove_potion_effect:
          type: SLOW_DIGGING
```

use the online editor https://ide.devs.beer/itemsadder/
