### ISSUE TITLE
[BUG] Can't place the furniture on ceiling (1.17.1)

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1043]
**Describe the bug**
Here is my furniture's config:
```yml
  grass_herbs:
    display_name: "Grass Herbs"
    resource:
      material: PAPER
      generate: false
      model_path: item/furniture/grass_hherbs
    behaviours:
      furniture:
        opposite_direction: false
        solid: false
        entity: item_frame
        fixed_rotation: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: true
          floor: false
```

so if i set:
```yml
placeable_on:
          walls: true
          ceiling: true
          floor: false
```
i can place furniture on the ceiling but it's can place it on the walls too. i don't want to make it place on the walls. just ceiling

**To Reproduce**
1. Just place the furniture on the ceiling

**Expected behavior**
It's should be can place on the ceiling when `ceiling: true` 😂 

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.4
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0
