### ISSUE TITLE
[BUG] It's look like i can place furniture in same place (1.17.1)

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1044]
**Describe the bug**
A bugs when i'm trying to spam placing furniture in same block location that already have furniture

**To Reproduce**
1. Place `furniture 1`
2. Spam right clicking around `furniture 1` while your hand have some furniture
3. If you hear the sound like placing item frame, that's happening now

**Videos**
https://streamable.com/xmoi8w

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.4
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Context**
My furniture's config i used:
```yml
  barrel_3:
    display_name: "Barrel"
    resource:
      material: PAPER
      generate: false
      model_path: item/furniture/laundry/barrel_3
    behaviours:
      furniture:
        opposite_direction: false
        solid: false
        entity: item_frame
        fixed_rotation: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```
