### ISSUE TITLE
[BUG] Light source on furnitures not working

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#1084]
**Describe the bug**
When i place some furniture with light source, the light source doesn't appear

**To Reproduce**
1. Place a furniture that have some light level in config
2. The furniture spawns without any problems but the light source don't spawn

**Expected behavior**
I don't know what is happening, the needed plugins on my servers are updated to latest versions (ProtocolLib, ItemsAdder, LoneLibs, LightAPI Fork).

**Screenshots**
Exambple dyeable lamp furniture that spawn without light (This bug happens with every furniture):
![2021-08-02_06 57 26](https://user-images.githubusercontent.com/77519944/127843837-60bb739a-30f2-4b9e-a727-0f245a5e9bc3.png)
```
  lampara1:
    display_name: '&fLampara (Pintable)'
    lore:
    - '&7Item tintable'
    permission: decoraciones
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: decoraciones/lampara1
    specific_properties:
      leather_horse_armor:
        color: E1E1E1
    behaviours:
      furniture:
        gravity: false
        small: true
        light_level: 7
        solid: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```

**Info (please complete the following information):**
 - Server version: (Purpur 1.16.5)
 - Client version: (Optifine 1.16.5)

**Special Info**
 - ItemsAdder version: 2.4.6
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Hope we can have a solution for this problem soon, thanks
