### ISSUE TITLE
[BUG] Anvil Repair not working and Menu problem.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1085]
Anvil Repair is not working for anything.

Also there's an issue with Items that do not have recipes, showing empty recipes and items that do have anvil repair set, not showing anvil repair in the ia menu.

Here's an example of how it's setup  https://paste.helpch.at/uqukimaheg.bash

but just like the screenshot below it only shows an empty recipe and no anvil repair in the menu.

**Screenshots**
As you can see here the Cutlass has an empty recipe but no tab for anvil repair, despite having no recipe in it's yml and having anvil repair present in its yml

![2021-08-02](https://user-images.githubusercontent.com/66942713/127851426-aa39a8ab-84f8-47a3-901c-b899a8f02c05.png)

 - Server version: (paper 1.17.1)
 - Client version: (minecraft 1.17.1)

 - ItemsAdder version: (example: 2.4.5)
 - LightAPI Fork version: (example: 3.5.2)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (# 513)
 
I don't use the Ores so no problem with Protocolib

**Comment by LoneDev6** [comment]
## Default itemsadder recipe to repair the ruby sword:
![image](https://user-images.githubusercontent.com/27242001/127865004-d9f00701-7214-4af6-8c3f-dc913ff4a7fa.png)

![image](https://user-images.githubusercontent.com/27242001/127865024-1312a975-ec55-4f45-ad32-b34917855a49.png)

```yml
recipes:
  anvil_repair:
    ruby_sword:
      permission: itemsadder.ruby_sword
      ingredient: itemsadder:ruby
      item: itemsadder:ruby_sword
 ```



-----------------




## A new recipe i created to show that it also works as you wanted

![image](https://user-images.githubusercontent.com/27242001/127865457-ade96a98-2bc4-47f3-bd82-402c40ab5804.png)

![image](https://user-images.githubusercontent.com/27242001/127865494-c6ebd74a-8a2b-45cc-8892-7fdefd295765.png)

```yml
recipes:
  anvil_repair:
    ruby_sword_test_no_bug:
      permission: itemsadder.ruby_sword
      ingredient: itemsadder:ruby_sword
      item: itemsadder:ruby_sword
```

**Comment by LoneDev6** [comment]
I fixed your configuration, it was missing the `recipes` attribute and the permissions.

```yml
info:
  namespace: customitems           
recipes:
  anvil_repair:
    magma_sword:
      permission: magma_sword
      ingredient: EMERALD
      item: customitems:magma_sword   
items:
  magma_sword:
    display_name: '&aMagma Sword'
    permission: magma_sword
    resource:
      material: STONE_SWORD
      generate: true
      model_path: item/weapons/magma_sword
    durability:
      max_custom_durability: 2980
    attribute_modifiers:
      mainhand:
        attackDamage: 8.0
        attackSpeed: 2.0            
```
