### ISSUE TITLE
Chest Commands FORK Problem | Error on console also | open not working |

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1088]
**Describe the bug**
Chest Commands FORK Problem | Error console also |   - "open: biome1" for Example not working 
First I Update Everything on my server to 1.17.1 but the problem is when I update the chest command Fork Last Update 
the `open` not working with me and also there is an error on the console 
https://paste.md-5.net/eyinidibab.css
![image](https://user-images.githubusercontent.com/68678154/128132643-1818efbe-d6a5-40ae-978b-e82a94d63620.png)

it was working fine Before the update I Even tried to put .yml on the end `open: biome1.yml` | but also did not work

```
biome1:
  ACTIONS:
  - "open: biome1"
  NAME: '&aAccept'
  KEEP-OPEN: true
  BLANK: true
  POSITION-X: 2
  POSITION-Y: 5  
```

**Info (please complete the following information):**
 - Server version: (paper 1.17.1)
 - Client version: (1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (v2.4.7)
 - LightAPI Fork version: (LightAPI v3.5.2)
 - LoneLibs version: (LoneLibs v1.0.14)
 - ProtocolLib version: (ProtocolLib v4.7.0)
