### ISSUE TITLE
[BUG] Huds disappear under IA 2.4.8

### ISSUE THREAD

**Issue by fnrcum** [PluginBugs/Issues-ItemsAdder#1095]
**Describe the bug**

The Thirst HUD seems to disappear now under 2.4.8 and only briefly appears when using an item to restore thirst. Also the API has not changed yet calling changes from my plugin seems to not affect the HUD element anymore. 

**To Reproduce**
1. Install 2.4.8
2. Comment out the thirst decrement values in the yaml files (this is just for now currently)
```yaml
triggers:
        decrement:
#          generic_over_time_60_minutes_inside:
#            min_sky_light: 0
#            max_sky_light: 13
#            every_ticks: 72000
#            amount: 0.5
#          generic_over_time_45_minutes_outside:
#            min_sky_light: 14
#            max_sky_light: 15
#            every_ticks: 54000
#            amount: 0.5
#          biome_over_time_desert_30_minutes_outside:
#            min_sky_light: 14
#            max_sky_light: 15
#            biome: DESERT
#            every_ticks: 36000
#            amount: 0.5
#          food_level_change:
#            each_food_level: 1
#            amount: 0.1
```
3. Wait for the thirst hood to vanish
4. Drink a watterskin
5. See how the HUD appears briefly and then slowly fades away

**Expected behavior**
The behaviour should remain as it was before unless there are config and api changes as well meaning the thirst handling externally should not be affected.

**Screenshots**
![93MNaliPSs](https://user-images.githubusercontent.com/10963542/128957534-99047a74-5779-424b-8cbe-f1451e15bc4d.gif)

**Info (please complete the following information):**
 - Server version: (example: paper 1.17.1)
 - Client version: (example: fabric 1.17.1-optifine)

**Special Info**
 - ItemsAdder version: : 2.4.8 beta
 - LightAPI Fork version: latest
 - LoneLibs version: latest released
 - ProtocolLib version: latest release

Extra tid bit of info, this is how I handle the IA thirst myself

```java
public static float changePlayerThirst(Player player, float change, boolean natural) {
        var huds = new PlayerHudsHolderWrapper(player);
        var thirstBar = new PlayerQuantityHudWrapper(huds, "realcraft:thirst_bar");
        float oldValue = thirstBar.getFloatValue();

        // Null check
        if (thirstBar == null) return -1.0f;

        thirstBar.setFloatValue(oldValue + change);

        // Fires an event for external use
        ThirstChangeEvent event = new ThirstChangeEvent(player, change, oldValue, natural);
        Bukkit.getServer().getPluginManager().callEvent(event);

        // If LOG_THIRST_CHANGES is set to true in config, then print out the log message
        if (logThirstChanges)
            getInstance().getLogger().info("Changed thirst level for " + player.getName() + " from " + oldValue + " to " + (oldValue + change));

        return oldValue + change;
    }
```

This should be according to the current api docs

**Comment by LoneDev6** [comment]
The only thing I changed is making the HUD disappear during the resourcepack install and if the resourcepack is not valid.
So I guess this is a bug, I'll take a look, thanks!

**Comment by LoneDev6** [comment]
I can't reproduce the issue following your steps.
I suspect there is another plugin modifying the actionbar.
ItemsAdder will hide the HUDs for a brief time in order to avoid hiding other plugins messages that use the actionbar.
I think that's what's happening as I can clearly see an actionbar message being shown in your video (a part of it since the video is cut).
![image](https://user-images.githubusercontent.com/27242001/129548815-e995deef-540c-4073-8c54-9aa4437e0217.png)


# My test
https://user-images.githubusercontent.com/27242001/129548573-d680126f-8338-466e-8461-1bd9a8f26987.mp4


```yml
info:
  namespace: "realcraft"
huds:
  thirst_bar:
    enabled: true
    show:
      auto: true
      creative: false
      underwater: false
      riding: false
    type: STATUS
    x_position_pixels: 10
    direction: LEFT
    value:
      player_stat_name: "thirst"
      start: 10
      min: 0
      max: 10
      triggers:
        increment:
          food_level_change:
            each_food_level: 1
            amount: 0.1
          player_respawn:
            amount: 10
        on_min_value:
          damage_player:
            #min 20 ticks
            every_ticks: 100
            damage: 0.5
          potion_effect:
            every_ticks: 100
            type: SLOW
            amplifier: 1
            duration: 100
    images:
      positive: "realcraft:thirst_bar_positive"
      half: "realcraft:thirst_bar_half"
      negative: "realcraft:thirst_bar_negative"
```
