### ISSUE TITLE
[Suggestion] special property: icon

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1096]
`icon:` is work with furniture, custom block or tripwire
that make player will see custom texture in inventory. but when player place the stuff, it's will display model instead

Edit 1:
If someone want to do it with furniture
that's mean they need to know that furniture will need 2 items as not same CustomModelData NBT

example:
```yml
resource:
  material: PAPER
  icon: chair_display.png
  model_path: chair
```
