### ISSUE TITLE
[Suggestion] REAL_WIRE expansion

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1110]
**I'm sorry this suggestion isn't by default, but this is easy to explain.**
REAL_WIRE is the perfect type of block for decorations (plants, crystals, and much more) Therefore, I would suggest REAL_WIRE expansion.

REAL_WIRE Expansion in .yml:
[rock.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7000918/rock.txt)

**Comment by LoneDev6** [comment]
Hello, thanks!

this is your suggestion:
```yml
            name: block.grass.break
    behaviours:
      tripwire:
        tall: false #Tall = tripwire would be one block higher
        water: false #Water = If the block were placed on water, the tripwire would be above water
	    thin: true #Thin = tripwire would be automatically attached = true
```

**tall**: can already be implemented just by making the model higher. The only issue is the hitbox will be at the bottom of the block. You can tell me "use two blocks" but I'd refuse since they will occupy 2 slots instead of one, the max slots number is limited to 127, sadly they are not infinite.

**water**: I can implement this in the next update, basically you want to rightclick water surface and place the REAL_WIRE block, right?

**thin**: this is not possible sadly, ItemsAdder uses all the available combinations of blockstates and you can't decide which one to use, to avoid conflicts with other blocks that may want to use the "attached" property


Thanks for your ideas! Keep posting them, I always appreciate new ideas for the plugin

**Comment by TeiBri** [comment]
> Hello, thanks!
> 
> this is your suggestion:
> 
> ```yaml
>     behaviours:
>       tripwire:
>         tall: false #Tall = tripwire would be one block higher
>         water: false #Water = If the block were placed on water, the tripwire would be above water
>         thin: true #Thin = tripwire would be automatically attached = true
> ```
> 
> ✖️**tall**: can already be implemented just by making the model higher. The only issue is the hitbox will be at the bottom of the block. You can tell me "use two blocks" but I'd refuse since they will occupy 2 slots instead of one, the max slots number is limited to 127, sadly they are not infinite.
> 
> ✅**water**: I can implement this in the next update, basically you want to rightclick water surface and place the REAL_WIRE block, right?
> 
> ✖️**thin**: this is not possible sadly, ItemsAdder uses all the available combinations of blockstates and you can't decide which one to use, to avoid conflicts with other blocks that may want to use the "attached" property
> 
> Thanks for your ideas! Keep posting them, I always appreciate new ideas for the plugin

I would add to Tall that it would only take up 1 slot.
![2021-08-17_18 04 34](https://user-images.githubusercontent.com/62265168/129761141-64a4cdfa-dc6f-4c1e-a714-adcf7e90c087.png)

**Comment by TeiBri2** [comment]
> Hello, thanks!
> 
> this is your suggestion:
> 
> ```yaml
>     behaviours:
>       tripwire:
>         tall: false #Tall = tripwire would be one block higher
>         water: false #Water = If the block were placed on water, the tripwire would be above water
>         thin: true #Thin = tripwire would be automatically attached = true
> ```
> 
> ✖️**tall**: can already be implemented just by making the model higher. The only issue is the hitbox will be at the bottom of the block. You can tell me "use two blocks" but I'd refuse since they will occupy 2 slots instead of one, the max slots number is limited to 127, sadly they are not infinite.
> 
> ✅**water**: I can implement this in the next update, basically you want to rightclick water surface and place the REAL_WIRE block, right?
> 
> ✖️**thin**: this is not possible sadly, ItemsAdder uses all the available combinations of blockstates and you can't decide which one to use, to avoid conflicts with other blocks that may want to use the "attached" property
> 
> Thanks for your ideas! Keep posting them, I always appreciate new ideas for the plugin

(It is my second profile TeiBri)
Look. Tall is actually possible now, but 50/50, because it is possible to move the model a block lower, but to place it on the ground so that the tripwire is a block higher is now inpossible. I actually want the "tall = true" function to allow that when I place the REAL_WIRE block so that it is tripwire up 1 block higher, which I think is possible if you've done furniture with a bigger hitbox. It only takes 1 slot as it does now. (by no means 2) Do you understand?

**Comment by LoneDev6** [comment]
I think it's smart to place the real_wire model in midair and make the model shifted down, so that the hitbox will be in the middle and the real_wire plant will use only 1 slot instead of two.
It's a smart idea

**Comment by TeiBri** [comment]
> I think it's smart to place the real_wire model in midair and make the model shifted down, so that the hitbox will be in the middle and the real_wire plant will use only 1 slot instead of two.
> It's a smart idea

Thank you for your praise, but I still don't program it, so it's up to you to add it. Thanks again for your attention. :)

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/129937035-1f137277-b57c-4805-bce9-93c921ce9516.png)

```yml
  dead_tall_grass:
    enabled: true
    display_name: display-name-dead_tall_grass
    resource:
      generate: false
      material: PAPER
      model_path: dead_tall_grass
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          shift_up: true # <---------- THIS
        sound:
          place:
            name: block.grass.place
          break:
            name: block.grass.break
```


https://user-images.githubusercontent.com/27242001/129937322-b15048a5-0855-46fd-a1dc-c9d26925f395.mp4

```yml
items:
  plastic_waste:
    enabled: true
    display_name: display-name-plastic_waste
    resource:
      generate: false
      material: PAPER
      model_path: plastic_waste
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          placeable_on_water: true # <--------- THIS (you can also add placeable_on_lava)
        cancel_drop: true
        sound:
          place:
            name: block.slime_block.place
          break:
            name: block.slime_block.place```
