### ISSUE TITLE
[BUG] Furniture lighting settings do not work

### ISSUE THREAD

**Issue by Miuss** [PluginBugs/Issues-ItemsAdder#1122]
**Describe the bug**
Furniture lighting settings do not work

**To Reproduce**
```yml
  ceiling_lamp:
    display_name: "天花板吊灯"
    resource:
      material: PAPER
      generate: false
      model_path: ceiling_lamp
    behaviours:
      furniture:
        entity: item_frame
        light_level: 12
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: true
          floor: false
```

**Expected behavior**
 furniture set entity: item_frame light_level: 12
There is no light display

**Screenshots**
![image](https://user-images.githubusercontent.com/26337587/130317951-fc4c43f6-fb56-45ab-a2ac-7d23d56b4df6.png)
![image](https://user-images.githubusercontent.com/26337587/130318087-9cb893db-83ff-43f9-a1f8-b3525df3f99a.png)

**Info (please complete the following information):**
 - Server version: (example: Tuinity 1.17.1)
 - Client version: (example: Optifine 1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.10
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.10

**Additional context**
