### ISSUE TITLE
[BUG] Mana Bar/Potion Spam Error

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1129]
I have my Mana Bar set to 5 points

I created a Potion that gives 10 points of Mana. 

I drank 1 potion of 10 point Mana and this Error started Spamming the Console

[06:40:35 WARN]: [ItemsAdder] Task #8531 for ItemsAdder v2.4.7 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6
        at dev.lone.itemsadder.Core.d.a.e.m(SourceFile:24) ~[ItemsAdder-2.4.7.jar:?]
        at dev.lone.itemsadder.Core.d.b.a.q(SourceFile:84) ~[ItemsAdder-2.4.7.jar:?]
        at dev.lone.itemsadder.Core.d.b.a.p(SourceFile:109) ~[ItemsAdder-2.4.7.jar:?]
        at dev.lone.itemsadder.Core.d.b.b.f(SourceFile:272) ~[ItemsAdder-2.4.7.jar:?]
        at dev.lone.itemsadder.Core.d.b.b.w(SourceFile:154) ~[ItemsAdder-2.4.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:831) [?:?]

Need a way to negate the excess mana when a mana potion has been drunk 

Paper 1.17.1 #196
MC Client 1.17.1
Lonelibs 1.0.14
Itemsadder 2.4.7

Not a critical issue once i manage to get the mana bar set working to 10

**Comment by LoneDev6** [comment]
Your bar doesn't have enough frames to satisfy the max value, this is a fix:
```yml
    images:
      frames:
        - "magiccraft:mana_bar_0"
        - "magiccraft:mana_bar_0"
        - "magiccraft:mana_bar_1"
        - "magiccraft:mana_bar_1"
        - "magiccraft:mana_bar_2"
        - "magiccraft:mana_bar_2"
        - "magiccraft:mana_bar_3"
        - "magiccraft:mana_bar_3"
        - "magiccraft:mana_bar_4"
        - "magiccraft:mana_bar_4"
        - "magiccraft:mana_bar_5"
        - "magiccraft:mana_bar_5"
```
