### ISSUE TITLE
Block's loot table

### ISSUE THREAD

**Issue by GHsorryiwon12345** [PluginBugs/Issues-ItemsAdder#1131]
Spawning mobs when breaking a block 
*Add effects to player
*Explosion
```
loots:
  blocks:
    luckyblock:
      type: luckyblock
      drop_only_first: true
      summon:
        zombie:
          min_amount: 1
          max_amount: 16
          chance: 100
```

**Comment by spiker5032** [comment]
You could probably do this by just adding a command to trigger @p when the block is mined on a chance.

`        execute_commands:
          example_open:
            command: 'summon zombie @p'
            as_console: false
            chance: 50`
            
            If lone makes this possible

**Comment by LoneDev6** [comment]
Should work.
```yml
        execute_commands:
          cmd:
            command: execute in {target-world} run summon pig {target-x} {target-y} {target-z}
            as_console: true
```
