### ISSUE TITLE
Insane Server Lag

### ISSUE THREAD

**Issue by user0347** [PluginBugs/Issues-ItemsAdder#1158]
**Describe the bug**
Getting insane TPS flucuation on v2,4,12, with about 20 players on

**To Reproduce**
Let server run normally

**Expected behavior**
No Lag

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: Vanilla 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.7
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Timings: https://timings.pl3x.net/?id=e7464d5325214f28b3d749a2e1764e93
Spark: https://spark.lucko.me/pm7BExjgYK

**Comment by user0347** [comment]
Downgrading to 2.4.9 helped, so it's something with a version between.

**Comment by LoneDev6** [comment]
It's caused by (somehow) laggy permissions check for the emojis.

In the meantime you can disable these settings in config.yml
```yml
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  player-display-name:
    enabled: false
    update-every-ticks: 1200
```
