### ISSUE TITLE
[Suggestion] glow color on dropped items

### ISSUE THREAD

**Issue by vgg5465** [PluginBugs/Issues-ItemsAdder#1164]
Add in the config an option to configure for every custom item or block the color glow when they were dropped on the ground.

**Comment by LoneDev6** [comment]
Very good idea, as noted on the Discord server.
I'll implement this in the 2.4.14 version

**Comment by LoneDev6** [comment]
This will be available in 2.4.17

![immagine](https://user-images.githubusercontent.com/27242001/134363891-d72e4364-c162-4f71-ba00-54f7cd5393fb.png)
```yml
    drop:
      show_name: true
      glow:
        enabled: true
        color: DARK_RED
```

You will need to install:
https://www.spigotmc.org/resources/api-glowapi.19422/
https://www.spigotmc.org/resources/api-packetlistenerapi.2930/

Sadly it's not very easy to change glow color of entities without writing tons of code, that's why I use this external lib.
