### ISSUE TITLE
[BUG] Right clicking AIR with item does not trigger events.interact.right

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#1194]
**Describe the bug**

As the title.

**To Reproduce**

1. Create a item like this:
```
items:
  time_scroll:
    display_name: "&d&lTime Scroll"
    resource:
      material: STICK
      generate: true
      textures:
      - itemsadder:item/knowledge_fragment.png
    behaviours:
      keep_on_death: true
    events_cooldown: 100
    events:
      interact:
        right:
          decrement_amount:
            amount: 1
          execute_commands:
            grant:
              as_console: true
              command: essentials:back {player}
```
2. Get the item
3. Right click AIR with the item
4. Nothing happens

FYI: Only right click some block with the item does it trigger the event.
FYI: There is no such problem in ItemsAdder 2.4.14

I guess the issue has something to do with the patch about BanItems. ( I am the person who talked to the dev of BanItems who talked to LoneDev6 about the cancel thing of BanItems)

**Expected behavior**
It should trigger events.interact.right if the player right clicks AIR with the item.

**Screenshots**

**Info (please complete the following information):**
- Server version: Purpur 1.17.1
- Client version: 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
- ItemsAdder version: Version: 2.4.15
- LightAPI Fork version: 3.5.2
- LoneLibs version: 1.0.14
- ProtocolLib version: 4.7.0

**Additional context**
