### ISSUE TITLE
Gui (/ia) does not show all items correctly

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#12]
> [<img alt="BillyGalbreath" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/BillyGalbreath) **Authored by [BillyGalbreath](https://github.com/BillyGalbreath)**
_<time datetime="2019-07-03T23:34:25Z" title="Thursday, July 4th 2019, 1:34:25 am +02:00">Jul 4, 2019</time>_
_Closed <time datetime="2019-09-11T13:27:51Z" title="Wednesday, September 11th 2019, 3:27:51 pm +02:00">Sep 11, 2019</time>_
---

The pagination of `/ia` GUI does not work correctly.

I have 63 custom items configured (including the icons used for the GUI).

![image](https://user-images.githubusercontent.com/332527/60630716-ffa81d00-9dc0-11e9-95dd-27ec064b267a.png)

I see a lot of my items on page 1 just fine

![image](https://user-images.githubusercontent.com/332527/60630722-09ca1b80-9dc1-11e9-9c92-06a6b928e293.png)

But on page 2 nothing shows

![image](https://user-images.githubusercontent.com/332527/60630727-1189c000-9dc1-11e9-84a4-771f37d6dc7c.png)

At first I thought it was just excluding the custom icons used for the GUI, but then I noticed some of my own items (emerald helmet, etc) are not shown on page 1 so should be on page 2.

I disabled all categories except "all" for my server. Here is my menu.yml

```
menu_settings:
  name: '&3&lServer special items'
  rows: 6
  recipe_view_title: '&3&lCrafing view'
  next_page_button:
    name: '&fNext page->'
    icon: icon_next_white
  previous_page_button:
    name: '&f<-Previous page'
    icon: icon_back_white
  back_button:
    name: '&fBack'
    icon: icon_cancel
  next_recipe:
    name: '&fNext recipe'
    icon: icon_right_blue
  previous_recipe:
    name: '&fPrevious recipe'
    icon: icon_left_blue
  smelting_recipe_button:
    name: '&fSmelting'
    icon: FURNACE
  edit_item_button:
    name: '&fEdit item'
    icon: WRITABLE_BOOK
  get_item_button:
    name: '&fGet item'
    icon: CHEST
  edit_vanilla_type_button:
    name: '&fVanilla type'
    icon: BUCKET
  edit_model_id_button:
    name: '&fModel ID'
    icon: PAPER
categories:
  all:
    enabled: true
    icon: ruby_block
    name: '&fAll'
    show_all_items: true
```
