### ISSUE TITLE
kill event trigger not working[BUG] 

### ISSUE THREAD

**Issue by tinkeringmatt** [PluginBugs/Issues-ItemsAdder#1201]
**Describe the bug**
When trying to use the kill event trigger, nothing happens, even though exactly replacing the kill with attack, triggers the event perfctly on the attack. The kill trigger never triggers the event no matter how you kill the entity/mob

**To Reproduce**
Creating an item with an obvious action that is then triggered either by attack or kill.
Watch as killing never triggers the action, yet the attack event trigger always works.

**Info (please complete the following information):**
 - Server version: papermc 1.17.1
 - Client version: fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.15
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Provide an example item for me to reproduce the issue, thanks

**Comment by tinkeringmatt** [comment]
abyssal_scythe:
    display_name: Abyssal Scythe
    resource:
      material: NETHERITE_SWORD
      generate: true
      model_id: 26
      textures:
      - item/abyssal_scythe.png
    events:
      kill:
        potion_effect:
          type: FAST_DIGGING
          duration: 300
          amplifier: 128
        potion_effect2:
          type: WEAKNESS
          duration: 300
          amplifier: 99

**Comment by tinkeringmatt** [comment]
Let me know if you need anything else, as this trigger would be pretty cool to have working.
For example if you kill a mob it gives you back 1 mana.
But as it stands it does not work no matter what Ive tried, and this is after talking with sircrafty pants trying many many things

**Comment by LoneDev6** [comment]
I'm confused, you said that the kill event doesn't work but in your example I see you're using the attack event.
I also don't see any mana modifier here.
```yml
  abyssal_scythe:
    display_name: Abyssal Scythe
    resource:
      material: NETHERITE_SWORD
      generate: true
      model_id: 26
      textures:
      - item/abyssal_scythe.png
    attribute_modifiers:
      mainhand:
        attackDamage: 12.0
        attackSpeed: 1.6
    events:
      attack:
        potion_effect:
          type: FAST_DIGGING
          duration: 300
          amplifier: 128
        potion_effect2:
          type: WEAKNESS
          duration: 300
          amplifier: 99
```



This is what you should have in your config:
```yml
  abyssal_scythe:
    display_name: Abyssal Scythe
    resource:
      material: NETHERITE_SWORD
      generate: true
      model_id: 26
      textures:
      - item/abyssal_scythe.png
    attribute_modifiers:
      mainhand:
        attackDamage: 12.0
        attackSpeed: 1.6
    events:
      kill:
        increment_player_stat:
          name: mana
          amount: 1
```
