### ISSUE TITLE
[Bug] Instantly sit on furniture when it's inside a WorldGuard region

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1204]
**Describe the bug**
when you put a chair on a floor you will sit on the same time | itemframe
Video = https://i.imgur.com/evbqaWv.mp4
```
  beach_chair:    
    display_name: "&6Beach Chair"
    lore:         
    - ':paintable:'                                                           
    resource:     
      material: LEATHER_HORSE_ARMOR                                                         
      generate: false                                                         
      model_path: item/beach_chair                                      
    behaviours:   
      furniture:  
        entity: item_frame                                                    
        solid: true                                                             
      furniture_sit:
        sit_height: 0.8
        sit_all_solid_blocks: true
        placeable_on:                                                         
          walls: false                                                        
          ceiling: false                                                      
          floor: true                                                         
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
```
itemadder = 2.4.16
