### ISSUE TITLE
[Suggestion] Allow custom item texture for custom armors (inventory)

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1213]
If it it working as intended, then why do custom leather item textures not get added to the item models?

For example, this IA item pack config
```  
ender_helmet:
    display_name: slimefun
    permission: slimefun
    resource:
      material: LEATHER_HELMET
      generate: true
      model_id: 2200063
      textures: 
      - item/raulh22/slimefun/slimefun/magicalarmor/ender_helmet.png
```
   
Results in this model file
```
{
  "parent": "item/generated",
  "textures": {
    "layer0": "item/leather_helmet",
    "layer1": "item/leather_helmet_overlay"
  },
  "overrides": []
}
```

What is the reason behind not being able to add leather armor textures, and also why are you forcing texture replacements?

_Originally posted by @Jas0nator in https://github.com/PluginBugs/Issues-ItemsAdder/issues/1147#issuecomment-919047693_
