### ISSUE TITLE
[Bug]: can't put a furniture made by item-frame on another funiture which is also made by item-frame

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#1221]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I make a custom table by item-frame,I can put vanilla blocks on it,but my other custom furniture like TV can't put on

### Steps to reproduce the issue

1.make two furnitures,one is table, anther one is TV.
2.both furniture made by item-frame
3.TV can't placed on table 

### Server version

purpur 1.17.1-1394

### ItemsAdder Version

2.4.17

### ProtocolLib Version

don't know 

### LoneLibs Version

don't know 

### LightAPI Version (optional)

3.5.2

### LibsDisguises Version (optional)

10.0.26-free

### FULL server log

no log

### Error (optional)

```shell
no error
```

### Screenshots/Videos

no screentshots

**Comment by LoneDev6** [comment]
Use armor_stand instead of item_frame.
Itemframes are meant to be used for furnitures that must be placed on ceiling or walls, not for normal furnitures.

The problem is that two armorstands cannot be near the same block, it's a Minecraft limitation, that's why it doesn't wok.


For example the default furnrnitures work fine.
![immagine](https://user-images.githubusercontent.com/27242001/135678610-1dd33bf9-93c4-430d-9b64-97a4b97f6cc2.png)

![immagine](https://user-images.githubusercontent.com/27242001/135678634-6b9bea3f-5ed5-4a93-a129-de591fe0113b.png)
![immagine](https://user-images.githubusercontent.com/27242001/135678642-4b27ed37-1b2b-4347-b8ae-530ac4f7e20a.png)
![immagine](https://user-images.githubusercontent.com/27242001/135678651-48ac031d-0aee-4d6e-9211-f64e83159ae5.png)


```yml
  glass_table:
    display_name: display-name-glass_table
    permission: glass_table
    lore:
    - 'lore-decorative-item'
    resource:
      material: PAPER
      generate: false
      model_path: item/glass_table
    behaviours:
      furniture:
        small: true
        solid: true
```


```yml
  tv:
    display_name: display-name-tv
    permission: tv
    lore:
    - 'lore-decorative-item'
    resource:
      material: PAPER
      generate: false
      model_path: item/tv
    behaviours:
      furniture:
        small: true
```
