### ISSUE TITLE
Preview emojis in chat by showing a big variant of the image on hover

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#1226]
### Describe the solution you'd like

1.I hope that a small-emoji can show big-emoji when you hover it just like the picture
（Maybe I need to make various size of this emoji,and in chat is small,when hover it,show the big one）
![emoji](https://user-images.githubusercontent.com/62246956/134777569-926d12ed-6c66-49ac-90b6-610e54343e2a.png)

2.I hope that when you click a emoji in chat,then your chat-line paste the emoji so you need not to  type the emoji's placeholder

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

The second suggestion is easy to archieve.The first one maybe difficult.

Hope you can find a way to let this idea true.

**Comment by tigerboy3050** [comment]
Those features would be pretty cool...

**Comment by LoneDev6** [comment]
It's a good idea, I'm thinking how to implement this

**Comment by LoneDev6** [comment]
I think this could achieved by adding a new attribute called `description` to the font_image configuration itself.
This will allow you to customize what is shown on hover.

An example would be:
```yml
  smile:
    permission: smile
    show_in_gui: true
    path: "font/emoji/smile.png"
    scale_ratio: 9
    y_position: 8
    description: ":smile_big:"
  smile_big:
    permission: smile
    show_in_gui: false
    suggest_in_command: false
    path: "font/emoji/smile_big.png"
```
