### ISSUE TITLE
wear and unwear event not triggered correctly

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1247]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

wear and unwear events not triggered correctly for custom items using DIAMOND_HELMET as material (and probably also other pieces).

setting the hat behaviour causes a double execution of the two events (both with DIAMOND_HELMET and PAPER)

### Steps to reproduce the issue

Use this configuration
```yml
info:
  namespace: example
items:
  test1:
    display_name: test
    permission: test1
    resource:
      material: DIAMOND_HELMET
      generate: false
    events:
      wear:
        execute_commands:
          cmd1:
            command: 'tellraw {player} {"text":"Action 1","color":"gold"}'
            as_console: true
            delay: 0
        play_sound:
            name: block.ancient_debris.hit
            volume: 1
            pitch: 1
      unwear:
        execute_commands:
          cmd1:
            command: 'tellraw {player} {"text":"Action 2","color":"gold"}'
            as_console: true
            delay: 0
        play_sound:
            name: block.ancient_debris.hit
            volume: 1
            pitch: 1
```

Right click to wear

### ItemsAdder Version

2.4.18

### ProtocolLib Version

4.7.1-SNAPSHOT-b530

### LoneLibs Version

1.0.14
