### ISSUE TITLE
Multiple CustomModelData material 

### ISSUE THREAD

**Issue by xMikux** [PluginBugs/Issues-ItemsAdder#1305]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Efina#0877

### Describe the solution you'd like

Will be great if material can enter multiple to match, is much useful on can upgrade armor.

**Example**

```yaml
  gilded_iron_chestplate:
    display_name: slimefun
    permission: slimefun
    resource:
      material: |
        GOLDEN_CHESTPLATE
        DIAMOND_CHESTPLATE
        LEATHER_CHESTPLATE
      generate: false
      model_id: 2200203
      model_path: "slimefun/armor/gilded_iron_armor/chestplate"
```

### Is your feature request related to a problem?

Because player can upgrade their armor, so after upgrade, the armor material will different, the texture can't match.

### Describe alternatives you've considered

Make a two same model_id & model_path, only different on material, but it will a little mess.

**Comment by LoneDev6** [comment]
Hello!
Currently the ItemsAdder Slimefun addon is old, there is no need anymore to use this addon.
You can just drag and drop Slimefun resourcepack files into ItemsAdder\resource_pack folder and run /iazip.
It will work just fine! :D

**Comment by xMikux** [comment]
yeah, but i remake one, and add more texture on it, it will useful when there have multiple armor type can match

**Comment by xMikux** [comment]
thinking about maybe i need to recreate this one, and told is not ia slimefun addon.

**Comment by LoneDev6** [comment]
What is the purpose of this feature request? What are you trying to create?
Anyway this is not doable in this way, you have to create a new item for each material.

**Comment by xMikux** [comment]
because if it can add multiple material, will be more clean to look, and don't need to add more new items with same model id and path.
```yaml
items:
  aluminum_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: |
        LEATHER_BOOTS
        GOLDEN_BOOTS
        IRON_BOOTS
        CHAINMAIL_BOOTS
        DIAMOND_BOOTS
        NETHERITE_BOOTS
      generate: false
      model_id: 2200816
      model_path: "armor/aluminum/aluminum_boots"
  aluminum_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: |
        LEATHER_CHESTPLATE
        GOLDEN_CHESTPLATE
        IRON_CHESTPLATE
        CHAINMAIL_CHESTPLATE
        DIAMOND_CHESTPLATE
        NETHERITE_CHESTPLATE
      generate: false
      model_id: 2200817
      model_path: "armor/aluminum/aluminum_chestplate"
  aluminum_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: |
        LEATHER_HELMET
        GOLDEN_HELMET
        IRON_HELMET
        CHAINMAIL_HELMET
        DIAMOND_HELMET
        NETHERITE_HELMET
      generate: false
      model_id: 2200818
      model_path: "armor/aluminum/aluminum_helmet"
  aluminum_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: |
        LEATHER_LEGGINGS
        GOLDEN_LEGGINGS
        IRON_LEGGINGS
        CHAINMAIL_LEGGINGS
        DIAMOND_LEGGINGS
        NETHERITE_LEGGINGS
      generate: false
      model_id: 2200819
      model_path: "armor/aluminum/aluminum_leggings"
```

**Comment by LoneDev6** [comment]
I think you totally misunderstood how the armors work in this case.
You can't recolor/retexture armors other than leather

**Comment by xMikux** [comment]
hmm maybe i need to retalk about this Feature request purpose. 

Because now if i want to add item texture with same id & model path, but different material, so i need to make like this
```yaml
  example_sword:
    display_name: example
    permission: example
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 123456
      model_path: "swords/example_sword"
  example_sword_1:
    display_name: example
    permission: example
    resource:
      material: WOODEN_SWORD
      generate: false
      model_id: 123456
      model_path: "swords/example_sword"
```

if it can add multiple material on one example_sword, it will more clean to look.
```yaml
  example_sword:
    display_name: example
    permission: example
    resource:
      material: |
        IRON_SWORD
        WOODEN_SWORD
      generate: false
      model_id: 123456
      model_path: "swords/example_sword"
```
and it won't cause too much confusion, or add to many same thing (only different on material)
same on armor example.
