### ISSUE TITLE
A way to make an energy system for items and blocks to use

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1314]
### Discord tag (optional)

https://www.spigotmc.org/members/entropy114.1175178/

### Describe the solution you'd like

I would like a way to set up and use an energy system, the energy system implementation described here could also be used for fuel systems, and would add basically infinite possibility, as server owners could create and name energy systems that would work as magic systems, fuel systems, or anything else

-----------------------------------------------------------------------------------------------------

first you would define the name of each system:

```yml
info:
  namespace: example
energy_systems:
  my_system:
    display_name: "MS"
    permission: example.my_system
    dimensions: (optional, defaults to all worlds enabled, defines if you want the energy system to only work in some worlds, so anything using that system would have no functionality outside of those worlds)
     - world
     - other_world
```
-----------------------------------------------------------------------------------------------------

then you would define the conversions of each system, if you want a system to be able to be converted to another:
conversions: (shows the conversion rate of exchange for systems, for example, 1 of my_system = 0.5 of other_system and 2.3 units of another_system)
      example: my_system - 1= example: other_system - 0.5
      example: my_system - 1= example: another_system - 2.3

-----------------------------------------------------------------------------------------------------

Next you would be able assign blocks as generators, with conditions for how they generate energy, what energy, etc.

```yml
  example_generator:
    display_name: solar panel
    resource:
      generate: true
      material: PAPER
      textures:
        - block/solar_panel.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
    hardness: 2
    blast_resistance: 1
    no_explosion: false
    generator:
      type: passive #the type of generator, passive doesn't require any fuel, it just needs to be placed in certain conditions.
      energy: my_system #the energy type that is generates
      light: 10 #the minimum light level need to generate energy
      time: day #the time of day needed to generate energy
      dimension: example, example2 # the dimension it needs to be in to generate energy
      on: obsidian #what block it needs to be placed on to generate energy, can be an itemsadder block
      energy_yield: 23.5 #how much energy it generates every 60 ticks (the interval can be adjusted as well)
      gen_time: 15 # how many ticks it takes before it generates more energy
```

```yml
  example_generator_fuel:
    display_name: Reactor
    resource:
      generate: true
      material: PAPER
      textures:
        - block/reactor.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
    hardness: 2
    blast_resistance: 1
    no_explosion: false
    generator:
      type: fuel #the type of generator, fuel requires items as well as any specified conditions.
      energy: my_system #the energy type that is generates
      surrounded: itemsadder: reactor_coolant #what block or liquid it needs to be surrounded by (not completely, it can have up to 4 sides not surrounded to allow for pipes and automatic waste collection systems)
      item: itemsadder: uranium - 3 #what item it needs to generate energy, and how much, can be an itemsadder item
      waste: itemsadder: nuclear_waste - 1 #defines a waste product it will generate, and how much
      energy_yield: 500 #how much energy it generates every 60 ticks (the interval can be adjusted as well)
      gen_time: 10 # how many ticks it takes before it generates more energy
```

-----------------------------------------------------------------------------------------------------

you would be able to allow items, vehicles, blocks, etc. to use energy systems energy would be displayed in lore, and using the durability bar, items would have the option to become useless when they run out of energy, or to break. items would also define their max energy unit storage, what value they start out with by default, what and energy system(s) they use. You could also make some items act as "batteries".

-----------------------------------------------------------------------------------------------------

you would then be able to add charger blocks:

```yml
  example_charger:
    display_name: charger
    resource:
      generate: true
      material: PAPER
      textures:
        - block/charger.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
    hardness: 2
    blast_resistance: 1
    no_explosion: false
    charger:
      energy: my_system #the energy type that it uses
      energy_charge: 500 #how much energy it charges the item with every 60 ticks (the interval can be adjusted as well)
      charge_time: 10 # how many ticks it takes before it sends the item more energy
```

-----------------------------------------------------------------------------------------------------
energy conversion blocks could be made so that people can allow players to convert energy systems to others:

```yml
  example_converter:
    display_name: converter
    resource:
      generate: true
      material: PAPER
      textures:
        - block/converter.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
    hardness: 2
    blast_resistance: 1
    no_explosion: false
    charger:
      energy_systems: my_system, other_system #the two energy types that it can convert
      conversion_time: 20 #how many ticks it takes to perform 5 conversions of an energy system to another, conversion rate defined by the conversion mechanic
```

-----------------------------------------------------------------------------------------------------

You could also make functional machines using energy systems:

```yml
  example_machine:
    display_name: machine
    resource:
      generate: true
      material: PAPER
      textures:
        - block/converter.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
    hardness: 2
    blast_resistance: 1
    no_explosion: false
    machine:
      gui: example_machine #the gui it uses, this suggestion would also implement very basic functional guis
```

-----------------------------------------------------------------------------------------------------

functional gui implementation, besides this system there would be default gui features for chargers, where you only define the texture, and which slot(s) are used for charging, fuel-based generator guis, where you define input slot(s) and optionally waste slots.

```yml
info:
  namespace: example
guis:
  energetic_infusion_crafting_gui:
    permission: example.energetic_infusion
    texture: 
    size: 3 #how many rows the gui is
    texture: guis/infusion.png
    energy_slot: 5 #the slot used to show how much energy is stored inside the machine
    button_slot: 15 #the slot that is clicked on to perform the action
    input_slots: 3, 12 #the slot(s) used for input, unused slots are automatically set so that you can't put items in them
    output_slots: 27 #the slot(s) used for output, unused slots are automatically set so that you can't put items in them
    input_1: nether_star, obsidian - 10 #the item(s) and amounts for the input, the _[number] at the end is used in case you want to add multiple recipes for the machine
    output_1: example: infused_obsidian#the item(s) and amounts for the output, the _[number] at the end is used in case you want to add multiple recipes for the machine
    energy_cost_1: 500 #the amounts of energy used to convert the input into the output, the _[number] at the end is used in case you want to add multiple recipes for the machine, energy is optional if you don't want it to use energy
    time_1: 20 S #how much time it takes to complete the action, you can add S or M to after the number to make it use minutes or seconds instead of ticks
```

-----------------------------------------------------------------------------------------------------

lastly, cables would have to implemented in some way, most likely a simple default "universal cable" block could be added.

### Is your feature request related to a problem?

I want to be able to add energy systems for players to play around with, and to have a unique progression system, but there isn't a way to do that at the moment, and though slimefun is nice, it uses vanilla blocks and items, and just isn't as customizable as I need.

### Describe alternatives you've considered

Slimefun and nova, there's not much else

### Additional context

I am in the process of porting the entirety of the aether mod to my server using itemsadder (and then modelengine and terra for mobs and generation), and it has machines that would require functional GUIS, but I am also porting draconic evolution, which requires and energy system, I also plan to add my own generators, machines, items, armors, etc. that would all require energy, like flamethrowers, jetpacks, and other fun items.
