### ISSUE TITLE
Full-set armor bonuses

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#1333]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Gust#1337

### Describe the solution you'd like

Add new feature for armor - complect attributes/beacon effects bonuses. Very simple and very useful.

### Is your feature request related to a problem?

More space for rebalance.

### Describe alternatives you've considered

.

### Additional context

Config
```
full_sets:
  sample_armor:
    equip:
      head: sample_helmet
      chest: sample_chestplate
      legs: sample_leggings
      feet: sample_boots
    bonuses:
      25_percents: 
        attribute_modifiers: 
          armor: 0
      50_percents:
        attribute_modifiers: 
          armor: 1
      75_percents: 
        attribute_modifiers: 
          armor: 2
      100_percents: 
        attribute_modifiers: 
          armor: 3
        beacon_effects:
          regeneration:
            amplifier: 3
```

**Comment by GHsorryiwon12345** [comment]
+1

**Comment by MrJorman** [comment]
UP !!!

**Comment by MrJorman** [comment]
Can you add a booking bonus?

If 1 thing is worn, then a 25% chance will work on the enemy weakness effect
If 2 things are worn, then 50% of the weakness effect will work on the enemy
If 3 things are worn, then 75% and so on.

**Comment by LoneDev6** [comment]
This is a good idea.
The problem is that this "percentage" logic is not really intuitive.

I think would be better to specify groups of armor pieces.
```yml
armors:
  sample_armor:
    equip:
      head: sample_helmet
      chest: sample_chestplate
      legs: sample_leggings
      feet: sample_boots
    bonuses:
      group_1: 
        group: 
          helmet: true
          chestplate: true
        potion_effects:
          regeneration:
            amplifier: 3
      group_2: 
        group: 
          helmet: true
          chestplate: true
          leggings: true
          boots: true
        potion_effects:
          regeneration:
            amplifier: 8
      ### other groups....
```
