### ISSUE TITLE
Custom sound effect when breaking, break, step on Custom Block

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1336]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

🌞 NightKunGz#0790

### Describe the solution you'd like

This feature will make custom block is more realistic!

Example:
https://streamable.com/pbo90s
(from Origin Realms Server)

### Is your feature request related to a problem?

-

### Describe alternatives you've considered

```yml
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        sound_effect:
          breaking: 'namespace:sound_here, <pitch>, <volume>'
          break: 'namespace:sound_here, <pitch>, <volume>'
          step_on: 'namespace:sound_here, <pitch>, <volume>'
```
