### ISSUE TITLE
Feature Request | Option to switch between Itemsadder's simulate block break particle and vanilla block break particle

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1337]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

🌞 NightKunGz#0790

### Describe the solution you'd like

I know `break_particles:` will not working if it changed to vanilla block break particle because `break_particles:` will is remove vanilla particle and adding simulate particle instead

so i decide to suggest 'Option to switch between Itemsadder's simulate block break particle and vanilla block break particle' instead

Example: https://streamable.com/pbo90s

this feature will make custom block break particle is more realistic (spreader and have mining particle)

### Is your feature request related to a problem?

Just want it because it's look like more realistic like vanilla block

### Describe alternatives you've considered

In `config.yml`

```yml
blocks:
  vanilla-block-break-particle: true #(Default: false)
```

if change this option to `true`
- Resourcepack will using vanilla block break particle (according block texture)
- `break_particles:` options will not working

**Comment by LoneDev6** [comment]
This had been fixed long time ago thanks to the new particles option.
```yml
  test:
    display_name: test
    resource:
      generate: true
      textures:
        - "test"
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: VANILLA
        cancel_drop: false
```
