### ISSUE TITLE
"execute_commands" "{player}" placeholder not replaced when triggered by "interact" event

### ISSUE THREAD

**Issue by NoobcoreNetwork** [PluginBugs/Issues-ItemsAdder#1342]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Joshie#0644

### What happened?

Hey! So I'm trying to create a functional trashcan and here is my attachment to a trash can furniture

```
    events:
      placed_armorstand:
        interact:
          execute_commands:
            cmd1:
              command: 'execute at @a run playsound minecraft:entity.ender_dragon.growl ambient %player_name%'
              as_console: true
              delay: 0
            cmd2:
              command: 'trash'
              as_console: false
              delay: 0
```

The console will not read the placeholders coming from IA at all the result is always

Console Output for the above command (When right clicking trashcan)
```
05.12 01:24:19 [Server] INFO Invalid name or UUID
05.12 01:24:19 [Server] INFO ...l ambient  %player_name%<--[HERE]`
```

I have tried with {player} %player_name% %player% and they all show up with the bare placeholder in the error above, no matter which one I use,

Running /papi parse me %player_name% works on my server perfectly fine

I have tried using the playsound command as a workaround but this just plays the trashcan sound to all the player in the area which isn't what I'm trying to achieve,

Let me know if more info is needed thanks!
              

### Steps to reproduce the issue

Details Explained in 'what happened' section

### Server version

This server is running Airplane version git-Airplane-99 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e68f5c2 on HEAD)

### ItemsAdder Version

2.4.23

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

**Comment by LoneDev6** [comment]
{player} not %player_name%

**Comment by wearenoobsuk** [comment]
> I have tried using the playsound command as a workaround but this just plays the trashcan sound to all the player in the area which isn't what I'm trying to achieve,

Tried {player} returns the same thing in the console

also to quote myself

'I have tried using the playsound command as a workaround but this just plays the trashcan sound to all the player in the area which isn't what I'm trying to achieve'

**Comment by wearenoobsuk** [comment]
```
    events:
      placed_armorstand:
        interact:
          execute_commands:
            cmd1:
              command: 'execute at @a run playsound minecraft:entity.ender_dragon.growl ambient {player}'
              as_console: true
              delay: 0
            cmd2:
              command: 'trash'
              as_console: false
              delay: 0
```

Console
`[23:22:24] [Server thread/INFO]: Invalid name or UUID
[23:22:24] [Server thread/INFO]: ...l ambient {player}<--[HERE]`

**Comment by LoneDev6** [comment]
> I have tried using the playsound command as a workaround but this just plays the trashcan sound to all the player in the area which isn't what I'm trying to achieve,

This is not normal, play_sound action will work, so use it instead.
```yml
        play_sound:
          name: entity.ender_dragon.growl
          volume: 1
          pitch: 1
```

I think it's related to a problem of your audio file. Minecraft only supports MONO sounds not STEREO sounds, read more here: https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/sounds/convert-sound-to-.ogg
"Remember to set "Change audio channels" to MONO or you will experience [audio problems](https://bugs.mojang.com/browse/MC-146721)"


You will have the same problem even by using the vanilla playsound command. 

Anyway `execute at @a run ` is not needed by the Minecraft playsound command and must likely to be the cause of the console error.
