### ISSUE TITLE
keep_on_death doesnt' work

### ISSUE THREAD

**Issue by BlazeLX** [PluginBugs/Issues-ItemsAdder#1347]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

behaviours doesn't work correct!
i have 4 items in one yml config, all of them have keep_on_death: true but working is only first item (BUT: Iif i get 5 items copy
, keeped was only 1)

### Steps to reproduce the issue

1. /iaget custombpitems:commonhead
2. /iaget custombpitems:commonchest
3. /iaget custombpitems:commonboots
4. /iaget custombpitems:commonlegs
5. kill
6. only helmet in my inventory
7. 1. /iaget custombpitems:commonhead
8. 1. /iaget custombpitems:commonhead
9. 1. /iaget custombpitems:commonhead
10. 1. /iaget custombpitems:commonhead
11. kill
12. only ONE helmet in my inventory

### Server version

git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)

### ItemsAdder Version

 ItemsAdder version 2.4.23

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

 LoneLibs version 1.0.15

### LibsDisguises Version (optional)

 LibsDisguises version 10.0.26

### Error (optional)

```shell
[23:34:05 INFO]: [ItemsAdder] Loaded 44 items
[23:34:05 INFO]: [ItemsAdder] Used 0/188 REAL block IDs.
[23:34:05 INFO]: [ItemsAdder] Used 28/750 REAL_NOTE block IDs.
[23:34:05 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs.
[23:34:05 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs.
[23:34:05 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs.
[23:34:05 INFO]: [ItemsAdder] Used 568/6608 available max font_images.
[23:34:05 INFO]: [ItemsAdder] [Init] Loaded 40 categories
[23:34:05 INFO]: [ItemsAdder] [Init] Loaded 44 items and stuff in 592ms
[23:34:05 INFO]: [ItemsAdder] [Pack] Checking resourcepack url...
[23:34:05 INFO]: [ItemsAdder] [Pack] Resourcepack URL (self-host): http://127.0.0.1:8163/pack.zip
[23:34:49 INFO]: UUID of player Blaze_LX is bb09637e-f530-43a5-a57f-55cb501ac271
[23:34:49 INFO]: Blaze_LX joined the game
[23:34:49 INFO]: Blaze_LX[/127.0.0.1:49238] logged in with entity id 327 at ([world]-152.24577337082417, 64.0, -27.912510134292532)
[23:34:59 INFO]: Blaze_LX issued server command: /iaget custombpitems:commonhead
[23:35:05 INFO]: Blaze_LX issued server command: /kill
[23:35:05 INFO]: Blaze_LX fell out of the world
[23:35:06 INFO]: [Blaze_LX: Killed Blaze_LX]
[23:35:13 INFO]: Blaze_LX issued server command: /kill
[23:35:13 INFO]: Blaze_LX fell out of the world
[23:35:13 INFO]: [Blaze_LX: Killed Blaze_LX]
[23:35:42 INFO]: Blaze_LX issued server command: /iaget custombpitems:commonhead
[23:35:43 INFO]: Blaze_LX issued server command: /iaget custombpitems:commonhead
[23:35:44 INFO]: Blaze_LX issued server command: /iaget custombpitems:commonhead
[23:35:44 INFO]: Blaze_LX issued server command: /iaget custombpitems:commonhead
[23:35:48 INFO]: Blaze_LX issued server command: /kill
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: ru
  dictionaries-lang: ru
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: custombpitems
items:
  commonhead:
    display_name: <r ИЗНАЧАЛЬНЫЙ ШЛЕМ>
    resource:
      material: DIAMOND_HELMET
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: head
        color: 994C17
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonchest:
    display_name: <r ИЗНАЧАЛЬНЫЙ НАГРУДНИК>
    resource:
      material: DIAMOND_CHESTPLATE
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: chest
        color: '#994c18'
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonlegs:
    display_name: <r ИЗНАЧАЛЬНЫЕ ПОНОЖИ>
    resource:
      material: DIAMOND_LEGGINGS
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: legs
        color: '#994c19'
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonboots:
    display_name: <r ИЗНАЧАЛЬНЫE БОТИНКИ>
    resource:
      material: DIAMOND_BOOTS
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: feet
        color: '#994c1a'
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
```

**Comment by LoneDev6** [comment]
This will be fixed, thanks

**Comment by BlazeLX** [comment]
It doesn't fixen (testet on same version with identical settings)
ProtocolLib, LoneLibs LightAPI and Lib's Disguises  was updated.

**Comment by LoneDev6** [comment]
> It doesn't fixed (testet on same version with identical settings)

Did you update ItemsAdder?

**Comment by LoneDev6** [comment]
Anyway I don't understand why are you setting the resource like that, it's totally wrong.
```yml
    resource:
      material: DIAMOND_BOOTS
      generate: true
```
Why are you setting the armor `material` explicitly, `generate: true` and not specifying any texture?
Anyway you should not set this at all. Armors don't need the `material` setting set.

```yml
 commonhead:
    display_name: <r ИЗНАЧАЛЬНЫЙ ШЛЕМ>
    resource:
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: head
        color: 994C17
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonchest:
    display_name: <r ИЗНАЧАЛЬНЫЙ НАГРУДНИК>
    resource:
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: chest
        color: '#994c18'
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonlegs:
    display_name: <r ИЗНАЧАЛЬНЫЕ ПОНОЖИ>
    resource:
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: legs
        color: '#994c19'
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
  commonboots:
    display_name: <r ИЗНАЧАЛЬНЫE БОТИНКИ>
    resource:
      generate: true
    durability:
      unbreakable: true
    specific_properties:
      armor:
        slot: feet
        color: '#994c1a'
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockback_resistance: 0.1
        max_health: 2
    lore:
    - '&fПервая работа администратора, выданная'
    - '&fучастникам первого боевого пропуска.'
    - ''
    - '&d&lОГРАНИЧЕННАЯ СЕРИЯ. НЕ КРАФТИТСЯ!'
    - ''
    - '&6&l&kТ &6&lЛЕГЕНДАРНОЕ &kТ'
    item_flags:
      - HIDE_UNBREAKABLE
    behaviours:
      keep_on_death: true
```

I tested again and it works fine.
