### ISSUE TITLE
New event for furniture

### ISSUE THREAD

**Issue by SirPenguini** [PluginBugs/Issues-ItemsAdder#1365]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Would be great if we could have a "placed_armorstand.break" event so we can run actions (e.g. execute commands) when furniture is broken. Thanks

### Is your feature request related to a problem?

Sort of - currently can't run actions when on furniture break.

### Describe alternatives you've considered

Tried different events such as "block_break" but none worked for me unforunately

**Comment by LoneDev6** [comment]
Will be added, sorry for the delay

**Comment by LoneDev6** [comment]
## armorstand based furniture
```yml
    events:
      placed_armorstand:
        interact:
          execute_commands:
            cmd:
              command: tell LoneDev interact
        break:
          execute_commands:
            cmd:
              command: tell LoneDev break
```

## itemframe based furniture
```yml
    events:
      placed_itemframe:
        interact:
          execute_commands:
            cmd:
              command: tell LoneDev interact
        break:
          execute_commands:
            cmd:
              command: tell LoneDev break
```
