### ISSUE TITLE
Vehicle Fueling Item Return

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1369]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sircraftypants#4875

### Describe the solution you'd like

Require a way of returning a custom item to a player when they refuel a vehicle.

### Is your feature request related to a problem?

Yes, I've created a complete refueling system for vehicles and need a way to return a depleted custom item.

### Describe alternatives you've considered

Wouldn't matter whether or not it's directly given to the player or dropped on the ground, so long as there's some way to do it.

### Additional context

An example is i've created a battery charging port, batteries and depleted batteries, i was looking to use a battery to fuel a vehicle and when i click the vehicle with the battery, the battery disappears and the vehicle returns a depleted battery which can be recharged at the battery charging station.

**Comment by SirCraftypants** [comment]
bump

**Comment by LoneDev6** [comment]
I currently have no idea on how to setup this in the configuration, how could it look like?

**Comment by SirCraftypants** [comment]
I was thinking maybe a gui where you place the a fuel can, that fuels the vehicle and you get an empty fuel can in return.

**Comment by SirCraftypants** [comment]
or when you throw the fuel can at the vehicle, it returns the empty fuel can to the player like a recipe returns a tool.

**Comment by SirCraftypants** [comment]
So

when you left click a Vehicle it opens the recipe inventory, you add the fuel items, it fuels the Vehicle and returns an item.

**Comment by LoneDev6** [comment]
This will be available in v3.0

```yml
          items:
            banana:
              fuel_amount: 30
              return_item: empty_banana
            pear:
              fuel_amount: 30
              return_item: empty_pear
```

Full example:
```yml
  black_go_cart:
    display_name: display-name-black_go_cart
    permission: black_go_cart
    resource:
      material: PAPER
      generate: false
      model_path: item/black_go_cart
    behaviours:
      vehicle:
        sit_height: 0
        step_height: 0.1
        hitbox:
          length: 1.7
          width: 1.7
          height: 1.7
        speed:
          drive: 1
          jump: 0.3
        fuel:
          start: 150
          max: 300
          items:
            COAL:
              fuel_amount: 1
              return_item: STONE
            CHARCOAL: 1
            COAL_BLOCK: 9
        smoke:
          amount: 2
          offset:
            x: 0
            y: 0
            z: -0.8
```
