### ISSUE TITLE
Support multiple FontImageWrapper on TexturedInventoryWrapper

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1420]
by @njibhu

When declaring the behavior for custom blocks in ItemsAdder config files it's possible to set a left and right textures for example on the Merchant UI.
Example:
```yml
...
    behaviours:
      block_trade_machine:
        title: Customization Table
        gui_texture:
          left: customization_table_left
          right: customization_table_right
          title_offset: -130
...
```

The `TexturedInventoryWrapper` API allows to open any kind of `InventoryType` but it's only possible to pass a single texture.
It would be great to have another method supporting left/right textures to create a custom merchant interface.
