### ISSUE TITLE
Directional blocks

### ISSUE THREAD

**Issue by Apiz05** [PluginBugs/Issues-ItemsAdder#1427]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Aech_#1655

### Describe the solution you'd like

I want that there an option to make the custom block to turn into pillar or logs like Spruce Log

### Is your feature request related to a problem?

i don't think the feature request related to a problem

### Describe alternatives you've considered

Maybe detect what side of the block the player see and place the block then it will change 

or make the block use items frame cause when im lag in OR it will show the items frame for the block (only for block like logs) 

### Additional context

I hope you get my point

**Comment by LoneDev6** [comment]
Sorry I don't understand your request, please explain

**Comment by Apiz05** [comment]
can you make a block like a minecraft logs 
![image](https://user-images.githubusercontent.com/80612886/149850669-4a2ce3af-05fa-4059-9767-2d0565bfd2e4.png)

like that picture 
the block can rotate when it in the different place

**Comment by Apiz05** [comment]
Yeah it true but it was their option to make it that way 
or you can make the block that can rotate is only for 5 block only or 10 
you decide it

**Comment by LoneDev6** [comment]
Someone implemented an addon that introduces that feature.
For now use this addon:
https://www.spigotmc.org/resources/directionalblock-itemsadder-addon.104485/

**Comment by LoneDev6** [comment]
Implementing it in the new 4.0.10 beta

Example pack: [directional_blocks_test.zip](https://github.com/user-attachments/files/19755753/directional_blocks_test.zip)


> [!WARNING]  
> Creating directional blocks will occupy 4 or 6 slots per block. This happens because each direction is a different block. There is no way to bypass that. It's a limitation of the game and any other content creation plugin would have this limitation.
You should not abuse directional blocks because they quickly will saturate your custom blocks usages.

> [!IMPORTANT]  
> `FURNACE` and `DROPPER` won't act like the vanilla machinery. They are just names to easily understand the type of block rotation.

## Furnace style

Act like vanilla furnace.

```yml
  directional_block_furnace:
    name: directional_block_furnace
    resource:
      material: PAPER
      generate: true
      textures:
      - block/furnace/directional_block_test_down.png
      - block/furnace/directional_block_test_east.png
      - block/furnace/directional_block_test_north.png
      - block/furnace/directional_block_test_south.png
      - block/furnace/directional_block_test_up.png
      - block/furnace/directional_block_test_west.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          directional_mode: FURNACE
```

![Image](https://github.com/user-attachments/assets/c4c6c501-a1fa-4cd1-a2de-67c3ad5d626a)

## Log style

Act like vanilla logs.

```yml
  directional_block_log:
    name: directional_block_log
    resource:
      material: PAPER
      generate: true
      textures:
      - block/log/directional_block_test_down.png
      - block/log/directional_block_test_east.png
      - block/log/directional_block_test_north.png
      - block/log/directional_block_test_south.png
      - block/log/directional_block_test_up.png
      - block/log/directional_block_test_west.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          directional_mode: LOG
```

![Image](https://github.com/user-attachments/assets/db9c84da-c30c-40c4-a53d-7850ebd3ad8b)

## Dropper style

Acts like the vanilla dropper.
In this particular case I decided to overwrite the automatically generated directional blocks `up` and `down` to customize the appearance of the block in this particular case, setting a different texture for the `north` face (front).
In the screenshot you can see the face texture is different.

```yml
  directional_block_dropper:
    name: directional_block_dropper
    resource:
      material: PAPER
      generate: true
      textures:
      - block/dropper/directional_block_test_down.png
      - block/dropper/directional_block_test_east.png
      - block/dropper/directional_block_test_north.png
      - block/dropper/directional_block_test_south.png
      - block/dropper/directional_block_test_up.png
      - block/dropper/directional_block_test_west.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          directional_mode: DROPPER
  directional_block_dropper_up:
    name: directional_block_dropper_up
    resource:
      material: PAPER
      generate: true
      textures:
      - block/dropper/directional_block_test_down.png
      - block/dropper/directional_block_test_east.png
      - block/dropper/directional_block_test_north_variant.png
      - block/dropper/directional_block_test_south.png
      - block/dropper/directional_block_test_up.png
      - block/dropper/directional_block_test_west.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
  directional_block_dropper_down:
    name: directional_block_dropper_down
    resource:
      material: PAPER
      generate: true
      textures:
      - block/dropper/directional_block_test_down.png
      - block/dropper/directional_block_test_east.png
      - block/dropper/directional_block_test_north_variant.png
      - block/dropper/directional_block_test_south.png
      - block/dropper/directional_block_test_up.png
      - block/dropper/directional_block_test_west.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
```
![Image](https://github.com/user-attachments/assets/c097ac52-80ba-4daf-865b-7726ad3e8b87)
