### ISSUE TITLE
Solid Option and Barriers are not placing correct

### ISSUE THREAD

**Issue by ZeonBT** [PluginBugs/Issues-ItemsAdder#1467]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Two rotations out of the four are bugged, with the solid option for the barriers, they are spawning in the wrong positions,

![2022-01-31_10 37 24](https://user-images.githubusercontent.com/44127152/151780247-9dc88a7c-7322-4ec0-b227-a5f78f7968c8.png)

### Steps to reproduce the issue

With the Solid option on for a 2x1 bench the barriers do not spawn on half of the model but ill spawn on the other side.

### Server version

1.18.1 PARER -177

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.8.0 -b540

### LoneLibs Version

1.0.16b

### ItemsAdder config.yml

```shell
This is the config used to make the bench 
banc:
    display_name: "&fBanc"
    permission: banc
    resource:
      material: STONE
      generate: false
      model_path: banc
    behaviours:
      furniture:
        small: true
        solid: true
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        opposite_direction: false
        fixed_rotation: true
        gravity: false
      furniture_sit:
        sit_height: 0.65
```

### Other files, you can drag and drop them here to upload. (optional)

[banc.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7970157/banc.zip)
![banc](https://user-images.githubusercontent.com/44127152/151781218-d34713bc-db01-40bc-be63-a7caac444f93.png

The model and texture if you want to test it

**Comment by LoneDev6** [comment]
```yml
  banc:
    display_name: "&fBanc"
    permission: banc
    resource:
      material: STONE
      generate: false
      model_path: banc
    behaviours:
      furniture:
        small: true
        solid: true
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: 0.5
          height_offset: 0
        opposite_direction: false
        fixed_rotation: true
        gravity: false
      furniture_sit:
        sit_height: 0.65  
```

This is a know behaviour and it's normal, you have to adjust the furniture hitbox offsets
https://itemsadder.devs.beer/plugin-usage/advanced/furniture/furniture-collisions#show-the-hitbox
