### ISSUE TITLE
Make `replace_near_blocks` and `replace_block` `from` argument work with vanilla block types

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#1520]
I want to make oak boards with a saw -> carved boards -> carved boards option # 2 -> carved boards option # 3 -> and return to oak boards again, that is, twist them in a circle using action (replace_block, replace_near_block). But your plugin does not allow me to do this, look at my config again.

### Other files, you can drag and drop them here to upload. (optional)
```yml
items:
  bitsaw_stone:
    display_name: '&fКаменная пила'
    lore:
    - '&3Может резать доски'
    resource:
      material: WOODEN_SWORD
      generate: true
      textures:
      - item/bitsaw_stone.png
    durability:
        max_custom_durability: 131
        disappear_when_broken: true
    attribute_modifiers:
      mainhand:
        attackDamage: 2.0
        attackSpeed: 3.0
    blocked_enchants:
      - ALL
    item_flags:
    - HIDE_ATTRIBUTES
    - HIDE_ENCHANTS
    events:
      interact.left:
        replace_near_blocks:
            radius:
                x: 1
                y: 1
                z: 1
            from: OAK_PLANKS
            to: gems:oak_planks_carved
            decrement_durability: 1
            no_physics: false
        replace_near_blocks_2:
            radius:
                x: 1
                y: 1
                z: 1
            from: gems:oak_planks_carved
            to: OAK_PLANKS
            decrement_durability: 1
            no_physics: false
        play_sound:
            name: item.axe.strip
        cancel: true
```
### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/sN4oQ0e9w68
