### ISSUE TITLE
placed_armorstand.break.cancel not working

### ISSUE THREAD

**Issue by PeterMa9621** [PluginBugs/Issues-ItemsAdder#1582]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Allow developers to listen on the furniture break event from ItemsAdder API and be able to cancel the event

### Is your feature request related to a problem?

I tried this
```
events:
      placed_armorstand:
        break:
          cancel: true
```
but it doesn't work, the furniture will still be break when I hit the furniture.
I also tried to listen block break event, and try to cancel it but it still doesn't work.

### Describe alternatives you've considered

We can also have an option to make the furniture unbreakable

**Comment by LoneDev6** [comment]
These will work fine in 3.1.2
```yml
    events:
      placed_armorstand:
        break:
          cancel: true
```

```yml
    events:
      placed_itemframe:
        break:
          cancel: true
```
