### ISSUE TITLE
Custom Entity Spawns

### ISSUE THREAD

**Issue by spiker5032** [PluginBugs/Issues-ItemsAdder#1583]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

spike#5032

### Describe the solution you'd like

Add custom spawns for entity's. Here is an example of what I think would be great.

```
entity_populators:
  monkey:
    entity: custom:monkey
    biomes:
    - FOREST
    - JUNGLE
    worlds:
    - world
    replaceable_mobs:
    - COW
    night_spawn: false
    chance: 20.0
    max_height: 45
    min_height: 25
    amount: 1
```

### Is your feature request related to a problem?

No current way to spawn entitys without commands or mythic mobs

### Describe alternatives you've considered

Using mythic mobs

**Comment by LoneDev6** [comment]
Example of the upcoming implementation:
```yml
info:
  namespace: test
entities:
  red_zombie:
    model_folder: entity/red_zombie
    can_sun_burn: false
    type: ZOMBIE
entities_populator:
  red_zombie:
    entity: test:red_zombie
    # This sets how to actually spawn the entity. By default uses REPLACE and types to all monsters and friendly
    # You can replace a vanilla mob when it's spawned or spawn your mob near it.
    # Note: This uses the Minecraft spawn logic, so gemerule `doMobSpawning false` will make this stop working.
    spawn_logic:
      method: REPLACE # or SPAWN_NEAR
      types:
      - ZOMBIE
    chance: 20.0
    amount: 1
    biomes:
    - FOREST
    - JUNGLE
    worlds:
    - world
    - "!banned_other_world"
    - "test_world_*"
    # you can also use x and z as location_range parameters, for example
    # to make edge of the worlds harder with more dangerous mobs
    location_range:
      y:
        min: 25
        max: 45
    weather:
    - CLEAR
    - RAIN
    - THUNDER
    - SNOW
    # you can create more intervals, this is useful to introduce dynamicity to your gameplay
    time:
      interval_1:
        min: 12000 # sunset. also supports the 'sunset' word directly
        max: 23000 # sunrise. also supports the 'sunrise' word directly
    light_level:
      min: 0
      max: 5

  red_zombie_1:
    entity: test:red_zombie
    spawn_logic:
      method: REPLACE # or SPAWN_NEAR
      types:
      - ZOMBIE
    chance: 100.0
    amount: 3
    worlds:
    - world*
    # you can also use x and z as location_range parameters, for example
    # to make edge of the worlds harder with more dangerous mobs
    location_range:
      y:
        min: 0
        max: 150
    weather:
    - CLEAR
    - RAIN
    - THUNDER
    - SNOW
    light_level:
      min: 0
      max: 15
```
