### ISSUE TITLE
Different cooldown displays

### ISSUE THREAD

**Issue by srnyx** [PluginBugs/Issues-ItemsAdder#1670]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

srnyx#0001

### Describe the solution you'd like

A way to change where the events cooldown will be displayed. It is currently displayed in the subtitle which is pretty big and obnoxious. I think it'd look nice in the boss bar, and it could even have the boss bar decrease as the cooldown decreased, it would be a nice touch.

### Is your feature request related to a problem?

The current way the events cooldown is displayed is annoying.

### Describe alternatives you've considered

Remaking the ItemsAdder events/actions I have into my own plugin so that I can customize the cooldown however I wish. Very impractical though.

**Comment by LoneDev6** [comment]
I might even make a custom HUD for that

**Comment by NoobcoreNetwork** [comment]
Hey hey, Running into issues with this myself, The title for cooldown is extremely obtrusive imo and something smaller would be alot better

**Comment by LoneDev6** [comment]
Note: Invisible cooldown was implemented in 3.6.0 #3042

## WIP of the custom cooldown HUD 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/1fa19738-4a84-445b-98c0-5f1292b4dcfd)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/cb61c72e-bdbc-451a-942e-60317579bc77)

**Comment by LoneDev6** [comment]
## 3 different items to experiment the different cooldowns
```yml
info:
  namespace: git
items:
  cooldown_test:
    enabled: true
    display_name: cooldown_test
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: PAPER
    events_settings:
      cooldown:
        indicator: HUD
        ticks: 60
        # This is by default. Not mandatory. Only needed if you want to use a custom hud.
        custom_hud: _iainternal:small_cooldown_bar
    events:
      interact:
        left:
          play_particle:
            name: CRIT
  cooldown_test_2:
    enabled: true
    display_name: cooldown_test_2
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: DIAMOND
    events_settings:
      cooldown:
        indicator: HUD
        ticks: 600
        # This is by default. Not mandatory. Only needed if you want to use a custom hud.
        custom_hud: _iainternal:small_cooldown_bar
    events:
      interact:
        left:
          play_particle:
            name: CRIT
  cooldown_test_3:
    enabled: true
    display_name: cooldown_test_3
    resource:
      generate: false
      model_path: minecraft:item/paper
      material: PAPER
    events_settings:
      cooldown:
        indicator: BOSSBAR
        ticks: 40
    events:
      interact:
        left:
          play_particle:
            name: CRIT
```
