### ISSUE TITLE
Hide durability tooltip per-item

### ISSUE THREAD

**Issue by srnyx** [PluginBugs/Issues-ItemsAdder#1671]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

srnyx#0001

### Describe the solution you'd like

Ability to hide the `Durability: X / Y` tooltip that is shown by default on items with durability (custom or not). In some cases I don't need this tooltip because I'll have my item use the same max durability as the material I have it set as. Thus it creates 2 of the same tooltips when advanced tooltips are enabled on the client.

### Is your feature request related to a problem?

I can only disable the durability tooltip for all items instead of per item, making it difficult to customize.

### Describe alternatives you've considered

Dealing with it or hiding durability tooltip for all items (would prefer dealing with it).

**Comment by LoneDev6** [comment]
3.2.5 will allow this:

```yml
info:
  namespace: test
items:
  test_dur_override_hide:
    display_name: test_dur_override_hide
    resource:
      material: IRON_SWORD
      generate: true
      textures:
      - minecraft:item/diamond.png
    durability:
      max_custom_durability: 3
      custom_durability: 3
      disappear_when_broken: false
      show_custom_durability_lore: false
  test_dur_override_show:
    display_name: test_dur_override_show
    resource:
      material: IRON_SWORD
      generate: true
      textures:
      - minecraft:item/diamond.png
    durability:
      max_custom_durability: 3
      custom_durability: 3
      disappear_when_broken: false
      show_custom_durability_lore: true
  test_dur_no_override:
    display_name: test_dur_no_override
    resource:
      material: IRON_SWORD
      generate: true
      textures:
      - minecraft:item/diamond.png
    durability:
      max_custom_durability: 3
      custom_durability: 3
      disappear_when_broken: false
```
