### ISSUE TITLE
Allow Potion id's as Ingredients

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1694]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sircraftypants#4875

### Describe the solution you'd like

To be able to use potion id's in Recipes and Machines.

I.e.

```
          rage_potion:
            ingredients:
              slot1:
                item: minecraft:potion:373:8202
                amount: 1
              slot2:
                item: minecraft:potion
                id: 373:8202
                amount: 1
            result:
              item: rage_potion
              amount: 1
```
i'm no dev but something like the 2 options above.

Looking to use two potions to create a new potion.

Also if not already on your list of to do's

ability to put ingredient stack amounts in Recipes and Machines.

### Is your feature request related to a problem?

no, not a problem, just an addon i'm working on that requires it.

### Describe alternatives you've considered

no alternatives.

**Comment by LoneDev6** [comment]
Available in the upcoming update.
Now ingredients support more properties when needed, in this case to specify a potion type.
Note: you can still just add the item type directly, like you used to do, the new structure is not mandatory.

```yml
info:
  namespace: myitems
recipes:
  crafting_table:
    test_potion_recipe:
      enabled: true
      pattern:
        - "XXX"
        - "XAX"
        - "XQX"
      ingredients:
        A:
          item: POTION
          potion_type: minecraft:strong_swiftness
        Q: STONE
      result:
        item: ACACIA_BOAT
        amount: 1
```



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0b96ab20-a3fc-403e-a9c4-8c795e2c195d)


List of possible potion types:
```
"minecraft:water",
"minecraft:mundane",
"minecraft:thick",
"minecraft:awkward",
"minecraft:night_vision",
"minecraft:long_night_vision",
"minecraft:invisibility",
"minecraft:long_invisibility",
"minecraft:leaping",
"minecraft:long_leaping",
"minecraft:strong_leaping",
"minecraft:fire_resistance",
"minecraft:long_fire_resistance",
"minecraft:swiftness",
"minecraft:long_swiftness",
"minecraft:strong_swiftness",
"minecraft:slowness",
"minecraft:long_slowness",
"minecraft:strong_slowness",
"minecraft:turtle_master",
"minecraft:long_turtle_master",
"minecraft:strong_turtle_master",
"minecraft:water_breathing",
"minecraft:long_water_breathing",
"minecraft:healing",
"minecraft:strong_healing",
"minecraft:harming",
"minecraft:strong_harming",
"minecraft:poison",
"minecraft:long_poison",
"minecraft:strong_poison",
"minecraft:regeneration",
"minecraft:long_regeneration",
"minecraft:strong_regeneration",
"minecraft:strength",
"minecraft:long_strength",
"minecraft:strong_strength",
"minecraft:weakness",
"minecraft:long_weakness",
"minecraft:luck",
"minecraft:slow_falling",
"minecraft:long_slow_falling",
```
