### ISSUE TITLE
Option for sound categories

### ISSUE THREAD

**Issue by HakanUnsalP** [PluginBugs/Issues-ItemsAdder#1699]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Hakan Abi#4419

### Describe the solution you'd like

```
sound:
  break:
    name: block.amethyst_block.break
    # sound_category: block
    volume: 1
    pitch: 1
``` 

### Is your feature request related to a problem?

It's not a problem but I think it's a feature that should be added

### Describe alternatives you've considered

as i said above

### Additional context

https://user-images.githubusercontent.com/58227275/167939395-1bff38cf-1159-4dfc-ae3e-440647cf44f9.mp4
