### ISSUE TITLE
add a new event to differentitate offhand-click and mainhand-click

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#1746]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I notice that version 3.1.6 "fixed interact event not working with offhand items"
But I don't want some offhand items can interact.
For example,I make a backpack let people put offhand.And When in mainhand and right-click,they can open enderchest.
So add a new event to differentiate this two.
mainhand-interact
offhand-interact

### Is your feature request related to a problem?

yes ,version 3.1.6 

### Describe alternatives you've considered

add a new event to differentiate this two.
mainhand-interact
offhand-interact

**Comment by LoneDev6** [comment]
Implemented.
Thanks a lot for your extreme patience, I apologize for the really long delay.

Here is an example which will work in the next plugin release:
```yml
info:
  namespace: git
items:
  events_test_all:
    enabled: true
    display_name: events_test_all
    lore:
      - test all interact events
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: PAPER
    events:
      interact:
        left:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"left"}'
        right:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"right"}'
        left_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"left_shift"}'
        right_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"right_shift"}'
      interact_mainhand:
        left:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main left"}'
        right:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main right"}'
        left_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main left_shift"}'
        right_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main right_shift"}'
      interact_offhand:
        left:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off left"}'
        right:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off right"}'
        left_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off left_shift"}'
        right_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off right_shift"}'
  events_test_main_off:
    enabled: true
    display_name: events_test_main_off
    lore:
      - test only mainhand and offhand
      - interact events
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: PAPER
    events:
      interact_mainhand:
        left:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main left"}'
        right:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main right"}'
        left_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main left_shift"}'
        right_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"main right_shift"}'
      interact_offhand:
        left:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off left"}'
        right:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off right"}'
        left_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off left_shift"}'
        right_shift:
          execute_commands:
            change_me_1:
              command: 'tellraw {player} {"text":"off right_shift"}'
```
