### ISSUE TITLE
Hiding custom durability is not working

### ISSUE THREAD

**Issue by KoltaiArmy** [PluginBugs/Issues-ItemsAdder#1802]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Custom durability bug in item lore:

### Steps to reproduce the issue

in itemsadder config:

```
items:
  clover_leggings:
    display_name: "Leprechaun Pants"
    mmoitem:
      type: ARMOR
      id: CLOVER_LEGGINGS
    resource:
      generate: true
      textures:
        - item/izzy_clover_pack/clover_pants
    specific_properties:
      armor:
        slot: legs
        custom_armor: clover_set_armor
```

in mmoitems armor.yml config:

```
CLOVER_LEGGINGS:
  base:
    material: LEATHER_LEGGINGS
    required-level: 20.0
    armor: 1.0
    name: <tier-color>Goblin Nadrág
    displayed-type: 
    tier: COMMON
    lore:
    - '&eÉrték:'
    - '&e★☆&7☆☆☆☆☆☆☆☆'
    disable-enchanting: true
    disable-repairing: true
    disable-smithing: true
    max-durability: 500.0
    pvp-damage-reduction: -10.0
    pve-damage-reduction: 1.0
```

Itemsadder config.yml:

```
items:
  hide-custom-durability-lore: false
```

Result:
![image](https://user-images.githubusercontent.com/36732586/175437370-8643cbf5-2f60-4891-a403-2b00897e7c98.png)

If you set "hide-custom-durability-lore" to true, you get this:
![image](https://user-images.githubusercontent.com/36732586/175437406-97bf82dc-a0c8-438c-b22a-5f245cf4759d.png)

### Server version

Current: git-Purpur-1628 (MC: 1.18.2)*

_Additional info:_
MMOITEMS version: 6.7.3

### ItemsAdder Version

3.2.0c-beta6

### ProtocolLib Version

5.0.0-snapshot-b556

### LoneLibs Version

1.0.19
