### ISSUE TITLE
blocks keep disappearing and glitching 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1805]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

the texture of the blocks keeps disappearing and glitching 

### Steps to reproduce the issue

I just update itemsadder to 1.19
and place any block and the problem gonna happen

### Server version

Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)
You are running the latest version
Previous version: git-Paper-339 (MC: 1.18.2

### ItemsAdder Version

ItemsAdder version 3.2.0c-beta6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b569

### LoneLibs Version

LoneLibs version 1.0.19

### LibsDisguises Version (optional)

10.0.28

**Comment by SNokerYT** [comment]
https://user-images.githubusercontent.com/68678154/175565109-78037b81-cb85-4ec0-b948-d92008e9340a.mp4

**Comment by LoneDev6** [comment]
Send me the block configuration.
It's hard to help you without any info

**Comment by SNokerYT** [comment]
```
  polished_strata:     
    display_name: Polished Strata                                      
    permission: blockus
    resource:     
      material: PAPER  
      generate: true   
      textures:        
      - block/polished_strata.png   
      - block/polished_strata.png   
      - block/polished_strata.png   
      - block/polished_strata.png   
      - block/polished_strata.png   
      - block/polished_strata.png   
    specific_properties:                                               
      block:      
        placed_model:  
          type: REAL_NOTE                                              
          break_particles: ITEM                                        
        break_tools_whitelist:                                         
        - AXE     
        - HAND 
```
