### ISSUE TITLE
Loot support more rules (weather, day/night, moon phase)

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#1811]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nailm#9364

### Describe the solution you'd like

Hi LoneDevs, could you make loot support more rules like weather, day/night and [moon phase](https://minecraft.fandom.com/wiki/Moon#Phases)? so that the looting can be more flexible. For now it supports biome, which is great. But with more rules I think it would be more interesting. Like we can let player fish "night fish" only at nights, or "rain fish" when it's raining.

```
loots:
  fishing:
    pufferfish:
      biomes:
        - WARM_OCEAN
      weather:
      - RAIN
      - THUNDER
      time:
      - NIGHT
      moon_phase:
      - FULL_MOON
      - FIRST_QUARTER
      items:
        item_1:
          item: stardew_valley:pufferfish
          min_amount: 1
          max_amount: 1
          chance: 5
```

### Is your feature request related to a problem?

Just a feature request to make the plugin better :)

### Describe alternatives you've considered

None
