### ISSUE TITLE
[BUG] TILE type block with custom model doesn't render

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#182]
> [<img alt="Golshr" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Golshr) **Authored by [Golshr](https://github.com/Golshr)**
_<time datetime="2020-04-18T20:37:39Z" title="Saturday, April 18th 2020, 10:37:39 pm +02:00">Apr 18, 2020</time>_
_Closed <time datetime="2020-04-20T13:31:50Z" title="Monday, April 20th 2020, 3:31:50 pm +02:00">Apr 20, 2020</time>_
---

**Describe the bug**
When I use the TILE block model type instead of the REAL type, it doesn't render properly

**To Reproduce**
Here is my block declaration : 
```yml
  nuclear_waste:
    display_name: nuclear_waste
    resource:
      material: STONE
      generate: false
      model_path: blocks/nuclear_waste
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: BLOCK
```
Block is ok when type is REAL
Please note that it doesn't work even when the blocks shape is a cube inherited from minecraft default models.

**Screenshots**
https://i.imgur.com/5h4JVTI.jpg

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: 2.0.9
