### ISSUE TITLE
Missing `parent` tag under `resource`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1889]
```yml
    resource:
      generate: true
      parent: "your_namespace:item/my_parent_item"
      material: PAPER
      textures:
        - my_texture
```
