### ISSUE TITLE
[very serious bug] Items are crafted through the crafting table, regardless of the item tag.

### ISSUE THREAD

**Issue by ninesik** [PluginBugs/Issues-ItemsAdder#1903]
### Discord tag (optional)

나인#1927

### What happened?

Briefly explain.
Put the stick on the crafting table
The iaitem on which the stick is the base is treated as being raised.
Normal players use sticks to extract rare items.
big bug!

### Steps to reproduce the issue

1.Create an ia item based on a stick.
2.Crafting is made with the item created on the basis of step 1.
3. Place the stick on the crafting table.
4. The stick turns into a rare item!

### Server version

git-Purpur-"56447ea" (MC: 1.19.2)*
Previous: git-Purpur-"7b57f0c" (MC: 1.19.2)

### ItemsAdder Version

3.2.3f

### ProtocolLib Version

[20:34:39 INFO]: [PlugMan] Plugin Information: ProtocolLib
[20:34:39 INFO]: - Version: 5.0.0-SNAPSHOT-b593

### LoneLibs Version

[20:35:13 INFO]: [PlugMan] Plugin Information: LoneLibs
[20:35:13 INFO]: - Version: 1.0.20

### Problematic items yml configuration file (optional)

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 59.22.52.26
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 20
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Other files, you can drag and drop them here to upload. (optional)

```yml
info:
  namespace: inmc
recipes:
  crafting_table:
    diamond_soul:
      permission: items
      enabled: true
      pattern:
      - DGD
      - GDG
      - DGD
      ingredients:
        D: item15
        G: item8
      result:
        item: inmc:item9
        amount: 1
    emerald_soul:
      permission: items
      enabled: true
      pattern:
      - EGE
      - GEG
      - EGE
      ingredients:
        E: item16
        G: item8
      result:
        item: inmc:item10
        amount: 1
    ruby_soul:
      permission: items
      enabled: true
      pattern:
      - RGR
      - GRG
      - RGR
      ingredients:
        R: item5
        G: item8
      result:
        item: inmc:item11
        amount: 1
    sapair_soul:
      permission: items
      enabled: true
      pattern:
      - SGS
      - GSG
      - SGS
      ingredients:
        S: item6
        G: item8
      result:
        item: inmc:item12
        amount: 1
    jasujung_soul:
      permission: items
      enabled: true
      pattern:
      - JGJ
      - GJG
      - JGJ
      ingredients:
        J: item17
        G: item8
      result:
        item: inmc:item13
        amount: 1
    topaz_soul:
      permission: items
      enabled: true
      pattern:
      - TGT
      - GTG
      - TGT
      ingredients:
        T: item18
        G: item8
      result:
        item: inmc:item14
        amount: 1
  cooking:
    titanum:
      permission: items
      ingredient:
        item: inmc:item7
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 5
      cook_time: 1200
      result:
        item: inmc:item8
        amount: 1
items:
  items1:
    display_name: '&f&l근원'
    permission: items
    mmoitem:
      type: material
      id: 근원
    resource:
      material: STICK
      generate: true
      textures:
      - item/1.png
  items2:
    display_name: '&f광물의 기운'
    permission: items
    mmoitem:
      type: material
      id: 광물의기운
    resource:
      material: STICK
      generate: true
      textures:
      - item/2.png
  items3:
    display_name: '&f작물의 기운'
    permission: items
    mmoitem:
      type: material
      id: 작물의기운
    resource:
      material: STICK
      generate: true
      textures:
      - item/3.png
  items4:
    display_name: '&f영혼석'
    permission: items
    mmoitem:
      type: material
      id: 영혼석
    resource:
      material: STICK
      generate: false
      model_path: "item/4"
  item5:
    display_name: 루비
    permission: items
    mmoitem:
      type: material
      id: 루비
    resource:
      material: STICK
      generate: false
      model_path: "item/5"
  item6:
    display_name: 사파이어
    permission: items
    mmoitem:
      type: material
      id: 사파이어
    resource:
      material: STICK
      generate: false
      model_path: "item/6"
  item7:
    display_name: 강철원석
    permission: items
    mmoitem:
      type: material
      id: 강철원석
    resource:
      material: STICK
      generate: false
      model_path: "item/7"
  item8:
    display_name: 강철주괴
    permission: items
    mmoitem:
      type: material
      id: 강철주괴
    resource:
      material: STICK
      generate: false
      model_path: "item/8"
  item9:
    display_name: 다이아의기운
    permission: items
    mmoitem:
      type: material
      id: 다이아의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/9"
  item10:
    display_name: 에메랄드의기운
    permission: items
    mmoitem:
      type: material
      id: 에메랄드의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/10"
  item11:
    display_name: 루비의기운
    permission: items
    mmoitem:
      type: material
      id: 루비의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/11"
  item12:
    display_name: 사파이어의기운
    permission: items
    mmoitem:
      type: material
      id: 사파이어의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/12"
  item13:
    display_name: 결정석의기운
    permission: items
    mmoitem:
      type: material
      id: 결정석의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/13"
  item14:
    display_name: 토파즈의기운
    permission: items
    mmoitem:
      type: material
      id: 토파즈의기운
    resource:
      material: STICK
      generate: false
      model_path: "item/14"
  item15:
    display_name: 강화다이아몬드
    permission: items
    mmoitem:
      type: material
      id: 강화다이아몬드
    resource:
      material: STICK
      generate: false
      model_path: "item/15"
  item16:
    display_name: 강화에메랄드
    permission: items
    mmoitem:
      type: material
      id: 강화에메랄드
    resource:
      material: STICK
      generate: false
      model_path: "item/16"
  item17:
    display_name: 결정석
    permission: items
    mmoitem:
      type: material
      id: 결정석
    resource:
      material: STICK
      generate: false
      model_path: "item/17"
  item18:
    display_name: 토파즈
    permission: items
    mmoitem:
      type: material
      id: 토파즈
    resource:
      material: STICK
      generate: false
      model_path: "item/18"
  item19:
    display_name: 무지개파편
    permission: items
    mmoitem:
      type: material
      id: 무지개파편
    resource:
      material: STICK
      generate: true
      textures:
      - item/19.png
  item20:
    display_name: 특수금괴
    permission: items
    mmoitem:
      type: material
      id: 특수금괴
    resource:
      material: STICK
      generate: false
      model_path: "item/20"
  item21:
    display_name: 젖병
    permission: items
    mmoitem:
      type: material
      id: 젖병
    resource:
      material: STICK
      generate: false
      model_path: "item/21"
  item22:
    display_name: 단단한뼈
    permission: items
    mmoitem:
      type: material
      id: 단단한뼈
    resource:
      material: STICK
      generate: false
      model_path: "item/22"
  item23:
    display_name: 꺼지지않는불
    permission: items
    mmoitem:
      type: material
      id: 꺼지지않는불
    resource:
      material: STICK
      generate: false
      model_path: "item/23"
  item24:
    display_name: 투명핵
    permission: items
    mmoitem:
      type: material
      id: 투명핵
    resource:
      material: STICK
      generate: false
      model_path: "item/24"
  item25:
    display_name: 특수거미줄
    permission: items
    mmoitem:
      type: material
      id: 특수거미줄
    resource:
      material: STICK
      generate: true
      textures:
      - item/25.png
  item26:
    display_name: 피묻은화살촉
    permission: items
    mmoitem:
      type: material
      id: 피묻은화살촉
    resource:
      material: STICK
      generate: false
      model_path: "item/26"
  item27:
    display_name: 더러운천
    permission: items
    mmoitem:
      type: material
      id: 더러운천
    resource:
      material: STICK
      generate: false
      model_path: "item/27"
  item28:
    display_name: 봉인된파편
    permission: items
    mmoitem:
      type: material
      id: 봉인된파편
    resource:
      material: STICK
      generate: false
      model_path: "item/28"
  items29:
    display_name: '&f&l테스트29'
    permission: items
    mmoitem:
      type: consumable
      id: 상급강화석
    resource:
      material: STICK
      generate: true
      textures:
      - item/29.png
  items30:
    display_name: '&f&l테스트30'
    permission: items
    mmoitem:
      type: consumable
      id: 강화석파편
    resource:
      material: STICK
      generate: true
      textures:
      - item/30.png
  items31:
    display_name: '&f&l테스트31'
    permission: items
    mmoitem:
      type: consumable
      id: 중급강화석
    resource:
      material: STICK
      generate: true
      textures:
      - item/31.png
  items32:
    display_name: '&f&l테스트32'
    permission: items
    resource:
      material: STICK
      generate: true
      textures:
      - item/32.png
  items33:
    display_name: '&f&l테스트33'
    permission: items
    mmoitem:
      type: consumable
      id: 하급강화석
    resource:
      material: STICK
      generate: true
      textures:
      - item/33.png
  items35:
    display_name: '&f&l겜블코인'
    permission: items
    resource:
      material: STICK
      generate: true
      textures:
      - item/35.png
```
