### ISSUE TITLE
IA compatibility with Denizen

### ISSUE THREAD

**Issue by Lexon2** [PluginBugs/Issues-ItemsAdder#1986]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Lexon2#6683

### Describe the solution you'd like

It would be nice to add ItemsAdder compatibility with Denizen like the Skript API.

### Is your feature request related to a problem?

Yeah, it's very hard to use items from IA in Denizen. For example, I can't use them in custom inventories/guis created by Denizen. 
Or, the same problem with blocks. I need to write scripts that will load IA cache from storage folder and then check whether a note block is custom or not. It's called "Overengineering" :)

### Describe alternatives you've considered

There are no alternatives.

### Additional context

P.s. I have a lot of ideas that could work great with ItemsAdder. :)

**Comment by LoneDev6** [comment]
I'm not familiar with Denizen, can you share more information?
Thanks

**Comment by Lexon2** [comment]
> I'm not familiar with Denizen, can you share more information? Thanks

Thank you for your answer!
To be honest, I'm not very strong in java, so the most valuable thing I can provide you with is the [GitHub page](https://github.com/DenizenScript/Denizen)

Also, there are some links from Denizen guide page ( not sure if needed ):
https://guide.denizenscript.com/guides/contributing/building.html
https://guide.denizenscript.com/guides/contributing/property-dev.html

To create item compatibility, I think you should check out some info about **Tags**, **Commands** and **Events** in Denizen. For example, this [link](https://github.com/DenizenScript/Denizen/tree/dev/plugin/src/main/java/com/denizenscript/denizen) ( not sure ):

**Comment by LoneDev6** [comment]
I'll try to add compatibility in the next update, thanks

**Comment by Lexon2** [comment]
> I'll try to add compatibility in the next update, thanks

Thx :)

**Comment by LoneDev6** [comment]
Example script which will be working on the new update:
```yml
my_world_script:
    type: world
    events:
        after player left clicks block:
            - narrate " "
            - if <player.item_in_hand.is_ia_block>:
                - narrate "Left click item is a custom block! <&6><player.item_in_hand.ia_namespaced_id>"
            - else:
                - narrate "Left click item is NOT a custom block! <&7><player.item_in_hand.material>"
            - narrate " "
        after player right clicks block:
            - if <player.is_sneaking>:
                - set_custom_block <context.location> ruby_block 
            - else:
                - narrate " "
                - if <player.item_in_hand.is_ia_item>:
                    - narrate "Right click item is a custom item! <&6><player.item_in_hand.ia_namespaced_id>"
                - else:
                    - narrate "Right click item is NOT a custom item! <&7><player.item_in_hand.material>"

                - if <context.location.is_ia_block>:
                    - narrate "Interacted block is a custom block! <&6><context.location.ia_namespaced_id>"
                - else:
                    - narrate "Interacted block is NOT a custom block!"
                - narrate " "
```
