### ISSUE TITLE
Add support to glow item frame (Furniture)

### ISSUE THREAD

**Issue by rafaelflromao** [PluginBugs/Issues-ItemsAdder#2011]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

AtlasGamerZ#7577

### Describe the solution you'd like

I would like to suggest to add support to glow item frame to furniture

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

I don't know another alternative.

### Additional context

I would like to add furniture that glows instead of emit light but it isn't possible once the only way to do that it's through glow item frame.

**Comment by LoneDev6** [comment]
Will be added in the new update.
```yml
    behaviours:
      furniture:
        small: true
        light_level: 7
        solid: true
        entity: glow_item_frame
```
