### ISSUE TITLE
HyperStones Anvil Compatibility Issue

### ISSUE THREAD

**Issue by MasterWolfx** [PluginBugs/Issues-ItemsAdder#2014]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

MasterWolfx - Leonardo C.#2503

### What happened?

Using an items adder item model inside HyperStones plugin leads to empty result inside the anvil.

### Steps to reproduce the issue

1. Insert an ItemsAdder item name inside "hyperstone.item-type" section of HyperStones config.
```yaml
hyperstone: 
    name: '&3&nHyperShard'
    lore:
      - "&3&l* &7Use this inside an anvil"
      - "&7with a weapon or an armor"
      - "&7to upgrade it."
    item-type: items_adder_item # <---- HERE
    glow: true
    min-drop-amount: 1
    max-drop-amount: 4
```
2. If you try to upgrade an item inside the anvil (ex. wooden sword + hyperstone) you will get an empty result. However if you click on the result slot HyperStones' upgrade system will still work.

### ItemsAdder Version

3.2.3-r9

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
Cannot reproduce the issue

https://user-images.githubusercontent.com/27242001/196936783-38b8e2bb-c929-432f-9b37-b11116a60226.mp4

Hyperstones configuration:
```yml
items:
  hyperstone:
    name: '&3&nHyperShard'
    lore:
      - "&3&l* &7Use this inside an anvil"
      - "&7with a weapon or an armor"
      - "&7to upgrade it."
    item-type: plastic
    glow: true
    min-drop-amount: 1
    max-drop-amount: 4
```

Note: the CustomModelData is not applied by your plugin, you should fix that.
