### ISSUE TITLE
Itemsadder blocks giving 10 mmocore profession experience to all professions on break

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-ItemsAdder#2028]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Have been going insane trying to figure out the cause of this issue. On a whim unloaded ItemsAdder and realized the problem stopped. It's for any ItemsAdder block...this is just what I used as example. 

Video: https://streamable.com/nsekoz

Block config from video:
```
  pot:
    display_name: Farming Plot
    lore:
    - "&f"
    - "&f"
    - "&7These special farming plots"
    - "&7can be used to grow crops."
    resource:
      material: PAPER
      generate: false
      model_path: 'base/pot'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
```

### Steps to reproduce the issue

1. Place IA real_note block
2. Break IA real_note block
3. Realize it's giving 10 MMOcore profession experience to all professions
4. Unload itemsadder
5. Realize issue is fixed

### Server version

git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### ItemsAdder Version

3.2.3-r9

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/nsekoz
