### ISSUE TITLE
get EXP for crafting

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#2062]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Raccoon#4485

### Describe the solution you'd like

the possibility to get EXP for crafting an item.

### Is your feature request related to a problem?

yes. because i want to get EXP fpr crafting stuff =)

### Describe alternatives you've considered

As an example:
```
   knife:
      permission: knife
      enabled: true
      pattern:
      - XXX
      - XDX
      - XSX
      ingredients:
        D: IRON_NUGGET
        S: STICK
      result:
        item: knife
        amount: 1
        give_exp:
          chance: 100
          min_amount: 0
          max_amount: 3
```
```
      result:
        give_exp:
          chance: 100
          min_amount: 0
          max_amount: 3
```
