### ISSUE TITLE
More Pack Hosting Options 

### ISSUE THREAD

**Issue by thefourcraft** [PluginBugs/Issues-ItemsAdder#2130]
## Patreon Upload Service
A private server for Patreon monthly supporters... 
```yml
patreon:
    enabled: true
    key: "" # Your Patreon-Uploader Key
```

## Amazon S3 Support For Pack Hosting
Adding Support for the [AWS S3 API](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html)
```yml
resource_pack:
  aws:
    enabled: true
    endpoint: s3.amazonaws.com # The endpoint of your S3 service
    region: eu-central-1 # The region of your S3 endpoint
    bucket: examplebucket # The name of your S3 bucket
    key_id: "" # Your S3 key id
    key_secret: "" # Your S3 key secret   
```
it will also add support for [Cloudflare's R2](https://www.cloudflare.com/lp/pg-r2/)
An example can be found on the Nova | Modding Framework code, they have support for [AWS S3](https://github.com/xenondevs/Nova/blob/main/nova/src/main/kotlin/xyz/xenondevs/nova/data/resources/upload/service/S3.kt)

### Describe alternatives you've considered

While Self Hosting Is good, it can be slow when a lot of players join at the same time...
it's not IA's fault it's mostly the server while updating to better hardware can improve this I think large server networks need better solutions!
it's also hard to keep track of all the files on individual servers
S3 support would eliminate that issue, and make it possible for large networks to take better control of their packs
