### ISSUE TITLE
broken recipes

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#2137]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Raccoon#4485

### What happened?

I have added steel as metal.
With the ingot it is possible to make nuggets out of it.
 Here is the recipe:
```
    steel_barren_nugget:
      permission: steelsmelting
      enabled: true
      shapeless: true
      ingredients:
        s: stahlbarren
      result:
        item: steel_nugget
        amount: 9
```

However, I get the error that in some slots I get another item, which should also be created with a steel ingot. However, the recipe is completely wrong and yet I get the item
```
    steel_boots:
      permission: steelarmor
      enabled: true
      pattern:
      - XXX
      - sXs
      - sXs
      ingredients:
        s: stahlbarren
      result:
        item: steel_boots
        amount: 1
```

### Steps to reproduce the issue

1. Both recipes work in older updates
2. tried to craft it, then the error.
3. tried to change names. but same error only with a different item which also needs the steel ingot

### ItemsAdder Version

3.3.0-beta-r8

### ProtocolLib Version

5.0.0 br602

### LoneLibs Version

1.0.21

### Error (optional)

```shell
No errors
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/62447455/204092091-bba4e6c8-497f-436c-b246-859b8f728337.mp4
