### ISSUE TITLE
Add MiniMessage Support for Item DisplayName and Lore

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#2224]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nailm#9364

### Describe the solution you'd like

I would like to use [MiniMessage format](https://docs.adventure.kyori.net/minimessage/index.html) in the item display name and lore, so the presentation would be more flexible.

For these reasons:
- Legacy format (&a&1 etc) cannot leverage the full power of "Text Components" added in MC 1.7, especially the [custom font for certain text](https://minecraft.fandom.com/wiki/Java_Edition_1.16#General_2) added in MC 1.16.
- With legacy format, you cannot specify a custom font for text that works with `Force Unicode Font: On` cuz all the text are forced to use the `default` font under `minecraft` namespace. Also, all the custom font chars break (they'd all become ☐) if the client have `Force Unicode Font: On`, which is bad.
- While using MiniMessage format, we can specify a custom font under some custom namespace like `myfontimages` for certain text. The custom font images rendered this way won't be affected by the `Force Unicode Font: On` at all. So the ☐ issue will be resolved!
- ItemsAdder already internally uses the `net.kyori` libs for generating Text Components, and it's time to take more advantage of it!

### Is your feature request related to a problem?

Yes, to deal with the `Force Unicode Font: On` issue with clients, and to provide more options for advanced users.

### Describe alternatives you've considered

None

### Additional context

I am aware of that SpigotAPI doesn't provide any methods to write Component Text in the item displayname & lore and it might create some obstacles to implemen this feature. But the good news is that the Spigot implementation (the class `CraftMetaItem`, [link](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java#266)) stores the item displayname and lore as raw JSON string, and this dates back to this [commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/560b65c4f8a15619aaa4a1737c7040f21e725cce#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java). Maybe using reflection + [gson serializer](https://docs.adventure.kyori.net/serializer/gson.html) can easily achieve this? tho very old MC versions might not be able to have this feature :x

Another way to do it might be directly write raw JSON strings in the item NBT tags.

**Comment by Akiranya** [comment]
I think it's better provide an option in the `config.yml` to **only** use MiniMessage format in the displayname and lore, instead of letting legacy and MIniMessage format coexist. Making them coexist would be very buggy as shown in another plugin (MMOItems).

**Comment by iqtesterr** [comment]
+1

**Comment by LoneDev6** [comment]
> Legacy format (&a&1 etc) cannot leverage the full power of "Text Components" added in MC 1.7, especially the [custom font for certain text](https://minecraft.fandom.com/wiki/Java_Edition_1.16#General_2) added in MC 1.16.

You can already do that using the `nbt` attribute to inject nbt properties.
https://itemsadder.devs.beer/plugin-usage/adding-content/custom-item-nbt
I updated the wiki page with this example too, for other admins to learn.

```yml
items:
  example_item_custom_name:
    enabled: true
    display_name: example_item_custom_name
    permission: custom.example_item_custom_name
    nbt: "{display:{Name:'{\"text\":\"TEST\", \"font\": \"alt\"}'}}"
```

NOTE: don't forget to escape all the `"` characters with `\` in front of them, or the file won't work anymore.

> With legacy format, you cannot specify a custom font for text that works with `Force Unicode Font: On` cuz all the text are forced to use the `default` font under `minecraft` namespace. Also, all the custom font chars break (they'd all become ☐) if the client have `Force Unicode Font: On`, which is bad.
> While using MiniMessage format, we can specify a custom font under some custom namespace like `myfontimages` for certain text. The custom font images rendered this way won't be affected by the `Force Unicode Font: On` at all. So the ☐ issue will be resolved!

This was already fixed by ItemsAdder in recent updates and doesn't require you to specify a custom font each time.
`Force Unicode Font: On` doesn't interfere anymore with any emoji/font image since some updates ago.

> ItemsAdder already internally uses the `net.kyori` libs for generating Text Components, and it's time to take more advantage of it!

I don't think it's really needed for now.

**Comment by LoneDev6** [comment]
Nevermind.
I implemented Minimessage support so you can easily customize your texts., I hope you will enjoy this new feature.

# NOTE
This requires LoneLibs 1.0.26 which will be published with the new ItemsAdder update.

## An example
```yml
info:
  namespace: git_2224
  dictionary-lang: en
dictionary:
  display-name-test_gradient_dictionary: <b><color:#57ff5c>test</color></b><gradient:#ff00ee:#f79459>Amogus</gradient>
items:
  test_gradient_dictionary:
    display_name: display-name-test_gradient_dictionary
    lore:
      - "&6yo0"
      - "&2yo1"
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: PAPER
  test_font:
    display_name: <gradient:#ff00ee:#f79459><font:alt>Alt font used for this item</font></gradient>
    lore:
      - "<gradient:#ff00ee:#f79459><font:alt>Alt font used for this item</font></gradient>"
      - "<gradient:#ff00ee:#f79459><font:alt>Alt font used for this item</font></gradient>"
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: PAPER   
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/5242f216-17de-4d54-87b7-0131b24741d5)
t/clear

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/27cfec18-ab66-4555-8d97-4e7ad6fe770b)
