### ISSUE TITLE
Keep items updated with configurations

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2247]
Continuation of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2166

Note: This task is very complex to achieve and can lead to an extreme amount of incompatibilities.
This feature can be enabled in the config.yml of itemsadder since not everyone will want it for the risk of introducing incompatibilities.

## Item updating ligic

- add enchants which are in the yml file and not in the world item but keep enchants that are not in the yml (because users might have enchanted the item)
- update the name and lore (even if this might cause some information to be lost because the lore might have been edited by another plugin)
- I won't update the custommodeldata since itemsadder already ensures that this value is not changed in any way as it has a cache system for this particular reason. Also updating the custommodeldata will break the `replace_properties` [feature](https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/events/actions#list-of-actions-properties), for example for the [lightsaber](https://github.com/ItemsAdder/OtherPacks/blob/e0205836ed4f5d0da56b21777d11fec1cf8dded4/contents/iaspecial_swords/configs/items/lightsabers.yml) of the default pack.
- I will automatically update the custom (leather) armors color code in case it changed in the yml file to make sure the armors don't have the wrong "worn" texture
- ??? Do you have any other thing in mind?

## Ability to decide when to trigger the item updater

Some of them may impact the performance but would be convenient

1. Picking up an item
2. Joining server (update all items in the inventory)
3. Changing world (same as above)
4. Placing an item in the craft table
5. Moving & draging an item

**Comment by PSYCHEER** [comment]
4. Placing an item in the craft table
Is not needed at all as and maybe 5. as you can do it on inventory click on item `onInventoryClickItem`

Will remove not needed updates as drag, move etc, just as far as item will be clicked, will be updated

**Comment by nhanledev** [comment]
I think each item should include a configuration setting to specify whether it needs to be updated to stay in sync with the server configuration. That behavior can be seen in other plugins.

**Comment by LoneDev6** [comment]
Implemented command `/iaitem enable-itemstack-auto-update` and `/iaitem disable-itemstack-auto-update`  to toggle auto update for the current hold itemstack.
This is useful if you want to have a single particular instance of the item that can't change during updates.
It will save a custom NBT attribute into the itemstack which will be checked later on during update and will make the itemstack skipped.

You cal also disable auto-updating for certain items completely, in their configuration file, because for example you might want to change the attack damage of a sword to a higher value and also their recipe or drop rate, but you don't want already crafted swords to have the new attack damage because they would be too op, because people might have crafted a lot of them. So the already crafted swords will still keep the old attack damage.
To do so you have to set this:

```yml
  test_item2:
    name: Test Item 2
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: IRON_SWORD
    max_stack_size: 16
    lore:
    - lol
    - lol
    enchants:
    - BREACH
    attribute_modifiers:
      head:
        armor_toughness: 30
    auto_update:
      enabled: false # <--- here
```

It can also be globally disabled in `config.yml` for every item in your configurations.
```yml
items:
# ....
  auto_update:
    enabled: true # <--- here
    fix_unstackable_items_on_click: true
```

(`fix_unstackable_items_on_click` refers to #4787)
