### ISSUE TITLE
[Suggestion] Run Java code on click event

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#227]
> [<img alt="Golshr" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Golshr) **Authored by [Golshr](https://github.com/Golshr)**
_<time datetime="2020-05-04T22:02:00Z" title="Tuesday, May 5th 2020, 12:02:00 am +02:00">May 5, 2020</time>_
_Closed <time datetime="2020-07-02T10:34:05Z" title="Thursday, July 2nd 2020, 12:34:05 pm +02:00">Jul 2, 2020</time>_
---

**Is your feature request related to a problem? Please describe.**
I'm developing plugin for a server and I would like to easily make link between it and ItemsAdder without creating a command to run for each functionality. I would like to run direct java code from click events.

**Describe the solution you'd like**
Something like that : 
```yml
events:
  right_click:
    java: 'Bukkit.getPlayer("Golshr").sendTitle("xyzzy", "");'
```
We can also imagine having already defined local variables to do things like : 
```yml
events:
  right_click:
    java: 'player.sendMessage("this is a " + targetedBlock.getType().toString());'
```
**Describe alternatives you've considered**
I made a HashMap<Block,Runnable> and ~~it looks like shit~~ it's not really efficient and doesn't exactly do the thing I want
