### ISSUE TITLE
Several bugs occur when repairing items that have custom durabilities

### ISSUE THREAD

**Issue by AllayBreeze** [PluginBugs/Issues-ItemsAdder#2285]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Raenzil#7359

### What happened?

When using a grindstone to merge two same IA items (I use Mythril Helmet in the video): 
1. Sometimes the output item's custom durability is same as the first input item, both lore and NBT.
2. Sometimes two items with the same material type, but different IA item type (or an IA item with a vanilla item) can be put into two input slots. The output item keep same NBTs as the first input item, but cannot be taken out.

When using an anvil to merge two same IA items:
The output item's custom durability will always be full.

When trying to merge two same IA items in crafting slots:
No any outputs.

### Steps to reproduce the issue

1. Create an IA item that has custom durability.
2. Get two items and make them damaged, and get a vanilla item with the same material type as the IA item, too.
3. Put two IA items in a grindstone for several times, and sometimes the output item will have wrong durability.
4. Try to put the IA item with the vanilla item in a grindstome for several times, and sometimes they're all be put successfully in input slots.
5. Put two IA items in an anvil, and the output item will always be brand new.
6. Put two IA items in crafting slots (in player inventory or a crafting table), and there'll be no any output.

### Server version

Current: git-Purpur-1900 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLivs version 1.0.22

### FULL server log

https://pastebin.com/ghxkcQn6

### Other files, you can drag and drop them here to upload. (optional)

```yml
info:
  namespace: terraria
armors_rendering:
  mythril_armor:
    color: '#d61003'
    layer_1: armor/mythril_armor_layer1
    layer_2: armor/mythril_armor_layer2
    use_color: false
items:
  mythril_helmet:
    display_name: display-name-mythril_helmet
    permission: mythril_armor
    resource:
      generate: true
      textures:
      - item/armor/mythril_helmet
    durability:
      max_custom_durability: 275
    specific_properties:
      armor:
        slot: head
        custom_armor: mythril_armor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 2
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/108282297/213912993-dfbe4433-0a06-4ac6-a41a-56f599e22e3b.mp4
