### ISSUE TITLE
MMOItems revision system not working on ItemsAdder item

### ISSUE THREAD

**Issue by Syrent** [PluginBugs/Issues-ItemsAdder#2305]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Syrent#1748

### What happened?

ItemsAdder doesn't support the MMOItems revision system. The ItemsAdder texture just disappears.

### Steps to reproduce the issue

1. Create an ItemsAdder item with this configuration:
```yml
info:
  namespace: ed
items:
  edsword:
    display_name: Ed Sword
    permission: edsword
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: item/emerald_in_the_desert_sword
    mmoitem:
      id: EMERALD_SWORD
      type: SWORD
```
2. Create an MMOItems item with this configuration:
```yml
EMERALD_SWORD:
  base:
    material: NETHERITE_SWORD
    name: <gradient:green:white>Emerald Sword
    enchants:
      sharpness: 6.0
      fire_aspect: 2.0
    tier: RARE
    lore: []
    revision-id: 1
```
3. Reload MMOItems using `/mi reload`
4. Reload ItemsAdder using `/iareload`
5. Get the item from `/ia` menu
6. Change the `fire_aspect` enchant from level `2` to level `1`
7. Change MMOItems item `revision-id` to `1`
```yml
EMERALD_SWORD:
  base:
    material: NETHERITE_SWORD
    name: <gradient:green:white>Emerald Sword
    enchants:
      sharpness: 6.0
      fire_aspect: 1.0
    tier: RARE
    lore: []
    revision-id: 2
```
8. Reload MMOItems using `/mi reload`
9. Reload ItemsAdder using `/iareload`
10. Drop and pickup ItemsAdder item (MMOItems update items data on certain events like pickup)
11. Item data being updated but **the texture disappear**

### Server version

Current: git-Purpur-1892 (MC: 1.19.3)*
Previous: git-Purpur-1876 (MC: 1.19.3)
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10527799/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ed
items:
  edsword:
    display_name: Ed Sword
    permission: edsword
    resource:
      material: NETHERITE_SWORD
      generate: false # Also tested with generate true
      model_path: item/emerald_in_the_desert_sword
    mmoitem:
      id: EMERALD_SWORD
      type: SWORD
```

### Other files, you can drag and drop them here to upload. (optional)

```yml
EMERALD_SWORD:
  base:
    material: NETHERITE_SWORD
    name: <gradient:green:white>Emerald Sword
    enchants:
      sharpness: 1.0
      fire_aspect: 2.0
    tier: RARE

    lore: []
    revision-id: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)
https://youtu.be/0HY2B5s7GUw

**Comment by LoneDev6** [comment]
I see no way to make the MMOItems revision system compatible since MMOitems doesn't know about itemsadder.
The only solution I have in mind is somehow to disable the revision system for these particular items.
I suggest you to contact MMOitems developers.

**Comment by Syrent** [comment]
Temporary solution for those who have the same problem:
Set custom model data for your item and use it in MMOItems.
Example:
```yml
info:
  namespace: ed
items:
  edsword:
    display_name: Ed Sword
    permission: edsword
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: item/emerald_in_the_desert_sword
      model_id: 2000
```
```yml
EMERALD_SWORD:
  base:
    material: NETHERITE_SWORD
    name: <gradient:green:white>Emerald Sword
    enchants:
      sharpness: 6
      fire_aspect: 2
      irreparable: 1
      frailty: 1
    custom-model-data: 2000
    max-durability: 500
    tier: RARE
    lore: []
    revision-id: 1
```

Note: You can check the item CustomModelData using `/iatag` command
Note: If CustomModelData not working try `/iacleancache items` command

Wiki link for CustomModelData: https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/resource#manually-specify-custom_model_data
