### ISSUE TITLE
Kicking player upon switching server

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#2331]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Lulux#4614

### What happened?

When changing servers I'm getting kicked for "not accepting the resourcepack" 

### Steps to reproduce the issue
0. Make sure to be on a velocity proxy with BungeePackFix
1. Log in on the main server where the texture pack is on apply on join
2. go to your lobby for example (that has the texture pack but not on apply join and it's the same one)
3. go back to the main server and you're kicked ! 
4. (BONUS) if it doesn't work try to be a new player without perms

### Server version

This server is running Pufferfish version git-Pufferfish-47 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 9b8cdc7 on HEAD)
You are running 10 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0 b606

### LoneLibs Version

1.0.23

### FULL server log

private

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 10
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://gyazo.com/addd4b5b6ca83112f93450dda0f591a0

**Comment by DarkyCat** [comment]
Somе problеm (On Vеlocity)

**Comment by LoneDev6** [comment]
Are you sure that your client has enabled the resourcepack in the server settings in the multiplayer menu?
![image](https://user-images.githubusercontent.com/27242001/221886088-a85e3061-01ff-456c-b09c-e863b88d1ff8.png)

**Comment by LuluxClient** [comment]
> Are you sure that your client has enabled the resourcepack in the server settings in the multiplayer menu?
> 
> ![image](https://user-images.githubusercontent.com/27242001/221886088-a85e3061-01ff-456c-b09c-e863b88d1ff8.png)
> 
> 

Yes

**Comment by LoneDev6** [comment]
Can't reproduce the issue.
There is something wrong in your network.

https://user-images.githubusercontent.com/27242001/229791375-e10ff53c-ee0c-4060-8f67-9d95a3c5b54c.mp4



## ItemsAdder config server 1:

```yml
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: 127.0.0.1:8163/generated.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
```

## ItemsAdder config server 2:

```yml
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ""
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
```

## Velocity bungeepackfix config:

```yml
messages:
  minimessage_support: true
  ignored_pack:
    enabled: true
    message: "&6Skipped resourcepack installation (you already loaded it). <red> test"
equal_pack_attributes:
  hash: true
  forced: true
  prompt_message: true
ignore_hash_in_url: true
main_spigot_server_name: server_1
ignored_servers:
  - ignored_1
  - ignored_2
log:
  ignored_respack: true
  sent_respack: true
  debug: true
```
