### ISSUE TITLE
[Suggestion] Add an action that allows you to cancel the actions or events of the vanilla items

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#2335]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Chimal1994#7902

### Describe the solution you'd like

Add an action that allows you to cancel the actions or events of the vanilla items

CancelVanilla or CancelEvent

CancelEvent:
    effects:
    - all

### Is your feature request related to a problem?

Yes, I discovered that ItemsAdder is missing this while trying to create enchanted apples with effects...

At first I decided to use ordinary apples and add effects to them, soon I realized that I could only use them when I was hungry... which was not what I wanted, so I took as a base a golden apple that you can eat whenever you want, and I soon realized that it is impossible to remove its effects...

events:
    eat:
        remove_position_effect:
            type: regeneration <--- didn't work

events:
    eat:
       execute_commands:
           cmd1:
                command: "/effect clear {player}minecraft:regeneration" <--- didn't work either

In the end I had to resort to another plugin, to do what I wanted... please add a cancelEvent

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment]
```yml
items:
  test_golden_apple:
    enabled: true
    display_name: test_golden_apple
    permission: special.test_golden_apple
    resource:
      material: GOLDEN_APPLE
      generate: false
      model_path: yourmodel
    events:
      eat:
        cancel: true
```

Please use the [vscode extension ](https://marketplace.visualstudio.com/items?itemName=LoneDev.ia-vscode)to edit your items.
