### ISSUE TITLE
replacing one placed furniture model with another

### ISSUE THREAD

**Issue by Radmir52** [PluginBugs/Issues-ItemsAdder#2337]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Идея кода такова: имеются 2 модели ставней для окон - открытые и закрытые. Щелчок по левой кнопке мыши закрытые ставни открывает, а открытые - закрывает.

Не удается заменить одну модель мебели на другую таким кодом:

```yml
  stavny_oak_close:
    display_name: stavny_oak_close
    resource:
      material: FLINT
      generate: false
      model_path: stavny/stavny_oak_close
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_open
             restorable: true
         play_sound:
           name: block.chest.open
           volume: 1
           pitch: 1
```

### Steps to reproduce the issue

1. Put the closed shutter model
2. By clicking on the right mouse button, the model of closed shutters should change to another model - open shutters

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.5.0 - b606

### LoneLibs Version

1.0.23
