### ISSUE TITLE
Add conditions to events

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#2341]
### Discord tag (optional)

Chimal1994#7902

### Describe the solution you'd like

Add conditions to the events to be able to perform more complex actions:

Example... extracting sap from a tree with a tool:

```yml
events:
  condition:
    in: BLOCK
    - OAK_LOG
  interact:
    right:
      give_item: my_items:sap
```

Example 2 get an item from a mob without having to kill it:

```yml
events:
  condition:
    in: MOB
    - CUSTOM_MOB_CHOCOLATE_COW
  interact:
    right:
      give_item: my_items:chocolate
```

Example_3 be able to create custom cubes

```yml
events:
  condition:
    in: LIQUID
    - WATER 
  interact:
    right:
      give_item: my_items:full_copper_bucket
  condition_2:
    in: LIQUID
    - LAVA
  interact:
    right:
      give_item: my_items:full_lava_copper_bucket
```

### Is your feature request related to a problem?

yes, currently there are not enough ways to set specific conditions for an action to happen, we only have the player stats but they are not useful for many ideas

**Comment by LoneDev6** [comment]
> Example... extracting sap from a tree with a tool:

This would introduce a duplication bug as people can right click the block infinitely and still get the `my_items:sap` item

> Example 2 get an item from a mob without having to kill it:

This can be introduced if I implement a new rule specifically for entity interact event.

```yml
    events:
      interact:
        entity:
          run_only_if:
            entity: my_mobs:custom_cow
          drop_item:
            item: my_custom_item
```

> Example_3 be able to create custom cubes

You mean custom buckets on cubes?
This would be more complex than implementing the configuration example you provided because I'd have to remove the water block where you interact, then give the filled bucket.
This is more likely a feature request for a bucket behaviour. I can implement it if you really need that.
