### ISSUE TITLE
Same `custom model data` with different `material type` cannot merge if using custom json `overrides` definition

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#2369]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Nailm#9364

### What happened?

IA cannot correctly merge the item model overrides if:

1. a model is defined in the IA config, with custom model id being X and material being Y
2. then I manually define a model override by writing a json file, with custom model id also being X but for a different material other than Y

Ideally, IA should be able to merge the files because the material is different, despite the custom model id is the same.

### Steps to reproduce the issue

I have defined a custom furniture like this (the file is at `plugins/ItemsAdder/contents/furnitures/configs/anniversary/1st_year_cake.yml`):

```yaml
info:
  namespace: furnitures
items:
  1st_year_cake:
    display_name: 1st Year Cake
    resource:
      material: PAPER
      generate: false
      model_id: 40000
      model_path: anniversary/1st_year_cake
    behaviours:
      furniture:
        entity: item_frame
        gravity: false
        small: false
        solid: true
        fixed_rotation: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
 ```
 
 **Note that the `material` is `PAPER` and the `model_id` is 40000**
 
 Now if I were to define a custom model override by manually writing a jsosn file: the used model and custom model data are identical to the one defined in IA config above but it's for **`leather_horse_armor` other than `paper`**. I put it in the path `plugins/ItemsAdder/contents/_colorable/resourcepack/minecraft/models/item/leather_horse_armor.json`:

```json
{
  "parent": "item/generated",
  "textures": {
    "layer0": "item/leather_horse_armor"
  },
  "overrides": [
    {
      "predicate": {
        "custom_model_data": 40000
      },
      "model": "furnitures:anniversary/1st_year_cake"
    }
  ]
}
```

Then, run `iazip`

IA would throw a warning:

> [23:24:12 WARN]: [!] CustomModelData 40000 for item 'leather_horse_armor' already used by ItemsAdder custom item 'furnitures:1st_year_cake'. Skipped.

As a result, the `overrides` that are manually written by me is not included in the output pack.

### Server version

Current: git-Purpur-1920 (MC: 1.19.3)*
Previous: git-Purpur-1919 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### Other files, you can drag and drop them here to upload. (optional)

My ItemsAdder `config.yml`: https://pastes.dev/uo04MGQkkr
