### ISSUE TITLE
Problem with the time of using a new item as fuel

### ISSUE THREAD

**Issue by Radmir52** [PluginBugs/Issues-ItemsAdder#2377]
### What happened?

In version 3.3.1 I observe such a fuel burning error.

```yml
items:
  briket_max:
    display_name: Стопка брикетов
    lore:
    - '&b&oВремя горения - 1 час.'
    resource:
      material: STICK
      generate: true
      textures:
      - item/briket_max.png
    behaviours:
      fuel:
        enabled: true
        machines:
        - BLAST_FURNACE
        - FURNACE
        - SMOKER
        burn_ticks: 72000
```
The duration of burning is not 1 hour, but about 5 minutes. If you take another fuel with 1 minute of burning, then everything is in order there.

### Steps to reproduce the issue

1. Put an item in the form of fuel in the furnace
2. Check that the burning time does not correspond to the setting

### Server version

1.19.2

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0.

### LoneLibs Version

1.0.23
