### ISSUE TITLE
Three different bugs on 3.4.0

### ISSUE THREAD

**Issue by Bobbyharron** [PluginBugs/Issues-ItemsAdder#2398]
### Discord tag (optional)

bobby_harron#7548

### What happened?

I've been having this issues since i updated:

1. When someone step on custom crops with vanilla material it drops the vanilla result. for example: if i have a custom potato crop that should drop a custom item, you step on it and drop potatoes.

https://www.youtube.com/watch?v=ZpvwR2DshCk&ab_channel=BobbyHarron

2. My custom blocks with noteblock material turns into vanilla noteblocks after a right click

https://www.youtube.com/watch?v=G14_OPPCM7o&ab_channel=BobbyHarron

3. When i repair custom tools in the crafting table the result is the vanilla material of the tool. For example: a ''copper pickaxe'' being repaired on crafting table with another copper pickaxe turns on a vanilla iron pickaxe
![image](https://user-images.githubusercontent.com/65925795/223755293-40434d92-0f54-4f7e-882e-803bf2e4464e.png)

### Server version

Purpur 1.19.3

### ItemsAdder Version

3.4.0 beta r11

### ProtocolLib Version

5.0.0 snapshot b612

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
> 1. https://www.youtube.com/watch?v=ZpvwR2DshCk&ab_channel=BobbyHarron

will be checked

> 2. https://www.youtube.com/watch?v=G14_OPPCM7o
> ![image](https://user-images.githubusercontent.com/27242001/223758319-3ae277f0-dddb-4d21-a3a9-08c93c07e59c.png)

Cannot reproduce it.
It might be caused by the custom inventories plugin you're using (not created by me).
Try to remove all other plugins and test if the issue occurs.

> 3. Make a custom tool, and repair it with the same custom tool, in the crafting table. the result is going to be the vanilla material

Will be checked, although last time I tested it worked fine.

**Comment by Bobbyharron** [comment]
> 

2. is using chestcommands fork , wich as far as i know, you did. And its using a click event from itemsadder

**Comment by LoneDev6** [comment]
Can you provide the block yml configuration? With the `events` configuration, thanks

**Comment by Bobbyharron** [comment]
the command use a custom command from the plugin mycmd to open the chestcommands menu

**Comment by LoneDev6** [comment]
# 1
fixed

# 2
cannot trigger, you might have another plugin interfering, please disable all plugins and check if it still happens.

https://user-images.githubusercontent.com/27242001/224064117-cf2b24b6-abd6-41ef-97d3-d365bb79da10.mp4


```yml
info:
  namespace: test_2398
items:
  test_2398:
    display_name: 'test_2398'
    lore:
    - '&8Una caja donde poder vender productos del oficio.'
    permission: cajadeventadegranjero
    resource:
      material: PAPER
      generate: false
      model_path: iasurvival:block/ruby_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: BARREL
    events:
      placed_block.interact:
        decrement_durability:
          amount: 1
        execute_commands:
          menubanco:
            command: 'chestcommands:cc open example {player}'
            as_console: true
```




# 3
cannot trigger, you might have another plugin interfering, please disable all plugins and check if it still happens.

https://user-images.githubusercontent.com/27242001/224063417-037371bc-fa02-4658-8a52-3fe5926b73dd.mp4
