### ISSUE TITLE
MMOitems displayname

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#2421]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Rickylachow#9809

### What happened?

 L'item non inserisce il displayname di MMOitems ma quello di itemsAdder

### Steps to reproduce the issue

Creare un item collegato ad MMOItems

### Server version

[11:00:03 INFO]: Checking version, please wait...
[11:00:04 INFO]: This server is running Paper version git-Paper-445 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4d7269e)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-420 (MC: 1.19.3)

### ItemsAdder Version

[11:00:22 INFO]: ItemsAdder version 3.4.0c-beta
[11:00:22 INFO]: Customized Minecraft without client mods!
[11:00:22 INFO]: Website: devs.beer
[11:00:22 INFO]: Author: LoneDev

### ProtocolLib Version

[11:00:34 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b614
[11:00:34 INFO]: Provides read/write access to the Minecraft protocol.
[11:00:34 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:00:45 INFO]: LoneLibs version 1.0.23
[11:00:45 INFO]: Collection of libs used by my plugins
[11:00:45 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
jungle_helmet:
    mmoitem:
      type: ARMOR
      id: JUNG_ELMO
    resource:
      generate: true
      textures:
      - item/jungle_helmet.png
      model_id: 12
    specific_properties:
      armor:
        slot: head
        custom_armor: jungle_armor
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/cYIctod

**Comment by RickyLaChow** [comment]
> è normale. volendo posso aggiungere una opzione per poter decidere quale nome usare, se quello di mmoitems o di itemsadder.

Sarebbe il top
Grazie mille <3

**Comment by LoneDev6** [comment]
The next update implements this new feature: `use_mmoitem_displayname`
```yml
info:
  namespace: test
items:
  test_inject_mmoitem:
    display_name: test inject mmoitem
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: PAPER
    mmoitem:
      id: THUNDER_BLESSING
      type: TALISMAN
      use_mmoitem_displayname: true
```
