### ISSUE TITLE
use only first -  not producing only 1 drop,

### ISSUE THREAD

**Issue by ryxan** [PluginBugs/Issues-ItemsAdder#2427]
### What happened?

when the special tag `drop_only_first`

```yml
gemrocks_block:
      type: iarunescape:gemrocks_block
      drop_only_first: true
      items:
        uncut_opal_item:
          item: iarunescape:uncut_opal_item
          min_amount: 1
          max_amount: 1
          chance: 99
        uncut_jade_item:
          item: iarunescape:uncut_jade_item
          min_amount: 1
          max_amount: 1
          chance: 88
        uncut_red_topaz_item:
          item: iarunescape:uncut_red_topaz_item
          min_amount: 1
          max_amount: 1
          chance: 30
        uncut_sapphire_item:
          item: iarunescape:uncut_sapphire_item
          min_amount: 1
          max_amount: 1
          chance: 7
        uncut_emerald_item:
          item: iarunescape:uncut_emerald_item
          min_amount: 1
          max_amount: 1
          chance: 4
        uncut_ruby_item:
          item: iarunescape:uncut_ruby_item
          min_amount: 1
          max_amount: 1
          chance: 4
        uncut_diamond_item:
          item: iarunescape:uncut_diamond_item
          min_amount: 1
          max_amount: 1
          chance: 3
```

It quite often drops 2 or more items.

### Steps to reproduce the issue

Place a block with loots and mine it, i have oroborous mines to regenerate the ore. 

i dont think it takes any specific steps, the use_only_first tag doesnt seem to work.

### ItemsAdder Version

ItemsAdder version 3.4.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b616

### LoneLibs Version

LoneLibs version 1.0.23

**Comment by LoneDev6** [comment]
I'll do some tests, strange since it worked fine in the past.

**Comment by LoneDev6** [comment]
# 1. I cannot reproduce the issue

The plugin works fine, it drops only the first item which matched the chance.
As you can see in the video it always drops only 1 item with my configuration.

```yml
info:
  namespace: test
items:
  test_block:
    display_name: test block
    resource:
      generate: false
      model_path: minecraft:block/stone
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: true
loots:
  blocks:
    change_me:
      type: test_block
      drop_only_first: true
      items:
        item1:
          item: STONE
          min_amount: 1
          max_amount: 1
          chance: 20
          ignore_fortune: false
        item2:
          item: DIAMOND
          min_amount: 1
          max_amount: 1
          chance: 50
          ignore_fortune: false
        item3:
          item: EMERALD
          min_amount: 1
          max_amount: 1
          chance: 35
          ignore_fortune: false
```

https://user-images.githubusercontent.com/27242001/229795121-ca0d9c7c-5681-4eec-85d8-811e6a72e745.mp4




# 2. You are using the configuration in the wrong way

It has no sense to set every item chance to 99.9 and set `drop_only_first: true`.
It will always drop the first item since the chance will always be almost 100%, and the other items won't ever be matched.
