### ISSUE TITLE
Use `item_display` to make furniture

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2458]
<details>

<summary>Outdated information</summary>

### Discord tag (optional)

EpicPlayerA10#3800

### Describe the solution you'd like

With the release of minecraft 1.19.4, new entities were added. One of them is `Item Display` and `Interaction Entity`.

### Item Display
The new [Item Display](https://minecraft.fandom.com/wiki/Display) can be used as a third option to `behaviours.furniture.entity` to display furniture. According to [minecraft wiki about display entities](https://minecraft.fandom.com/wiki/Display#Entity_data) we can see that `Item Display` can hold an item with a type and with tags (nbt).

So on our Item Display we can set an item type to for example a paper (it depends what item type is set in the furniture config) and a `CustomModelData` to an according number to display correct model.

What is also really cool in Item Displays is the fact that you can choose an `Item Display Transform`! There are a few options (`none`, `thirdperson_lefthand`, `thirdperson_righthand`, `firstperson_lefthand`, `firstperson_righthand`, `head`, `gui`, `ground`, `fixed`). If someone was working in blockbench on creating models then some of `Item Display Transform`s are known to him. But there is also a new `Item Display Transform` called `none` that will use raw model without any transformations! This means that when you create a model, then you don't have to apply this model correctly to an armor stand or an item frame.

`Item Display Transform` can be used in config under a `behaviours.furniture.item_display_transformation`

The config can look something like this:
```yml
info:
  namespace: testnamespace
items:
  test_furniture:
    display_name: "Test Furniture That Uses Item Display"
    resource:
      material: PAPER
      generate: false
      model_path: test_furniture
    behaviours:
      furniture:
        entity: item_display # New furniture entity
        item_display_transformation: none # none, thirdperson_lefthand, thirdperson_righthand, firstperson_lefthand, firstperson_righthand, head, gui, ground, and fixed
```

### Interaction Entity

NOTE from LoneDev: this feature won't be implemented. More info: #3193

The new [Interaction Entity](https://minecraft.fandom.com/wiki/Interaction) can be used as an alternative for hitboxes. This would be very efficient.

Instead of raycasting and checking if raycast is intersecting with hitbox, we can now just spawn an interaction entity with correct width and height. Then we can just listen for any interaction or attack event to recognize if player broke furniture or only interacted with it.

#### Advantages:
- Very efficient
- You can set any size on interaction entity

#### Disadvantages:
- The scroll click (creative pick item) won't work anymore because client does not send any packet on scroll click an interaction entity.
- You can only set `width` and `height` without `length`

So we can leave the choice to the owner of a server by adding to the furniture config an option to select a hitbox type under `behaviours.furniture.hitbox.type` like this:
```yml
info:
  namespace: testnamespace
items:
  test_furniture:
    display_name: "Test Furniture That Uses Item Display"
    resource:
      material: PAPER
      generate: false
      model_path: test_furniture
    behaviours:
      furniture:
        entity: item_frame
        hitbox:
          type: interaction_entity # raycast, interaction_entity
          width: 1
          height: 1.5
```

</details>

**Comment by LoneDev6** [comment]
This will be implemented and it's already planned.
Anyway the hitbox part will stay the same since I have to maintain backwards compatibility with 1.19.3 and lower.

**Comment by EpicPlayerA10** [comment]
> This will be implemented and it's already planned.

That's great :)

> Anyway the hitbox part will stay the same since I have to maintain backwards compatibility with 1.19.3 and lower. ItemsAdder raycasting is already efficient and was extensively tested to make sure it's not heavy on busy servers.

I mean that you could add Interaction Entity as a new type for hitbox. The default type would be the Raycast type. And the owner would optionally set in furniture config a type to `Interaction Entity`. Anyway, this is your choice whether you want to implement it.

**Comment by EpicPlayerA10** [comment]
Referring to the topic about `Item Display` I want to suggest one more thing:

When you add `Item Display` support then you can also add an option to furniture config called `transformation`. It is in the [wiki](https://minecraft.fandom.com/wiki/Display#Entity_data)). It means that you can set your own `right_rotation`, `left_rotation`, `scale` and `translation`. This would look something like this:
```yml
info:
  namespace: testnamespace
items:
  test_furniture:
    display_name: "Test Furniture That Uses Item Display"
    resource:
      material: PAPER
      generate: false
      model_path: test_furniture
    behaviours:
      furniture:
        entity: item_display
        item_display_transformation: none
        # Your own transformation
        transformation:
          right_rotation:
            # Quaternion representation
            quaternion:
              x: 0.5
              y: 0.4
              z: 0.5
              w: 0.1
            # or "Axis-Angle representation"
            axis_angle:
              angle: 30
              axis:
                x: 1
                y: 2
                z: 1
          left_rotation:
            # Quaternion representation
            quaternion:
              x: 0.5
              y: 0.4
              z: 0.5
              w: 0.1
            # or "Axis-Angle representation"
            axis_angle:
              angle: 30
              axis:
                x: 1
                y: 2
                z: 1
          # Scale
          scale:
            x: 1
            y: 2
            z: 1

          translation:
            x: 1
            y: -2
            z: 3
```

**Comment by iqtesterr** [comment]
The RayCasting is good without doubt, but it only support 3x3x3 due to performance. If we want to make a bigger furniture and since item display support scale. Technically we can make as big as we want. In this situation RayCasting is not enough, adding interaction entity as hitbox should be consider as a new option:D

**Comment by iqtesterr** [comment]
Another thing is we can right click interaction entity. That is useful and flexible!

**Comment by iqtesterr** [comment]
Looking forward to your consideration and implementation after you back.

**Comment by LoneDev6** [comment]
> The RayCasting is good without doubt, but it only support 3x3x3 due to performance

I don't understand what you mean, ItemsAdder hitboxes have no size limit.

**Comment by iqtesterr** [comment]
> > The RayCasting is good without doubt, but it only support 3x3x3 due to performance
> 
> I don't understand what you mean, ItemsAdder hitboxes have no size limit.
> 
> Note: please do not use this as a chat, each message is sent as a single email notification to every participants of the thread. Thanks

Sorry for my spam, I noticed the size in the wiki.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/89851397/719c66de-71d7-4f4c-ac5b-7482c9c118bf)

**Comment by LoneDev6** [comment]
Notes:
Might need to implement a new property for furniture: `adjust_legacy_armor_stand_model: true` which will allow loading of armor_stand models and adjust their location to be shown correctly using item_display, since some admins might want to switch to item_display without having to manually open every model and update it.

This setting might be added under `transformation`, to automatically load the needed transformations (which will be hardcoded into the plugin).

**Comment by Domm1** [comment]
> Notes: Might need to implement a new property for furniture: `adjust_legacy_armor_stand_model: true` which will allow loading of armor_stand models and adjust their location to be shown correctly using item_display, since some admins might want to switch to item_display without having to manually open every model and update it.
> 
> This setting might be added under `transformation`, to automatically load the needed transformations (which will be hardcoded into the plugin).

Hello, any news about display entites for furniture? Ive been looking forward to the announcement but months passed by. Or did I just miss look it? Thanks!

**Comment by LoneDev6** [comment]
Not really, still planned.
I might have to scale down the updates and discard some other requests in order to prioritize what really is important for the plugin future.

**Comment by LoneDev6** [comment]
Implemented, example config:

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0dcb5aa9-a8c0-46e8-a28b-0278f1adf2ae)

```yml
  test_furniture_legacy_item_frame:
    display_name: "test_furniture_legacy_item_frame"
    resource:
      material: PAPER
      generate: false
      model_path: itemsadder:item/oak_wood_park_bench
    behaviours:
      furniture:
        entity: item_display
        small: true
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: -0.5
        display_transformation:
          transform: FIXED
          adjust_legacy_model:
            type: item_frame
```
