### ISSUE TITLE
Disable Custom Drops From Mobs Spawned By Mob Spawner

### ISSUE THREAD

**Issue by GridLockMC** [PluginBugs/Issues-ItemsAdder#2463]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

SlimPhat#0069

### Describe the solution you'd like

I would like to have an option to determine if a custom mob drop can be dropped or not from a mob spawned by a mob spawner. So any natural spawned mob would drop the custom item but a mob spawned by a mob spawner would not drop the custom item. 

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

I can try and find other plugins to try and make this happen but would be nice if itemsadder could do it itself so I can create custom items and have them drop how I like.

**Comment by LoneDev6** [comment]
There is already but I forgot to document it.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/791#issuecomment-812539203

```yml
loots:
  mobs:
    change_me:
      type: PIG
      ignore_spawner: true
      items:
        change_me:
          item: ACACIA_BOAT
          min_amount: 2
          max_amount: 2
          chance: 100
```
