### ISSUE TITLE
Faster configuration rule to add items into the `/ia` GUI

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2467]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DinoBoss#6985

### Describe the solution you'd like

A new selector would be a good idea to add something new to ia for configurators who have very large files of items and armor then to place it in 1 category would be good a way to place everything in 1 line, this will leave 1 example of 2 way to do it 1 is more comfortable as it is 1 symbol only.

### Is your feature request related to a problem?

If I literally want to add models from companies like artbykev and think that I have to add 1 x 1 path gives a lot of time that takes away when by programming the dev could solve this.

### Describe alternatives you've considered

No other because adding it 1x1 would take too long.

### Additional context

info:
  namespace: ejemplo_artbykev
categories:
  ejemplo_artbykev
    enabled: true
    icon: "ejemplo_artbykev:item_exemple"
    name: 'exemple categori'
    permission: "ia.admin"
    items:
      - "ejemplo_artbykev:*" #This line would be the only one that points to all the items in the path yml could point more expesifico so it would be easier for the developer but the idea would be that with 1 single line add all the items already created in the item_exemple.yml

**Comment by LoneDev6** [comment]
Good idea, will be implemented in a future update

**Comment by dinobossytnew** [comment]
It could be added to the machines, or trade maquians that are made with itemsadders.

**Comment by LoneDev6** [comment]
> It could be added to the machines, or trade maquians that are made with itemsadders.

Sure, but please provide an example of how you'd use them in configuration.
Thanks!

**Comment by LoneDev6** [comment]
Examples:

## Wildcard

Matches any item which has `example` namespace.

```yml
categories:
  test:
    enabled: true
    skip_if_already: false
    icon: example:my_item
    name: TEST
    permission: ia.menu.seecategory.test
    items:
      - example:*
```

Matches any namespace which has `some_item` item.
```yml
categories:
  test:
    enabled: true
    skip_if_already: false
    icon: example:my_item
    name: TEST
    permission: ia.menu.seecategory.test
    items:
      - *:some_item
```

## Regex

Matches any armor item of the `iasurvival` namespace

```yml
  armors:
    enabled: true
    skip_if_already: false
    icon: iasurvival:ruby_helmet
    name: display-category-armors
    permission: ia.menu.seecategory.armors
    items:
      - iasurvival\:(.*)_helmet
      - iasurvival\:(.*)_chestplate
      - iasurvival\:(.*)_leggings
      - iasurvival\:(.*)_boots
```
