### ISSUE TITLE
Event placed_itemframe.interact not work.

### ISSUE THREAD

**Issue by WMGameLive** [PluginBugs/Issues-ItemsAdder#2541]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

切西瓜#9050

### What happened?

My server have some items, if player place the item in itemframe and right click it, it will play sound, everything work fine when I use 3.3.1, but after I update the plugin, it is not work anymore.

### Steps to reproduce the issue

1. place a ItemsAdder's item that had placed_itemframe.interact event in itemframe.
2. right click it, it is not working.

### Server version

Current: git-Purpur-1961 (MC: 1.19.4)*

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

v5.0.0-SNAPSHOT-b632

### LoneLibs Version

1.0.24

### Error (optional)

```shell
no error.
```

**Comment by WMGameLive** [comment]
```
    events:
      interact:
        right:
          play_sound:
            name: "venderoe:plushie.plushie_custom_andrew20324_01"
            volume: 0.5
            pitch: 1.0
      placed_itemframe:
        interact:
          play_sound:
            name: "venderoe:plushie.plushie_custom_andrew20324_01"
            volume: 0.5
            pitch: 1.0
```
interact.right is work, but placed_itemframe.interact not work.
