### ISSUE TITLE
Add netherite resistance to lava property to a custom item

### ISSUE THREAD

**Issue by Replaycchi** [PluginBugs/Issues-ItemsAdder#2543]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add a property to make item lava resistant like netherite, maybe in durability section ?

### Is your feature request related to a problem?

I've made a custom armor which is an upgrade of netherite one but it won't resist lava anymore now

### Describe alternatives you've considered

```
durability:
  max_custom_durability: 200
  custom_durability: 32
  disappear_when_broken: false
  unbreakable: false
  usages: 5
  **lava_resistance: true**
```
