### ISSUE TITLE
Add SuperiorSkyblock compatibility

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#2562]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

kfx#3113

### Describe the solution you'd like

Hey,
It would be awesome if IA could define custom block parsers for custom blocks and/or other placeable furniture/decorations using SuperiorSkyblock's API.

That would allow the SuperiorSkyblock to generate ItemsAdder's custom blocks and furniture on the islands - that plugin is used by thousands of servers, so I'm sure that would help bring the new era of SkyBlock servers and boost the popularity of IA even more (since it's a very nice and unique feature).

https://wiki.bg-software.com/superiorskyblock/overview/api/register-your-own-block-keys
https://wiki.bg-software.com/superiorskyblock/overview/api

It would be great if we (IA users) could add an extra section in the IA configuration for each custom block that we would like to register to SuperiorSkyblock. Something like this:

```
  random_block:
    display_name: Random Block
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/random_block
    specific_properties:
      superior-block-key: IA_RANDOM_BLOCK
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
```

Of course, if there is a better way to implement this feature that would be fine as well. This is just an example.

Sorry if this is a duplicate of other feature requests, I tried searching the Github but it seems that no one has suggested this yet.

Thank you!

### Is your feature request related to a problem?

/

### Describe alternatives you've considered

/
