### ISSUE TITLE
Custom Player Drops

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2574]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Be awesome if Itemsadder allowed us to set custom IA items to drop from players on death.

### Is your feature request related to a problem?

Yes, unable to find a plugin that will provide the solution.

### Describe alternatives you've considered

No alternatives, all custom player drop plugins i can find are discontinued.

**Comment by LoneDev6** [comment]
You mean custom loot?
You can already create a loot in ItemsAdder which uses the `PLAYER` entity type.
https://itemsadder.devs.beer/plugin-usage/adding-content/loots#mobs

```yml
    player:
      type: PLAYER
      items:
        item_1:
          item: my_items:custom_item_1
          min_amount: 1
          max_amount: 1
          chance: 100
```
