### ISSUE TITLE
Destroy Item after Command

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2585]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I have an item that when clicked in hand, runs a command but i'd like the item to be removed/destroyed from the players hand after the commands run.

I'd prefer not to have to make the item a tool just to use the durability destroy item way if i could.

Hoping you could do it so that we could use a  `disappear_after_command_run: true` action instead.

### Is your feature request related to a problem?

Yes, unable to use the disappear action without having to use a tool for durability.

### Describe alternatives you've considered

No alternatives as wish to do it with itemsadder rather than add more plugins to my already large list of plugins.

**Comment by LoneDev6** [comment]
You can try using:
```yml
        decrement_amount:
          amount: 1
```

**Comment by SirCraftypants** [comment]
I've tried different combinations and can't get it to disappear after first use

```yaml
info:
  namespace: customitems
items:
  pouch_of_plunder:
    display_name: Pouch of Plunder
    permission: pouch.of.plunder
    resource:
      material: STICK
      generate: true
      textures:
      - item/bags/medium_sack_of_holding.png
    events_cooldown: 150 ########### <-- EXAMPLE 60 seconds      
    events:
      interact:
        right:
          play_sound:
            name: minecraft:entity.pillager.celebrate
            volume: 1
            pitch: 1
          execute_commands:
            first_cmd:
              as_console: false
              command: 'eco give {player} 50'             
        durability: 
          max_custom_durability: 1          
          custom_durability: 1  
          disappear_when_broken: true 
          usages: 1 
        decrement_amount:     
          amount: 1

**Comment by SirCraftypants** [comment]
I just don't understand what the decrement is decrementing when there's nothing to decrement from seeing as i'm using STICK, i.e. why i mentioned at the start that i did not wish to use an vanilla tools. 

Maybe i'll try execute command with /iaremove instead as this decrement way isn't working and the wiki is very vague on decrement.

**Comment by SirCraftypants** [comment]
/iaremove with a 1 tick delay works fine.

**Comment by LoneDev6** [comment]
I don't see how the decrement logic is vague.
It decrements the amount of the current custom item.
1-1 = 0.
You have an item that you want to be destroyed on use.

> /iaremove with a 1 tick delay works fine.

It opens your server to duplication glitches as people can spamclick Q to drop the item right before the /iaremore command is executed.

-----
Also I still don't know why after 3 years of using Itemsadder you still edit your files without using the extension to check if properties exist or not while writing them down.
No idea why you put `durability` here for 2 reasons:
- this item has no durability, it's a stick.
- there is no durability property under `events`, it would have been a property of the item itself.

```yml
info:
  namespace: customitems
items:
  pouch_of_plunder:
    display_name: Pouch of Plunder
    permission: pouch.of.plunder
    resource:
      material: STICK
      generate: true
      textures:
      - item/bags/medium_sack_of_holding.png
    events_cooldown: 150 ########### <-- EXAMPLE 60 seconds      
    events:
      interact:
        right:
          play_sound:
            name: minecraft:entity.pillager.celebrate
            volume: 1
            pitch: 1
          execute_commands:
            first_cmd:
              as_console: false
              command: 'eco give {player} 50'             
        durability: # ???????????????????
          max_custom_durability: 1          
          custom_durability: 1  
          disappear_when_broken: true 
          usages: 1 
        decrement_amount:     
          amount: 1
```

Also why did you put the `decrement_amount` under `interact` and not `interact`->`right`?
Obviously it won't do anything ingame, it's in the wrong place.
Please stop editing your files without using the configurations extension and start reading its suggestions.
You have to press CTRL+SPACE to get suggestions while writing down.

I fixed your configuration.

```yml
info:
  namespace: customitems
items:
  pouch_of_plunder:
    display_name: Pouch of Plunder
    permission: pouch.of.plunder
    resource:
      material: STICK
      generate: true
      textures:
      - item/bags/medium_sack_of_holding.png
    events_cooldown: 150 ########### <-- EXAMPLE 60 seconds      
    events:
      interact:
        right:
          play_sound:
            name: minecraft:entity.pillager.celebrate
            volume: 1
            pitch: 1
          execute_commands:
            first_cmd:
              as_console: false
              command: 'eco give {player} 50'             
          decrement_amount:     
            amount: 1
```
