### ISSUE TITLE
recipe some feature is broken

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#2593]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Bug

### Steps to reproduce the issue

**There used to be no problem with this method.**

**Vanilla Item Recipe Rule**
![image](https://user-images.githubusercontent.com/80433772/235835468-8700652a-3e0e-4b1c-99ff-9f49255c3442.png)
![image](https://user-images.githubusercontent.com/80433772/235835533-de3671d2-ee1c-427c-b877-2041cf3bda3d.png)
![image](https://user-images.githubusercontent.com/80433772/235835582-aa8cd537-cb87-4c23-ab49-cec6ecf334cd.png)

```yml
amethyst_alloy_sword:
      enabled: true
      pattern:
      - E
      - E
      - W
      ingredients:
        E: rtuserver:amethyst_alloy
        W: STICK
      result:
        item: rtuserver:amethyst_alloy_sword
        amount: 1
```
It must same as Vanilla Item Recipe Rule.
But It is broken since some update...

**ItemsAdder Item Recipe Rule**
![image](https://user-images.githubusercontent.com/80433772/235835986-88747721-3fc3-4373-8d6a-342e295234c9.png)
![image](https://user-images.githubusercontent.com/80433772/235836013-54790b02-72ca-4c57-be4e-74477c3f2d8d.png)
![image](https://user-images.githubusercontent.com/80433772/235836041-28413808-2531-424d-9a53-5694d2ec0a6c.png)

```yml
amethyst_alloy_sword:
      enabled: true
      pattern:
      - EXX
      - EXX
      - WXX
      pattern_2:
      - XEX
      - XEX
      - XWX
      pattern_3:
      - XXE
      - XXE
      - XXW
      ingredients:
        E: rtuserver:amethyst_alloy
        W: STICK
      result:
        item: rtuserver:amethyst_alloy_sword
        amount: 1
```
This method is very very stupid....

### Server version

Paper 1.19.4 Build 522
Purpur 1.19.4 Build 1967
Plazma 1.19.4 Git [d644aad](https://github.com/PlazmaMC/Plazma/commit/d644aad71e6cba73c6a641a34d68898575ba57a2)

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.0.0-SNAPSHOT-b632

### LoneLibs Version

1.0.24

### FULL server log

No error
