### ISSUE TITLE
Self-host port appearing behind 

### ISSUE THREAD

**Issue by KarlPro123** [PluginBugs/Issues-ItemsAdder#2607]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

KarlPro123#9259

### What happened?

We are using a reverse proxy system to hide our server's IP address so using "127.0.0.1" as the server-ip in the self-host configuration section isn't possible, as the player downloading the resource pack simply can't access the main server this way, it's also connected to Cloudflare. We decided to make an url which could be used by ItemsAdder that's directly connected to the server and allow players to download the resource pack. It is also already connected to the 8163 port. The problem is that when player tries to download the resource pack, ItemsAdder puts the pack-port behind the url, so it'd look like this: example.resourcepack.com:8163. However, it won't download the pack this way, as the url itself is already connected to the port as I said.
 
I don't know if there's other ways to fix this, but maybe a config option to disable the port appearing behind the server-ip (for setups like I have).

Example of the configuration like I have:

```   
      self-host:
      enabled: true
      server-ip: example.resourcepack.com
      pack-port: 8163
```

### Steps to reproduce the issue

The only thing that causes this problem is that I use an url to access the pack, but that's required in my situation. 

### Server version

This server is running Paper version git-Paper-521 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcec5b1)

### ItemsAdder Version

ItemsAdder version 3.4.1b

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
It's not possible because of how Cloudflare works. You cannot specify a port on a Cloudflare protected website domain.
What you can do is use auto external host if you want the pack to be automatically uploaded without having to manually upload it everytime on Dropbox or similar.

**Comment by KarlPro123** [comment]
> It's not possible because of how Cloudflare works. You cannot specify a port on a Cloudflare protected website domain. What you can do is use auto external host if you want the pack to be automatically uploaded without having to manually upload it everytime on Dropbox or similar.

To be more precise.

I have an url and it's protected by Cloudflare, but in our servers Nginx system we re-routed all the traffic to the port already specified in the config. 

**The problem that appeared:** (for example: we want to be like r**esourcepack.example.com/pack.zip**, but right now it will download from resourcepack.example.com:8643/pack.zip (puts the port automatically behind the url) and we don't want the port there, as the link simply doesn't work with it. I would like a config option to disable the port appearing behind the server-ip.

**Comment by LoneDev6** [comment]
Thanks, I now understand the issue.
Do you have any idea of how to structure the configuration to implement that feature?
```yml
    self-host:
      enabled: false
      server-ip: 'resourcepack.example.com'
      pack-port: 8163
```

**Comment by KarlPro123** [comment]
It can be as simple as 

```
    self-host:
      enabled: true
      server-ip: 'resourcepack.example.com'
      pack-port: 8163
      disable-port-behind-server-ip: true/false
```
      
or anything similar

**Comment by LoneDev6** [comment]
Maybe more like:
```yml
    self-host:
      enabled: true
      server-ip: 'resourcepack.example.com'
      pack-port: 8163
      append-port: true
```
