### ISSUE TITLE
Furniture hitbox limited to `item_frame` vanilla hitbox

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2609]
### Discord tag (optional)

EclipseMC#7777

### What happened?

after update lastest version of IA, block command was not executed sometimes.
In the video, the furniture is quickly right-clicked. It worked well in previous versions (3.3.0).

youtube : https://youtu.be/py_5mfKECVM

### Steps to reproduce the issue

```yml
  furniture_kitchen_table_fireplace:
    display_name: 가스레인지 테이블
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: funitures/kitchen_table_fireplace
    behaviours:
      furniture:
        entity: item_frame
        gravity: false
        fixed_rotation: true
        small_hitbox: false
        opposite_direction: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: -0.5
        sound:
          place:
            name: block.stone.place
          break:
            name: block.stone.break
    events:
      placed_itemframe:
        break:
          execute_commands:
            cmd1:
              command: ecsefurnitures {player}
              as_console: true
        interact:
          execute_commands:
            cmd1:
              command: 요리 창 {player}
              as_console: true
```

### Server version

purpur 1.19.2 RO.1

### ItemsAdder Version

3.4.1b

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

1.0.24

### FULL server log

command was not printed in logs, nothing special errors.
