### ISSUE TITLE
More control over predicates

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2612]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

EpicPlayerA10#3800

### Describe the solution you'd like

Add a way that you can set your own predicates, not limiting to these "filename-based" predicates (For example when you want to create a bow, then you are limited to only 3 pulling states by adding `_0`, `_1`, `_2` to the filename).

Also to maintain backwards compatibility we can add an option to item config called `filename_based_item_states` which will be true by default.

This would look something like this:
```yml
info:
  namespace: test
items:
  testbow:
    display_name: Test Bow
    permission: test.testbow
    resource:
      material: BOW
      generate: false
      model_path: testbow

      filename_based_item_states: false # Set this to false to avoid bugs in item_states
      item_states:
        # These pulling states are shown at other time intervals
        - predicate:
            pulling: 1
          model_path: testbow_pulling_0
        - predicate:
            pulling: 1
            pull: 0.1
          model_path: testbow_pulling_1
        - predicate:
            pulling: 1
            pull: 0.3
          model_path: testbow_pulling_2
        - predicate:
            pulling: 1
            pull: 0.4
          model_path: testbow_pulling_3
        - predicate:
            pulling: 1
            pull: 0.7
          model_path: testbow_pulling_4
        - predicate:
            pulling: 1
            pull: 0.8
          model_path: testbow_pulling_5
```

### Is your feature request related to a problem?

In a way, this is related to this issue #1317

### Describe alternatives you've considered

I haven't come up with an alternative yet.
