### ISSUE TITLE
`unequip` event not triggered in some special cases (out of the plugin scope)

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2620]
Continuation of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2605

Find a way to detect `/clear` command and similar commands which should trigger unequip event.
One solution could be to check each ~10 ticks if the player has an item with `unequp` event attached and trigger it if the item is no longer equipped.

**Comment by Distolfix** [comment]
how can i fix it

**Comment by HamtaBot** [comment]
> Continuation of #2605
> 
> Find a way to detect `/clear` command and similar commands which should trigger unequip event. One solution could be to check each ~10 ticks if the player has an item with `unequp` event attached and trigger it if the item is no longer equipped.

Could be cool but performance wise it would be a bit bad

**Comment by Distolfix** [comment]
I'm not sure if you have fixed it, it's not mentioned in the changelog, so if it hasn't been resolved yet.

**Comment by LoneDev6** [comment]
If it's not mentioned in the changelog then it's not fixed.
It's scheduled to be fixed in the next release as noted.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/21a71a12-2739-4b6f-88f3-d258102acb8c)

**Comment by Distolfix** [comment]
Ciao @LoneDev6 volevo chiederti una cosa, quando davo i kit, gli oggetti che hanno degli effetti li dovevo mettere nell'inventario, poichè se con lo /kit mettevo che l'armor del kit la dava già indossata, non faceva partire i poteri, la domanda può essere scontata, ma con questo aggiornamento previsto nella 3.5.1 con CMI potrò mettere gli oggetti (le armor) già indossate in modo che partono gli effetti?

**Comment by LoneDev6** [comment]
Sì

**Comment by LoneDev6** [comment]
Implemented a setting to disable this in case you don't need.
`handle-wear-held-actions-on-unexpected-inventory-changes: true`

This new feature will correctly detect ANY change on the hold/worn item, so events will trigger every time.
For example /clear and similar commands.

## NOTE: it's not instant. Check if made each second to avoid useless CPU usage.

Example config to test:
```yml
info:
  namespace: git_2620
items:
  test_2620_hat:
    display_name: test_2620_hat
    resource:
      material: FEATHER
      generate: true
      textures:
        - item/stone_sword
    behaviours:
      hat: true
    events:
      wear:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unwear:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_helmet:
    display_name: test_2620_helmet
    resource:
      generate: true
      textures:
        - item/stone_sword
    specific_properties:
      armor:
        slot: HEAD
    events:
      wear:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unwear:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_chestplate:
    display_name: test_2620_chestplate
    resource:
      generate: true
      textures:
        - item/stone_sword
    specific_properties:
      armor:
        slot: CHEST
    events:
      wear:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unwear:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_leggings:
    display_name: test_2620_leggings
    resource:
      generate: true
      textures:
        - item/stone_sword
    specific_properties:
      armor:
        slot: LEGS
    events:
      wear:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unwear:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_feet:
    display_name: test_2620_feet
    resource:
      generate: true
      textures:
        - item/stone_sword
    specific_properties:
      armor:
        slot: FEET
    events:
      wear:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unwear:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620:
    display_name: test_2620
    resource:
      material: STONE_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
    events:
      held:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unheld:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_2:
    display_name: test_2620_2
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
    events:
      held:
        potion_effect:
          type: ABSORPTION
          duration: 99999999999999999999
          amplifier: 1
      unheld:
        remove_potion_effect:
          type: ABSORPTION
  test_2620_off:
    display_name: test_2620_off
    resource:
      material: WOODEN_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
    events:
      held_offhand:
        potion_effect:
          type: INCREASE_DAMAGE
          duration: 99999999999999999999
          amplifier: 1
      unheld_offhand:
        remove_potion_effect:
          type: INCREASE_DAMAGE
  test_2620_off_2:
    display_name: test_2620_off_2
    resource:
      material: WOODEN_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
    events:
      held_offhand:
        potion_effect:
          type: ABSORPTION
          duration: 99999999999999999999
          amplifier: 1
      unheld_offhand:
        remove_potion_effect:
          type: ABSORPTION
```
