### ISSUE TITLE
Add API Method: CustomFurnitrue#setFurniture(CustomStack)

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#2630]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

API method

```java
/***
It change Furniture Item in (ItemFrame or ArmorStand)
*/
void CustomFurnitrue#setFurniture(CustomStack)
void CustomFurnitrue#setFurniture(CustomFurniture)
void CustomFurnitrue#setFurniture(String namespacedID)
```

### Is your feature request related to a problem?

Im currently developing interactive furniture.
Like opned window and closed window.
but current IA API is too bad for this work.....

These are the things I've tried

1) **I thought it was gonna work**
Get ItemFrame A and B from Furniture A and B.
Set Item in ItemFrame-A to item in ItemFrame-B.
But Furniture-A (changed ItemFrame-A) != Furmiture-B

2) **I know that (Item in ItemFrame of Furniture) != (Item of CustomStack of Furniture)**
Get ItemFrame-A from Furniture-A
Get CustomStack-A from NamespacedID from Furniture-A
Set Item in ItemFrame-A to item of CustomStack-A

3) **Too bad method.. and not work well..**
Remove Furnitrue-A
Spawn Furnitrue-B with location of Furniture-A (CustomFurniture#spawnPreciseNonSolid)
and with many edited location
**It may work. BUT. This creates blink and often shows itemframe for short time**

4) etc (I need API method..)

I tried to implement it with the current API for two weeks, but there was no way
I even tried to use obfuscated code of ItemsAdder
It was all stupid hardcoding and ways not to work
 
**Feature Request)
Furniture-A#setFurniture(Furniture-B).
now Furniture-A is Funiture-B
WITHOUT breaking IA custom hitbox.**

### Describe alternatives you've considered

I saw ItemsAdder obfuscated code.

my idea code of itemframe furniture code 
from (bq.class / 212 line / private Entity a(Player var1, Location var2, ItemStack var3, Block var4, BlockFace var5, Consumer var6))
public void setFurniture(CustomStack customStack) {
    ItemStack var9 = customStack.getItemStack().clone();
    var9.setAmount(1);
    NItem var10 = new NItem(var9);
    String var11 = jC.h(var9);
    if (var11 != null) {
        var10.a("IAOrigName", var11);
        var10.b("display").d("Name");
        var10.bt();
    }
    ((ItemFrame)this.bukkitEntity).setItem(var9);
}

### Additional context

Thx for making ItemsAdder!
IA is so good for higher quality!

**Comment by LoneDev6** [comment]
The methods you're requesting would still cause the blinking effect because they would remove the old furniture and add the new one.

Anyway one thing you can do is just copy the CustomModelData from one furniture to the other, which is exactly what the built-in YML solution allows.

```yml
info:
  namespace: my_items
items:
  test_furniture:
    display_name: test furniture
    resource:
      generate: false
      model_path: test_furniture
      material: PAPER
    behaviours:
      furniture:
        hitbox:
          height: 1
          length: 1
          width: 1
        entity: armor_stand
    events:
      placed_armorstand:
        interact:
          replace_properties:
            custom_model_data:
              copy_from_item: test_furniture_open
              restorable: true
  test_furniture_open:
    display_name: test furniture open
    resource:
      generate: false
      model_path: test_furniture_open
      material: PAPER
    behaviours:
      furniture:
        hitbox:
          height: 1
          length: 1
          width: 1
        entity: armor_stand
```
