### ISSUE TITLE
New events for item_frame

### ISSUE THREAD

**Issue by HamtaBot** [PluginBugs/Issues-ItemsAdder#2637]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

HamtaBot#0001

### What happened?

There no proper way of removing an effect given by items events section on config for placing item on item frames, i tried to use interact.entity but it also do the trick on mobs and i dont want that, i want to be able to remove a potion effect from my sword when a player place it on an item frams cus for now with the config bellow it doesnt remove the effect

    events:
      held:
        potion_effect:
          type: FAST_DIGGING
          duration: 99999999999999999999
          amplifier: 1
      unheld:
        remove_potion_effect:
          type: FAST_DIGGING   
      drop:
        remove_potion_effect:
          type: FAST_DIGGING     
      placed_itemframe.interact:
        remove_potion_effect:
          type: FAST_DIGGING       
      placed_block.interact:
        remove_potion_effect:
          type: FAST_DIGGING     
      interact.entity:
        remove_potion_effect:
          type: FAST_DIGGING

### Steps to reproduce the issue

use my config i sent on a sword and place the sword on a item frame, the effect will not remove

### Server version

1.17.1 pufferfish

### ItemsAdder Version

3.4.1c

### ProtocolLib Version

5.0.0

### LoneLibs Version

still dont know how to check it

**Comment by HamtaBot** [comment]
there is also no drop.offhand

**Comment by LoneDev6** [comment]
I think it's to implement your feature we need two new events:
- item frame put item
- item frame remove item

The reason is because the current event `placed_itemframe.interact` is misleading. This event is triggered only for furniture created using item_frame entity.

**Comment by HamtaBot** [comment]
> I think it's to implement your feature we need two new events:
> 
> * item frame put item
> * item frame remove item
> 
> The reason is because the current event `placed_itemframe.interact` is misleading. This event is triggered only for furniture created using item_frame entity.

oh i see yeah that was confusing me lol , also for the drop.offhand is it possible cuz currently if someone have an item in offhand and drop it the effect is still here

**Comment by LoneDev6** [comment]
> drop.offhand is it possible cuz currently if someone have an item in offhand and drop it the effect is still here

Even on latest IA version?

**Comment by HamtaBot** [comment]
oh im missing one version 1 sec

**Comment by HamtaBot** [comment]
its fixed nvm

**Comment by HamtaBot** [comment]
do you have any ETA for that feature , i'm waiting this to finish the biggest update my server never got (working on it since a year now)

**Comment by HamtaBot** [comment]
Alright thank sounds good

**Comment by HamtaBot** [comment]
> Not really, I plan to release it for the next update, I'm currently prioritizing some important compatibility issues. Probably after 3.4.1b, so like an in-between version like 3.4.1d, maybe at the end of the month.

hey do you have any news about this ^^

**Comment by LoneDev6** [comment]
> oh i see yeah that was confusing me lol , also for the drop.offhand is it possible cuz currently if someone have an item in offhand and drop it the effect is still here

Offhand drop already triggers the drop event.
Please make sure to use the latest version of the plugin.

If you still can reproduce the issue make a video and provide a configuration.

----

The requested features are going to be implemented in the upcoming update.
`item_frame.put_item`
`item_frame.remove_item`
and:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2784
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2783

**Comment by LoneDev6** [comment]
Example usage:
```yml
info:
  namespace: myitems
items:
  new_events_test:
    enabled: true
    display_name: new_events_test
    resource:
      generate: false
      material: DIAMOND_HELMET
      model_path: minecraft:block/stone
    events:
      item_frame:
        put_item:
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"item_frame.put_item", "color": "green"}'
        remove_item:
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"item_frame.remove_item", "color": "green"}'
      armor_stand:
        put_item:
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"armor_stand.put_item", "color": "aqua"}'
        remove_item:
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"armor_stand.remove_item", "color": "aqua"}'
```
