### ISSUE TITLE
player can't break non-solid furniutre on survival mode

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2692]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EclipseMC#7777

### What happened?

player can't break non-solid furniutre on survival mode

### Steps to reproduce the issue

1. create non-solid items. 

```yml
 sprinkler_3:
    display_name: 고급 스프링쿨러
    resource:
      material: PAPER
      generate: false
      model_path: 'crops/base/sprinkler_3'
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: true
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 0.6
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```

2. break furniture with survival mode.

### Server version

purpur 1.19.2 RO.1

### ItemsAdder Version

3.4.1e

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/fATyIQ3niNw
