### ISSUE TITLE
player hud doesnt work properly

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#2705]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

some players the hud stays stable and doesnt decrement on some players it decrements
```yml
font_images:
  fear_positive:
    suggest_in_command: false
    path: hud/fear/positive
    y_position: -5
  fear_negative:
    suggest_in_command: false
    path: hud/fear/negative
    y_position: -5
  fear_half:
    suggest_in_command: false
    path: hud/fear/half
    y_position: -5
huds:
  nature:
    enabled: true
    show:
      auto: true
      creative: false
      underwater: true
      riding: false
    type: STATUS
    x_position_pixels: 10
    direction: LEFT
    value:
      player_stat_name: nature
      start: 10
      min: 0
      max: 10
      triggers:
        decrement:
          generic_over_time_30_minutes_inside:
            min_sky_light: 0
            max_sky_light: 2
            every_ticks: 600
            amount: 0.5
     #     generic_over_time_30_minutes_outside:
     #       min_sky_light: 14
     #       max_sky_light: 15
     #       every_ticks: 100
     #       amount: 1.5
     #     biome_over_time_desert_30_minutes_outside:
      #      min_sky_light: 0
     #       max_sky_light: 15
     #       biome: DESERT
      #      every_ticks: 20
     #       amount: 0.5
        increment:
     #     generic_over_time_30_minutes_inside:
     #       min_sky_light: 0
     #       max_sky_light: 13
     #       every_ticks: 500
     #       amount: 1.5
          generic_over_time_30_minutes_outside:
            min_sky_light: 3
            max_sky_light: 15
            every_ticks: 600
            amount: 0.5
          player_respawn:
            amount: 0
        on_min_value:
          damage_player:
            every_ticks: 60
            damage: 2
          potion_effect:
            every_ticks: 1000
            type: BLINDNESS
            amplifier: 1
            duration: 1000
    images:
      positive: mobitems:fear_positive
      half: mobitems:fear_half
      negative: mobitems:fear_negative
```

this is my hud config

### Steps to reproduce the issue

add a hud that decreases and increases the stat under certain sky light
some players stat will get stuck and dont decrease or increase

### ItemsAdder Version

3.4.1e

### ProtocolLib Version

5.0.0-SNAPSHOT-636

### LoneLibs Version

1.0.24
