### ISSUE TITLE
Custom enchants and lore switched

### ISSUE THREAD

**Issue by Domzzo** [PluginBugs/Issues-ItemsAdder#2735]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Domzzo

### What happened?

When having using predefined enchants (Advanced enchants) for armor its shown after the lore, if adding it in game it gets added before the lore.

### Steps to reproduce the issue

Put this to an armor item along with lore defined.
    enchants:
      - protection:5
      - waterwalker:1
 
When getting the item in game the custom enchant will show after lore.

### Server version

This server is running Paper version git-Paper-539 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 90a0835)

### ItemsAdder Version

ItemsAdder version 3.4.1f2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-645

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

No errors in console.

### Error (optional)

```shell
No errors in console.
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Posnetek zaslona 2023-06-13 151617](https://github.com/PluginBugs/Issues-ItemsAdder/assets/107621105/fe2e713d-cf09-42f7-955d-4d4edd77487d)
![Posnetek zaslona 2023-06-13 151708](https://github.com/PluginBugs/Issues-ItemsAdder/assets/107621105/e16523bf-e902-4244-a01c-9a1634a3edc5)

**Comment by LoneDev6** [comment]
Please write down a proper explanation for the first picture and for the second picture.
How to obtain item in first screenshot and how to obtain the second?

Please be specific.

**Comment by Domzzo** [comment]
```
  aquboots:
    display_name: "aquboots"
    lore:
    - ""
    - "&#91E8F9&oʀᴇᴛʀɪᴇᴠᴇᴅ ғʀᴏᴍ ᴛʜᴇ ᴅᴇᴘᴛʜs ᴏғ"
    - "&#91E8F9&oᴛʜᴇ ᴅᴇᴇᴘᴇsᴛ ᴏᴄᴇᴀɴ"
    permission: aquarmor
    resource:
      generate: true
      textures:
      - s_aqua:aquboots
    specific_properties:
      armor:
        slot: FEET
        custom_armor: aquarmor
    enchants:
      - protection:5
      - waterwalker:1
```

      
      The above is armor configuration for the first picture, I have applied 'waterwalker' enchant through configuration, after doing /iaget aquboots in game it shows the custom 'waterwalker' enchant after the lore.
      

```
        aquboots:
    display_name: "aquboots"
    lore:
    - ""
    - "&#91E8F9&oʀᴇᴛʀɪᴇᴠᴇᴅ ғʀᴏᴍ ᴛʜᴇ ᴅᴇᴘᴛʜs ᴏғ"
    - "&#91E8F9&oᴛʜᴇ ᴅᴇᴇᴘᴇsᴛ ᴏᴄᴇᴀɴ"
    permission: aquarmor
    resource:
      generate: true
      textures:
      - s_aqua:aquboots
    specific_properties:
      armor:
        slot: FEET
        custom_armor: aquarmor
    enchants:
      - protection:5
```

The above is configuration without 'waterwalker' enchant, after doing /iaget aquboots and doing /ae enchant waterwalker 1 on the item, it displays as on second picture.
