### ISSUE TITLE
New behaviour `complex_furniture` - use custom entities to create animated furniture

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2745]
Would be nice to use the current custom entities system to create furniture which can have also animations.

# Some considerations

## Temporary workaround until the update is released

For now you can create an "admin" furniture just by creating a custom ItemsAdder entity which is based on ARMOR_STAND as type and then you can spawn it yourself using the `/iaentity spawn` command in your spawn location, lobby or protected areas.

## Why isn't it implemented right now
The reason this is not current a feature is that I fear people from abusing it and then complain about performance.
For example giving that feature to players is very dangerous because they could spawn lot of furniture around.

## Important notes

- must make some sort of checking to avoid players placing too many furniture near the same chunk
- make big ass warnings to make admins aware that:
  - they should not make furniture easy to craft, to avoid people abusing them
  - they should not make furniture using too many bones or too detailed

**Comment by LoneDev6** [comment]
```yml
  ceiling_fan:
    name: Ceiling Fan
    resource:
      material: PAPER
      generate: true
      texture: item/ceiling_fan
    behaviours:
      complex_furniture:
        entity: ceiling_fan
        light_level: 10
        solid: true
        drop_when_mined: true
        max_per_chunk: 2
        static: true
        placement_offset:
          ceiling: -0.5
          wall: 2
          floor: 0
    events:
      placed_furniture:
        break:
          execute_commands:
            command:
              command: minecraft:tell {player} break furniture!
        interact:
          execute_commands:
            command:
              command: minecraft:tell {player} interact furniture!
```

**Comment by LoneDev6** [comment]
## Example

Draft tutorial here: https://itemsadder.devs.beer/~/changes/652/plugin-usage/adding-content/furniture-complex
Download the example pack here: [test_complex_furniture_beta_1.zip](https://github.com/user-attachments/files/18989415/test_complex_furniture_beta_1.zip)

```yml
info:
  namespace: my_furniture
items:
  # https://itemsadder.devs.beer/~/changes/652/plugin-usage/adding-content/furniture-complex
  ceiling_fan:
    name: Ceiling Fan
    resource:
      material: PAPER
      generate: true
      texture: item/ceiling_fan
    behaviours:
      complex_furniture:
        entity: ceiling_fan
        light_level: 10
        solid: true
        static: true
        drop_when_mined: true
        max_per_chunk: 99999
        placement_offset:
          ceiling: -0.5
          # wall: 2
          floor: 0.1
        sound:
          break: minecraft:item.armor.equip_diamond
          place: minecraft:item.armor.equip_diamond
    events:
      placed_furniture:
        break:
          execute_commands:
            command:
              command: minecraft:tell {player} break furniture!
              as_console: true
        interact:
          execute_commands:
            command:
              command: minecraft:tell {player} interact furniture!
              as_console: true
entities:
  ceiling_fan:
    model_folder: entity/ceiling_fan
    type: ARMOR_STAND
    gravity: false
```
