### ISSUE TITLE
Rename WorldGuard furniture flags to avoid confusion

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2783]
Currently flags names are misleading.

I will rename them from:
- `ia-placed-armorstand-interact`
- `ia-placed-itemframe-interact`

to: `ia-placed-furniture-interact`.

The old rules will still work if enabled in config.yml:
```yml
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
```
