### ISSUE TITLE
Hats don't trigger wear (and maybe unwear too)

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2789]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Putting on a hat doesn't trigger wear/unwear

### Steps to reproduce the issue

1. Try any hat from iawearables, none of them trigger wear event

### Server version

git-Purpur-"2e5dcc6" (MC: 1.20.1)

### ItemsAdder Version

3.5.0b

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

Not needed

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
This is working fine on the latest version `3.5.0c-r6`.

```yml
  ruby_pickaxe_hat:
    enabled: true
    display_name: display-name-ruby_pickaxe_hat
    permission: iawearables.ruby_pickaxe_hat
    resource:
      material: FEATHER
      generate: false
      model_path: hat/ruby_pickaxe_hat
    behaviours:
      hat: true
    events:
      wear:
        execute_commands:
          change_me_1:
            command: tell {player} amogus
```
