### ISSUE TITLE
The 'CustomiModelData starting value' configuration is invalid

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#2792]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The ModeId assigned after modifying the value of CustomimModelData starting value in the configuration file is not the starting value of the configuration

Sorry, it was not fixed in the previous update and the issue has been reissued #2753 
#

### Steps to reproduce the issue

1.Modifying CustomimModelData starting value
```yml
  items:
    CustomModelData-starting-value:
      ALL: 100000
      DIAMOND: 110000
```

2.Edit files under this path contents\_iainternal\configs\icons.yml
3.Add the following content at the beginning of the file
```yml
items:
  test1:
    enabled: true
    display_name: display-name-icon_left_blue
    resource:
      material: PAPER
      model_id: 10042
      generate: true
      textures:
        - icons/icon_left_blue
```

4.Clear the contents of the storage folder and restart the server
5.In file items_ids_cache.yml, you will see the following content
```yml
PAPER:
  _iainternal:test1: 10042
  _iainternal:icon_left_blue: 10043
  _iainternal:icon_right_blue: 10044
  _iainternal:icon_search: 10045
  _iainternal:icon_cancel: 10046
  _iainternal:icon_arrow_chest: 10047
  _iainternal:icon_back_orange: 10048
  _iainternal:icon_next_orange: 10049
```

Among them, `_iainternal:test1: 10042` is the modeId specified in the configuration, and the rest of the content did not generate a modeId according to the configuration requirements in the config

### Server version

This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)

### ItemsAdder Version

ItemsAdder version 3.5.0b

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25
