### ISSUE TITLE
Issue with some recipes

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2804]
Some particular recipes have issues, caused by recipes hashing collisions.
Source: https://discord.com/channels/533407895010803753/533413171403292712/1121162472594870425

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/8b6c5a88-6b74-4334-b4f9-51442d9baf2b)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0d669a0b-88d2-456d-a58a-30601f0b5ee5)

Full config:
```yml
info:
  namespace: recipe_bug
recipes:
  crafting_table:
    bamboo_wooden_hoe2:
      enabled: true
      pattern:
        - Xww
        - XsX
        - XsX
      ingredients:
        w: BAMBOO_PLANKS
        s: STICK
      result:
        item: item1
        amount: 1
    crimson_wooden_shovel:
      enabled: true
      pattern:
        - XwX
        - XsX
        - XsX
      ingredients:
        w: CRIMSON_PLANKS
        s: STICK
      result:
        item: item2
        amount: 1
items:
  item1:
    enabled: true
    display_name: item1
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: EMERALD
  item2:
    enabled: true
    display_name: item2
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: DIAMOND
```
