### ISSUE TITLE
Unlock recipes when clicking on custom item in inventory

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2805]
Allow recipes to be discovered when an ingredient/result is interacted in any container.
This allows to avoid confusion since previously recipes were discovered only on item pickup.

```yml
  custom-recipes:
      # .....
      on-item-click:
        any: true
        ingredients: true
```
