### ISSUE TITLE
2x2 recipes not working correctly in player inventory

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2806]
This recipe for example does not return any result if used in the player inventory.

```yml
    EGGS:
      permission: iasurvival.various.EGGS
      enabled: true
      pattern:
        - XX
        - XN
      ingredients:
        'N': iasurvival:eggs_nest
      result:
        item: EGG
        amount: 3
      return_items:
        replace:
          eggs_nest: nest
```
