### ISSUE TITLE
Update smithing to new 1.20 mechanics

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2815]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

Smithing is currently broken in IA because Mojang updated the smithing mechanics in 1.20 to force the use of templates.

I suggest updating the current system to allow vanilla smithing templates to be used in IA, as well as being able to make custom smithing templates (if that's possible).

For more info: https://minecraft.fandom.com/wiki/Smithing_Template#Chest_loot

Made a new issue instead of bumping #524.

### Steps to reproduce the issue

1. Add smithing item
3. /iazip
4. It doesn't work

### Server version

Current: git-Purpur-2001 (MC: 1.20.1)*
Previous: git-Purpur-1996 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.5.0b

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs 1.0.25

### FULL server log

https://pastebin.com/ipgmigLt

### Error (optional)

```shell
No error in console.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: testserv
recipes:
  smithing:
    super_axe:
      permission: testserv
      enabled: true
      base: DIAMOND_AXE
      addition: testserv:test_ingot
      result:
        item: testserv:super_axe
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

Smithing table now requires template to upgrade items (example with netherite upgrade template and netherite pickaxe):
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80675840/d0e82f6e-a91f-469a-a75b-cdb43bcfb388)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80675840/bee3c3e5-694e-46ee-814e-fae64173010b)

**Comment by yorik100** [comment]
Good idea!

**Comment by LoneDev6** [comment]
# Testing on latest 4.0.8-beta-2

## Example recipe

![Image](https://github.com/user-attachments/assets/39b14706-5ae1-450b-b6ef-488e3bae37d7)

```yml
info:
  namespace: test
recipes:
  smithing:
    test_smithing:
      enabled: true
      base: DIAMOND_SWORD
      addition: EMERALD
      result:
        item: ruby_sword
        amount: 1
```

### Attributes are kept

#### Enchants

![Image](https://github.com/user-attachments/assets/9aca1de4-d7b7-4f2e-a2a6-2aef68bafe55)

![Image](https://github.com/user-attachments/assets/2e4c9cb1-95c9-4b6c-8834-b54499e2dd36)

#### Lore, Display name

![Image](https://github.com/user-attachments/assets/e224a654-1604-4fdc-9d23-3f826aa4dad8)

![Image](https://github.com/user-attachments/assets/070c7164-8c4e-460d-9c2d-1f43a49d3899)

------
It also supports durability, custom nbt data, custom model data etc, based on the settings.
```yml
        move_attributes:
          other_nbt: true
          durability: true
          name: true
          lore: true
          custom_model_data: true
          enchants: true
          material: false
```


### Testing new `template` attribute

![Image](https://github.com/user-attachments/assets/5eb6ef02-30ec-4a19-abc9-4b3f0e52d369)
