### ISSUE TITLE
Allow multiple instances of the same item in the grid of shapeless recipes 

### ISSUE THREAD

**Issue by L0stedMrlion** [PluginBugs/Issues-ItemsAdder#2831]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Mrlion#4679

### What happened?

My recipe dont work with shapeless: true.

info:
  namespace: lionsproject
recipes:
  crafting_table:
    crafting_soul_ingot:
      enabled: true
      shapeless: true
      pattern:
      - AAA
      - ABB
      - BBX
      ingredients:
        A: lionsproject:gilded_ingot
        B: ECHO_SHARD
      result:
        item: lionsproject:soul_ingot
        amount: 2

### Steps to reproduce the issue

x

### Server version

git-Purpur-1980 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.5.0c

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest(3).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11918189/latest.3.log)

### Error (optional)

```shell
x
```

### Problematic items yml configuration file (optional)

```shell
x
```

### Other files, you can drag and drop them here to upload. (optional)

x

### Screenshots/Videos (you can drag and drop files or paste links)

x

**Comment by LoneDev6** [comment]
This is not a shapeless recipe as you added "pattern" property.
```yml
info:
  namespace: lionsproject
recipes:
  crafting_table:
    crafting_soul_ingot:
      enabled: true
      shapeless: true
      ingredients:
        A: lionsproject:gilded_ingot
        B: ECHO_SHARD
      result:
        item: lionsproject:soul_ingot
        amount: 2
```

Anyway for now shapeless recipes support only 1 item of the same type, you can't have multiple instances of the same item in the grid.
I will probably find a solution for that in a future update.
