### ISSUE TITLE
Toggle particle effect for players around

### ISSUE THREAD

**Issue by makeevrserg** [PluginBugs/Issues-ItemsAdder#2909]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

makeevrserg

### Describe the solution you'd like

In root config.yml add option
```yaml
items:
  # This will enabled particle display for all players, not only for one who casted it
  display-particles: true
```

### Is your feature request related to a problem?

Other players don't see particle effects of `events.play_effect`. 

Bad for us because we have magic wands and etc, which creates particles. And without those particles other players can't see whether player casted spell or not.

### Describe alternatives you've considered

We've tried shoot_particle, but it doesn't work as it required to us

We also tried to use it with api, but there's not such event

### Additional context

I'm talking about `events.play_effect` and `events.play_particle`

### Example
When below code is executed in game only player who interacted will see this effect. But we expect to other player around also will see this

Same with play_particle
```yaml
    events:
      interact:
        right:
          play_effect:
            name: DRAGON_BREATH
```
