### ISSUE TITLE
Projectile options

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2913]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sircraftypants#4875

### Describe the solution you'd like

i've found Range Weapon feature requests but nothing in them about Projectiles so hoping this will be possible and accepted.

```yaml
    behaviours:
      gun:
        projectile: custom_guns:energy_cell  
          amount: 1            <- could require more than
        decrement_usages:
          amount: 15
        remove: custom_guns:energy_cell     <- at 0 decrement
          amount: 1 
            trigger:
              give: custom_guns:empty_energy_cell  <- after remove   (could also have drop option instead here)
              amount: 1
```

### Is your feature request related to a problem?

Need to be able to create ammo that will act as an ammo clip rather than have stacks of ammunition in the inventory.

### Describe alternatives you've considered

The alternative is to use another plugin for range weapons entirely which is not an option.
