### ISSUE TITLE
Issue with Executableitem as an IA item

### ISSUE THREAD

**Issue by kristophergeou** [PluginBugs/Issues-ItemsAdder#2925]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Even though the executable item as an ia item seems to be working just fine since i ve tested it with the checkitem expansion, stacking it with a normal executable item isnt possible. It seems that IA doesnt copy properly the executable's item name in the nbt

The `/paper dumpitem` of the executable item
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/114158743/c629c628-2171-40a2-bb0d-b119ee8580ee)

The `/paper dumpitem` of the executable item of itemsadder
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/114158743/209a275f-72f8-4316-b9f4-def9117d1f0d)

I have followed the instructions from here: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/executableitems 

Thats my config for the itemsadder executableitem 
```yml
  raw_mythril:
    display_name: executableitem_mythril
    executableitem:
      id: mythril
    resource:
      material: PAPER
      generate: true
      textures:
        - raw_mythril.png
```
And thats the executableitem config 
```yml
name: '&ctest'
material: PAPER
glow: false
disableStack: false
keepItemOnDeath: false
canBeUsedOnlyByTheOwner: false
storeItemInfo: false
unbreakable: false
usage: 0
usageLimit: -1
cancelEventIfNoPerm: false
cancelEventIfNotOwner: false
disabledWorlds: []
recognitions: []
customModelData: 10061
nbt:
  '0':
    key: PublicBukkitValues
    type: COMPOUND
    value:
      nbt:
        '0':
          key: score:usage
          type: INT
          value: 1
        '1':
          key: executableitems:ei-id
          type: STRING
          value: mythril
  '3':
    key: itemsadder
    type: COMPOUND
    value:
      nbt:
        '0':
          key: namespace
          type: STRING
          value: minerals_pack
        '1':
          key: id
          type: STRING
          value: raw_mythril
config_5: true
config_update: true
dropOptions:
  glowDrop: false
  glowDropColor: WHITE
  displayNameDrop: false
hiders:
  hideEnchantments: false
  hideUnbreakable: false
  hideAttributes: false
  hidePotionEffects: false
  hideUsage: false
  hideDye: false
enchantments: {}
giveFirstJoin:
  giveFirstJoin: false
  giveFirstJoinAmount: 1
  giveFirstJoinSlot: 0
restrictions: {}
variables: {}
activators: {}
displayConditions:
  playerConditions: {}
  worldConditions: {}
  itemConditions: {}
  placeholdersConditions: {}
  enableFeature: false
attributes: {}
```

### Steps to reproduce the issue

1) Get a custom item imported from ia and do `/ei create test`, which will create an executableitem called `test` 
2) go to the itemsadder config of that item and follow the instructions here https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/executableitems to make that `test` executableitem to change it to an itemsadder one.
3) Get the test executableitem with `/ei give {player} test 1` and run `/paper dumpitem` 
4) Get the test itemsadder executableitem with `/iaget test 1` and run `/paper dumpitem` 
 

### Server version

This server is running Paper version git-Paper-50 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 990be16)
You are 50 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-40 (MC: 1.20.1)

### ItemsAdder Version

Itemsadder Version: 3.5.0-r2
Executableitem Version: 6.0.2

### ProtocolLib Version

ProtoLib Version: 5.1.0 - 654

### LoneLibs Version

Lonelibs version: 1.0.25
