### ISSUE TITLE
Splash Potions

### ISSUE THREAD

**Issue by ImmortalBeastYT** [PluginBugs/Issues-ItemsAdder#2946]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

immortalrhyme

### Describe the solution you'd like

A way to make spalsh potions inside ItemsAdder.

For example, you throw a custom splash potion, when it hits the ground we can use the `item_hit_ground` event to give an effect to players in an effective radius. Maybe it could look like this:

```
example_splash_potion:
    display_name: Example Splash Potion
    permission: example_splash_potion
    resource:
      material: SPLASH_POTION
      generate: true
      textures:
      - example_splash_potion.png
    events:
      item_hit_ground:
        splash_potion:
          effect: EFFECT
          effect_modifier: 0
          effective_radius: 3
```

### Is your feature request related to a problem?

I've been looking for a solution to this on and off for a while, and I think it'd be better for useability if this was a native feature

### Describe alternatives you've considered

I've considered maybe trying to log the position where the splash potion item lands and use that in another plugin, however that doesn't seem to be possible
