### ISSUE TITLE
Range not working

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2951]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sircraftypants#4875

### What happened?

Under gun_shot,  range isn't working as it's supposed too.

I tested the below at different ranges

```yaml
    events:
      gun_shot:
        play_sound:
          name: minecraft:m41apulse
          volume: 1
          pitch: 1
        play_effect:
          name: SMOKE
        damage_entity_in_sight:
          entity_groups:
            - HOSTILE
            - PLAYERS
          damage: 15
          range: 12          
```

### Steps to reproduce the issue

Use a projectile weapon and test its set range.

### Server version

This server is running Paper version git-Paper-111 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

[08:25:18 INFO]: ItemsAdder version 3.5.0c-r4
[08:25:18 INFO]: Customized Minecraft without client mods!
[08:25:18 INFO]: Website: devs.beer
[08:25:18 INFO]: Author: LoneDev

### ProtocolLib Version

[08:24:24 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-665
[08:24:24 INFO]: Provides read/write access to the Minecraft protocol.
[08:24:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[08:24:57 INFO]: LoneLibs version 1.0.25
[08:24:57 INFO]: Collection of libs used by my plugins
[08:24:57 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
info:
  namespace:gun
items:
    rifle:
    enabled: true
    display_name: "Rifle"
    permission: custom.guns  
    resource:
      material: PAPER
      generate: false
      model_path: item/pulse_rifle
    behaviours:
      gun:
        projectile: custom_guns:energy_cell  
    blocked_enchants:
      - ALL
    events_cooldown: 2.5 ########### <-- EXAMPLE 1 seconds            
    events:
      gun_shot:
        play_sound:
          name: minecraft:m41apulse
          volume: 1
          pitch: 1
        play_effect:
          name: SMOKE
        damage_entity_in_sight:
          entity_groups:
            - HOSTILE
            - PLAYERS
          damage: 15
          range: 12
```
