### ISSUE TITLE
Recipe rework request

### ISSUE THREAD

**Issue by auyylaso** [PluginBugs/Issues-ItemsAdder#2970]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

slop_me

### Describe the solution you'd like

A rework of the recipe system.
Current system : 
```yml
apple_juice:
  enabled: true
  pattern:
    - AA
    - JX
  ingredients:
    A: APPLE
    J: food:juicer
  result:
    item: food:apple_juice
    amount: 1
```
Purposed rework :
```yml
apple_juice:
  enabled: true
  shapeless: true
  ingredients:
    A: 'APPLE', 2
    J: food:juicer
  result:
    item: food:apple_juice
    amount: 1
```
Current system : 
```yml
mixing_bowl:
  enabled: true
  pattern:
  - XXX
  - WSW
  - XWX
  ingredients:
    S: STICK
    W: OAK_PLANKS
  result:
    item: food:mixing_bowl
    amount: 1
```
Purposed rework :
```yml
    mixing_bowl:
      enabled: true
      pattern:
      - XXX
      - WSW
      - XWX
      ingredients:
        S: STICK
        W: 'OAK_PLANKS', 'BIRCH_PLANKS', 'DARK_OAK_PLANKS' //so on so on
      result:
        item: food:mixing_bowl
        amount: 1
```  
Current system :
```yml
butter:
  enabled: true
  shapeless: true
  ingredients:
    SP: food:sauce_pan
    C: food:cream
    S: food:salt
  result:
    item: food:butter
    amount: 1
  return_items:
    replace:
      A: food:sauce_pan
```
Purposed rework :
```yml
butter:
  enabled: true
  shapeless: true
  ingredients:
    SP: food:sauce_pan
    C: food:cream
    S: food:salt
  result:
    item: food:butter
    amount: 1
  return_items:
      A: food:sauce_pan
```

 Side note replace is actually currently completely broken refer to https://github.com/PluginBugs/Issues-ItemsAdder/issues/2968

### Is your feature request related to a problem?

Yes and no. It's probably not a problem for everyone but for me it's really hampering my ability to work quickly and efficiently within the yml files.

### Describe alternatives you've considered

Making my own plugin importing itemsadder. Making multiple recipes for the same item for multiple ingredients.
