### ISSUE TITLE
Loot entity NBT rule not working when NBT path has 1 key 

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2994]
```yml
chat_panthere:
  type: CAT
  nbt:
    profession:
      path: variant
      value: all_black
      type: string
  items:
    item_1:
      item: collectionnables:cadre_chat_panthere
      min_amount: 1
      max_amount: 1
      chance: 100
```
