### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack - loots configuration NBT rule

### ISSUE THREAD

**Issue by imh3ro** [PluginBugs/Issues-ItemsAdder#3008]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.herodev

### What happened?

Plugin not starting. Gives an error/warning and doesn't load. Other people on discord and forum experiencing this too. 

Forum post:
https://forum.devs.beer/d/1815-weird-error-after-updating-to-the-latest-version-and-plugin-doesnt-start

### Steps to reproduce the issue

1. Update to the current latest version v3.5.0c-r5
2. Start the server

### Server version

This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)

### ItemsAdder Version

v3.5.0c-r5

### ProtocolLib Version

5.1.1-SNAPSHOT-668

### LoneLibs Version

LoneLibs version 1.0.25

### Error (optional)

```shell

[17:22:30 WARN]: [ItemsAdder] Plugin ItemsAdder v3.5.0c-r5 generated an exception while executing task 162

java.lang.VerifyError: Bad type on operand stack

Exception Details:

Location:

ia/m/fa.k(Lorg/bukkit/entity/Entity;)Z @189: invokevirtual

Reason:

Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'dev/lone/LoneLibs/nbt/nbtapi/NBTCompound'

Current Frame:

bci: @189

flags: { }

locals: { 'ia/m/fa', top, top, 'java/lang/Object', 'dev/lone/LoneLibs/nbt/nbtapi/NBTType' }

stack: { 'java/lang/Object', 'java/lang/String' }

Bytecode:

0000000: bb00 0559 2bb7 0030 4d2c 2ab4 0023 0332

0000010: b600 33b6 003a 9a00 0503 ac2c 2ab4 0023

0000020: 0332 b600 323a 0419 04b2 001b a500 082c

0000030: 4ea7 0077 2c2a b400 2303 32b6 0031 4e04

0000040: 3605 1505 2ab4 0023 be04 64a2 0028 2d2a

0000050: b400 2315 0532 b600 2fb6 003a 9a00 0503

0000060: ac2d 2ab4 0023 1505 32b6 0028 4e84 0501

0000070: a7ff d22d 2ab4 0023 2ab4 0023 be04 6432

0000080: b600 2fb6 003a 9a00 0503 ac2d 2ab4 0023

0000090: 2ab4 0023 be04 6432 b600 2e3a 0419 042a

00000a0: b400 21a5 0005 03ac 1904 b200 20a6 001b

00000b0: 2d2a b400 232a b400 23be 0464 32b6 002d

00000c0: 2ab4 0024 b600 4bac 1904 b200 1ea6 001b

00000d0: 2d2a b400 232a b400 23be 0464 32b6 002b

00000e0: 2ab4 0024 b600 44ac 1904 b200 1ca6 001b

00000f0: 2d2a b400 232a b400 23be 0464 32b6 0029

0000100: 2ab4 0024 b600 3eac 1904 b200 1da6 001b

0000110: 2d2a b400 232a b400 23be 0464 32b6 002a

0000120: 2ab4 0024 b600 41ac 1904 b200 1aa6 001b

0000130: 2d2a b400 232a b400 23be 0464 32b6 0027

0000140: 2ab4 0024 b600 3bac 1904 b200 1fa6 001b

0000150: 2d2a b400 232a b400 23be 0464 32b6 002c

0000160: 2ab4 0024 b600 48ac 03ac

Stackmap Table:

full_frame(@27,{Object[#9],Top,Object[#5]},{})

same_frame(@52)

full_frame(@66,{Object[#9],Top,Top,Object[#4],Top,Integer},{})

same_frame(@97)

chop_frame(@115,2)

same_frame(@139)

full_frame(@168,{Object[#9],Top,Top,Object[#18],Object[#7]},{})

same_frame(@200)

same_frame(@232)

same_frame(@264)

same_frame(@296)

same_frame(@328)

full_frame(@360,{},{})

at ia.m.eQ.d(SourceFile:97) ~[ItemsAdder_3.5.0c-r5.jar:?]

at ia.m.eQ.a(SourceFile:57) ~[ItemsAdder_3.5.0c-r5.jar:?]

at ia.m.G.a(SourceFile:2463) ~[ItemsAdder_3.5.0c-r5.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-169]

at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-169]

at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by hillbilly1911** [comment]
i am having the same issue

**Comment by DexterSK** [comment]
same...

**Comment by LoneDev6** [comment]
This seems to be caused by a bad configuration of an nbt match rule for an ItemsAdder loot.
Check your loots to see which one has a bad NBT type.
For example:
```yml
loots:
  mobs:
    villager:
      type: VILLAGER
      nbt:
        profession:
          path: VillagerData.profession
          value: minecraft:farmer
          type: xxxx # <---- WRONG
      items:
        item_1:
          item: iawearables:straw_hat
          min_amount: 1
          max_amount: 1
          chance: 100
```

Use the [official VSCODE extension](https://itemsadder.devs.beer/plugin-usage/files-editor) to get the list of valid `type` values.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/9d73da14-376a-4a67-ba90-ccba209d982a)

-----
It's strange btw, you shouldn't really get any error for invalid type tags.
You should get this message:
`Unknown nbt.type 'xxxx' for nbt path 'VillagerData.profession'. Allowed: string, int, float, double, byte, short`.

Can you try checking if your Java installation is correctly installed? Also try redownloading the ItemsAdder JAR file.

Thanks

**Comment by Agaloth** [comment]
So technically this would be wrong?
```
loots:
    grass:
      type: GRASS
      items:
        four_leaf_clover:
          item: itemsadder:four_leaf_clover
          min_amount: 1
          max_amount: 1
          chance: 1```

**Comment by LoneDev6** [comment]
No it's good, I was referring to the nbt rule logic

**Comment by Agaloth** [comment]
> No it's good, I was referring to the nbt rule logic

After testing, the issue indeed comes from Itemsadder default pack, I plugman reloaded to keep testing until it worked.

Removing this part made Itemsadder boot up:

```
loots:
  mobs:
    villager:
      type: VILLAGER
      nbt:
        profession:
          path: VillagerData.profession
          value: minecraft:farmer
          type: string
      items:
        item_1:
          item: itemsadder:straw_hat
          min_amount: 1
          max_amount: 1
          chance: 100
    ender_dragon:
      type: ENDER_DRAGON
      items:
        item_1:
          item: itemsadder:ender_dragon_wings
          min_amount: 1
          max_amount: 1
          chance: 100
```
