### ISSUE TITLE
ItemFrame Furnitures can be overlapped in same locations....

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#3014]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

ItemFrame Furnitures can be overlapped in same locations....

### Steps to reproduce the issue

I already said about this..
(For testing, break blocks, and them get blocks)
Video: https://youtu.be/I_OpbN382Eo

### Server version

Paper 1.19.4 latest haha

### ItemsAdder Version

3.5.0c-r5b

### ProtocolLib Version

5.0.0-625

### LoneLibs Version

1.0.25

**Comment by IPECTER** [comment]
@LoneDev6 
here!
```yml
items:
  picture:
    display_name: ''
    resource:
      material: PAPER
      model_path: block/picture
    template: true
    behaviours:
      furniture:
        shift_interact_rotate: false
        placeable_on:
          walls: true
          ceiling: false
          floor: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 0.15
```
