### ISSUE TITLE
Replace a custom block by a custom block with event

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3015]
This config doesn't work in the current plugin version.
It should replace the broken custom block with another custom block but it doesn't.

```yml
info:
  namespace: blocks

items:  
  buche_chene_mousse:
    enabled : true
    permission: ""
    display_name: "%#949393%Bûche de chêne moussue"
    lore:
    - ':block:'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        cancel_drop: true
        hardness: 1
        no_explosion: false
        sound:
          place:
            name: block.wood.place
            volume: 1
            pitch: 0.9
          break:
            name: block.wood.break
            volume: 1
            pitch: 0.9
    events:
      placed_block:
        break:
          replace_block:
            from: buche_chene_mousse
            to: escargot
            decrement_durability: 0
    resource:
      material: PAPER
      generate: true
      textures:
        - joueur/buche_chene_mousse_down
        - joueur/buche_chene_mousse_east
        - joueur/buche_chene_mousse_north
        - joueur/buche_chene_mousse_south
        - joueur/buche_chene_mousse_up
        - joueur/buche_chene_mousse_west
      model_id: 17000

  escargot:
    enabled : true
    permission: ""
    display_name: "%#fffb00%Escargot"
    lore:
    - ''
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.grass.place
          break:
            name: block.grass.break
    resource:
      material: PAPER
      generate: false
      model_path: insectes/escargot
      model_id: 17001
```
