### ISSUE TITLE
`permission` attribute name is misleading

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3023]
Would be better to change it to `permission_suffix` since it's exactly what is used for.

----

For example this configuration:
```yml
info:
  namespace: iasurvival
items:
  dark_amethyst_block:
    enabled: true
    display_name: display-name-dark_amethyst_block
    permission: iasurvival.minerals.dark_amethyst_block
    resource:
      material: PAPER
      generate: true
      textures:
        - block/minerals/dark_amethyst_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: PURPLE_CONCRETE
```

`permission: iasurvival.minerals.dark_amethyst_block`

This is the `see item` permission for this item: `ia.user.ia.seeitem.iasurvival.minerals.dark_amethyst_block`.
This allows easy use of the `*` operator to assign your permissions in smart ways, for example to give all `iasurvival` minerals `see item` permissions to a player:
`ia.user.ia.seeitem.iasurvival.minerals.*`.

The suffix logic is meant to allow the admin to easily organize permissions by grouping them, like shown in the previous example.
