### ISSUE TITLE
Better cooldown configuration settings

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3042]
Better cooldown configuration settings.
Also draft of the `indicator` feature #1670 which introduces `HIDDEN` and `TITLE` for now.

From:
```yml
events_cooldown: 20
```

To:
```yml
    events_settings:
      cooldown:
        ticks: 20
        indicator: HIDDEN
```
