### ISSUE TITLE
Flow control over actions

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3043]
Introduce a way to partially control the flow of the event actions in order to create more customized logic for custom items.

- `stop_if_last_success`: Doesn't execute this and the next actions if the previous action **succeeded**
- `stop_if_last_fail`: Doesn't execute this and the next actions if the previous action **failed**
- `skip_if_last_success`: Doesn't execute this action if the previous action **succeeded**
- `skip_if_last_fail`: Doesn't execute this action if the previous action **failed**
- `stop_if_any_success`: Doesn't execute this and the next actions if **ANY** of the previous actions **succeeded**
- `stop_if_any_fail`: Doesn't execute this and the next actions if **ANY** of the previous actions **failed**
- `skip_if_any_success`: Doesn't execute this action if **ANY** of the previous actions **succeeded**
- `skip_if_any_fail`: Doesn't execute this action if **ANY** of the previous actions **failed**
- `stop_if_success`: Doesn't execute this and the next actions if a specific previous action **succeeded**
- `stop_if_fail`: Doesn't execute this and the next actions if a specific previous action **failed**
- `skip_if_success`: Doesn't execute this action if a specific previous action **succeeded**
- `skip_if_fail`: Doesn't execute this action if a specific previous action **failed**

Some example items:

```yml
info:
  namespace: actions_flow_test
items:
  block_replacer:
    display_name: actions_flow_test:block_replacer
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: STONE_SWORD
    lore:
      - "Item which plays <yellow>critical particle</yellow>"
      - "and <yellow>block.barrel.open sound</yellow>"
      - "and reduces durability if if <aqua>replace_block</aqua> is successful."
      - " "
      - "It also avoids instant replacement of the block due"
      - "to the fact that both <aqua>replace_block</aqua> actions would interfere."
    events:
      interact_mainhand:
        left:
          replace_block:
            from: GRASS_BLOCK
            to: STONE
            decrement_durability: 1
          replace_block_2:
            from: STONE
            to: GRASS_BLOCK
            decrement_durability: 1
            flow:
              skip_if_last_success: true
          play_particle:
            name: CRIT
            flow:
              stop_if_last_fail: true
          play_sound:
            name: block.barrel.open
            volume: 1
            pitch: 1
          decrement_durability:
            amount: 1
  magic_wand:
    display_name: actions_flow_test:magic_wand
    resource:
      generate: false
      model_path: minecraft:item/stick
      material: STONE_SWORD
    lore:
      - "Magic wand which plays <yellow>critical particle</yellow>"
      - "and <yellow>block.barrel.open sound</yellow>"
      - "and reduces durability if if <aqua>damage_entity_in_sight</aqua> is successful."
    events:
      interact_mainhand:
        left:
          shoot_particle:
            name: CRIT
            distance: 7
          damage_entity_in_sight:
            damage: 1
            distance: 8
          play_particle:
            name: CRIT
          play_sound:
            name: block.barrel.open
            volume: 1
            pitch: 1
          decrement_durability:
            amount: 1
  block_replacer_advanced:
    display_name: actions_flow_test:block_replacer_advanced
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: STONE_SWORD
    lore:
      - "Item which plays <yellow>critical particle</yellow>"
      - "and <yellow>block.barrel.open sound</yellow>"
      - "and reduces durability if if <aqua>replace_block</aqua> is successful."
      - " "
      - "It also avoids instant replacement of the block due"
      - "to the fact that both <aqua>replace_block</aqua> actions would interfere."
    events_settings:
      cooldown:
        ticks: 4
        indicator: HIDDEN
    events:
      interact_mainhand:
        left:
          replace_block:
            from: GRASS_BLOCK
            to: STONE
            decrement_durability: 1
          play_particle__replace_block:
            name: CRIT
            flow:
              skip_if_fail: replace_block
          play_sound__replace_block:
            name: block.barrel.open
            volume: 1
            pitch: 1
            flow:
              skip_if_fail: replace_block
          ####
          replace_block_2:
            from: STONE
            to: GRASS_BLOCK
            decrement_durability: 1
            flow:
              skip_if_success: replace_block
          play_particle__replace_block_2:
            name: EXPLOSION_NORMAL
            flow:
              skip_if_success: replace_block
          play_sound__replace_block_2:
            name: block.note_block.flute
            volume: 1
            pitch: 1
            flow:
              skip_if_success: replace_block
          #####
          decrement_durability:
            amount: 1
            flow:
              skip_if_any_fail: true
```

This new feature will fix this particular use case: #1520
