### ISSUE TITLE
legacy hex color format not working anymore

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3057]
More info: https://forum.devs.beer/d/1859-how-to-use-legacy-hex-color-format-in-ia-351

> Hi there! I haven't been able to find an answer to this, is it possible to continue using the old hex color formatting in the latest ia update? (ex. &#xxxxx)
> 
> I ask this because I have over 200 items that use this format. I try to stay up to date with ia for all the new features and fixes, but if it is not possible to continue using the old format this will take me many many hours to change every single config, not to mention that this may also break some custom crafting recipes added by other plugins which will then have to be remade. Any help at all is greatly appreciated, I am desperately hoping there is a config option or something that I've completely looked over to resolve this. Thank you!

```yml
info:
  namespace: git
items:
  test_item_hex_legacy:
    display_name: "&#538fe3˖&#5b95e5B&#639be6l&#6aa1e8u&#72a7eae&#7aadebb&#82b3ede&#89b9eel&#91bff0l"
    permission: test_item_hex_legacy
    resource:
      material: PAPER
      generate: false
      model_path: minecraft:item/emerald
```

**Comment by LoneDev6** [comment]
Compatibility will be added.
Anyway please consider using this method for the new items that you will create:
```yml
  test_item_hex_legacy_2:
    display_name: "<gradient:#538fe3:#91bff0>˖Bluebell"
    permission: test_item_hex_legacy
    resource:
      material: PAPER
      generate: false
      model_path: minecraft:item/emerald
```
