### ISSUE TITLE
Option to specify the used block states

### ISSUE THREAD

**Issue by hugohuetzel** [PluginBugs/Issues-ItemsAdder#3102]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

HugoHuetzel

### Describe the solution you'd like

Add the option to define the used list of block states of the block (for example north=true, south=false, ... for tripwire).
This is needed to share a Geyser block mappings file. Without fixed block states list, the mapping is different on every system.

### Is your feature request related to a problem?

Sharing Geyser block mappings file

### Describe alternatives you've considered

Don't know

**Comment by hugohuetzel** [comment]
For items it is possible to specify the custommodeldata in the config. But this is missing for the block states list for custom blocks

**Comment by LoneDev6** [comment]
> Without fixed block states list, the mapping is different on every system.

You just have to make sure that each server has the same `plugins/ItemsAdder/storage/`, this folder contains the custom model data for each item and also the blockstates for each custom block.

(note: make a backup before replacing files)

**Comment by BredyAK** [comment]
Hey there @LoneDev6 , the new option could be located at `items.specific_properties.block.placed_model.blockstate`, and here is an example:

```yaml
items:
  red_block:
    enabled: true
    display_name: red_block-display-name
    resource:
      material: PAPER
      generate: false
      model_id: 2
      model_path: minecraft:item/generated
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
          blockstate: instrument=basedrum,note=1,powered=false # <- New option here!
        drop_when_mined: false
        hardness: 3
        blast_resistance: 3
        break_tools_whitelist:
          - STONE_PICKAXE
          - IRON_PICKAXE
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
        sound:
          break:
            name: minecraft:internal.block.stone.break
            volume: 1.0
            pitch: 0.8
          place:
            name: minecraft:internal.block.stone.place
            volume: 1.0
            pitch: 0.8
          hit:
            name: minecraft:internal.block.stone.hit
            volume: 0.25
            pitch: 0.5
          step:
            name: minecraft:internal.block.stone.step
            volume: 0.15
            pitch: 1.0
          fall:
            name: minecraft:internal.block.stone.fall
            volume: 0.5
            pitch: 0.75
```

Refer to this thread in Discord: [https://discord.com/channels/533407895010803753/1348438925454344243](https://discord.com/channels/533407895010803753/1348438925454344243):

> How to manually set a specific blockstate for an IA item? Because there are some blockstates leave blank in IA for some other usage, and I've read the official doc https://itemsadder.devs.beer/plugin-usage/adding-content/advanced-block-properties/manual-editing-blockstates and it seems that IA only support to merge blockstates, not specify one. And I've also check the cache files, they are messy and not human-readying-friendly. (Blockstates in cache files are represented by numbers)
