### ISSUE TITLE
All Events get the attribute 'Chance'

### ISSUE THREAD

**Issue by ryxan** [PluginBugs/Issues-ItemsAdder#3127]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

so basically from what i could find the only event where chance applies is 'drop_exp' it would be nice if chance could be applied to all the events. like for example 'execute commands'.  

in my bellow example im trying to execute a command 25% of the time when breaking a placed block. but it doesnt seem to work, unless im configuring it incorrectly.

```
events:
      placed_block.break:
          execute_commands:
            cmd1:
              chance: 25
              command: 'tellraw {player} {"text":"Test","color":"gold"}'
              as_console: true
              delay: 0
```

```
1. Add the experience drop directly in the custom block creation
This has a downside, you can only set the experience drop to custom blocks, not to vanilla blocks.
  ruby_block:
    display_name: display-name-ruby_block
    permission: ruby_block
    resource:
      material: PAPER
      generate: true
      textures:
      - block/ruby_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: REDSTONE_BLOCK
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
    events:
      placed_block:
        break:
          drop_exp:
            chance: 100
            min_amount: 0
            max_amount: 3
```

### Is your feature request related to a problem?

Kind of, i need to execute commands on a percentage basis, but i cant figure out how without the chance attribute working for all events.

### Describe alternatives you've considered

None.
