### ISSUE TITLE
You cannot place blocks with 2D ICON on custom blocks

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#3150]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I followed step by step how to create "Block 2D Icon" it works well on vanilla blocks, but when trying to place it on custom blocks, they cannot be placed even with shift-right-click

### Steps to reproduce the issue

Create as it is in the wiki, and try placing on a custom block

https://itemsadder.devs.beer/plugin-usage/adding-content/block/block-2d-icon

### ItemsAdder Version

ItemsAdder version 3.6.1-beta

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.26

**Comment by LoneDev6** [comment]
I will update the wiki, basically one of the recent ItemsAdder new updates introduced a new event called `right_shift`, so you also have to use it in your configuration otherwise it won't triggered.

```yml
info:
  namespace: myitems
items:
  2d_furniture:
    display_name: 2d_furniture
    permission: 2d_furniture
    resource:
      material: PAPER
      generate: true
      textures:
      - item/2d_furniture
    events:
      interact:
        right:
          place_furniture:
            furniture: furniture
            decrement_amount: true
        right_shift:
          place_furniture:
            furniture: furniture
            decrement_amount: true
```

**Comment by paulreob** [comment]
@LoneDev6 but that is for furnitures, and for blocks like REAL_WIRE??

**Comment by LoneDev6** [comment]
I'm sure same thing will work fine, use the `right_shift` event too. Let me know.

**Comment by paulreob** [comment]
```yaml
  trevol_item:
    display_name: "Trevol"
    resource:
      material: PAPER
      generate: true
      textures:
      - misc_blocks/trevol_item
    events:
      interact:
        right:
          set_block:
            block: trevol
            decrement_amount: true
        right_shift:
          set_block:
            block: trevol
            decrement_amount: true
  trevol:
    display_name: "Trevol"
    resource:
      material: PAPER
      generate: false
      model_path: misc_blocks/trevol
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.stone.place
```
            
this no working :(
