### ISSUE TITLE
Implement `Tag` for custom items

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3161]
Similarly to the [vanilla tags](https://minecraft.fandom.com/wiki/Tag).
Would be nice to have some sort of attributes (tags) to group various items and be able to use this information in the plugin configurations.

### For example
Be able to make a tool break a particular group of blocks faster.
Let's say there is a pack which has various items:
- my_items:block1 (a rare ore)
- my_items:block2 (a rare ore)
- my_items:block3 (a common ore)

In this case a I cannot identify which ore is rare or not only based on the name, so wildcard notations (for example `block*`) won't work.

So a property `tags` could be introduced:
```yml
  block1:
    display_name: 'block1'
    resource:
      material: PAPER
      model_path: block/block1
    tags:
      - rare_ore
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: false
```

Which could be used in some special properties to match the needed group of custom blocks.
(note: this is just an example, this property `break_speed` doesn't exists).
```yml
  tool1:
    display_name: tool1
    resource:
      generate: true
      material: STONE_AXE
      textures:
        - "item/tool1"
    specific_properties:
      tool:
        break_speed:
          rule_rare_ores:
            blocks_tags:
            - rare_ore
            multiplier: 2
```
