### ISSUE TITLE
vertical radius pickaxe break

### ISSUE THREAD

**Issue by el211** [PluginBugs/Issues-ItemsAdder#3170]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

deleteduserf49f9c5e

### Describe the solution you'd like

i want the pickaxe to break 2 blocks basically when we break first block it breaks also second one
here is a video showing how its supposed to work :
https://cdn.discordapp.com/attachments/533413171403292712/1176518320976044073/Minecraft_2023-11-21_14-42-54.mp4?ex=656f2912&is=655cb412&hm=bb786fcd23d3d3d0c2dfadee67a3c310fabbecfda5479e1f34bf3aa2502b3379&

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

i want the pickaxe to break 2 blocks basically when we break first block it breaks also second one
here is a video showing how its supposed to work :
https://cdn.discordapp.com/attachments/533413171403292712/1176518320976044073/Minecraft_2023-11-21_14-42-54.mp4?ex=656f2912&is=655cb412&hm=bb786fcd23d3d3d0c2dfadee67a3c310fabbecfda5479e1f34bf3aa2502b3379&

**Comment by LoneDev6** [comment]
How did you implement this to show it in the video?
What is it from?

**Comment by el211** [comment]
> How did you implement this to show it in the video?
> What is it from?

it's from a bedrock server called histeria.fr
if you want to join it let me know ill give u the pickaxe In hand

**Comment by el211** [comment]
i also had a plugin that was made for me a long time ago that would allow a pickaxe to have vertical radius , i could send you this plugin if you wish

**Comment by LoneDev6** [comment]
I see, interesting idea, I can implement it

**Comment by el211** [comment]
> I see, interesting idea, I can implement it

when do you think this will be implemented ? do you have a specific date or smthg ? cz its urgent form my side , I can pay a little more to accelerate this if needed

**Comment by el211** [comment]
> I can schedule it for tomorrow if you send a proper donation. Open a private payment ticket on the forum. https://forum.devs.beer/

I just opened a ticket cna you pls check it?

**Comment by LoneDev6** [comment]
I answered!

This config will work in the upcoming update:
```yml
info:
  namespace: git
items:
  vertical_pickaxe:
    enabled: true
    display_name: Vertical Pickaxe
    resource:
      generate: false
      model_path: minecraft:item/diamond_pickaxe
      material: DIAMOND_PICKAXE
    events:
      block_break:
        multiple_break:
          size: 2
          vertical: true
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: true
```
