### ISSUE TITLE
Decrement durability is not failing if durability didn't change

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#3171]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sircraftypants#4875

### What happened?

I've tried to setup Guns with both Range and Distance but, you still seem to be able to hit the target further way than the set distance.

example config:  https://paste.helpch.at/wekawifiye.yaml

Can hit targets more than 10 blocks away, i used a target block and redstone lantern block to test.

### Steps to reproduce the issue

1. Add the linked gun config
2. Setup Redstone Lantern target. 
3. Shoot target block from outside 10 block radius.

### Server version

Paper-297 1.20.2

### ItemsAdder Version

ItemsAdder_3.6.2-beta-r4

### ProtocolLib Version

ProtocolLib-673

### LoneLibs Version

LoneLibs version 1.0.27

**Comment by LoneDev6** [comment]
Because you're mixing gun behaviour with manual events+action.
Gun behaviour uses invisible arrows to create its own gun logic.

If you want to create a weapon you have to decide if you want to let itemsader handle the logic using the internal gun logic or if you want to manually create a weapon using the damage_entity_in_sight action.

If you decide to use damage_entity_in_sight you won't be able to use projectiles as they don't exist with this logic, they are only part of the gun behaviour.

You should use a vanilla item type which has durability or use custom usages as alternative solution to simulate projectiles.
Then add a decrement usages/dusability to make sure to decrement the times you can shoot with that weapon.
Don't forget to check if the decrement action failed or not, to understand if you can still shoot with that weapon.

NOTE: the next code will work only after the update 3.6.2b because decrement_durability wouldn't trigger stop_if_last_fail because of a bug which I discovered while making the weapon example for you.

An example:
```yml
items:  
  bigboy_flintlock_pistol:
    enabled: true
    display_name: "Bigboy Flintlock Pistol"
    permission: custom.guns
    lore:
    - '&a[ &eCooldown&f: &a20&fsec &a]'
    - '&a[ &eDamage&f: &f4 &a]'     
    - '&a[ &eRange&f: &f10 &a]'  
    - '&a[ &eAmmo&f: Musket Ball &a]'    
    resource:
      material: STONE_SWORD
      generate: false
      model_path: item/bigboy_flintlock_pistol
    durability:
      max_custom_durability: 200
      custom_durability: 50
      disappear_when_broken: false
    blocked_enchants:  
      - ALL        
    events:
      interact:
        right:
          decrement_durability:
            amount: 1
          play_sound:
            flow:
              stop_if_last_fail: true
            name: block.ancient_debris.hit
            volume: 1
            pitch: 1
          play_effect:
            name: SMOKE
          damage_entity_in_sight:
            entity_groups:
              - HOSTILE
              - PLAYERS
            damage: 4
            distance: 10
```
