### ISSUE TITLE
Problem with hosting priorities

### ISSUE THREAD

**Issue by softy-oniguru** [PluginBugs/Issues-ItemsAdder#3181]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

oniguru_official

### What happened?

I can't make self-host due to the fact that my machine is installed on a closed IP, which is difficult to open, for this I use a third-party program. How can this be implemented? (priorities only self-host)

### Steps to reproduce the issue

```
resource-pack:
  hosting:
    no-host:
      enabled: false
    self-host:
      enabled: true # highest priority?
      server-ip: 192.168.0.1 # > opened with publichostname
      pack-port: 80
    external-host:
      enabled: true
      url: 'http://publichostname-192.168.0.1-80/generated.zip' # don't work
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
```

### Server version

Current: git-Purpur-2092 (MC: 1.20.2)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs version 1.0.30
