### ISSUE TITLE
Placeholder support in item lore items

### ISSUE THREAD

**Issue by leogianfagna** [PluginBugs/Issues-ItemsAdder#3184]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Placeholders are not supported in item lores on config. Like this example:
```yml
  elixir_alquimia:
    enable: true
    display_name: 'Elixir de alquimia'
    lore:
    - '&fEsse elixir está montado e serve'
    - '&fpara adquirir a experiência da'
    - '&f%#FF2323%habilidade alquimia&f que ele guarda.'
    - ''
    - '%#349133%Beba para receber experiência.'
    - '%localtime_time%'
    resource:
      material: GOLDEN_APPLE
      generate: true
      textures:
      - item/elixires/elixir1
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142264317/92990a01-de33-4ba2-800c-909f18ef8d56)

It would be nice if the placeholder can be parsed and display on item lore, like we can do with other plugins like Essentials:
```yml
  kit:
    delay: 604800
    items:
    - diamond_helmet 1 name:&#F8FF05Capacete_VIP_Ouro lore:&fਦ_&e{USERNAME} protection_environmental:3
      durability:2
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/142264317/0490058b-0a34-49a2-98da-0e7acff11441)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

The placeholder could be parsed based on the player will received it.
