### ISSUE TITLE
[Suggestion] 1.16 hex colors

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#320]
Add support for 1.16 hex colors to each of my plugins

**Comment by LoneDev6** [comment]
Will be added in the next update, example:
```yml
  iron_arrow:
    display_name: "%#FE5A00%Iron Arrow"
    permission: arrows.iron_arrow
    resource:
      material: ARROW
      generate: true
      textures:
      - "minecraft:item/spectral_arrow.png"
    events:
      item_hit_entity:
          damage_entity:
            damage: 1
```
