### ISSUE TITLE
Scoreboard numbers are not removed on 1.20.4

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3205]
https://forum.devs.beer/d/2046-socreboard-numbers-are-not-removed-from-1203

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7c988be0-f13e-422e-ab22-093bb1ee00a6)

**Comment by LoneDev6** [comment]
Added a new option for 1.20.4 which doesn't require to run `/iazip` to be disabled/enabled.

```yml
effects:
  hide-scoreboard-numbers: true # No /iazip and supports 1.20.3+ clients
  hide-scoreboard-numbers-old-clients: true # Requires /iazip to apply and supports 1.20.2 and lower clients
```

You can enable both options to support all clients.
