### ISSUE TITLE
Shapeless recipe makes you lose items

### ISSUE THREAD

**Issue by PainOchoco** [PluginBugs/Issues-ItemsAdder#3212]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Some players were trying to mass craft a custom ItemsAdder recipe and they lost a lot of items.

### Steps to reproduce the issue

1. Add any shapeless recipe to the config (working example below)
2. Go to a crafting table
3. Take ~10 stacks of the ingredients
4. Shift click the custom recipe in the recipe book
5. Notice you lost a lot of items

Video below

### Server version

Current: git-Purpur-1982 (MC: 1.19.4)

### ItemsAdder Version

3.6.2-beta-r4 

### ProtocolLib Version

5.1.0-SNAPSHOT-649

### LoneLibs Version

1.0.27

### Other files, you can drag and drop them here to upload. (optional)

```yml
info:
  namespace: something
recipes:
  crafting_table:
    black_dye:
      permission: something.perm
      enabled: true
      shapeless: true
      ingredients:
        i: yellow_dye
        r: blue_dye
        c: red_dye
      result:
        item: black_dye
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://jmp.sh/F84IBZDp
