### ISSUE TITLE
use emote at the same time you sneak, when emote end, it will count the player as if they are sneaking. 

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#3249]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I use sneak + left click as an skill for my server. and the way I did it was making a mythicmobs skill and iaemote.
but the problem is when player use the skill, or in other word, using any emote at the same time they sneak (short sneak)
, you will still be counted as sneaking until you press shift again (even though you physically didn't anymore)

and this is a problem because I have many functions to use when player is sneaking, like example: sneak to pick ground item etc.
and I have tested (sneak emote at the same time) and then the player are now able to collect ground item (the system counted them as if they are still sneaking) even though they are physically walking (which I don't want player to run and get items easily)

ps. I'm already sure that this problem is not caused by other plugin issue (such as skript and mythicmobs, they are just for test)
beside I tried adding  delay 20 tick delay and there's no error. (emote are being displayed and I don't need to press 2nd shift to stop the sneak)

### Steps to reproduce the issue

1. make emote with cancel conditions sneak: false
2. use this skript to check when player is sneaking
```
on join:
    while player is online:
        if player is sneaking:
            broadcast "you are sneaking" 
        wait 20 tick
```
3. use this mythicmobs skills

```
Swing1:  
  Skills:
  - onSwing{osw=Sword-Shift-L;auraName=Sword-Shift-L;d=1000;i=1;charges=1} @Self
  
Sword-Shift-L:
  Conditions:
  - crouching true     
  Skills:
  - command{c="iaemote sword_shift_L <target.name>"} @Self       
```
4. join the server.
5. test the skill by using activating Swing1 skills, and then press shift(crouching) and left click(swing).
6. player will still being counted as if they are sneaking even though they are not

### Server version

git-Purpur-1985 (MC: 1.19.4)

### ItemsAdder Version

3.6.2d-beta-2

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.27

### Problematic items yml configuration file (optional)

this is emote config
```
  sword_shift_L:
    id: sword_shift_L
    cancel_conditions:
      sneak: false
      take_damage: false
      deal_damage: false
      in_air: false
    can_player_move: true 
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/90768288/0dc18af3-6e54-490e-a23a-7f7ccf59cb86
