### ISSUE TITLE
Displaying decimal digits for "attackDamage" and "attackSpeed"

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#3292]
### What happened?

If I have attackDamage and attackSpeed ​​with commas, if I look at the items in the AI ​​menu or the items directly in Minecraft it does not display anything after the comma.
Example :
If I put
attackDamage: 4.5 attackSpeed: 0.9
This displays:
attackDamage: 4 attackSpeed: 0
I don't know how much is actually taken into account, I haven't done this kind of test, I'm just looking at the information display. I think this concerns all items, I have this on axes, swords, pickaxes so probably all of them. I was able to check with the configuration of the ruby ​​ax from the iasurvival pack and otherwise a terraria pack etc.

### Steps to reproduce the issue

Simply modify the settings on an item such as a sword, ax or other to do /iazip and you only get numbers without commas displayed.
```yml
info:
  namespace: terraria
items:
  tin_sword:
    display_name: display-name-tin_sword
    resource:
      material: STONE_SWORD
      generate: true
      textures:
      - item/tin_sword
    durability:
      max_custom_durability: 150
    attribute_modifiers:
      mainhand:
        attackDamage: 4.5
        attackSpeed: 1.6
```

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80985545/a2410c30-9f12-4206-b8a5-7408d08a73b5)

### Server version

git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-5

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.42

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13840110/latest.log)

### Other files, you can drag and drop them here to upload. (optional)

[swords.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/13840173/swords.txt)

### Screenshots/Videos (you can drag and drop files or paste links)

![Sans titre 2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80985545/0849405c-7d33-4880-97e8-da2d885430df)
