### ISSUE TITLE
Text effects module still running even if `effects.text-effects.enabled: false` 

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3297]
In the next update chat, sign and book `text-effects` settings `true` status will be ignored if text effects are disabled.

Example: 
In this case `text-effects.enabled` is set to `false` so all other options will be disabled too.
```yml
  text-effects:
    enabled: false
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```
