### ISSUE TITLE
[Suggestion] Prevent multiple types of seeds from appearing at the same time

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#330]
> [<img alt="yebanme" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/yebanme) **Authored by [yebanme](https://github.com/yebanme)**
_<time datetime="2020-07-08T02:38:09Z" title="Wednesday, July 8th 2020, 4:38:09 am +02:00">Jul 8, 2020</time>_
_Closed <time datetime="2020-10-02T15:49:13Z" title="Friday, October 2nd 2020, 5:49:13 pm +02:00">Oct 2, 2020</time>_
---

**Is your feature request related to a problem? Please describe.**
When the grass is broken, there is a certain probability of dropping seeds, but sometimes multiple seeds appear at the same time,It doesn't seem logical

**Describe the solution you'd like**
There is only one type of seed when grass is destroyed
In the following example, suppose  appears tomato_seeds, then garlic_seeds and rice_seeds no longer allows computation

**Additional context**
```
grass:
      type: GRASS
      items:
        tomato_seeds:
          item: itemsadder:tomato_seeds
          min_amount: 1
          max_amount: 2
          chance: 5
        garlic_seeds:
          item: itemsadder:garlic_seeds
          min_amount: 1
          max_amount: 2
          chance: 5
        rice_seeds:
          item: itemsadder:rice_seeds
          min_amount: 1
          max_amount: 2
          chance: 10
```
