### ISSUE TITLE
The furniture with colored textures can be dyed into other colors by players using a workbench.

### ISSUE THREAD

**Issue by 89009332** [PluginBugs/Issues-ItemsAdder#3310]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

FuMeng#4071

### Describe the solution you'd like

The furniture with colored textures can be dyed into other colors by players using a workbench. I hope to have a permission to control whether players can dye the furniture.

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

Controlling whether players can dye furniture would suffice.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1318#issuecomment-976727227

> I recently introduced a fix which prevents custom player armors items to be recolored to avoid people from recoloring custom armors to change their appearance and scam people by selling fake armors.
I will now add a fix to allow LEATHER_HORSE_ARMOR to be colored 👍🏻 this wasn't intended

This basically was introduced because some user requested the `LEATHER_HORSE_ARMOR` items to be forcefully allowed to be colored.
I could introduce a new property for the `LEATHER_HORSE_ARMOR` custom items to avoid some of them from being colored, correct?
Because you might want your players to color some of the furnitures.

**Comment by 89009332** [comment]
Yes, a custom option is needed to control it.

**Comment by LoneDev6** [comment]
New property:
```yml
info:
  namespace: test
items:
  leather_horse_armor:
    display_name: leather horse armor test
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: LEATHER_HORSE_ARMOR
    specific_properties:
      leather_horse_armor:
        can_be_recolored_in_crafting_table: true
```
