### ISSUE TITLE
/iazip does not reload the pack correctly and the colors do not work in the item names.

### ISSUE THREAD

**Issue by Slowedgg** [PluginBugs/Issues-ItemsAdder#3316]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Dear LoneDev, the /iazip function is not working as it should or as it was working in the previous updates, when I make changes in my items configuration for example in the names, /iazip is not loading the changes. After several uses of the command it usually loads the changes made. The following is that the hex colors are not working in the item names but they are working in the lore.

### Steps to reproduce the issue

 /iareload
 /iazip

After several attempts of these commands the changes are finally loaded.

### Server version

[15:10:05 INFO]: Checking version, please wait...
[15:10:06 INFO]: This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
You are running the latest version

### ItemsAdder Version

[15:10:27 INFO]: ItemsAdder version 3.6.3-beta-7
[15:10:27 INFO]: Customized Minecraft without client mods!
[15:10:27 INFO]: Website: devs.beer
[15:10:27 INFO]: Author: LoneDev

### ProtocolLib Version

[15:10:42 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[15:10:42 INFO]: Provides read/write access to the Minecraft protocol.
[15:10:42 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:10:57 INFO]: LoneLibs version 1.0.45
[15:10:57 INFO]: Collection of libs used by my plugins
[15:10:57 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
soul_block:
    display_name: '&#5AEA1CSoul Block'
    lore:
    - ':tradable_tag: :uncommon_tag:'
    - ""
    - ' &f◇ &#9EFB75Use this block to get magic tools &f◇ '
    resource:
      material: PAPER
      generate: true
      textures:
      - blocks/soul_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        no_explosion: false
        light_level: 12
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/75852372/0df7240f-ede5-4cdd-b679-6576fbadd2cc)

**Comment by LoneDev6** [comment]
> the /iazip function is not working as it should or as it was working in the previous updates
this is strange, can't reproduce that

> The following is that the hex colors are not working
You should not report multiple issues on the same issue page.
Anyway you can use minimessage new format to format your texts:
<https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+>
Please let me know, thanks

```yml
soul_block:
    display_name: '<color:#5aea1c>Soul Block'
    lore:
    - ':tradable_tag: :uncommon_tag:'
    - ""
    - ' <white>◇</white> <color:#9EFB75>Use this block to get magic tools</color> <white>◇</white> '
    resource:
      material: PAPER
      generate: true
      textures:
      - blocks/soul_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        no_explosion: false
        light_level: 12
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7d4fd7c5-299f-4912-8e12-da783c64b786)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/dd2b678b-7566-4e76-a9c6-5f6085dcd65f)
