### ISSUE TITLE
Mobs spawned from spawners do not drop loots

### ISSUE THREAD

**Issue by KermX** [PluginBugs/Issues-ItemsAdder#3332]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kerm.mc

### What happened?

Mobs spawned from spawners do not drop custom loots. 

### Steps to reproduce the issue

1. create a loots.yml file that adds an item to any mob loot table
2. spawn the mob using a mob spawner
3. kill the mob

### Server version

This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

### Problematic items yml configuration file (optional)

```shell
loots:
  mobs:
    pig:
      type: PIG
      items:
        item_1:
          item: mob_loots_expansion:pig_leather
          min_amount: 1
          max_amount: 2
          chance: 2
```

**Comment by LoneDev6** [comment]
`ignore_spawner` is by default set to true to avoid excessive farming.
Set it to false.

```yml
loots:
  mobs:
    pig:
      type: PIG
      ignore_spawner: false
      items:
        item_1:
          item: mob_loots_expansion:pig_leather
          min_amount: 1
          max_amount: 2
          chance: 2
```
