### ISSUE TITLE
put percentage on block or furniture "events" (EJ:give)

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3352]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Ritsu#9014

### Describe the solution you'd like

For example, it allows you to give the "item" from time to time.
or run the command every so often for the block or furniture daily with a percentage and quantities like a block when mining it

### Is your feature request related to a problem?

to create more variety and objects that can have a useful life without breaking the survival game mode

### Describe alternatives you've considered

For example, it allows you to give the "item" from time to time.
or run the command every so often for the block or furniture daily with a percentage and quantities like a block when mining it

### Additional context

to create more variety and objects that can have a useful life without breaking the survival game mode

**Comment by RitsuElAnti** [comment]
Sorry for my bad writing, but my request was to be able to add percentages in the give event for example (chance and quantities) as in the mining drop of a block, now I change the word and specify well

**Comment by LoneDev6** [comment]
So basically you want a furniture that can be interacted daily to get prizes with random quantity and chance?
I think this is a little but out of the scope of the plugin.

By the way furniture and blocks can already have delay in the interaction event.

This should work for your idea.
```yml
    behaviours:
      furniture:
        enabled: true
    events_settings:
      cooldown:
        bossbar:
          color: BLUE
        ticks: 1728000 # 24 hours
    events:
      placed_furniture:
        interact:
          drop_item:
            item: DIAMOND
            min_amount: 1
            max_amount: 5
            chance: 30
```
