### ISSUE TITLE
event multiple break patterns

### ISSUE THREAD

**Issue by czychuuu** [PluginBugs/Issues-ItemsAdder#3379]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

czychuuu

### Describe the solution you'd like

add patterns in which multiple break works
for example
```
  pickaxe:
    enabled: true
    resource:
      material: DIAMOND_PICKAXE
      generate: true
      textures:
        - item/pickaxe
    events:
      block_break:
        multiple_break:
          pattern: {
             X  X  X
             X  B*  X
             X  B  X
          }
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: false
```
X means any block
B block to break
and * center/mined block

depth would be nice if possible

### Is your feature request related to a problem?

none

### Describe alternatives you've considered

none
