### ISSUE TITLE
Optionally add all worlds to the World Populators + Blacklist certain worlds

### ISSUE THREAD

**Issue by ZERO511-55** [PluginBugs/Issues-ItemsAdder#3433]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

zero511dash55

### Describe the solution you'd like

I'd really like to see an ItemsAdder update that supports whitelisting all present and future worlds having world populators and blacklisting certain worlds from world populators. Obviously, at first glance this can look pretty conflicting but I think "blacklisted-worlds" would have the highest priority to override whitelisted worlds and of course this should be an optional feature/way to configurate because not everyone will want to use this.

Example of how it could be done via config.

```
  custom_block:
    block: myitems:custom_block
    whitelisted-worlds:
    - all (or just *)
    blacklisted-worlds:
    - world_nether
    - world_the_end
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chunk_chance: 70.0
    max_height: 45
    min_height: 25
    vein_blocks: 6
    chunk_veins: 1
```

### Is your feature request related to a problem?

It's not a exactly a problem, I'm just working on a PlayerWorlds plugin for my network and it's impossible to list every world under the "worlds" list when the worlds are player-generated.

### Describe alternatives you've considered

I've considered implementing the ItemsAdder API into my plugin but I honestly cannot manage to wrap my head around using the API. I think I'm just not that experienced at using other APIs. My plugin is complete, I just don't know how to implement the ItemsAdder API to get what I'm requesting this feature for.

### Additional context

N/A
