### ISSUE TITLE
`/iacleancache items` does not remove item with old material when changed material

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3446]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

epicplayera10

### What happened?

When I create some item in itemsadder, I run `/iazip` and then I change the material of that item to something different and I run `/iazip` again, then when I run `/iacleancache items` then it wouldn't delete from cache the item that uses old material.

### Steps to reproduce the issue

1. Create test item like this:
```yaml
info:
  namespace: test
items:
  test_sword:
    enabled: true
    display_name: Test Sword
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
        - "test_sword.png"
```
2. Run `/iazip`
3. Change the material of that item to for example `STONE_SWORD`
4. Run `/iazip`
5. Run `/iacleancache items`
6. See that there are two the same items with different material inside `items_ids_cache.yml`

### Server version

This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45
