### ISSUE TITLE
Action permission doesnt work in furnitures

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#3531]
### What happened?

When i added a action permission it is not required to interact with furnitures.
```yml
  forge_station:
    display_name: "Magma Eritici"
    permission: forgestation
    lore:
      - "&7Bu masa ile materyaller karıştırılır."
    resource:
      material: FEATHER
      generate: false
      model_path: crafting_stations/forge_station
    behaviours:
      furniture:
        entity: item_frame
        gravity: true
        fixed_rotation: false
        small: false
        light_level: 7
        solid: true
        opposite_direction: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
    events:
      placed_furniture:
        interact:
          execute_commands:
            cmd1:
              permission: table.magmaeritici
              command: "mi stations open magmaeritici {player}"
              as_console: true
```
### Steps to reproduce the issue

add a furniture
add event.placedfurniture.executecommands
then permission to the cmd like this
```yml
    events:
      placed_furniture:
        interact:
          execute_commands:
            cmd1:
              permission: table.magmaeritici
              command: "mi stations open magmaeritici {player}"
              as_console: true
```

the permission is not required

### Server version

Current: git-Purpur-2137 (MC: 1.20.4)*
Previous: git-Pufferfish-47 (MC: 1.20.4)
* You are 28 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment]
This is misconfigured.
This should be the correct way, setting permission in the `execute_commands` attribute not in the command.
I will fix the itemsadder vscode extension to reflect that logic, thanks for the report.

```yml
    events:
      placed_furniture:
        interact:
          execute_commands:
            permission: table.magmaeritici
            cmd1:
              command: tell {player} bro
              as_console: true
```
