### ISSUE TITLE
Make `model_path` accept other namespaces

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3630]
Currently the plugin returns an error when the item is in a namespace different from the one provided in the model path attribute.
Example:
`[13:34:37 ERROR]: [ItemsAdder] Model file 'modern_test/models/iaalchemy:item/energy_converter.json' not found in any pack for item 'modern_test:test_furniture'. File: /contents/modern_test/config.yml`

```yml
info:
  namespace: modern_test
items:
  test_furniture:
    display_name: "Test Furniture That Uses Item Display"
    resource:
      material: PAPER
      generate: false
      model_path: iaalchemy:item/energy_converter
```
