### ISSUE TITLE
Flow and Execute Commands Action Compatibility

### ISSUE THREAD

**Issue by SSubnoir** [PluginBugs/Issues-ItemsAdder#3641]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ssubnoir

### Describe the solution you'd like

I wish to be able to use flow customization on execute command actions (specifically on each command separately), and I wish to be able to detect when a specific execute command action "fails".

### Is your feature request related to a problem?

In regular command block logic, when a command is unable to run due to it's conditions not being satisfied, it returns the action as a failure. An example of this would be "/execute if score @p thescore matches 0", where if the closest player does have a score of 0 for "thescore", the command is treated as a success, and if not, is treated as a failure.

However, when this is attempted in an execute commands action, the plugin does not recognize that the event failed, and using a "skip_if_fail" flow customization to check the event will never skip any event, regardless if the command fails. While it's not the end of the world, this is highly inconvenient.

One other small detail is that flow customizations cannot be used on specific execute command actions, regardless of the effects they would have.

### Describe alternatives you've considered

I have found a weird workaround to this issue, where by having an execute command action give the player "luck" when its conditions are satisfied, and then having a clear effect action attempt to remove said affect immediately afterwards, I can get a single fail or success detection on the clear effect action to then determine if the rest of my actions will run or not. While it works, it's certainly not very intuitive.

### Additional context

If this were to be implemented, it would significantly increase the capability of creators to add functionalities to their items.
It would also make me blush and be happy or something idk
Have a nice evening

**Comment by LoneDev6** [comment]
> when a command is unable to run due to it's conditions not being satisfied, it returns the action as a failure

Can you please provide an item configuration on how your logic would look like and how you would expect it to work?

**Comment by SSubnoir** [comment]
[example.json](https://github.com/user-attachments/files/15773812/example.json)

^ Only a .json file because I couldn't upload a .yml file

In this example file, the code would run 2 execute commands actions when the player holding the item right clicks
The first of these actions checks if the player's score for "example_score" is 0, and depending on if it is or not, it should return either a success or a failure
The second action will run after 100 ticks or 5 seconds pass, and will teleport the player 20 blocks into the air
Due to the addition of the flow segment to the "effect_comand" action, it should only teleport the player if the previous "cause_comand" action was a success, being skipped in the event that it failed

I hope this was useful.

**Comment by LoneDev6** [comment]
The next update supports any vanilla command success/fail status.
I am writing this info in the wiki, will be updated in the next hours: https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/events/actions#flow-customization

--- 
## Notes:

The ia-vscode extension has a bug where the `flow` attribute is misaligned in the `execute_commands` section.
I will post an update.

In the meantime this is the edited version of the item you sent:

```yml
info:
  namespace: test
items:
  test_flow:
    enabled: true
    display_name: test_flow
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: DIAMOND
    events:
      interact:
        right:
          execute_commands:
            cause_command:
              command: 'execute if score {player} example_score matches 0'
              as_console: true
              delay: 0
          execute_commands_2:
            effect_command:
              command: 'tp {player} ~ ~2 ~'
              as_console: true
            flow:
              skip_if_fail: execute_commands
```
