### ISSUE TITLE
1.20.6 - Add legacy NBT compatibility in item configuration

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3654]
```yml
info:
  namespace: modern_test
items:
  nbt_test_legacy:
    enabled: true
    display_name: nbt_test_legacy
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: PAPER
    nbt: "{RepairCost:1,display:{Name:\"This is using the legacy simple NBT notation\"}}"
  nbt_test_new:
    enabled: true
    display_name: nbt_test_new
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: PAPER
    nbt: "{components:{\"minecraft:custom_name\":'\"This is using the new NBT notation\"',\"minecraft:repair_cost\":1}}"
```
