### ISSUE TITLE
Permission break only blocks can be broken by anyone

### ISSUE THREAD

**Issue by EnderQuinn** [PluginBugs/Issues-ItemsAdder#3804]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

umezawashino

### What happened?

I'm using AuraSkills in my server. I wanted to make each profession more rewarding than normal, so I set up permission groups as rewards at certain level.
For example, someone who reached level 25 in Mining will get the "Mining" LuckPerms Group. 
Now, I wanted to enhance this further, give these groups a purpose. Then I thought I could achieve this by making blocks be breakable by only those who have certain permission. I asked around, and was redirected to the Wiki, which didn't really help me except give a basic idea of it.
After a while, I got helped by Verum, but we were still unable to solve the issue as even with the group negative break permission was still able to break the said block.

### Steps to reproduce the issue

Create a clean server

Upload required plugins

Start the server

Make a custom block with specified permission

Make a custom LP group and give that group negative permission (for example: 'ia.user.block.break.ruby_ore' and make it false)

Make your parent that LP group

You can still break the block :(

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Error (optional)

```shell
No error.
```

### Problematic items yml configuration file (optional)

```shell
blocktest:
    display_name: "Permission Block"
    permission: tutorial.blocktest
    resource:
      generate: true
      material: PAPER
      textures:
        - misc/i113_3.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: false
```

**Comment by Andre601** [comment]
I'm not sure, but I don't think ItemsAdder has permissions for block break permissions.

Given you use LP could you use its verbose command to check what permissions are checked. Tho, this could be a bit spammy in the end.

**Comment by EnderQuinn** [comment]
Checked with verbose, it doesn't check for the "ia.block.break.xxx". Either it doesn't recognize it, or it doesn't exist like you said. But if it doesn't exist, why is it listed on wiki?

**Comment by Andre601** [comment]
What wiki page are you talking about exactly?

**Comment by EnderQuinn** [comment]
https://itemsadder.devs.beer/plugin-usage/permissions
This one.
![image](https://github.com/user-attachments/assets/f5486955-ac15-4154-a55d-c089ce6d0415)

**Comment by Andre601** [comment]
The only thing I can currently find is the [permission](https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/permission) page displaying a `permission_suffix` option in its example, so perhaps this is what you need to set here, because the permissions page also mentions `permission_suffix` here.

Other than that can I myself not get a clear answer for you on what you need here, so we have to wait for LoneDev to provide an answer.

**Comment by EnderQuinn** [comment]
Yeah, I had done it with the permission_suffix before. But like I stated, I got in touch with the moderator "Verum", and we tried a few things. One of them was to change the permission_suffix back into the regular permission. Of course, it didn't work.

**Comment by Verdux** [comment]
Verum here, yeah I spent a while with this customer trying various things. There just appears to be no active permission check when a player breaks a block, no matter how it's configured. Unsure if this is a broken feature or incorrect wiki listing.

**Comment by LoneDev6** [comment]
You have to specify your permission suffix in the block configuration.
By default all blocks are breakable.
There i no need to negate the permission, just set it to positive for the groups that are supposed to break the block and set the  `permission_suffix` properties as shown in this example:

```yml
info:
  namespace: iasurvival
items:
  ruby_ore:
    enabled: true
    display_name: display-name-ruby_ore
    permission: iasurvival.items.ruby_ore
    resource:
      material: PAPER
      generate: true
      textures:
        - block/ores/ruby_ore
    specific_properties:
      block:
        permission_suffix:
          break: iasurvival.ruby_ore
          place: iasurvival.ruby_ore
        hardness: 4
        placed_model:
          type: REAL_NOTE
          break_particles_material: REDSTONE_ORE
        cancel_drop: true
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
          - _hammer
```
