### ISSUE TITLE
Turn glowing items on and off

### ISSUE THREAD

**Issue by Leahcimkrob** [PluginBugs/Issues-ItemsAdder#3829]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Bloody_Mind

### Describe the solution you'd like

Please provide a way to turn off glowing items, such as a colored redstone lamp that can switch between two block states.

### Is your feature request related to a problem?

my colored redstone blocks can only glow, but you can't turn them off

### Describe alternatives you've considered

There is no other way to achieve this

**Comment by LoneDev6** [comment]
This already can be done

https://github.com/user-attachments/assets/e77e4f7f-7451-4d6d-b88e-b6c4b44f55a4

```yml
info:
  namespace: test
items:
  test_change_state_block_interact:
    name: Test Change State Block Interact
    resource:
      generate: false
      model_path: minecraft:block/diamond_block
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: false
    events:
      placed_block:
        interact:
          replace_block:
            from: test_change_state_block_interact
            to: test_change_state_block_interact_on
            decrement_durability: 0
  test_change_state_block_interact_on:
    name: Test Change State Block Interact ON
    resource:
      generate: false
      model_path: minecraft:block/emerald_block
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: false
        light_level: 15
    events:
      placed_block:
        interact:
          replace_block:
            from: test_change_state_block_interact_on
            to: test_change_state_block_interact
            decrement_durability: 0
```
