### ISSUE TITLE
Custom NBT tags remove default itemsadder NBT Tags

### ISSUE THREAD

**Issue by Emsa001** [PluginBugs/Issues-ItemsAdder#3890]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Emsa001

### What happened?

it doesn't generate any logs, just when I set nbt tag it removes all default nbt tags from itemsadder

```yml
info:
  namespace: technology
items:
  phone:
    display_name: "Phone"
    permission: itemsadder.phones
    nbt: "{level:1}"
    resource:
      material: FLINT
      generate: false
      model_path: phones/phonesobjects/phone
```

![image](https://github.com/user-attachments/assets/c937c9cb-c9c2-45cf-85ba-28c358a5cae3)

### Steps to reproduce the issue

1. Set the custom NBT tag
2. Default Itemsadder NBT tags are gone 🤯

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.56

### Error (optional)

```shell
no error
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: technology
items:
  phone:
    display_name: "Phone"
    permission: itemsadder.phones
    nbt: "{level:1}"
    resource:
      material: FLINT
      generate: false
      model_path: phones/phonesobjects/phone
```
