### ISSUE TITLE
Attributes doesn't work

### ISSUE THREAD

**Issue by xTribalist** [PluginBugs/Issues-ItemsAdder#3895]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have a custom weapon/tools with the following attribute modifiers
    attribute_modifiers:
      mainhand:
        attackDamage: 15
        attackSpeed: 1.1
        
 However, the damage to an entity (sheep) is just 6, the diamond sword is even better.

### Steps to reproduce the issue

Just use the same modifiers I did and it should be  able to reproduce

### Server version

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

https://mclo.gs/Luk30CM

### Error (optional)

```shell
no error when hitting mobs using the custom weapon/tool
```

### Screenshots/Videos (you can drag and drop files or paste links)

none

**Comment by LoneDev6** [comment]
Works fine for me.
```yml
info:
  namespace: test
items:
  test_attributemodifiers:
    enabled: true
    display_name: test_attributemodifiers
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: minecraft:item/emerald
    attribute_modifiers:
      mainhand:
        attackDamage: 50
      
```

https://github.com/user-attachments/assets/43290b06-6d79-4671-a449-b7292b8d1311
