### ISSUE TITLE
1.20.6 - use native food properties

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3902]
New itemstack attribute which allows any item to behave as food, specifies the nutrition and saturation amount, effects and some other interesting flags.
This allows getting rid of all the custom food logic code from ItemsAdder.

New attribute: 
```yml
food:
  nutrition: 1
  saturation: 1
  can_always_eat: false
  eat_seconds: 2
  effects:
    effect_1:
      potion: SPEED
      duration: 20
      amplifier: 1
      ambient: true
      particles: true
      icon: true
      probability: 1
    effect_2:
      potion: INSTANT_HEALTH
      duration: 20
      amplifier: 1
      ambient: true
      particles: true
      icon: true
      probability: 1
```
