### ISSUE TITLE
The furniture placement direction is reversed after converting to display item.

### ISSUE THREAD

**Issue by WMGameLive** [PluginBugs/Issues-ItemsAdder#3927]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

The furniture placement direction is reversed after converting to display item.

### Steps to reproduce the issue

1. Make an item frame furniture that faces the player when placed.
2. Set auto_convert_to_item_display to true, then reload the config or restart the server.
3. Place the furniture again.
4. You can now notice that the furniture's direction is reversed compared to the original furniture.

### Server version

> version
[01:34:54 INFO]: Checking version, please wait...
[01:34:54 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

> version ItemsAdder
[01:35:26 INFO]: ItemsAdder version 4.0.2-alpha-test-7
[01:35:26 INFO]: Customized Minecraft without client mods!
[01:35:26 INFO]: Website: devs.beer
[01:35:26 INFO]: Author: LoneDev

### ProtocolLib Version

> version ProtocolLib
[01:35:55 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[01:35:55 INFO]: Provides read/write access to the Minecraft protocol.
[01:35:55 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version LoneLibs
[01:36:11 INFO]: LoneLibs version 1.0.57
[01:36:11 INFO]: Collection of libs used by my plugins
[01:36:11 INFO]: Authors: LoneDev and others

### Full Server Log

no errors

### Error (optional)

```shell
no errors
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: venderoe
items:
  chair:
    display_name: Chair
    resource:
      material: COAL
      generate: false
      model_path: furniture/007/chair
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: -0.0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.6
        opposite_direction: true
        sit_all_solid_blocks: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![furniture](https://github.com/user-attachments/assets/6e696f5a-803c-4b16-8217-28589f86cbcc)
