### ISSUE TITLE
Blocks can't be broke by using axe

### ISSUE THREAD

**Issue by Steve29794** [PluginBugs/Issues-ItemsAdder#3936]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

You can't break a custom block if you use the axe

### Steps to reproduce the issue

1. Create a block and set break_tools_whitelist to contains any axes
2. Place the block
3. Break it by using axe

### Server version

This server is running Leaf version git-Leaf-"83c2468" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 83c2468 on ver/1.20.4)
* You are running the latest version
Previous version: git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/a9DAy6O

### Error (optional)

```shell
None
```

### Problematic items yml configuration file (optional)

```yaml
wood_5x:
    display_name: display-name-wood_5x
    resource:
      generate: true
      material: PAPER
      textures:
        - block/wood_5x.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
          - DIAMOND_AXE
          - NETHERITE_AXE
          - IRON_AXE
          - STONE_AXE
        hardness: 10
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://1drv.ms/v/c/45e82de034226652/EcZAFh1_neVEvsoT5oUXGfoBZfd6_CMlPHT8Vp9A348pPQ?e=NKRQJz
