### ISSUE TITLE
Old furnace bug is again in game!

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#3937]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

PSYCHEER

### What happened?

![image](https://github.com/user-attachments/assets/fafa035d-964c-474a-ab20-a039cc5c1e0a)
![image](https://github.com/user-attachments/assets/39fdc976-0641-4964-9d05-b1f737c338d9)

### Steps to reproduce the issue

1. Put item into furnace
2. Look what's wrong
3. Be nice in warm and laugh a lot xD

### Server version

![image](https://github.com/user-attachments/assets/bf137606-b26a-441d-be14-9c33951a4630)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/5a819067-5cc3-425d-8ceb-52a31bc174b7)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/5a2a918e-0793-4a1f-9d2b-27d22d9001b7)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/656a2a67-d211-4384-a8a9-4721c6ef4d85)

### Full Server Log

https://mclo.gs/a1g8Hue

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: df
items:
  copper_sword:
    display_name: Copper Sword
    permission: copper_set
    resource:
      material: IRON_SWORD
      generate: true
      textures:
        - item/copper_sword
recipes:
  anvil_repair:
    copper_sword:
      permission: copper_set
      enabled: true
      ingredient: copper_ingot
      item: df:copper_sword
```
