### ISSUE TITLE
boot/helmet

### ISSUE THREAD

**Issue by TheCrazyKid1** [PluginBugs/Issues-ItemsAdder#3942]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

TheCrazyKid

### What happened?

the chestplate and pants are working with my honey texurepack but not the helmet and boots i have went to discord and the plugin helper said come here so here i am.

### Steps to reproduce the issue

after adding the /iazip command
look at the boot and helmet
nothing

### Server version

Current: git-Purpur-2169 (MC: 1.20.4)

### ItemsAdder Version

items adder version 3.6.4

### ProtocolLib Version

protocolib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

loneslib version 1.0.57

### Full Server Log

https://mclo.gs/tNTDQ8P

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: my_items
armors_rendering:
  honey_armor:
    use_color: false
    color: "#101010"
    layer_1: armor/honey_armor/layer_1
    layer_2: armor/honey_armor/layer_2
    #animation:
      #speed: 30
      #interpolation: true
items:
 honey_armor_helmet:
    display_name: honey_armor helmet
    permission: honey_armor
    resource:
      generate: true
      textures:
      - item/honey_armor/helmet
    durability:
      max_custom_durability: 275
    specific_properties:
      armor:
        slot: head
        custom_armor: honey_armor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 1
 honey_armor_chestplate:
    display_name: honey_armor chestplate
    permission: honey_armor
    resource:
      generate: true
      textures:
      - item/honey_armor/chestplate
    durability:
      max_custom_durability: 400
    specific_properties:
      armor:
        slot: chest
        custom_armor: honey_armor
    attribute_modifiers:
      chest:
        armor: 2
        armorToughness: 1
 honey_armor_leggings:
    display_name: honey_armor leggings
    permission: honey_armor
    resource:
      generate: true
      textures:
      - item/honey_armor/leggings
    durability:
      max_custom_durability: 375
    specific_properties:
      armor:
        slot: legs
        custom_armor: honey_armor
    attribute_modifiers:
      legs:
        armor: 4
        armorToughness: 1
 honey_armor_boots:
    display_name: honey_armor boots
    permission: honey_armor
    resource:
      generate: true
      textures:
      - item/honey_armor/boots
    durability:
      max_custom_durability: 325
    specific_properties:
      armor:
        slot: FEET
        custom_armor: honey_armor
    attribute_modifiers:
      feet:
        armor: 1
        armorToughness: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

aaaa
