### ISSUE TITLE
 java.lang.IllegalStateException: We don't have CustomModelData! Check hasCustomModelData first!

### ISSUE THREAD

**Issue by HaydoPotato1310** [PluginBugs/Issues-ItemsAdder#3947]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

HaydoPotato1310

### What happened?

When creating a custom set of armour, the custom colour works but when wearing the armour, it just looks like coloured armor, as if I was simply making a simple armour.

### Steps to reproduce the issue

Follow the steps on the wiki to create a custom armour set, and import the textures 
Save the .yml file, reload itemsadder, then run /iazip. 
Get the armour piece and wear it

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-alpha-test-8-pre-release-4

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/Nfgkx23

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: agritite_set
armors_rendering:
  agritite: 
    color: '#C98B26'
    layer_1: armor/agritite/agritite_layer_1
    layer_2: armor/agritite/agritite_layer_2
    use_color: false
items:
  agritite_helmet:
    display_name: '&6Agritite Helmet'
    permission: agritite_helmet
    resource:
      generate: true
    durability:
      max_custom_durability: 625
    specific_properties:
      armor:
        slot: head
        custom_armor: agritite
    attribute_modifiers:
      head:
        armor: 4
        armorToughness: 3
        attackDamage: 1
        movementSpeed: -0.004
        attackSpeed: 0.1
  agritite_chestplate:
    display_name: '&6Agritite Chestplate'
    permission: agritite_chestplate
    resource:
      generate: true
    durability:
      max_custom_durability: 800
    specific_properties:
      armor:
        slot: chest
        custom_armor: agritite
    attribute_modifiers:
      chest:
        armor: 9
        armorToughness: 3
        attackSpeed: 0.1
        attackDamage: 1
        movementSpeed: -0.004
  agritite_leggings:
    display_name: '&6Agritite Leggings'
    permission: agritite_leggings
    resource:
      generate: true 
    durability:
      max_custom_durability: 780
    specific_properties:
      armor:
        slot: legs
        custom_armor: agritite
    attribute_modifiers:
      legs:
        armor: 7
        armorToughness: 3
        attackSpeed: 0.1
        attackDamage: 1
        movementSpeed: -0.004
  agritite_boots:
    display_name: '&6Agritite Boots'
    permission: agritite_boots
    resource:
      generate: true
    durability:
      max_custom_durability: 700
    specific_properties:
      armor:
        slot: feet
        custom_armor: agritite
    attribute_modifiers:
      feet:
        armor: 4
        armorToughness: 3
        attackSpeed: 0.1
        attackDamage: 1
        movementSpeed: -0.004
```

### Other files, you can drag and drop them here to upload. (optional)

![agritite_layer_2](https://github.com/user-attachments/assets/c9cba02e-0471-46ac-b174-3b41de5f4586)
![agritite_layer_1](https://github.com/user-attachments/assets/ef3fdc85-6483-4d29-ab92-358b45b080a0)

### Screenshots/Videos (you can drag and drop files or paste links)

<img width="271" alt="Screenshot 2024-08-30 at 12 18 36" src="https://github.com/user-attachments/assets/60c24b00-f779-41d0-bfb2-5d69d0d96c6d">
