### ISSUE TITLE
Armor not rendered 

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#3949]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Rickylachow

### What happened?

I can't see the armor after updating to 1.21

### Steps to reproduce the issue

Create an armor -> equip the armor

### Server version

[12:01:55 INFO]: Checking version, please wait...
[12:01:55 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[12:01:48 INFO]: ItemsAdder version 4.0.2-alpha-test-7
[12:01:48 INFO]: Customized Minecraft without client mods!
[12:01:48 INFO]: Website: devs.beer
[12:01:48 INFO]: Author: LoneDev

### ProtocolLib Version

[12:02:29 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[12:02:29 INFO]: Provides read/write access to the Minecraft protocol.
[12:02:29 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:02:38 INFO]: LoneLibs version 1.0.57
[12:02:38 INFO]: Collection of libs used by my plugins
[12:02:38 INFO]: Authors: LoneDev and others

### Full Server Log

let me know if is needed 

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: item_custom
armors_rendering:
  giubotto_armor:
    color: "#d60000"
    layer_1: item/giubotto_layer_1
    layer_2: item/giubotto_layer_2
    use_color: false
items:
  giubotto_antiproiettile_chest:
    display_name: Chest giubotto
    permission: my_armor_chestplate
    durability:
      max_custom_durability: 602
    resource:
      generate: false
      model_path: item/giubotto_antiproiettile_chest
    specific_properties:
      armor:
        slot: chest
        custom_armor: giubotto_armor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
```
