### ISSUE TITLE
Prevent Auto-Generation of Shader Files with Emote Set to True

### ISSUE THREAD

**Issue by EyatMC** [PluginBugs/Issues-ItemsAdder#3961]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Eyat

### Describe the solution you'd like

.

### Is your feature request related to a problem?

Hello,
I discovered that enabling Emote to true causes a conflict with my existing core shader.
I tried merging the two vsh files into one and using it, but since Emote is set to true, running the iazip command replaces it with ItemsAdder's vsh file, causing the issue again.

### Describe alternatives you've considered

Therefore, the only way to resolve this issue is to ensure that the shader files are not automatically generated even if `emote` is set to true. Is this possible?

### Additional context

![image-7](https://github.com/user-attachments/assets/5acca016-b5c7-4098-bba2-21220c1ada6e)

**Comment by EyatMC** [comment]
Thank you for your response. 
A few people, including myself, are skilled enough to manually merge shaders. If you could add the relevant option, it would allow us to use both without any issues. Please consider adding this option.

**Comment by LoneDev6** [comment]
Added in the upcoming update
`extract_emotes_shaders: true`

```yml
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      delay_packets: false
      extract_emotes_shaders: true
  furniture:
    auto_convert_to_item_display: false
```
