### ISSUE TITLE
Unexpected result when merging

### ISSUE THREAD

**Issue by marcjoancr** [PluginBugs/Issues-ItemsAdder#3964]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

I don't know if Wiki doesn't cover everything but merging resourcepacks it's not working, I have this structure:
```
.
├── authentic_shadows
│   └── resourcepack
│       └── assets
│           └── minecraft
├── better_glass_panes
│   └── resourcepack
│       └── assets
│           ├── continuity
│           └── minecraft
├── better_lanterns
│   └── resourcepack
│       └── assets
│           ├── arcanelanterns
│           ├── minecraft
│           └── thinair
├── crops_3d
│   └── resourcepack
│       └── assets
│           └── minecraft
├── faithless_shader_fix
│   └── resourcepack
│       └── assets
│           ├── minecraft
│           ├── polytone
│           └── realms
├── fire_rekindled
│   └── resourcepack
│       └── assets
│           ├── charm
│           ├── create
│           ├── minecraft
│           └── supplementaries
├── _iainternal
│   ├── configs
│   │   ├── dictionaries
│   │   ├── huds
│   │   └── lang_overwrite
│   └── resourcepack
│       └── assets
│           └── _iainternal
├── loading_screen
│   └── resourcepack
│       └── assets
│           └── minecraft
├── more_particles
│   └── resourcepack
│       └── assets
│           └── minecraft
├── origins_reborn
│   └── resourcepack
│       └── assets
│           └── minecraft
├── osmium
│   ├── configs
│   └── resourcepack
│       └── assets
│           └── osmium
├── simple_grass_flowers
│   └── resourcepack
│       └── assets
│           └── minecraft
├── tutorial
│   ├── configs
│   └── resourcepack
│       └── assets
│           └── tutorial
├── unobtrusive_weather
│   └── resourcepack
│       └── assets
│           ├── minecraft
│           └── particlerain
└── vervada_enchanced_plants
    └── resourcepack
        └── assets
            └── minecraft
````

And with this order:
```
    contents-folders-priority:
    - vanilla
    - origins_reborn
    - faithless_shader_fix
    - _iainternal
    - vervada_enchanced_plants
    - crops_3d
    - better_lanterns
    - better_glass_panes
    - more_particles
    - authentic_shadows
    - unobstrusive_weather
    - simple_grass_flowers
    - tutorial
    - loading_screen
```

3D assets gets a little bit messy and the merging doesn't act as vanilla resourcepack merging.

I tried with vanilla minecraft merging with that specific order all these packs and doesn't look like ItemsAdder

### Steps to reproduce the issue

1. Download 2 resources that overlaps each other
2. Merge with priority, the one who has minor change should load after
3. Generate zip output

Now without Items adder make same process and the results are different.
[1.21.x Better Glass Panes.zip](https://github.com/user-attachments/files/16839520/1.21.x.Better.Glass.Panes.zip)
[Fire_Rekindled.zip](https://github.com/user-attachments/files/16839521/Fire_Rekindled.zip)
[Particles+V.1.3.1.zip](https://github.com/user-attachments/files/16839522/Particles%2BV.1.3.1.zip)
[Blockier Goat Horn v1.1 f9-34.zip](https://github.com/user-attachments/files/16839523/Blockier.Goat.Horn.v1.1.f9-34.zip)
[unobtrusive_weather.zip](https://github.com/user-attachments/files/16839524/unobtrusive_weather.zip)
[Authentic Shadows_1.21.zip](https://github.com/user-attachments/files/16839525/Authentic.Shadows_1.21.zip)
[Better+Lanterns+v1.2(mc-1.21).zip](https://github.com/user-attachments/files/16839526/Better%2BLanterns%2Bv1.2.mc-1.21.zip)
[Simple Grass Flowers v1.8.1.zip](https://github.com/user-attachments/files/16839527/Simple.Grass.Flowers.v1.8.1.zip)
[crops-3d.zip](https://github.com/user-attachments/files/16839528/crops-3d.zip)
[Vervada-s-enhanced-plants.zip](https://github.com/user-attachments/files/16839530/Vervada-s-enhanced-plants.zip)

### Server version

Running Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS; Amazon.com Inc. Corretto-21.0.4.7.1) on Linux 6.1.0-23-amd64 (amd64)
This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-alpha-test-7

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/S882Dlh

### Problematic items yml configuration file (optional)

```yaml
metrics: true
update-checker: true
resource-pack:
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  apply-during-chunk-load-phase: true
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: mc.mallorcanostra.cat
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    lock-player: true
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - origins_reborn
    - faithless_shader_fix
    - _iainternal
    - vervada_enchanced_plants
    - crops_3d
    - better_lanterns
    - better_glass_panes
    - more_particles
    - authentic_shadows
    - unobstrusive_weather
    - simple_grass_flowers
    - tutorial
    - loading_screen
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  custom:
    note: true
    mushroom: true
    chorus: true
    wire: true
    fire: true
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  hide-custom-durability-lore: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  enabled: true
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      delay_packets: false
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
debug:
  benchmark: false
  resourcepacks:
    log_player_install: true
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: true
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: true
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-09-02_18 03 14](https://github.com/user-attachments/assets/8181ee79-b28c-44c2-b22c-3dc72af3ebf6)

_No response_
