### ISSUE TITLE
Textures dont work, pls help

### ISSUE THREAD

**Issue by PythonNerd12** [PluginBugs/Issues-ItemsAdder#3973]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Philly622

### What happened?

no idea, i cant get textures to work if i did the ranks brake, i use betterranks i use gravel host if u need any more info lmk, my dev tried and he coulnt fix it.

### Steps to reproduce the issue

1. put the textutre  in the server
2. do /ia
3. and the texture doesjt load its just  a sword

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2095 (MC: 1.20.2)
* You are running the latest version

### ItemsAdder Version

[11:44:53 INFO]: ItemsAdder version 3.6.4-release-3
[11:44:53 INFO]: Customized Minecraft without client mods!
[11:44:53 INFO]: Website: devs.beer
[11:44:53 INFO]: Author: LoneDev

### ProtocolLib Version

: ProtocolLib version 5.2.0-SNAPSHOT-679
[12:04:53 INFO]: Provides read/write access to the Minecraft protocol.
[12:04:53 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:45:17 INFO]: LoneLibs version 1.0.55
[11:45:17 INFO]: Collection of libs used by my plugins
[11:45:17 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/bjGYjXA

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: andromedasword
items:
  andromeda_sword:
    permission: sword.andromeda_sword
    display_name: '&5&ka&5&lAndromeda Sword&5&ka'
    resource:
      material: NETHERITE_SWORD
      generate: true
      textures:
        - items/andromedasword.png
```
