### ISSUE TITLE
Custom Blocks doesnt update next to lava/water

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#3974]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

wassabi

### What happened?

I have a Skyblock server where I have generators that summon custom blocks but when it's mined next to a lava or water source, it doesnt update those liquid sources

### Steps to reproduce the issue

1. Place Lava
2. Place custom block next to it
3. Break block

### Server version

![image](https://github.com/user-attachments/assets/b2428bbb-bc06-472e-835b-ddd9be6dc380)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/37157f04-e9c5-493f-af26-93a29622abd2)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/fbda74ad-ee57-4929-b6be-537443ffac3f)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/5524265a-f73f-4d72-a145-19395bf70ecc)

### Full Server Log

https://mclo.gs/Rp3YCs1

### Problematic items yml configuration file (optional)

```yaml
items:
  mithril_ore_light:
    display_name: "Mithril Ore Light"
    resource:
      material: PAPER
      model_id: 76990
      generate: true
      textures:
        - "skyblock/mithrite/ores/mithril_ore_light.png"
    events:
      placed_block:
        break:
          drop_exp:
            chance: 100
            min_amount: 1
            max_amount: 3
    specific_properties:
      block:
        cancel_drop: true
        hardness: 1
        placed_model:
          type: REAL_NOTE
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
        break_tools_whitelist:
          - IRON_PICKAXE
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/d216db05-f6d8-4e1b-b56e-4cb6bfd4d37e
