### ISSUE TITLE
Durability with ViaVersion, dont work fine

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3988]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

i updated my server from 1.20.4 to 1.21.1 and armor attributes and durabilities dosnt work fine usign advancedenchantment 9.11.0

### Steps to reproduce the issue

updating server from 1.20.4

### Server version

pufferfish 1.21.1 build 15

### ItemsAdder Version

version 10 hotfix

### ProtocolLib Version

build 726

### LoneLibs Version

LoneLibs 1.0.58

### Full Server Log

i cant uplaod to mclo.gs

**Comment by Andre601** [comment]
> i cant uplaod to mclo.gs

If you can't upload to that site, use any other paste site then such as https://paste.helpch.at, https://pastes.dev or similar.

**Comment by SliderKP** [comment]
> > i cant uplaod to mclo.gs
> 
> If you can't upload to that site, use any other paste site then such as https://paste.helpch.at, https://pastes.dev or similar.

https://paste.helpch.at/iyisorixob.makefile

**Comment by SliderKP** [comment]
![image](https://github.com/user-attachments/assets/c287b890-af16-4789-a29b-944559110eb1)
im not using leak actually, just in this test server xD

**Comment by LoneDev6** [comment]
Provide a video of the issue and configurations of the items which have issues.

**Comment by SliderKP** [comment]
> Provide a video of the issue and configurations of the items which have issues.

in this image you can see the problem:
![image](https://github.com/user-attachments/assets/308adfa9-0ff8-4f25-b688-4c811ed04117)
"Durabilidad 26/55"
(durability 26/55) and when i stay in older version (1.20.4) the durability working are the upside ("Durabilidad 602/602")
this is the config:
```
  ecknighthelmet:
    display_name: Knight Helmet
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsbundle/ecdarkknighthelmet.png
    durability:
      max_custom_durability: 602
    specific_properties:
      armor:
        slot: head
        custom_armor: ecknightarmor
    attribute_modifiers:
      head:
        armor: 8
        armorToughness: 3
```

Thanks a lot for your answer, if u think this is not detailed i can make a video but, i think is innecesary, i still waiting for another answer.
