### ISSUE TITLE
You can no longer view recipes in-game

### ISSUE THREAD

**Issue by Technofied** [PluginBugs/Issues-ItemsAdder#3993]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

technofied

### What happened?

You can no longer see recipes for any items.

### Steps to reproduce the issue

1. Open /ia.
2. Click on a item **with a recipe**.
3. Observe the absence of a recipe. :(

**Works with any type of recipe.**

### Server version

[13:01:04 INFO]: Checking version, please wait...
[13:01:05 INFO]: This server is running Paper version 1.21.1-69-master@925c3b9 (2024-09-07T20:43:21Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[13:01:22 INFO]: ItemsAdder version 4.0.2-beta-release-10
[13:01:22 INFO]: Customized Minecraft without client mods!
[13:01:22 INFO]: Website: devs.beer
[13:01:22 INFO]: Author: LoneDev

### ProtocolLib Version

[13:01:32 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[13:01:32 INFO]: Provides read/write access to the Minecraft protocol.
[13:01:32 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[13:01:40 INFO]: LoneLibs version 1.0.58
[13:01:40 INFO]: Collection of libs used by my plugins
[13:01:40 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/J5sx3Zh

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/fc3085ac-7922-41ca-9df5-c93c1e6d0088)

**Comment by Andre601** [comment]
Please share the item file that has this item.
But usually, if this is shown does it mean there is no recipe defined.

**Comment by Technofied** [comment]
> Please share the item file that has this item. But usually, if this is shown does it mean there is no recipe defined.

Here is an example recipe and item which worked on the version(s) prior.
```yaml
info:
  namespace: jobs
recipes:
  crafting_table:
    superior_aa_grade_amethyst_ring:
      permission: jeweller.recipes
      enabled: true
      pattern:
      - ABA
      - CDC
      - CCC
      ingredients:
        A: NETHERITE_INGOT
        B: TINTED_GLASS
        C: AMETHYST_CLUSTER
        D: AMETHYST_BLOCK
      result:
        item: jobs:superior_aa_grade_amethyst_ring
        amount: 1
items:
  superior_aa_grade_amethyst_ring: 
    display_name: "<color:#9B5FC0>Superior AA-Grade Amethyst Ring"
    lore:
    - "&7&oA relic of ancient mountains, this amethyst ring radiates wisdom and serenity."
    permission: jeweller.recipes
    resource:
      material: AMETHYST_SHARD
      generate: true
      textures:
      - item/superior_aa_grade_amethyst_ring
```
