### ISSUE TITLE
Resourcepack failed to load (With specific settings)

### ISSUE THREAD

**Issue by arturek1666** [PluginBugs/Issues-ItemsAdder#3995]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

artuditu

### What happened?

When changed specific settings to fix the heads having strange texture, with is:
```
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: false - Changed that from true to false. 
    expert_users:
      delay_packets: false
      extract_emotes_shaders: false - Changed that from true to false as it failed to load but still not loading
```
      
This would normally fix head issues, as I have 2 servers one with is 1.20.4 and chainging the emotes: false is working fine, and if I do same with 1.21.1 It breaks loading of resourcepack for all players. 

### Steps to reproduce the issue

1. Go to plugins folder 
2. Open ItemsAdder folder
3. Open config.yml
4. Change the settings: 
    emotes: true to emotes: false
5. Restart the server
6. Do iazip and then iareload to load newest resourcepack
7. Join the server and try to load server resourcepack - Please note downloading manually did not allow it load it either. 

### Server version

[21:06:03 INFO]: [37mCurrent Purpur Version: 1.21.1-2303-88352c3 (MC: 1.21.1)*
* You are running the latest version
[37mPrevious: 1.21.1-2298-a61db94 (MC: 1.21.1)

### ItemsAdder Version

[21:06:29 INFO]: ItemsAdder version 4.0.2-beta-release-10
>
[21:06:29 INFO]: Customized Minecraft without client mods!
>
[21:06:29 INFO]: Website: devs.beer
>
[21:06:29 INFO]: Author: LoneDev

### ProtocolLib Version

[21:07:14 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
>
[21:07:14 INFO]: Provides read/write access to the Minecraft protocol.
>
[21:07:14 INFO]: Authors: dmulloy2[97m and comphenix
>

### LoneLibs Version

[21:07:47 INFO]: LoneLibs version 1.0.58
>
[21:07:47 INFO]: Collection of libs used by my plugins
>
[21:07:47 INFO]: Authors: LoneDev[97m and others
>

### Full Server Log

https://mclo.gs/WMjv29P
