### ISSUE TITLE
Add support to "paletted_permutations"

### ISSUE THREAD

**Issue by EspartaProJunior** [PluginBugs/Issues-ItemsAdder#3998]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

master_masaki

### What happened?

Technically the textures are not on the server because they are generated on the client by the atlas, so it gives errors that the texture does not exist

### Steps to reproduce the issue

https://drive.google.com/file/d/17_z8NOI4KsOYoGaIVBL8sBdGV-O71VHW/view?usp=sharing

### Server version

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

ItemsAdder_4.0.2-alpha-test-8-pre-release-4.jar

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs_1.0.57.jar

### Full Server Log

i dont have logs, i know

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: painter
items:
  white_bricks:
    display_name: '&fWhite Painted Bricks'
    permission: "painter.blocks"
    resource:
      material: BRICK
      generate: true
      textures:
      - minecraft:block/bricks_white
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        cancel_drop: false
        hardness: 0.4
        sound:
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.8
        break_tools_blacklist:
        - _AXE
```
