### ISSUE TITLE
CIT inconsistency

### ISSUE THREAD

**Issue by debugtarget** [PluginBugs/Issues-ItemsAdder#4004]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

.debugtarget

### What happened?

When using Itemsadder to make custom armor textures, the armor textures do not show up when using mods with CIT rendering capabilities (namely OptiFine and CITResewn.), if the armor texture is attached to a plugin item like MMOItems. For this purpose a properties file is made in minecraft/optifine/cit/[name].
I am currently working with 2 different custom armor sets, despite their CIT property files being identical, with the exception of the file paths and ModelData of course, only one of them is shown correctly when OptiFine is in use.

Attached you see an image of a total of 4 armor sets. The first two from the left armor sets are obtained from MMOItems, I have checked multiple times that the ModelData is entered correctly for this item. The last two from the left are obtained internally from Itemsadder.
![image](https://github.com/user-attachments/assets/063c876c-5551-4a63-b908-b4894ed1d3de)

Note that the helmet works both in Itemsadder and in MMOItems, but the full set only works in Itemsadder. Below are the two property files.

minecraft/optifine/cit/bone_helmet/bone.properties
```
type=armor
items=leather_helmet\ leather_chestplate\ leather_leggings\ leather_boots
texture.leather_layer_1=layer_1
texture.leather_layer_1_overlay=layer_1
texture.leather_layer_2=layer_2
texture.leather_layer_2_overlay=layer_2
nbt.CustomModelData=51000
```
minecraft/optifine/cit/bone_helmet
![image](https://github.com/user-attachments/assets/5fde2293-46b4-4344-b4c0-486492ed8bb0)
This configuration of the bone helmet works.

minecraft/optifine/cit/padded_set/padded.properties
```
type=armor
items=leather_helmet\ leather_chestplate\ leather_leggings\ leather_boots
texture.leather_layer_1=layer_1
texture.leather_layer_1_overlay=layer_1
texture.leather_layer_2=layer_2
texture.leather_layer_2_overlay=layer_2
nbt.CustomModelData=50000
```
minecraft/optifine/cit/padded_set
![image](https://github.com/user-attachments/assets/ca37a19c-9724-4129-a119-18e4df472165)
This configuration of the padded set does not work.

For some odd reason, if the file path `minecraft/optifine/cit/padded_set/padded.properties` is renamed to `minecraft/citresewn/cit/padded_set/padded.properties` the armor shows up correctly for people that are using CITResewn, but not for people that are using OptiFine.

I have already contacted the Itemsadder Discord support about this, I was told to open a Github issue.

### Steps to reproduce the issue

1. Create Itemsadder config
2. Create MMOItems item
3. Check functionality in Itemsadder
4. Attach NBT and dye color to MMOItem
5. Create CIT property file
6. Reload pack

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version
Previous version: git-Pufferfish-49 (MC: 1.20.4)

### ItemsAdder Version

[11:49:24 INFO]: ItemsAdder version 3.6.4-release-3
[11:49:24 INFO]: Customized Minecraft without client mods!
[11:49:24 INFO]: Website: devs.beer
[11:49:24 INFO]: Author: LoneDev

### ProtocolLib Version

[11:49:39 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[11:49:39 INFO]: Provides read/write access to the Minecraft protocol.
[11:49:39 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:49:50 INFO]: LoneLibs version 1.0.56
[11:49:50 INFO]: Collection of libs used by my plugins
[11:49:50 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/612Ws5e

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: realmfall
armors_rendering:
  padded:
    color: "#4a5d6f"
    layer_1: armors/padded-set/layers/layer_1
    layer_2: armors/padded-set/layers/layer_2
    use_color: false
items:   
  padded_coif:
    display_name: "Padded Coif"
    permission: padded
    resource:
      generate: true
      model_id: 50000
      textures:
        - armors/padded-set/textures/padded_coif.png
    specific_properties:
      armor:
        slot: head
        custom_armor: padded
  padded_gambeson:
    display_name: "Padded Gambeson"
    permission: padded
    resource:
      generate: true
      model_id: 50000
      textures:
        - armors/padded-set/textures/padded_gambeson.png
    specific_properties:
      armor:
        slot: chest
        custom_armor: padded
  padded_leggings:
    display_name: "Padded Leggings"
    permission: padded
    resource:
      generate: true
      model_id: 50000
      textures:
        - armors/padded-set/textures/padded_leggings.png
    specific_properties:
      armor:
        slot: legs
        custom_armor: padded
  padded_boots:
    display_name: "Padded Boots"
    permission: padded
    resource:
      generate: true
      model_id: 50000
      textures:
        - armors/padded-set/textures/padded_boots.png
    specific_properties:
      armor:
        slot: feet
        custom_armor: padded
```

### Other files, you can drag and drop them here to upload. (optional)

![layer_1](https://github.com/user-attachments/assets/e53d23a9-c0f8-4dcd-aacb-464c1c4a135c)
![layer_2](https://github.com/user-attachments/assets/234eeb17-fecb-439a-b261-a9882795d54e)
