### ISSUE TITLE
Ore block drop itself(and normal drops) when mining it

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#4016]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jeffry1829

### What happened?

I mine cassiterite_ore in iasurvival, and it will drop itself and cassiterite_fragments. (It also applies to other ores)

### Steps to reproduce the issue

Install iasurvival, mine it.

### Server version

Current Purpur Version: 1.21.1-2305-fdfc12e (MC: 1.21.1)*

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/vT0duuU

### Problematic items yml configuration file (optional)

```yaml
cassiterite_ore:
      type: iasurvival:cassiterite_ore
      items:
        cassiterite_fragment:
          item: iasurvival:cassiterite_fragment
          min_amount: 1
          max_amount: 2
          chance: 80
        cobblestone:
          item: COBBLESTONE
          min_amount: 1
          max_amount: 1
          chance: 30
      exp:
        exp_1:
          min_amount: 1
          max_amount: 2
          chance: 50
```

### Other files, you can drag and drop them here to upload. (optional)

[loots.yml.txt](https://github.com/user-attachments/files/17055915/loots.yml.txt)
[cassiterite_ore.yml.txt](https://github.com/user-attachments/files/17055916/cassiterite_ore.yml.txt)
