### ISSUE TITLE
Custom recipes with duplicate key won't get registered nor generate any warning

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4023]
For example `cassiterite` from the default `iasurvival` namespace.

`contents\iasurvival\configs\ores\recipes\recipe_cassiterite.yml`
```yml
recipes:
  crafting_table:
    cassiterite:
      permission: iasurvival.cassiterite
      enabled: true
      pattern:
        - XXX
        - XCC
        - XCC
      ingredients:
        C: iasurvival:cassiterite_fragment
      result:
        item: iasurvival:cassiterite
        amount: 1
```

`contents\iasurvival\configs\blocks\recipes_minerals_blocks.yml`
```yml
    cassiterite:
      permission: iasurvival.blocks.minerals_blocks.cassiterite
      enabled: true
      pattern:
        - XXX
        - XBX
        - XXX
      ingredients:
        B: iasurvival:cassiterite_block
      result:
        item: iasurvival:cassiterite
        amount: 9
```
