### ISSUE TITLE
Set custom name with NBT won't work correcly

### ISSUE THREAD

**Issue by Tareyu** [PluginBugs/Issues-ItemsAdder#4033]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Tareyu#5152

### What happened?

Hi I would like to change the name of an item with the NBT line but I think there is a problem since 1.21 update!
![Capture d’écran 2024-09-19 211729](https://github.com/user-attachments/assets/f5ac1414-e312-45fc-b2fe-be40d83fc8d9)

I have 2 \\ which generates instead of one
![Capture d’écran 2024-09-19 211811](https://github.com/user-attachments/assets/af0c61d2-e8bc-43f7-a22d-2b749632f868)

And finally won't work.
![Capture d’écran 2024-09-19 211752](https://github.com/user-attachments/assets/5623c247-c08d-4138-b2e9-8744ec25f483)

No error in my console.

Thank you for your reply, I'll wait to resolve this issue before updating my server.

### Steps to reproduce the issue

I use this tutorial to set custom name for nbt:
https://itemsadder.devs.beer/plugin-usage/adding-content/custom-item-nbt

### Server version

This server is running Paper version 1.21.1-99-master@1bc02e6 (2024-09-25T02:41:02Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-74-971a7a5 (MC: 1.21.1)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/kPKy3RW

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vexcraft
items:
  steel_ingot:
    enabled: true
    display_name: "Test"
    permission: "vexcraft.items.steel_ingot"
    nbt: "{display:{Name:'{\"text\":\"TEST\"}'}}"
    resource:
      material: IRON_INGOT
      generate: false
      model_id: 1
      model_path: "item/steel_ingot"
recipes:
  crafting_table:
    steel_ingot_from_block:
      permission: vexcraft.recipes.steel_ingot
      enabled: false
      pattern:
      - XXX
      - XAX
      - XXX
      ingredients:
        A: vexcraft:steel_block
      result:
        item: vexcraft:steel_ingot
        amount: 9
  cooking:
    steel_ingot:
      permission: vexcraft.cooking.steel_ingot
      enabled: false
      ingredient:
        item: IRON_INGOT
      machines:
      - BLAST_FURNACE
      exp: 2.0
      cook_time: 400
      result:
        item: vexcraft:steel_ingot
        amount: 1
```
