### ISSUE TITLE
Item Substitution In recipes 

### ISSUE THREAD

**Issue by wolflord212312** [PluginBugs/Issues-ItemsAdder#4040]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

djjewl

### Describe the solution you'd like

Ability to have Multiple ingredients under 1 Identifier that would allow for any of the resources specified to be used to craft it instead of making 10-20 Patterns for the same thing

EXAMPLE
```
    item1:
      enabled: true
      pattern:
        - "XXX"
        - "AXA"
        - "AAA"
      ingredients:
        A: OAK_SLAB
        A: BIRCH_SLAB
        A: CHERRY_SLAB
        A: DARK_OAK_SLAB
        A: JUNGLE_SLAB
        A: ACACIA_SLAB
        A: CRIMSON_SLAB
        A: WARPED_SLAB
        A: SPRUCE_SLAB
```
        
        This would make Item one as long as any of the slabs are in the pattern
        
Currently this does not seem to be possible, And would as such need to make tons of patterns for what should be a simple process.

Would also like tag support something that can use Bukkit tags  to get things like all the wodden slabs and add them to the recipe as substitutable.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Tag.html

Tag in this istance would be  WOODEN_SLABS (or #WOODEN_SLABS Using the # to identify a tag.)

### Is your feature request related to a problem?

Inability to Satisfy my need for simplicity.
And leading to way to big of files.

### Describe alternatives you've considered

None this is the only way, that i see Possible.
