### ISSUE TITLE
Mace attributes are always addition to Base stats, instead of setting them.

### ISSUE THREAD

**Issue by EnderQuinn** [PluginBugs/Issues-ItemsAdder#4055]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

umezawashino

### What happened?

When configuring attributes, the mace attributes always ends up adding to the base attributes of the player:
![image](https://github.com/user-attachments/assets/8ce88834-d58c-45d1-b2bd-d4f1d90f4b39)

This isn't intended, and instead of adding to the base attributes, it should "Set" the base attributes of the player, like so:
![image](https://github.com/user-attachments/assets/1f4bc524-8e73-43b6-8f26-69e796cc66a5)

### Steps to reproduce the issue

Simply create an custom item config, make the resource material mace, add custom attributes.

### Server version

This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/yZHB2ou

### Problematic items yml configuration file (optional)

```yaml
upgraded_club:
    display_name: "ᴜᴘɢʀᴀᴅᴇᴅ ᴄʟᴜʙ"
    permission: umess_items
    durability:
      max_custom_durability: 200
    attribute_modifiers:
      mainhand:
        generic.attack_damage: 12
        generic.attack_speed: 0.75
    lore:
      - ''
      - '&7ʀᴀʀɪᴛʏ: ᴄᴏᴍᴍᴏɴ'
    resource:
      material: MACE
      generate: true
      textures:
        - weapons_tools/blunts/upgraded_club.png
```

**Comment by LoneDev6** [comment]
![image](https://github.com/user-attachments/assets/dc3f8b4c-f382-451f-ba22-a88e6f67ac4f)

> Sort of, although I'm simply experiencing issues with being able to spam the mace.. because attack speed is not updating

**Comment by LoneDev6** [comment]
Lore is now fixed.

![image](https://github.com/user-attachments/assets/8948463d-13e4-42e0-897f-9e9050bf3876)
![image](https://github.com/user-attachments/assets/ab0d566c-3a85-4dbc-9a35-0ad04bd4fe8d)

```yml
info:
  namespace: test
items:
  test_mace:
    enabled: true
    display_name: test_mace
    resource:
      material: MACE
      generate: false
      model_path: minecraft:diamond
    durability:
      max_custom_durability: 200
    attribute_modifiers:
      mainhand:
        generic.attack_damage: 12
        generic.attack_speed: 0.75
    lore:
      - ''
      - '&7ʀᴀʀɪᴛʏ: ᴄᴏᴍᴍᴏɴ'
  test_mace_netherite_axe:
    enabled: true
    display_name: test_mace_netherite_axe
    resource:
      material: NETHERITE_AXE
      generate: false
      model_path: minecraft:diamond
    durability:
      max_custom_durability: 200
    attribute_modifiers:
      mainhand:
        generic.attack_damage: 12
        generic.attack_speed: 0.75
    lore:
      - ''
      - '&7ʀᴀʀɪᴛʏ: ᴄᴏᴍᴍᴏɴ'
```
