### ISSUE TITLE
Calling .remove() on furniture entities does not work

### ISSUE THREAD

**Issue by bobcat4848** [PluginBugs/Issues-ItemsAdder#4065]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jacobc

### What happened?

When trying to call .remove() on a furniture item when it's close to other blocks, it doesn't work. Workaround is to use getNearbyEntities() with a range and remove all entitles in the range that are not a LivingEntity.

### Steps to reproduce the issue

1. Have a furniture entity that uses an item (not a block) as the material
2. Spawn the furniture using CustomFurniture.spawn() or CustomFurniture.spawnPreciseNonSolid(), this returns a CustomFurniture item.
3. Keep track of this object, try to .remove() this furniture when it's close to other blocks, it won't work. It does remove when it's not surrounded by other blocks. See images to understand what I am talking about.

### Server version

This server is running Paper version 1.21.1-122-master@4430e96 (2024-10-12T21:18:42Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-148-20f5165 (MC: 1.20.6)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/XJmuUaW

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: fishing
items:
  copper_fishing_net:
    display_name: '&8Copper Fishing Net'
    permission: copper_fishing_net
    resource:
      material: PAPER
      generate: false
      model_path: item/copper_fishing_net
      model_id: 4100
    behaviours:
      furniture:
        entity: armor_stand
        small: true
        fixed_rotation: true
        permission_suffix:
          break: fishing.net
          place: fishing.net
        placeable_on:
          floor: false
          ceiling: false
          walls: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/90b8bca3-18c1-4b7b-bd9d-a48cba9d9588)
![image](https://github.com/user-attachments/assets/d519027a-c8a6-40a6-aaed-f7db0f5e7047)
