### ISSUE TITLE
Block hardness is not taken into account by tools of efficiency 4+

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#4083]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

.nohere

### What happened?

in the configuration of custom blocks, hardness is not taken into account when you have an item with an effectiveness 4 enchantment or higher, which just oneshot the block.

The bug only occurs with an axe.
This bug is also present in version 1.20.4

In the video, hardness is set to an extreme value to illustrate the bug.

### Steps to reproduce the issue

1. configure a block with a hardness e.g. 40 for an ext value
2. place the block
3. break the block with an enchanted tool efficiency 4 or more
4. notice that the block is oneshot

### Server version

This server is running PaperSquid version 1.21.1-DEV-master@b858544 (2024-09-16T16:41:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
Unknown version
Previous version: 1.21-DEV-e2c88d1 (MC: 1.21)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/54e6873b-18c2-49e9-b22b-2ef9abddd057)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/02c5ff7d-bf5f-4427-b618-d0f8aedfd48a)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/c1f9a8dc-4dcb-4c61-b97e-fcacaa788472)

### Full Server Log

https://mclo.gs/Y2m8bts

### Problematic items yml configuration file (optional)

```yaml
beech_log:
    display_name: "<white>beech_log"
    permission: "Rivrs.wood.beech_log"
    resource:
      material: PINK_DYE
      model_id: 700
      generate: false
      model_path: "tree/adventure_island/beech/beech_log"
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        cancel_drop: true
        break_tools_blacklist:
        - WOODEN_PICKAXE
        - STONE_PICKAXE
        - IRON_PICKAXE
        - GOLDEN_PICKAXE
        - DIAMOND_PICKAXE
        - NETHERITE_PICKAXE
        break_tools_whitelist:
        - AXE
        hardness: 40
        blast_resistance: 1
        no_explosion: true
        sound:
          break:
            name: minecraft:block.wood.break
            volume: 0.2
            pitch: 0.9
          place:
            name: minecraft:block.wood.place
            volume: 0.2
            pitch: 0.9
          hit:
            name: minecraft:block.wood.hit
            volume: 0.2
            pitch: 0.9
          step:
            name: minecraft:block.wood.step
            volume: 0.2
            pitch: 0.9
          fall:
            name: minecraft:block.wood.fall
            volume: 0.2
            pitch: 0.9
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/JjfVeq5QxJ8
