### ISSUE TITLE
1.21.1 - Custom Durability does not work on leather armour

### ISSUE THREAD

**Issue by DevNinjaMC** [PluginBugs/Issues-ItemsAdder#4095]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Ever since updating to 1.21.1 from 1.20.4, My armours (leather) with custom durability are using the default leather armour durability. I've tired changing the configs and stuff and it still doesn't help. I'm really in need of support.

The image attached is of the items that were used before updating to 1.21.1 and they are now at negative durability
![image](https://github.com/user-attachments/assets/85ce363a-019b-464e-ae2a-fd797ba1cbf8)

### Steps to reproduce the issue

1. 1.21.1, latest version of itemsadder, a config with custom durability set

### Server version

 This server is running Pufferfish version 1.21.1-20-HEAD@3415da0 (2024-10-21T02:44:49Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Previous version: git-Pufferfish-52 (MC: 1.20.4)

### ItemsAdder Version

[16:58:51 INFO]: ItemsAdder version 4.0.3
[16:58:51 INFO]: Customized Minecraft without client mods!
[16:58:51 INFO]: Website: devs.beer
[16:58:51 INFO]: Author: LoneDev

### ProtocolLib Version

[16:59:30 INFO]: ProtocolLib v5.4.0-SNAPSHOT-735
[16:59:30 INFO]: Authors: dmulloy2 and Comphenix

### LoneLibs Version

[16:59:46 INFO]: LoneLibs version 1.0.59

### Full Server Log

https://mclo.gs/SRKE0Qg

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: heavenset
items:
  heavenset_helmet:
    display_name: Heaven Helmet
    permission: heavenset.helmet
    resource:
      generate: true
      textures:
      - armor/heavenset_helmet_icon.png
    specific_properties:
      armor:
        custom_armor: heavenset_armor
        slot: head
    attribute_modifiers:
      head:
        armor: 3
    durability:
      max_custom_durability: 630
      custom_durability: 630
    enchants:
      - protection:6
      - unbreaking:6
      - blast_protection:6
      - mending:1
      - aqua_affinity:1
    blocked_enchants:
      - ALL
  heavenset_chestplate:
    display_name: Heaven Chestplate
    permission: heavenset.chestplate
    resource:
      generate: true
      textures:
      - armor/heavenset_chestplate_icon.png
    specific_properties:
      armor:
        custom_armor: heavenset_armor
        slot: chest
    attribute_modifiers:
      chest:
        armor: 8
    durability:
        max_custom_durability: 800
        custom_durability: 800
    enchants:
      - protection:6
      - unbreaking:6
      - blast_protection:6
      - mending:1
    blocked_enchants:
      - ALL
  heavenset_leggings:
    display_name: Heaven Leggings
    permission: heavenset.leggings
    resource:
      generate: true
      textures:
      - armor/heavenset_leggings_icon.png
    specific_properties:
      armor:
        custom_armor: heavenset_armor
        slot: legs
    attribute_modifiers:
      legs:
        armor: 6
    durability:
      max_custom_durability: 750
      custom_durability: 750
    enchants:
      - protection:6
      - unbreaking:6
      - blast_protection:6
      - mending:1
    blocked_enchants:
      - ALL
  heavenset_boots:
    display_name: Heaven Boots
    permission: heavenset.boots
    resource:
      generate: true
      textures:
      - armor/heavenset_boots_icon.png
    specific_properties:
      armor:
        custom_armor: heavenset_armor
        slot: feet
    attribute_modifiers:
      feet:
        armor: 3
    durability:
      max_custom_durability: 600
      custom_durability: 600
    enchants:
      - protection:6
      - unbreaking:6
      - blast_protection:6
      - mending:1
      - feather_falling:5
      - depth_strider:4
    blocked_enchants:
      - ALL
```
