### ISSUE TITLE
Inject NBT data into items from a separate file

### ISSUE THREAD

**Issue by Slarof** [PluginBugs/Issues-ItemsAdder#4114]
### Discord tag (optional)

vova_erofeev

### Describe the solution you'd like

I want the components to be independent of the nbt line, like attributes (**Attribute modifiers**) in the configuration of items.

---- removed old examples, check this message history to read them.

**Comment by LoneDev6** [comment]
ItemsAdder acts like a multi-layer between Minecraft and the artist.
The artist shouldn't worry to know what components are, this is why I abstracted configurations entries.

If you feel like some components or features are missing please report it on Github and I will try to implement compatibility.
If you want you can manually add NBT using the [`nbt` property](https://itemsadder.devs.beer/plugin-usage/adding-content/custom-item-nbt) which supports components.

**Comment by Slarof** [comment]
Since the offer was rejected, I ask you to please describe in detail and in detail the ways to obtain and fill in the nbt and the components in it

- I'm faced with the problem that I don't understand how to properly design components in nbt by looking at the wiki etc.: https://discord.com/channels/533407895010803753/1309539361750253588

**Comment by Slarof** [comment]
Okay. Still, I was able to find a solution that satisfies me and uses what you suggest

Here is an example
```yml
items:
  turtle_chestplate:
    display_name: "Черепаший нагрудник"
    nbt: "{components: {
    \"minecraft:attribute_modifiers\": {
      modifiers: [
        {
          id: \"minecraft:turtle_chestplate\",
          type: \"minecraft:armor\",
          amount: 6.0d,
          operation: \"add_value\",
          slot: \"feet\"
        }
      ]
    },
    \"minecraft:equippable\": {
      slot: \"feet\",
      model: \"equipments:turtle_chestplate\",
      allowed_entities: \"minecraft:player\"
    },
    \"minecraft:rarity\":\"common\"}}"
    resource:
      material: IRON_CHESTPLATE
      generate: true
      textures:
        - item/turtle_chestplate
```

**Comment by LoneDev6** [comment]
What I can do is adding a new property called `nbt_data_file` that supports a `.nbt` file name.
This allows you to write Minecraft items NBT components files easily.

Example:

```yml
info:
  namespace: combat
items:
  turtle_chestplate:
    display_name: "Черепаший нагрудник"
    nbt_data_file: "my_file.nbt"
    attribute_modifiers:
      chest:
        armor: 6
        oxygen_bonus: 1
        water_movement_efficiency: 0.3
        submerged_mining_speed: 0.26
    resource:
      material: IRON_CHESTPLATE
      generate: true
      textures:
        - combat/item/turtle_chestplate
```

`my_file.nbt`
```json
{
   "id":"minecraft:iron_chestplate",
   "components":{
      "minecraft:item_name":"'Черепаший нагрудник'",
      "minecraft:max_damage":440,
      "minecraft:attribute_modifiers":[
         {
            "id":"turtle_chestplate",
            "type":"minecraft:armor",
            "amount":6,
            "operation":"add_value",
            "slot":"chest"
         },
         {
            "id":"turtle_chestplate",
            "type":"minecraft:oxygen_bonus",
            "amount":1,
            "operation":"add_value",
            "slot":"chest"
         },
         {
            "id":"turtle_chestplate",
            "type":"minecraft:water_movement_efficiency",
            "amount":0.3,
            "operation":"add_value",
            "slot":"chest"
         },
         {
            "id":"turtle_chestplate",
            "type":"minecraft:submerged_mining_speed",
            "amount":0.26,
            "operation":"add_value",
            "slot":"chest"
         }
      ],
      "minecraft:item_model":"equipments:turtle_chestplate",
      "minecraft:equippable":{
         "slot":"chest",
         "model":"equipments:turtle_armor",
         "allowed_entities":"minecraft:player",
         "dispensable":true
      },
      "minecraft:repairable":{
         "items":"minecraft:turtle_scute"
      }
   }
}
```
