### ISSUE TITLE
Items with durability loss no longer work in recipes

### ISSUE THREAD

**Issue by nlTarzan** [PluginBugs/Issues-ItemsAdder#4131]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

403224656393535488

### What happened?

I made custom tools and armor. When I got them fresh from the IA interface I'm able to smelt them in a furnace and they turn into ingots, but as soon as I change something about the item (ie. durability, name, trim) I can no longer smelt the item.

### Steps to reproduce the issue

1. Grab an item that you can smelt from Itemsadder
2. Make it lose durability, change it's name in an anvil or apply a trim
3. Try to smelt it in a Furnace

### Server version

This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://api.mclo.gs/1/raw/lhLWs5t

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: solar
items:
  #INGOTS
  solar_ingot:
    display_name: "Solar Ingot"
    resource:
      material: FEATHER
      generate: true
      textures:
        - item/solar_ingot
recipes:
  cooking:
    solar_pickaxe:
      permission: iasolar.smelting
      ingredient:
        item: solar_pickaxe
      machines:
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: solar_ingot
        amount: 1
    solar_axe:
      permission: iasolar.smelting
      ingredient:
        item: solar_axe
      machines:
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: solar_ingot
        amount: 1
    solar_shovel:
      permission: iasolar.smelting
      ingredient:
        item: solar_shovel
      machines:
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: solar_ingot
        amount: 1
    solar_hoe:
      permission: iasolar.smelting
      ingredient:
        item: solar_hoe
      machines:
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: solar_ingot
        amount: 1
```
