### ISSUE TITLE
`item_display` furniture hitbox not rotating when placed

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4135]

**Comment by LoneDev6** [comment]
Note on how to setup the models in blockbench

![image](https://github.com/user-attachments/assets/887f82ae-9d91-4a20-9dd0-0c6d1e88484f)

**Comment by Andre601** [comment]
There is also the invis option, which may be better.

**Comment by LoneDev6** [comment]
```yml
info:
  namespace: test
items:
  test_furniture_block:
    display_name: test_furniture_block
    resource:
      material: MAGENTA_DYE
      generate: false
      model_path: test:test_furniture_block
    behaviours:
      furniture:
        entity: item_display
        gravity: false
        fixed_rotation: true
        solid: true   
        hitbox:
          length: 1
          width: 1
          height: 1    
        placeable_on:
          floor: true
          ceiling: true
          walls: true
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
```

[test_furniture_block.json](https://github.com/user-attachments/files/17777382/test_furniture_block.json)
