### ISSUE TITLE
Stop sounds when emote ends

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-ItemsAdder#4155]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

If emote is stopped, stop the sound too
This could help by doing emote packs because I am doing like dances with music and it repeats if you stop

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Using the command /stopsound @e[type=minecraft:player,sort=nearest,distance=10] for example

**Comment by mario638** [comment]
I have seen that distance doesn't work in stopsound so here it would be the command updated `stopsound @a[dx=10,dy=10,dz=10,sort=nearest]`
Here is a code that I have made in CE (Conditional Events) for making this to work
`Events:
  event1:
    type: custom
    custom_event_data:
      event: dev.lone.itemsadder.api.Events.PlayerEmoteEndEvent
      player_variable: getPlayer()
    actions:
      default:
      - 'player_command_as_op: stopsound @a[dx=10,dy=10,dz=10,sort=nearest]'`

**Comment by mario638** [comment]
@LoneDev6 Bump

**Comment by Andre601** [comment]
> [@LoneDev6](https://github.com/LoneDev6) Bump

Don't bump issues, or else you will be punished.

**Comment by mario638** [comment]
> > [@LoneDev6](https://github.com/LoneDev6) Bump
> 
> Don't bump issues, or else you will be punished.

![Image](https://github.com/user-attachments/assets/e2cd6a32-766b-429a-87cc-02d442095401)

**Comment by LoneDev6** [comment]
I can add it to the emote yml configuration.
For example something like that:
```yml
on_stop:
  stop_sounds: true
```

**Comment by mario638** [comment]
Sure and I think is much better

**Comment by LoneDev6** [comment]
```yml
info:
  namespace: iatest
emotes:
  test_emote:
    id: test_emote
    can_player_move: false  # fixed
    hide_equipment:
      helmet: true
      mainhand: true
      offhand: true
    cancel_conditions:
      sneak: true
      deal_damage: true
      in_air: true
      take_damage: true
    on_stop:
      stop_sounds: true  # new option: stops all played sound on emote cancel
      skip_emote_end: true  # new option: interrupts the emote on cancel
```
