### ISSUE TITLE
craft recipe function is broken

### ISSUE THREAD

**Issue by DrJekyllH** [PluginBugs/Issues-ItemsAdder#4161]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Jekyll

### What happened?

Craft recipe with some options is not work
1. Can’t craft more than one item with Decrement_durability item
2. Can't craft item with shapeless option
3. Ingredients items put on the crafting table but result items may not be created
4. After iazip, the relationship between result items and recipes may break down, resulting in non-functional or different items being created.

### Steps to reproduce the issue

1. server boot
2. login
3. put items on the craft table
5. issue iazip
6. put items on the craft table

### Server version

 This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.4

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

 LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/SNLENbk

**Comment by Barlaf** [comment]
Hello !
Same issue with the Decrement_durability feature. If the item have not all the durability, the craft was no recognize.
## Sample code
```yml
cuir_tanne_netherite:
      permission: blcombat.craft
      enabled: true
      pattern:
      - CMC
      - CCC
      - XXX
      ingredients:
        C: blcombat:cuir_royal
        M: blcombat:marteau_netherite
      result:
        item: blcombat:cuir_tanne
        amount: 1
      return_items:
        decrement_durability:
          marteau_netherite:
            item: marteau_netherite
            amount: 1
```
## Result
Item with max durability:
![image](https://github.com/user-attachments/assets/5d346fe0-88fb-4f1e-91d9-7e67a830b9e1)
Item with lose durahbility:
![image](https://github.com/user-attachments/assets/e82e4dcf-a9ed-4632-adc6-42a32da7a1c0)
