### ISSUE TITLE
Old config.yml entries not updated

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4163]

**Comment by PSYCHEER** [comment]
```yml
metrics: true
update-checker: true
  apply-on-join: false
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 30
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    lock-player: true
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: minecraft.ttf
    shift: '[0,0]'
    size: 11
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      optifine: true
      vanilla: true
    disable-overwrite-leather-armor-layers-textures: true
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: false
    contents-folders-priority:
    - vanilla
    - Enhanced Boss Bars
    - VanillaBarsAway
    - _iainternal
    - simple_vanilla_enhancer
    - myIcons
    - twitteremojis
    - merged_pack01
    - UniqueDark
    - pumpkins
    - CinematicStudio
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    - BetterHud/build
    compress-shader-files: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  atlas_support: false
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  apply-during-chunk-load-phase: true
  description: ItemsAdder
  format:
    auto: true
    value: 41
  supported_formats:
    enabled: false
    min_inclusive: 41
    max_inclusive: 9999
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
    delay_ticks: 1
  allow_other_plugins_resourcepacks: true
  notify_other_plugins_resourcepacks: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
  custom:
    mushroom: true
    chorus: true
    note: true
    wire: false
    fire: true
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  enabled: true
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: false
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: false
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 3600
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: false
    chat:
      enabled: false
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    customitems-name-and-lore:
      enabled: true
    customitem-name-and-lore:
      enabled: true
    legacy_colors_compatibility: true
  hide-scoreboard-numbers-old-clients: false
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: false
    interval-rendering-packets-ticks: 1
    expert_users:
      delay_packets: false
      extract_emotes_shaders: false
  furniture:
    auto_convert_to_item_display: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup: {}
      on-item-click: {}
      automatically: true
  remove-vanilla-recipes:
    enabled: true
    list:
      NETHERITE_HELMET: true
      NETHERITE_CHESTPLATE: true
      NETHERITE_LEGGINGS: true
      NETHERITE_BOOTS: true
      NETHERITE_SWORD: true
      NETHERITE_PICKAXE: true
      NETHERITE_AXE: true
      NETHERITE_SHOVEL: true
      NETHERITE_HOE: true
      SHIELD: true
      ARMOR_STAND: true
      HOPPER: true
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
    log-files-reloading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: false
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
  resourcepacks:
    log_player_install: false
    compression:
      files: true
      overlays: true
  blocks-populators:
    log-generation: false
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: false
```
