### ISSUE TITLE
Custom blocks performance issue

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4165]
https://discord.com/channels/533407895010803753/1301895549917728860

> Hello,  even with custom blocks all set to false in config since I don't use them to logic behind them is still running
players make op big redstone farms and items adder for some reason keeps checking stuff that I disabled in config, eating performance
Spigot 1.20.6, java 21, latest ItemsAdder

![image](https://github.com/user-attachments/assets/c343474a-a83a-4be6-b210-b4efe9ee8e60)
![image](https://github.com/user-attachments/assets/70b81108-4f05-4adb-a500-60ef5fe1b47f)

```yml
blocks:
  light-api: false
  fix-liquids-flow: false
  fix-floating-blocks: false
  fix-glitched-blocks:
    enabled: false
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: false
    send-actionbar: false
  campfire_enhancements:
    enable: false
    unlit_on_place: false
    allow_any_item: false
    drop_when_broken: false
  custom:
    note: false
    mushroom: false
    chorus: false
    wire: false
    fire: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: false
  remove-unused-palettes-on-region-save: false
```
