### ISSUE TITLE
Any of HEAD/SKULL cannot be reskinned/remodeled

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#4170]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

PSYCHEER

### What happened?

I'm trying to do custom 3D model wearable trough HEAD/SKULL material, but cannot

![{3DAC0743-3DA4-4073-A6D4-130ACF1A119B}](https://github.com/user-attachments/assets/b28d9677-1c36-404c-b17f-4e1bfe94a249)

```yml
  helmet:
    display_name: Wolverine's Helmet
    permission: wolverine
    resource:
      material: CREEPER_HEAD
      generate: false
      model_path: "helmet/wolverine_helmet"
    durability:
      max_custom_durability: 400
    attribute_modifiers:
      head:
        armor: 7
        armorToughness: 1
        ```

### Steps to reproduce the issue

Create helmet trough creeper_head, player_head, skeleton_skull, wither_skeleton_skull
Check for the issue

### Server version

![{A6D658B7-95D6-47B9-8768-FDE1699532B3}](https://github.com/user-attachments/assets/2c1211ed-a1a1-443e-bc07-b58a85e245be)

### ItemsAdder Version

![{91B8D6CA-3E8F-4A34-BA0D-5BF5370AAF15}](https://github.com/user-attachments/assets/ff7e64d1-5750-44f4-ac13-9dcc6928d91d)

### ProtocolLib Version

![{794779C3-0F12-4B6F-A34F-40B2B560A7B9}](https://github.com/user-attachments/assets/1cf93573-cc8b-402b-babe-679f98af6aa3)

### LoneLibs Version

![{ECAB8967-86BB-4B27-8BAC-C271942E81DC}](https://github.com/user-attachments/assets/1607a50d-5b43-49b6-a3bc-0ff185d3ab00)

### Full Server Log

https://mclo.gs/KOLoEbA
