### ISSUE TITLE
Error in the console when using items with components in nbt

### ISSUE THREAD

**Issue by Slarof** [PluginBugs/Issues-ItemsAdder#4173]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

vova_erofeev

### What happened?

When using items with components in nbt, an error pops up in the console

If anything, the item with the components is running on the server

### Steps to reproduce the issue

1. Opening the configuration of the item
2. Adding the nbt line with the components and save
3. Start the server and see an error related to nbt, although the element is functioning

### Server version

Current Purpur Version: 1.21.3-2342-959c29d (MC: 1.21.3)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 4.0.4
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-736
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.61
Collection of libs used by my plugins
Authors: LoneDev and others

### Full Server Log

https://mclo.gs/WeLMekf

### Error (optional)

```shell
[14:36:47 ERROR]: [ItemsAdder] [Items] 'test:something'. Error injecting 'nbt' property. File: /contents/test/configs/something.yml
[14:36:47 ERROR]: [ItemsAdder] Error: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: test

items:
  something:
    display_name: TEXT
    nbt: "{components:{\"minecraft:item_name\":'\"TEXT\"',\"minecraft:max_stack_size\":99,\"minecraft:rarity\":\"epic\"}}"
    permission: nothing
    resource:
      material: PAPER
      generate: true
      textures:
        - minecraft:items/wheat
```
