### ISSUE TITLE
NBT attribute not applying `item_name` and `lore`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4179]
NBT attribute not applying `item_name` and `lore`, they get overwritten by ItemsAdder properties.
This was introduced by mistake while fixing #4137

**Comment by LoneDev6** [comment]
# Examples
```yml
info:
  namespace: test_custom_nbt
categories:
  test_custom_nbt:
    name: test_custom_nbt
    items:
    - "test_custom_nbt*"
items:
  custom_nbt_item_data:
    display_name: "Injected nbt data into this item"
    lore:
    - 'test item: custom_nbt_item_data'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: examples.test
    nbt: '{my-custom-nbt-tag:"hello this is a custom tag", another-tag:"useless"}'
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
  custom_nbt_item_custom_name_legacy_nbt:
    enabled: true
    display_name: custom_nbt_item_custom_name_legacy_nbt
    lore:
    - 'test item: custom_nbt_item_custom_name_legacy_nbt'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    nbt: "{display:{Name:'{\"text\":\"TEST\", \"font\": \"alt\", \"italic\":false}'}}"
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
  custom_nbt_item_custom_name:
    enabled: true
    display_name: example_item_custom_name
    lore:
    - 'test item: custom_nbt_item_custom_name'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    nbt: "{components:{\"minecraft:custom_name\":'{\"text\":\"TEST\", \"font\": \"alt\", \"italic\":false}', \"minecraft:custom_data\": {\"bro\":'asd'}}}"
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
  custom_nbt_item_display_name_component:
    enabled: true
    display_name: '{"text\":"TEST", "font": "alt"}'
    lore:
    - 'test item: custom_nbt_item_display_name_component'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
  custom_nbt_item_display_name_minimessage:
    enabled: true
    display_name: '<font:minecraft:alt>TEST</font>'
    lore:
    - 'test item: custom_nbt_item_display_name_minimessage'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
  custom_nbt_item_display_name_classic:
    enabled: true
    display_name: '&6TEST'
    lore:
    - 'test item: custom_nbt_item_display_name_classic'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
```


![image](https://github.com/user-attachments/assets/f677101c-5b1d-4d04-85ca-537c04b00123)
![image](https://github.com/user-attachments/assets/f0169b5d-ccc6-4881-a45d-337df67689c1)
![image](https://github.com/user-attachments/assets/c7d94e41-c1f9-4cbe-8894-96c66f31d95a)
![image](https://github.com/user-attachments/assets/025b45f0-ac6a-47cb-a99b-241059dd01ea)
![image](https://github.com/user-attachments/assets/3309b5c6-f040-4eb8-ae70-21998a7231d0)
![image](https://github.com/user-attachments/assets/63f9a545-1cff-4386-bf12-8e0bf192cd2e)
