### ISSUE TITLE
Setting apply-during-chunk-load-phase has no effect

### ISSUE THREAD

**Issue by EagL3-GIT** [PluginBugs/Issues-ItemsAdder#4184]
So I repaired the configuration but its still asking before join.. 
I have tried these two methods:

```
  apply_during_chunk_load_phase: false
  apply_on_join:
    enabled: true
    delay_ticks: 200
  
  apply_during_chunk_load_phase: false
  apply_on_join:
    enabled: false
    delay_ticks: 200
```

              This is the correct option, you might have some left over old options in the config.yml, remove them.
```yml
resource-pack:
  uuid: "d69238f2-b7ce-30b0-8262-17cd9490f29d"
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
    delay_ticks: 1
```

_Originally posted by @LoneDev6 in https://github.com/PluginBugs/Issues-ItemsAdder/issues/4154#issuecomment-2498182393_
