### ISSUE TITLE
Add JSON component support to `display_name` property

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4191]
Related to #4179
People use the `nbt` attribute to use JSON components in the item name.
This feature allows users to directly set that into the `display_name` property.

## Example
```yml
  custom_nbt_item_display_name_component:
    enabled: true
    display_name: '{"text\":"TEST", "font": "alt"}'
    lore:
    - 'test item: custom_nbt_item_display_name_component'
    - 'test line from IA config 1'
    - 'test line from IA config 2'
    - 'test line from IA config 3'
    permission: custom.test
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: "minecraft:item/diamond"
    durability:
      durability: 650
      max_durability: 1324
    attribute_modifiers:
      mainhand:
        attackDamage: 30
        attackSpeed: 25
```
