### ISSUE TITLE
target_potion_effect attack not working

### ISSUE THREAD

**Issue by cpr061** [PluginBugs/Issues-ItemsAdder#4202]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

When using the target_potion_effect with the attack event with a sword, it doesn't work.

### Steps to reproduce the issue

1. Create a netherite sword that uses the "attack" event.
2. Try to fix the event code where hitting a entity gives them the poison effect.
3.  Test to make sure attacking a entity (mob) gives them the poison effect.

### Server version

This server is running CraftBukkit version 4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.6-legacy

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-736

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/jAJfrS5#L5160

**Comment by LoneDev6** [comment]
Works fine for me.
Make sure to use the vs code extension to edit your files, check the wiki.
```yml
info:
  namespace: test
items:
  test_target_potion:
    enabled: true
    display_name: test_target_potion
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: NETHERITE_SWORD
    events:
      attack:
        target_potion_effect:
          type: GLOWING
          ambient: true
          amplifier: 10000
          duration: 1000000

```

https://github.com/user-attachments/assets/c7e0d4f0-2c9a-42aa-a1f5-a13b3582ab8c
