### ISSUE TITLE
Add `icon`, `particles` and `ambient` properties for potion effects

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#4217]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mauriciooficial

### What happened?

allow effect potions to be removed from the player's view when wearing ItemsAdder armor.

```yaml
boots:
    display_name:  Boots
    fire_resistant: true
    nbt: '{Unbreakable:1b}'
    resource:
      generate: true
      textures:
      - armor/boots_icon.png
    specific_properties:
      armor:
        custom_armor: armor
        slot: feet
    item_flags:
    - HIDE_ADDITIONAL_TOOLTIP
    events:
      wear:
        potion_effect:
          type: FAST_DIGGING
          duration: 1000000
          amplifier: 2
        potion_effect2:
          type: SPEED
          duration: 1000000
          amplifier: 2
      unwear:
        remove_potion_effect:
        type: FAST_DIGGING
    attribute_modifiers:
      feet:
        armor: 4
        armorToughness: 3
        knockbackResistance: 0.1```
```

for example take this slimefun armor, when I equip it the effects of potions don't appear to me, but I get the effects of the potion: 

slimefun armor: https://prnt.sc/WT_I5DTntlh6

ItemsAdder armor: https://prnt.sc/VO8UuzyK5jDh ( the effects of potions appear on the player when equipping armor )

my suggestion is that you allow us to hide the particles when we equip armor with ItemsAdder potion effects

### Steps to reproduce the issue

wear itemsadder armor

### Server version

Paper version 1.20.6-151-ver/1.20.6@a4f0f5c

### ItemsAdder Version

ItemsAdder_4.0.4

### ProtocolLib Version

ProtocolLib 5.4.0-SNAPSHOT-736

### LoneLibs Version

LoneLibs_1.0.61

### Full Server Log

no error
