### ISSUE TITLE
Durability issues started again on latest beta build (released now i think)

### ISSUE THREAD

**Issue by sennby** [PluginBugs/Issues-ItemsAdder#4225]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

senby8

### What happened?
![image](https://github.com/user-attachments/assets/38f6ef48-357a-483e-b698-30e303ea5a9f)

![image](https://github.com/user-attachments/assets/3b690846-e010-420c-b58f-28d123421150)

In my config i have dura to 1800, it was working for a long time, broke, it got fixed in a beta, now it is seeming broken again.
However if i go grab a new item it is working, so i presume this would be for already existing items from a certain point in time ?
This user just lost this helmet while fighting a mob, broke basically instantly.

### Steps to reproduce the issue

Set custom duability in your IA item config and it will default to the item. 

### Server version

This server is running UniverseSpigot version 1.21.1-DEV-ver/1.21.1-plus@a1e53b4 (2024-11-30T22:05:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-DEV-a1e53b4 (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.5-beta-14

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-734

### LoneLibs Version

LoneLibs version 1.0.62

### Full Server Log

cant right now will later if its needed.

### Problematic items yml configuration file (optional)

```yaml
ecriverstonehelmet:
    display_name: '&#00FFE0&lᴅ&#3FE4EA&lᴇ&#7EC9F3&lʟ&#68B3F2&lᴛ&#519DF1&lᴀ Helmet' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol14/ecriverstonehelmet.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: head
        custom_armor: ecriverstonearmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - unbreaking:3
    lore:
      - ''
      - '            &#519DF1&l✶ &#00FFE0&lᴅ&#3FE4EA&lᴇ&#7EC9F3&lʟ&#68B3F2&lᴛ&#519DF1&lᴀ ✶'
      - '&#FFFF70&l✶ &#00FFE0&lᴘ&#0FF9E2&lʀ&#1EF2E4&lᴏ&#2CECE7&lᴛ&#3BE6E9&lᴇ&#4ADFEB&lᴄ&#59D9ED&lᴛ&#68D3F0&lᴏ&#77CCF2&lʀ &#7BC6F3&lᴏ&#76C1F3&lғ &#71BCF2&lᴛ&#6BB7F2&lʜ&#66B2F2&lᴇ &#61ADF2&lɢ&#5CA7F1&lᴏ&#56A2F1&lᴅ&#519DF1&ls &#FFFF70&l✶'
      - ''
```
