### ISSUE TITLE
Can remove `item_display` furniture in GriefPrevention without permission

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#4234]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mauriciooficial

### What happened?

when furniture is placed in item-display, anyone can remove it from their property even without permission.

this video shows on one side the furniture and armor support and on the other item-display:

video: https://youtu.be/xfJvSTO-ayo

configs bug:

```yaml
santacosmetic2:
  display_name: ''
  resource:
    material: PAPER
    generate: false
    model_path: santa_decoration/santacosmetic2
  behaviours:
    furniture:
      entity: item_display
      display_transformation:
        adjust_legacy_model: item_frame
```

config 2 no bug:

```yaml
santa_claus:
  display_name: ' '
  resource:
    material: PAPER
    generate: false
    model_path: santa_decoration/santa_claus
  behaviours:
    furniture:
      entity: item_frame
      solid: false
      hitbox:
        width: 1.0
        height: 1.0
        length: 1.0
```

itemsadder doesn't seem to be using the terrain protection in display item

### Steps to reproduce the issue

place furniture in item-display and place on the ground in a terrain protected by griefprevention

### Server version

Paper version 1.20.6-151

### ItemsAdder Version

ItemsAdder 4.0.5

### ProtocolLib Version

ProtocolLib 5.4.0-SNAPSHOT-736

### LoneLibs Version

LoneLibs 1.0.62

### Full Server Log

no error
