### ISSUE TITLE
Rename `apply_during_chunk_load_phase` to make it more clear

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4258]
Change this config entry to make it more clean.

From
```yml
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
```
To
```yml
  auto_apply:
    enabled: true
    before_join: true
    delay_ticks: 1
```
