### ISSUE TITLE
Negative custommodeldata bug?

### ISSUE THREAD

**Issue by malejkopecek** [PluginBugs/Issues-ItemsAdder#4267]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

I uploaded new textures, but unfortunately they don't load and it throws an error in the console when /iazip. I haven't found in any other plugin why it shouldn't load

### Steps to reproduce the issue

I don't know the way that create this issue

### Server version

Server is running on Purpur-1.21.1

### ItemsAdder Version

ItemsAdder version 4.0.6

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-738

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/Fv1Ngwd

### Error (optional)

```shell
19:46:16[INFO] | ResourcePack | [Pack] Generated resourcepack assets.
19:46:16[INFO] | ResourcePack | [Pack] Compressing resource_pack ...
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812479. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812478. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812477. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812476. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812475. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812474. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812473. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812472. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812471. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812470. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812469. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812468. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812467. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812466. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812465. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812464. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812463. Skipping.
19:46:16[ERROR] | ResourcePack | WTF? Negative custom model data found for material leather_horse_armor with custom model data -1352812462. Skipping.
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: danmaikold
items:
  candy_cane:
    display_name: "Candy Cane"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/candy_cane
      model_id: 2024001
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  candy_lamp_floor:
    display_name: "Candy Lamp Floor"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/candy_lamp_floor
      model_id: 2024002
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  candy_lamp_table:
    display_name: "Candy Lamp Table"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/candy_lamp_table
      model_id: 2024003
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  christmas_lights_string_large:
    display_name: "Christmas Ligts String Large"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/christmas_lights_string_large
      model_id: 2024004
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  christmas_lights_string_small:
    display_name: "Christmas Lights String Small"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/christmas_lights_string_small
      model_id: 2024005
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  christmas_tree:
    display_name: "Christmas Tree"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/christmas_tree
      model_id: 2024006
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
  ginger_lands_painting:
    display_name: "Ginger Lands Painting"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/ginger_lands_painting
      model_id: 2024007
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  gingerbread_chair:
    display_name: "Gingerbread Chair"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_chair
      model_id: 2024008
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1.2
      furniture_sit:
       sit_height: 0.85
  gingerbread_cookie:
    display_name: "Gingerbread Cookie"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_cookie
      model_id: 2024009
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 2
  gingerbread_fireplace:
    display_name: "Gingerbread Fireplace"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_fireplace
      model_id: 2024010
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 3
          height: 2
  gingerbread_snow_globe:
    display_name: "Gingerbread Snow Globe"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_snow_globe
      model_id: 2024011
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  gingerbread_stool:
    display_name: "Gingerbread Stool"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_stool
      model_id: 2024012
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
      furniture_sit:
       sit_height: 0.85
  gingerbread_table:
    display_name: "Gingerbread Table"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/gingerbread_table
      model_id: 2024013
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  nutcracker:
    display_name: "Nutcracker"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/nutcracker
      model_id: 2024014
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
  small_gift:
    display_name: "Small Gift"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/small_gift
      model_id: 2024015
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  tall_gift:
    display_name: "Tall Gift"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/tall_gift
      model_id: 2024016
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
  wide_gift:
    display_name: "Wide Gift"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/wide_gift
      model_id: 2024017
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  wreath:
    display_name: "Wreath"
    resource:
      generate: false
      material: LEATHER_HORSE_ARMOR
      model_path: furniture/christmas_furniture/wreath
      model_id: 2024018
    behaviours:
      furniture:
        solid: false
        entity: item_frame
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

In /ia it looks like this

![image](https://github.com/user-attachments/assets/289ae37c-7d61-4d3e-a135-8b6b8fc73db8)
