### ISSUE TITLE
Problem with baking in the furnace

### ISSUE THREAD

**Issue by pjindras** [PluginBugs/Issues-ItemsAdder#4273]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

When I bake an item, I get the same item -> it doesn't bake at all like it should and it throws me what I baked.

See video.
https://youtu.be/g4MgJt_ZVZk

### Steps to reproduce the issue

Try to bake it with my item.

### Server version

Paper build 132  Minecraft 1.21.1

### ItemsAdder Version

4.0.6

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/yjDzh1o

### Error (optional)

```shell
There is no error.
```

### Problematic items yml configuration file (optional)

```yaml
silveringot:
      ingredient:
        item: minerals_pack:silver
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 5
      cook_time: 400
      result:
        item: minerals_pack:silver_ingot
        amount: 1
    jadeingot:
      ingredient:
        item: minerals_pack:raw_jade
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 3
      cook_time: 300
      result:
        item: minerals_pack:jade_ingot
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/g4MgJt_ZVZk

**Comment by Andre601** [comment]
ItemsAdder returns the Ingredient as result, if it is unable to get the configured result item.
This means that it could be a configuration issue on your end.

Please test on a simple server setup with only ItemsAdder and its dependencies and see if the issue persîsts.

It could also help if you would share your configuration for wherever `minerals_pack:silver_ingot` is.

And finally: There is no error.
This is wrong. There are a ton of errors from various plugins, including ItemsAdder.

**Comment by pjindras** [comment]
Yes, but there is no error when the event happens. 
This is silver ingot config:

```
  silver_ingot:
    display_name: "&fStříbrný ingot"
    resource:
      material: PAPER
      generate: true
      textures:
        - silver_ingot.png

```
