### ISSUE TITLE
`use_cooldown` nbt(item component/MC 1.21.1+) got ignored at POTION/projectiles

### ISSUE THREAD

**Issue by minejango2** [PluginBugs/Issues-ItemsAdder#4279]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

The item's "use_cooldown" nbt got ignored.
For example, if put a projectile or food value such as ender_pearl or wind_charge in the material and put use_cooldown nbt value at nbt, take out the item and test it, can keep throwing or eating it without actually applying the cooldown.

(I checked item's nbt by /data merge entity @s SelectedItem, there was a use_cooldown nbt.)
(There are a few errors in the latest log, but they were simply my mistake in typing nbt incorrectly, and there were no error messages in the final test. (still uploded latest.log))
(I used Google Translator. sorry if my words were aggresive)

### Steps to reproduce the issue

item doesn't ignore use_cooldown nbt.

### Server version

Paper version 1.21.4-49-main@953f6f9 (2024-12-27T00:08:09Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.6

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-738

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/kohIM9F

### Problematic items yml configuration file (optional)

```yaml
c_windcharge:
    enabled: true
    display_name: '&ftest'
    specific_properties:
      potion:
        color: 3145556
    nbt: "{components: {\"minecraft:consumable\": {consume_seconds: 1f, sound: \"minecraft:block.glass.break\"}, \"minecraft:max_stack_size\":16, \"minecraft:use_cooldown\": {seconds: 10.0f}}}"
    resource:
      material: ender_pearl
      generate: true
      textures:
        - "minecraft:item/potion_overlay"
        - "minecraft:item/potion"
```

### Screenshots/Videos (you can drag and drop files or paste links)

![ezgif-7-247dba6763](https://github.com/user-attachments/assets/b2d8f4ca-cdc1-4cbb-b2de-22efe3791892)
