### ISSUE TITLE
`potion_type` not recognized in recipes

### ISSUE THREAD

**Issue by GLufano** [PluginBugs/Issues-ItemsAdder#4289]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

lufano

### What happened?

I have crafts that use water potions as ingredients that stopped working when I updated to 1.21.
Before, I used the instructions introduced in https://github.com/PluginBugs/Issues-ItemsAdder/issues/1694 since there is nothing on the WIKI about it, but now I can't do it anymore.
I need to reload several times to make it work in the furnace and in the craft it considers it to be an Uncraftable Potion and doesn't craft it at all.

### Steps to reproduce the issue

1. I configure the craft of the item that uses **POTION** with ItemsAdder;
2. I start the server;
3. I take the ingredients and place them in the correct position;
4. It returns nothing.
5. I check with `/iarecipe` and it says **UNCRAFTABLE POTION** as an ingredient.

### Server version

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-260 (MC: 1.20.2)

### ItemsAdder Version

4.0.6

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/R1tjYol

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: laboria
recipes:
  crafting_table:
    agua_filtrada:
      permission: cidadao.craft
      enabled: true
      pattern:
      - FFF
      - FAF
      - FFF
      ingredients:
        A:
          item: POTION
          potion_type: minecraft:water
        F: laboria:charcoal_fragments
      result:
        item: laboria:agua_filtrada
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

![javaw_G5CwTfgwRs](https://github.com/user-attachments/assets/e45eb2c6-84e6-4f24-aac2-b3fd5aca45aa)
![javaw_yQUur6mfOj](https://github.com/user-attachments/assets/8ded0867-45bf-46c0-9470-b85e62e43437)
