### ISSUE TITLE
craft attributes not working

### ISSUE THREAD

**Issue by ArkiSSTB** [PluginBugs/Issues-ItemsAdder#4305]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

arkadiolus

### Describe the solution you'd like

I need the ability to create custom recipes that ignore attributes such as item durability and enchantments.

### Is your feature request related to a problem?

In version IA 4.0.6, it's not possible to properly create custom recipes, as many features from earlier versions no longer work, such as shapeless and move_attributes. I created a recipe where you need to place a netherite sword and a new item, and it works fine. However, if the sword is not at full durability or if it is enchanted, the recipe doesn't work. I would like this feature to be available.

### Describe alternatives you've considered

Initially, I tried to craft my custom item through the smithing table, but I discovered that the game does not allow IA items to be placed in the smithing table.

### Additional context

```
    enderite_sword:
      permission: weaponus.crafts
      enabled: true
      pattern:
      - acb
      ingredients:
        a: blockus:enderite_template
        b: blockus:enderite
        c: netherite_sword
      result:
        item: weaponus:enderite_sword
        amount: 1
        move_attributes:
          enchants: true
          durability: true
```

![image](https://github.com/user-attachments/assets/68212982-ca15-431d-8130-57ac6405cb9a)
![image](https://github.com/user-attachments/assets/11828c12-0fc9-4e90-8c47-a5681f07a290)
