### ISSUE TITLE
Furnace sometimes outputs more materials than configured

### ISSUE THREAD

**Issue by ArkiSSTB** [PluginBugs/Issues-ItemsAdder#4306]
### Discord Username (optional)

arkadiolus

### What happened?

I added a recipe for the furnace. It should work so that if I smelt 1 ore, I get 1 ingot. The problem is that when I smelt the ore, it gives me 2 ingots. The "amount" parameter doesn't work at all. I tried changing the value to 5, but it still gives me 2 ingots.

### Steps to reproduce the issue

Smelt 1 item and produces 2

### Server version

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-80-c2294d7 (MC: 1.21.3)

### ItemsAdder Version

4.0.5

### ProtocolLib Version

5.4.0-SNAPSHOT-739

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/rzW95GG#L497

### Error (optional)

```shell
there are no errors
```

### Problematic items yml configuration file (optional)

```yaml
cooking:
    enderite_furn:
      permission: weaponus.crafts
      ingredient:
        item: blockus:enderite_ore
      machines:
      - FURNACE
      - BLAST_FURNACE
      cook_time: 200
      result:
        item: blockus:enderite_scrap
        amount: 1
```

### Other files, you can drag and drop them here to upload. (optional)

```
  enderite_scrap:
    display_name: Enderite Scrap
    resource:
      material: PAPER
      generate: true
      textures:
      - enderite_scrap.png
```

```
  enderite_ore:
    display_name: Enderite Ore
    resource:
      generate: true
      material: PAPER
      textures:
        - enderite_ore.png
    specific_properties:
      block:
        hardness: 4
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/91c47645-9045-4b92-8e99-78e88778028a)
