### ISSUE TITLE
Custom Tools Can't Break Custom Blocks

### ISSUE THREAD

**Issue by Litning11** [PluginBugs/Issues-ItemsAdder#4307]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Litning11

### What happened?

My custom tools aren't able to break custom blocks, vanilla tools work fine but custom ones won't. 

### Steps to reproduce the issue

Create a custom tool in ItemsAdder, create a custom block in ItemsAdder, add said tool to the block break whitelist. Try to break the block with the tool. 

### Server version

Purpur 1.21.4-2376-4bf1b98 (MC: 1.21.4)*

### ItemsAdder Version

4.0.6 (also tested with 4.0.7 Beta 5)

### ProtocolLib Version

5.4.0-SNAPSHOT-739

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/k0wdts0

### Problematic items yml configuration file (optional)

```yaml
compacted_dirt:
    display_name: '&eCompacted Dirt'
    resource:
      generate: true
      material: PAPER
      textures:
        - compacted/compacted_dirt.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        break_particles: ITEM
        sound:
          break:
            name: block.gravel.break
            pitch: 1
            volume: 1
          place:
            name: block.gravel.place
            pitch: 1
            volume: 1
          step:
            name: block.gravel.step
            pitch: 1
            volume: 1
          hit:
            name: block.gravel.hit
            pitch: 1
            volume: 1
        break_tools_whitelist:
          - SHOVEL
        hardness: 1```

```  oiled_masterwork_shovel:
    display_name: "&dMasterwork Shovel"
    resource:
      material: NETHERITE_SHOVEL
      generate: true
      textures:
      - tools/masterwork_shovel.png
    durability:
      max_custom_durability: 2945
    enchants:
      - DIG_SPEED:7
      - MENDING:1
      - DURABILITY:3```
```
