### ISSUE TITLE
Shapeless Recipes Do Not Work With Custom Items

### ISSUE THREAD

**Issue by Litning11** [PluginBugs/Issues-ItemsAdder#4308]
### Discord Username (optional)

Litning11

### What happened?

As title, creating shapeless recipes with custom IA items does not work at all, and no item can be created.

In contrast, shaped recipes with both vanilla and custom do work, and shapeless recipes with only vanilla items also works. So the issue here lies specifically with shapeless custom item recipes. 

### Steps to reproduce the issue

Create a shapeless recipe using custom items as an ingredient. Try to craft it. 

### Server version

Purpur 1.21.4-2376-4bf1b98 (MC: 1.21.4)*

### ItemsAdder Version

4.0.6 (also tested on the latest 4.0.7 beta)

### ProtocolLib Version

5.4.0-SNAPSHOT-739

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/k0wdts0

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: theriel
items:
  mysword:
    display_name: My Sword
    permission: mysword
    durability:
      max_custom_durability: 1324
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - item/mysword.png
  capturecube:
    display_name: Capture Cube
    permission: theriel.capturecube
    resource:
      material: PAPER
      generate: false
      model_path: minecraft:item/emerald
  capturecube-full:
    display_name: Capture Cube (Full)
    permission: theriel.capturecube
    resource:
      material: PAPER
      generate: false
      model_path: minecraft:item/diamond
recipes:
  crafting_table:
    capturecube:
      permission: theriel.capturecube
      enabled: true
      pattern:
      - XPX
      - PEP
      - XPX
      ingredients:
        P: POTION
        E: ENDER_PEARL
      result:
        item: theriel:capturecube
        amount: 1
    mysword:
      permission: theriel.capturecube
      enabled: true
      shapeless: true
      ingredients:
        A: theriel:capturecube
        B: theriel:capturecube-full
      result:
        item: theriel:mysword
        amount: 1

```
