### ISSUE TITLE
Armour not Applying Correct Attributes

### ISSUE THREAD

**Issue by Litning11** [PluginBugs/Issues-ItemsAdder#4325]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Litning11

### What happened?

It appears the custom armour set I made is not actually taking the attributes as it should. I have a set with similar setup to netherite, but during testing it does not perform as expected.

### Steps to reproduce the issue

All values tested with full crit hits to death. The numbers correspond to each part of the armour, with the first number being the armour value, and the second being the toughness value.

For example, in this set: Helmet: 3,3 Chestplate: 8,3 Leggings: 6,3 Boots: 2,3. The first number represents armour, and the second number represents armour toughnes. 

**Sword with 15 Attack Damage**
- Full enchanted neth armour (3,3 8,3 6,3, 3,3) 10 hits.
- Full enchanted custom armour (3,3 8,3 6,3 2,3) 3 hits

While the values being tested are not identical (difference of one armour point), they should not be dying that quick comparatively. 

### Server version

Purpur 1.21.4-2376-4bf1b98 (MC: 1.21.4)*

### ItemsAdder Version

4.0.6 (also tested on 4.0.7 beta builds). 

### ProtocolLib Version

5.4.0-SNAPSHOT-739

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/k0wdts0

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
:

  namespace: christmas

armors_rendering:

  nutcracker_armour:
    color: "#d60000"
    layer_1: armour_layers/nutcracker_layer_1
    layer_2: armour_layers/nutcracker_layer_2
    use_color: false

items:

  nutcracker_helmet:
    display_name: "&bNutcracker Hat"
    resource:
      generate: true
      textures:
      - armour/nutcracker_helmet
    durability:
      max_custom_durability: 363
    specific_properties:
      armor:
        slot: head
        custom_armor: nutcracker_armour
    attribute_modifiers:
      chest:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.5

  nutcracker_chestplate:
    display_name: "&bNutcracker Chestplate"
    resource:
      generate: true
      textures:
      - armour/nutcracker_chestplate
    durability:
      max_custom_durability: 528
    specific_properties:
      armor:
        slot: chest
        custom_armor: nutcracker_armour
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 0.5

  nutcracker_leggings:
    display_name: "&bNutcracker Leggings"
    resource:
      generate: true
      textures:
      - armour/nutcracker_leggings
    durability:
      max_custom_durability: 495
    specific_properties:
      armor:
        slot: legs
        custom_armor: nutcracker_armour
    attribute_modifiers:
      chest:
        armor: 6
        armorToughness: 3
        knockbackResistance: 0.5

  nutcracker_boots:
    display_name: "&bNutcracker Boots"
    resource:
      generate: true
      textures:
      - armour/nutcracker_boots
    durability:
      max_custom_durability: 429
    specific_properties:
      armor:
        slot: FEET
        custom_armor: nutcracker_armour
    attribute_modifiers:
      chest:
        armor: 2
        armorToughness: 3
        knockbackResistance: 0.5
```
