### ISSUE TITLE
ARMORS NOT RENDERING AFTER UPDATING TO 1.21

### ISSUE THREAD

**Issue by pmgalileo** [PluginBugs/Issues-ItemsAdder#4326]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

@gaalileo

### What happened?

After updating to 1.21, and then to 1.21.3, the armors no longer render. I'm using ItemsAdder 4.0.5 1.21.3 (Paper). Armors worked perfectly fine on 1.20.1, and I noticed this problem as early as 1.20.6. I've tried all the suggested fixes from Discord, but nothing has helped.

### Steps to reproduce the issue

create custom armor and then equip it

### Server version

Paper version 1.21.3-82-ver/1.21.3@5a60ffb (2024-12-23T19:10:30Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.5

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

/

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
generate-custom-armors-textures:
      vanilla: true
      optifine: true

  japan_armor_samurai:
    color: '#8c196f'
    layer_1: item/weapon/sets/japan_armor/samurai_armor_layer_1
    layer_2: item/weapon/sets/japan_armor/samurai_armor_layer_2
    use_color: false

  samurai_chestplate:
    display_name: Samurai Chestplate
    resource:
      generate: true
      textures:
      - item/weapon/sets/japan_armor/samurai_chestplate
    specific_properties:
      armor:
        slot: chest
        custom_armor: japan_armor_samurai
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/e1cb3609-ceb7-4d7d-94c3-ae6795964b0a)
