### ISSUE TITLE
Custom Guis we can use as custom crafting tables

### ISSUE THREAD

**Issue by Luckyyless** [PluginBugs/Issues-ItemsAdder#4331]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

making a gui, and a player could interact with it in any way. Example:

```
interactable_gui:
  name (for example: workbench_premium):
    type: CHEST / DOUBLE_CHEST
    name: <name of a gui>
    inside_crafts:
      result_slot: <number>
      slots:
        name (for example: slot_123):
          slot: 11
        name (for example: slot_456):
          slot: 13

And then, we can create a recipe usign this gui.

recipes:
  workbench_premium:
    name:
      pattern:
        slot_123:
          type: BONE_MEAL
        slot_456:
          type: myitems:sulfur
      result:
        item: myitems:gunpowder
        amount: 1


and, for example, I want to open it by right-clicking my furniture:


    events:
      placed_itemframe:
        interact:
          open_interactable_gui:
            name1:
              gui: workbench_premium
```

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

none

### Additional context

sorry for my english, I have a lot of mistakes probably :(
