### ISSUE TITLE
`play_sound` new property `stop_previous` to enable/disable sound stop before playing it

### ISSUE THREAD

**Issue by leogianfagna** [PluginBugs/Issues-ItemsAdder#4336]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

When performing fast clicks with using a custom item that has sounds, the sound is removed, making it very buggy and bad.
This get even worse with there is a lot of players with the item. Let's say there are two players with an item that plays a sound. If the sound is being played by one player, when the other player uses the item, the sound that was playing at the time **is interrupted and started by the other player**. Imagine if there are several players together trying to use this item, it is practically impossible to play any sound and it becomes extremely buggy.

I added videos of the bug.

### Steps to reproduce the issue

1. Create this item:
```yml
  ak47:
    enabled: true
    display_name: "Arma de fogo"
    lore:
      - "&7Use &eClique direito &7para atirar!"
    resource:
      material: ORANGE_DYE
      generate: false
      model_path: ak
    behaviours:
      gun:
        projectile: ausmilitar:pente_ak
    events:
      gun_shot:
        # This method fix the problem, but causes a large amount of spam in the server
        # execute_commands:
          # cmd1:
            # command: 'playsound ausmilitar:item.arma.tiro master @a ~ ~ ~ 1 0.7 1'
            # as_console: true
        play_sound:
          name: ausmilitar:item.arma.tiro # any sound here
          volume: 2
          pitch: 0.7
        play_effect:
          name: SMOKE
      gun_no_ammo:
        play_sound:
          name: ausmilitar:item.arma.municao
          volume: 1
          pitch: 1
```

2. Give the item for 2+ players
3. Ask them to spam clicks (to reproduce sounds)
4. See how buggy the sound gets.

### Server version

[19:34:16 INFO]: Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version

### ItemsAdder Version

[19:34:40 INFO]: ItemsAdder version 4.0.6

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-739

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/cOIwnj7 (nothing to see here)

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
ak47:
    enabled: true
    display_name: "Arma de fogo"
    lore:
      - "&7Use &eClique direito &7para atirar!"
    resource:
      material: ORANGE_DYE
      generate: false
      model_path: ak
    behaviours:
      gun:
        projectile: ausmilitar:pente_ak
    events:
      gun_shot:
        # This method fix the problem, but causes a large amount of spam in the server
        # execute_commands:
          # cmd1:
            # command: 'playsound ausmilitar:item.arma.tiro master @a ~ ~ ~ 1 0.7 1'
            # as_console: true
        play_sound:
          name: ausmilitar:item.arma.tiro # any sound here
          volume: 2
          pitch: 0.7
        play_effect:
          name: SMOKE
      gun_no_ammo:
        play_sound:
          name: ausmilitar:item.arma.municao
          volume: 1
          pitch: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

Problem (is more clear with more players but you can notice the interrupt sounds):

https://github.com/user-attachments/assets/752183de-c20c-4ff7-906d-3607f2375acf

What should be (used /playsound just to test, is impossible to use because of spam):

https://github.com/user-attachments/assets/0df03dbc-1633-4181-ad74-f03c58fd87d0

**Comment by Andre601** [comment]
Please test if this issue appears on a **bare-bones Server Setup** as described in https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187 to eliminate any possibility of other plugins causing this problem.

**Comment by LoneDev6** [comment]
A new `stop_previous` property will be added, it's defaulted to `true`.
```yml
      gun_no_ammo:
        play_sound:
          name: ausmilitar:item.arma.municao
          volume: 1
          pitch: 1
          stop_previous: false
```
