### ISSUE TITLE
Implement rate-limit on self-host

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4339]
Implement a rate-limit logic to avoid attacks without setting up a firewall.

**Comment by LoneDev6** [comment]
```yml
    self-host:
      enabled: false
# ....
      protection:
        rate_limit:
          enabled: true
          threshold: 3
          period_seconds: 2
          ban:
            enabled: true
            duration_minutes: 30
            fail_threshold: 5
        block_requests_not_from_game_client: false
```
