### ISSUE TITLE
The ia model is applied in Mythimobs, and the mob display name is not displayed

### ISSUE THREAD

**Issue by Ummio** [PluginBugs/Issues-ItemsAdder#4341]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

yueful

### What happened?

Using the IA model in Mythimobs
Mobs displayname is unable to display
If the IA model is not used, it can be displayed normally

### Steps to reproduce the issue

.

### Server version

[17:25:46 INFO]: Checking version, please wait...
[17:25:47 INFO]: This server is running Gale version 1.21.4-DEV-ver/1.21.4@e11a842 (2025-01-15T11:14:33Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
Unknown version

### ItemsAdder Version

[17:26:05 INFO]: ItemsAdder version 4.0.7
[17:26:05 INFO]: Customized Minecraft without client mods!
[17:26:05 INFO]: Website: devs.beer
[17:26:05 INFO]: Author: LoneDev

### ProtocolLib Version

[17:26:18 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-739
[17:26:18 INFO]: Provides read/write access to the Minecraft protocol.
[17:26:18 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:26:30 INFO]: LoneLibs version 1.0.63
[17:26:30 INFO]: Collection of libs used by my plugins
[17:26:30 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/xRzPAg5

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
MythicMobs
mob_minotaur_normal_1_lv2:
  Type: husk
  Display: '[2]牛头人'
  Health: 20
  Damage: 4
  Armor: 0
  Options:
    KnockbackResistance: 0.1
    MovementSpeed: 0.2
    PreventRandomEquipment: true
  Skills:
  - customentity{model=mob_minotaur:normal_1} @self ~onSpawn
  - cmd{c=erank add <trigger.name> 1 -s} @trigger ~ondeath
  - customentity{attack=攻击} @self ~onAttack
  - customentity{walk=走路} @self ~onAttack
  - customentity{idie=待机} @self ~onAttack


ItemsAdder

info:
  namespace: mob_minotaur
entities:
  normal_1:
    display_name: "牛头人"
    type: ZOMBIE
    model_folder: entity/normal_1
```
