### ISSUE TITLE
ExecutableItems 7.25.2.9 and SCore 5.25.2.9 compatibility

### ISSUE THREAD

**Issue by ChiefWarPig** [PluginBugs/Issues-ItemsAdder#4349]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

warpig1163

### What happened?

Ssomar has updated the API in executable ites breaking the compatability to import Executable Items into Items Adder. This causes players to be unable to join the server. 

### Steps to reproduce the issue

1. Install the latest versions of IA & Executable Items. 
2. Create an item in Executable Items and then add to the IA Config the item import syntax as bellow:  
executableitem:
      id: chronicles_crate
3. Start the server and try to join

### Server version

This server is running Paper version 1.21.4-126-main@fb5b173 (2025-01-25T20:51:32Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-120-30046e0 (MC: 1.21.4)

### ItemsAdder Version

ItemsAdder version 4.0.7

### ProtocolLib Version

ProtocolLib Version 5.4.0-SNAPSHOT-739

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/WHgOTiC#L1168

### Error (optional)

```shell
[12:08:56] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[12:08:56] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/ssomar/score/api/ExecutableItemsAPI
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//dev.lone.itemsadder.Core.OtherPlugins.ExecutableItems.ExecutableItemsHook.getExecutableItem(SourceFile:10)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.lq.hS(SourceFile:1041)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.ag.b(SourceFile:801)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.ag.c(SourceFile:647)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.afk.d(SourceFile:130)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.ag.a(SourceFile:641)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//itemsadder.m.ag.l(SourceFile:296)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//dev.lone.itemsadder.Main.iZ(SourceFile:509)
[12:08:56] [Server thread/WARN]: 	at ItemsAdder_4.0.7.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:423)
[12:08:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:284)
[12:08:56] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[12:08:56] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[12:08:56] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[12:08:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:656)
[12:08:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:605)
[12:08:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
[12:08:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
[12:08:56] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322)
[12:08:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163)
[12:08:56] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
[12:08:56] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[12:08:56] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.ssomar.score.api.ExecutableItemsAPI
[12:08:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[12:08:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[12:08:56] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[12:08:56] [Server thread/WARN]: 	... 21 more
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: elitecreatures
armors_rendering:
  chronicles_set:
    color: '#8c1965'
    layer_1: chronicles_set/chronicles_armor_layer_1
    layer_2: chronicles_set/chronicles_armor_layer_2
    use_color: false
items:
  chronicles_helmet:
    display_name: Chronicles Helmet
    resource:
      generate: true
      textures:
      - chronicles_set/chronicles_helmet.png
    specific_properties:
      armor:
        slot: head
        custom_armor: chronicles_set
  chronicles_chestplate:
    display_name: Chronicles Chestplate
    resource:
      generate: true
      textures:
      - chronicles_set/chronicles_chestplate.png
    specific_properties:
      armor:
        slot: chest
        custom_armor: chronicles_set
  chronicles_leggings:
    display_name: Chronicles Leggings
    resource:
      generate: true
      textures:
      - chronicles_set/chronicles_leggings.png
    specific_properties:
      armor:
        slot: legs
        custom_armor: chronicles_set
  chronicles_boots:
    display_name: Chronicles Boots
    resource:
      generate: true
      textures:
      - chronicles_set/chronicles_boots.png
    specific_properties:
      armor:
        slot: FEET
        custom_armor: chronicles_set
  chronicles_axe:
    display_name: Axe
    permission: elitecreatures.use
    resource:
      material: IRON_AXE
      generate: false
      model_path: chronicles_set/chronicles_axe
  chronicles_battle_axe:
    display_name: Battle Axe
    permission: elitecreatures.use
    resource:
      material: IRON_AXE
      generate: false
      model_path: chronicles_set/chronicles_battle_axe
  chronicles_blade:
    display_name: Blade
    permission: elitecreatures.use
    resource:
      material: IRON_SWORD
      generate: false
      model_path: chronicles_set/chronicles_blade
  chronicles_bow:
    display_name: Bow
    permission: elitecreatures.use
    resource:
      material: BOW
      generate: false
      model_path: chronicles_set/chronicles_bow
  chronicles_chest:
    display_name: Chest
    permission: elitecreatures.use
    executableitem:
      id: chronicles_crate
    resource:
      material: PAPER
      generate: false
      model_path: chronicles_set/chronicles_chest
    behaviours:
      furniture:
        entity: armor_stand
        small: true
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 1
          height: 1
          width_offset: 0.5
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.5
  chronicles_halberd:
    display_name: Halberd
    permission: elitecreatures.use
    resource:
      material: IRON_SWORD
      generate: false
      model_path: chronicles_set/chronicles_halberd
  chronicles_hat:
    display_name: Hat
    permission: elitecreatures.use
    resource:
      material: PAPER
      generate: false
      model_path: chronicles_set/chronicles_hat
    behaviours:
      hat: true
  chronicles_hoe:
    display_name: Hoe
    permission: elitecreatures.use
    resource:
      material: IRON_HOE
      generate: false
      model_path: chronicles_set/chronicles_hoe
  chronicles_key:
    display_name: Key
    permission: elitecreatures.use
    resource:
      material: PAPER
      generate: false
      model_path: chronicles_set/chronicles_key
  chronicles_pickaxe:
    display_name: Pickaxe
    permission: elitecreatures.use
    resource:
      material: IRON_PICKAXE
      generate: false
      model_path: chronicles_set/chronicles_pickaxe
  chronicles_fishing_rod:
    display_name: Fishing Rod
    permission: elitecreatures.use
    resource:
      material: FISHING_ROD
      generate: false
      model_path: chronicles_set/chronicles_fishing_rod
  chronicles_shield:
    display_name: Shield
    permission: elitecreatures.use
    resource:
      material: SHIELD
      generate: false
      model_path: chronicles_set/chronicles_shield
  chronicles_shovel:
    display_name: Shovel
    permission: elitecreatures.use
    resource:
      material: IRON_SHOVEL
      generate: false
      model_path: chronicles_set/chronicles_shovel
  chronicles_spear:
    display_name: Spear
    permission: elitecreatures.use
    resource:
      material: IRON_SWORD
      generate: false
      model_path: chronicles_set/chronicles_spear
  chronicles_staff:
    display_name: Staff
    permission: elitecreatures.use
    resource:
      material: IRON_SWORD
      generate: false
      model_path: chronicles_set/chronicles_staff
  chronicles_sword:
    display_name: Sword
    permission: elitecreatures.use
    resource:
      material: IRON_SWORD
      generate: false
      model_path: chronicles_set/chronicles_sword
  chronicles_wings:
    display_name: Wings
    permission: elitecreatures.use
    resource:
      material: PAPER
      generate: false
      model_path: chronicles_set/chronicles_wings
  chronicles_wings_self:
    display_name: Wings Self
    permission: elitecreatures.use
    resource:
      material: PAPER
      generate: false
      model_path: chronicles_set/chronicles_wings_self
```

### Other files, you can drag and drop them here to upload. (optional)

EI item config: 
name: '#2400d6C#3410c8h#4320bar#5330ado#62409fn#725091i#816083c#917076l#a07f68e#b08f5as
  #bf9f4cC#cfaf3eh#debf31e#eecf23s#fddf15t'
lore:
- §e-------------------------
- §5Decorative cover for chests
- §e-------------------------
material: PAPER
glow: false
disableStack: false
keepItemOnDeath: false
canBeUsedOnlyByTheOwner: false
cancelEventIfNotOwner: false
onlyOwnerBlackListedActivators: []
storeItemInfo: false
unbreakable: false
usage: 1
usageLimit: -1
isDurabilityBasedOnUsage: false
cancelEventIfNoPermission: false
whitelistedWorlds: []
recognitions: []
keepDefaultAttributes: true
customModelData: 10007
config_5: true
config_update: true
ignoreKeepDefaultAttributesFeature: true
nbt:
  '0':
    key: itemsadder
    type: COMPOUND
    value:
      nbt:
        '0':
          key: namespace
          type: STRING
          value: elitecreatures
        '1':
          key: id
          type: STRING
          value: chronicles_chest
dropOptions:
  glowDrop: false
  glowDropColor: WHITE
  displayNameDrop: false
hiders:
  hideEnchantments: false
  hideUnbreakable: false
  hideAttributes: false
  hidePotionEffects: false
  hideUsage: true
  hideDestroys: false
  hidePlacedOn: false
  hideDye: false
  hideArmorTrim: false
enchantments: {}
giveFirstJoin:
  giveFirstJoin: false
  giveFirstJoinAmount: 1
  giveFirstJoinSlot: 0
restrictions: {}
variables: {}
displayConditions:
  playerConditions: {}
  worldConditions: {}
  itemConditions: {}
  placeholdersConditions: {}
  enableFeature: false
food:
  nutrition: 1
  saturation: 1
  isMeat: false
  canAlwaysEat: false
  eatSeconds: 1
attributes: {}
activators:
  activator0:
    name: '&eActivator'
    option: PLAYER_ALL_CLICK
    typeTarget: NO_TYPE_TARGET
    usageModification: 0
    cancelEvent: false
    noActivatorRunIfTheEventIsCancelled: false
    silenceOutput: false
    autoUpdateItem: true
    updateName: true
    updateLore: true
    updateDurability: true
    updateAttributes: true
    updateEnchants: true
    updateCustomModelData: true
    updateArmorSettings: true
    cooldownOptions:
      cooldown: 0
      isCooldownInTicks: false
      cooldownMsg: '&cYou are in cooldown ! &7(&e%time_H%&6H &e%time_M%&6M &e%time_S%&6S&7)'
      displayCooldownMessage: true
      cancelEventIfInCooldown: false
      pauseWhenOffline: false
      pausePlaceholdersConditions: {}
    globalCooldownOptions:
      cooldown: 0
      isCooldownInTicks: false
      cooldownMsg: '&cYou are in cooldown ! &7(&e%time_H%&6H &e%time_M%&6M &e%time_S%&6S&7)'
      displayCooldownMessage: true
      cancelEventIfInCooldown: false
      pauseWhenOffline: false
      pausePlaceholdersConditions: {}
    otherEICooldowns: {}
    requiredItems: {}
    requiredExecutableItems: {}
    requiredMagics: {}
    detailedSlots:
    - -1
    commands: []
    playerConditions: {}
    worldConditions: {}
    itemConditions: {}
    customConditions:
      ifNeedPlayerConfirmationCancel: false
    placeholdersConditions: {}
    variablesModification: {}
