### ISSUE TITLE
`consumable` and `food` attribute revamp - add 1.21.2+ features

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4354]
This was first introduced with that task https://github.com/PluginBugs/Issues-ItemsAdder/issues/3902 , but Mojang introduces new features and changes to the `food` attribute separating it into `food` and `consumable`.
I will implement the new `consumable` features (use [this useful tool](https://www.gamergeeks.net/apps/minecraft/give-command-generator) to test).

Note: I must also implement #2247 as soon as possible because these properties are in the item NBT itself, so updating them in the config won't automatically apply the change on already crafted items in the world.

In the meantime I will implement a `/iaitem <update>` command to force update of items #4363 .

Example:
```yml
  test_consumable_food:
    enabled: true
    display_name: test_consumable_food
    resource:
      generate: false
      model_path: minecraft:item/emerald
      material: STONE
    consumable:
      animation: eat
      can_always_eat: true
      eat_seconds: 3
      nutrition: 1
      saturation: 0.5
      sound: block.anvil.step
      particles: false
      effects:
        play_sound_1:
          sound: minecraft:block.anvil.place
        apply_status_effects:
          effects:
            effect_1:
              potion: ABSORPTION
              duration: 12000
              amplifier: 0
        teleport_randomly:
          diameter: 5
```
