### ISSUE TITLE
length is longer than maximum allowed (17>16)

### ISSUE THREAD

**Issue by SchlumpfkopfYT** [PluginBugs/Issues-ItemsAdder#4356]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

SchlumpfkopfYT

### What happened?

Whenever there is a joint or even if it is short, igenwann appears (the received string length is longer than maximum allowed (17>16))

### Steps to reproduce the issue

I can hardly tell you that because it keeps coming back 

### Server version

1.16.5

### ItemsAdder Version

3.6.4-Release-3

### ProtocolLib Version

5.4.0-Snapshot-739

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/A22Yypf

### Error (optional)

```shell
/
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: betterranks
font_images:
  owner:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "owner.png"
    scale_ratio: 9
    y_position: 8
  coowner:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "coowner.png"
    scale_ratio: 9
    y_position: 8
  leitung:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "leitung.png"
    scale_ratio: 9
    y_position: 8
  admin:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "admin.png"
    scale_ratio: 9
    y_position: 8
  devplus:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "devplus.png"
    scale_ratio: 9
    y_position: 8
  supplus:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "supplus.png"
    scale_ratio: 9
    y_position: 8
  builderplus:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "builderplus.png"
    scale_ratio: 9
    y_position: 8
  dev:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "dev.png"
    scale_ratio: 9
    y_position: 8
  builder:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "builder.png"
    scale_ratio: 9
    y_position: 8
  sup:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "sup.png"
    scale_ratio: 9
    y_position: 8
  t-builder:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "t-builder.png"
    scale_ratio: 9
    y_position: 8
  t-dev:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "t-dev.png"
    scale_ratio: 9
    y_position: 8
  t-sup:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "t-sup.png"
    scale_ratio: 9
    y_position: 8
  content:
    permission: "betterranks.player"
    show_in_gui: true
    suggest_in_command: false
    path: "content.png"
    scale_ratio: 9
    y_position: 8
  youtube:
    permission: "betterranks.player"
    show_in_gui: true
    suggest_in_command: false
    path: "youtube.png"
    scale_ratio: 9
    y_position: 8
  vip:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "vip.png"
    scale_ratio: 9
    y_position: 8
  p:
    permission: "betterranks.p"
    show_in_gui: true
    suggest_in_command: false
    path: "player.png"
    scale_ratio: 9
    y_position: 8
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1333883982999191613/1333883983498575914/Screenshot_2025-01-28_193547.png?ex=679a83c4&is=67993244&hm=b95bbc6f5466049adb3cbd3ae5c28da38be7b0d22018512c72590362440b94ec&
