### ISSUE TITLE
Behaviour:hat durability - custom durability

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#4364]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

Hey there!
You've certainly heard about 3D helmets! These helmets are usually done for cosmetics only.
I want to change this, I want to use them as normal piece of armour.

Durability for these custom helmets can work based on NBT so no need to save them separately!

```yml
info:
  namespace: my_items
items:
  my_simple_helmet:
    display_name: my_helmet_simple_helmet
    permission: my_helmet_simple
    behaviour: hat
    resource:
      material: paper
      generate: false
      model_path: helmets/my_threed_helmet
    attribute_modifiers:
      head:
        armor: 9
        armorToughness: 1
```

This is simple config of it, but for now, 4.0.7, durability doesn't change its behaviour, Minecraft doesn't recognize its durability and I see it as a big disadvantage as it can better this project up!

### Is your feature request related to a problem?

A bit, yes, described above.

### Describe alternatives you've considered

:| Didn't?
