### ISSUE TITLE
Rename `interact.left` to `interact_left` to avoid excessive nesting

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4367]
Before
```yml
    events:
      interact:
        left:
          damage_entity:
            damage: 5
          decrement_amount:
            amount: 1
        right:
          explosion:
            power: 1
            fire: true
            break_blocks: false
```

After
```yml
    events:
      interact_left:
        damage_entity:
          damage: 5
        decrement_amount:
          amount: 1
      interact_right:
        explosion:
          power: 1
          fire: true
          break_blocks: false
```

This allows for a better reading of long list of events, because `interact` wouldn't be visible until you scroll up.
This also reduces the nesting, which is known to cause indentation mistakes.
