### ISSUE TITLE
Worldguardflag has no effect

### ISSUE THREAD

**Issue by Leahcimkrob** [PluginBugs/Issues-ItemsAdder#4372]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

bloody_mind

### What happened?

We have Worldguard and plotsquared on our server. Vehicles can also be removed with plot boundaries. The Worldguard flag ia-vehicle-personal-remove and ia-vehicle-remove have no effect.

Regardless of whether both are True or False, the vehicles can still be removed.

We noticed it since 4.0.7.

### Steps to reproduce the issue

we set the ia-vehicle-remove to false and players can still remove cars

### Server version

> version
[17:45:05 INFO]: Checking version, please wait...
[17:45:06 INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-131-84281ce (MC: 1.21.1)

### ItemsAdder Version

> version itemsadder
[17:45:47 INFO]: ItemsAdder version 4.0.7
[17:45:47 INFO]: Customized Minecraft without client mods!
[17:45:47 INFO]: Website: devs.beer
[17:45:47 INFO]: Author: LoneDev

### ProtocolLib Version

> version protocollib
[17:46:27 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-735
[17:46:27 INFO]: Provides read/write access to the Minecraft protocol.
[17:46:27 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version lonelib
[17:46:51 INFO]: LoneLibs version 1.0.63
[17:46:51 INFO]: Collection of libs used by my plugins
[17:46:51 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/M1s6zd6

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vehicles
items:
  mm_tractor:
    display_name: <gradient:#FF0F73:#FF3DE1><bold>Traktor
    resource:
      material: PAPER
      generate: false
      model_id: 3500000
      model_path: mm_tractor
    behaviours:
      vehicle:
        small: true
        fixed_rotation: false
        sit_height: 2.5
        step_height: 0.5
        hitbox:
          length: 3
          width: 3
          height: 3
        speed:
          drive: 0.2
          jump: 0.2
          fly: 0
        fuel:
          start: 250
          max: 500
          items:
            "vehicles:fuel_diesel": 10
        smoke:
          amount: 25
          offset:
            x: 0.2
            y: 2.0
            z: 1.2     
  mm_train:
    display_name: <gradient:#2BFF63:#28FBFF><bold>Zug
    resource:
      material: PAPER
      generate: false
      model_id: 3500001
      model_path: mm_train
    behaviours:
      vehicle:
        small: true
        fixed_rotation: false
        sit_height: 0
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 2
        speed:
          drive: 0.5
          jump: 0.3
          fly: 0
        fuel:
          start: 300
          max: 600
          items:
            COAL: 1
            CHARCOAL: 1
            COAL_BLOCK: 9
        smoke:
          amount: 50
          offset:
            x: 0
            y: 1.8
            z: 1.2            
  mm_lorry:
    display_name: <gradient:#FF2E23:#FF9D0A><bold>LKW
    resource:
      material: PAPER
      generate: false
      model_id: 3500002
      model_path: mm_lorry
    behaviours:
      vehicle:
        small: true
        fixed_rotation: false
        sit_height: -0.8
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 2
        speed:
          drive: 0.8
          jump: 0.3
          fly: 0
        fuel:
          start: 400
          max: 800
          items:
            "vehicles:fuel_diesel": 10     
        smoke:
          amount: 15
          offset:
            x: -0.3
            y: 0.2
            z: -2.0                     
  mm_truck:
    display_name: <gradient:#6546FF:#D96DFF><bold>Pickup-Truck
    resource:
      material: PAPER
      generate: false
      model_id: 3500003
      model_path: mm_truck
    behaviours:
      vehicle:
        small: true
        fixed_rotation: false
        sit_height: 0
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 2
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 10
          offset:
            x: 0.0
            y: 0.2
            z: -1.2            
  enegal_vocho_red:
    display_name: <red><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500004
      model_path: enegal_vocho_red
    behaviours:
      vehicle:
        small: false
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0                
  enegal_vocho_orange:
    display_name: <#EF5700><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500005
      model_path: enegal_vocho_orange
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_yellow:
    display_name: <yellow><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500006
      model_path: enegal_vocho_yellow
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_green:
    display_name: <green><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500007
      model_path: enegal_vocho_green
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_light_blue:
    display_name: <#0DA7F0><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500008
      model_path: enegal_vocho_light_blue
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_blue:
    display_name: <blue><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500009
      model_path: enegal_vocho_blue
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_pink:
    display_name: <#CC003D><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500010
      model_path: enegal_vocho_pink
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_purple:
    display_name: <#A009CD><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500011
      model_path: enegal_vocho_purple
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_gray:
    display_name: <gray><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500012
      model_path: enegal_vocho_gray
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_white:
    display_name: <white><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500013
      model_path: enegal_vocho_white
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  enegal_vocho_black:
    display_name: <#353535><bold>VW Beetle
    resource:
      material: PAPER
      generate: false
      model_id: 3500014
      model_path: enegal_vocho_black
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1.0
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.5
          jump: 0.3
          fly: 0
        fuel:
          start: 150
          max: 300
          items:
            "vehicles:fuel_benzin": 25
        smoke:
          amount: 20
          offset:
            x: 0.2
            y: 0.0
            z: -3.0               
  sebxter_tesla_cybertruck:
    display_name: <gray><bold>Tesla Cybertruck
    resource:
      material: PAPER
      generate: false
      model_id: 3500015
      model_path: sebxter_tesla_cybertruck
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -1
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.8
          jump: 0.3
          fly: 0
        fuel:
          start: 250
          max: 600
          items:
            "vehicles:fuel_battery_red": 150
            "vehicles:fuel_battery_yellow": 150
            "vehicles:fuel_battery_green": 150
            "vehicles:fuel_battery_blue": 150
  train_basic_coaster_cart:
    display_name: <gradient:#2BFF63:#28FBFF><bold>Zug
    resource:
      material: PAPER
      generate: false
      model_id: 3500016
      model_path: train_basic_coaster_cart
    behaviours:
      vehicle:
        small: false
        fixed_rotation: false
        sit_height: -2.0
        step_height: 0.5
        hitbox:
          length: 3
          width: 2
          height: 2
        speed:
          drive: 0.5
          jump: 0.3
          fly: 0
        fuel:
          start: 600
          max: 1200
          items:
            COAL: 1
            CHARCOAL: 1
            COAL_BLOCK: 9
        smoke:
          amount: 200
          offset:
            x: 0.02
            y: 1.8
            z: 2.25             
  train_basic_coaster_head:
    display_name: <gradient:#2BFF63:#28FBFF><bold>Zug
    resource:
      material: PAPER
      generate: false
      model_id: 3500017
      model_path: train_basic_coaster_head
    behaviours:
      vehicle:
        small: false
        fixed_rotation: false
        sit_height: -1.5
        step_height: 0.5
        hitbox:
          length: 3
          width: 2
          height: 2
        speed:
          drive: 0.1
          jump: 0.3
          fly: 0     
  demon_train:
    display_name: <gradient:#2BFF63:#28FBFF><bold>Zug
    resource:
      material: PAPER
      generate: false
      model_id: 3500018
      model_path: demon_train
    behaviours:
      vehicle:
        small: false
        fixed_rotation: false
        sit_height: 1.0
        step_height: 0.5
        hitbox:
          length: 3
          width: 2
          height: 2
        speed:
          drive: 0.5
          jump: 0.3
          fly: 0
        fuel:
          start: 600
          max: 1200
          items:
            COAL: 1
            CHARCOAL: 1
            COAL_BLOCK: 9
        smoke:
          amount: 200
          offset:
            x: 0.45
            y: 3.4
            z: 5.2   
  demon_train_carriage:
    display_name: <gradient:#2BFF63:#28FBFF><bold>Zug
    resource:
      material: PAPER
      generate: false
      model_id: 3500019
      model_path: demon_train_carriage
    behaviours:
      vehicle:
        small: false
        fixed_rotation: false
        sit_height: 0.0
        step_height: 0.5
        hitbox:
          length: 3
          width: 2
          height: 2
        speed:
          drive: 0.1
          jump: 0.3
          fly: 0 
  pontiac_gto_1967:
    display_name: <gray><bold>Pontiac GTO 1967
    resource:
      material: PAPER
      generate: false
      model_id: 3500020
      model_path: pontiac_gto_1967
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -2
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 1.8
          jump: 0.3
          fly: 0
        fuel:
          start: 250
          max: 600
          items:
            "vehicles:fuel_benzin": 150
        smoke:
          amount: 20
          offset:
            x: 0.0
            y: 0.0
            z: -4.5 
  pontiac_gto_1967_fire:
    display_name: <gradient:#D9AB2F:#BA2401><bold>Pontiac GTO 1967
    lore:
      - "<dark_gray>- <gray>Lackierung: <gradient:#DD350C:#FF6600><bold>FIRE"
    resource:
      material: PAPER
      generate: false
      model_id: 3500021
      model_path: pontiac_gto_1967_fire
    behaviours:
      vehicle:
        fixed_rotation: false
        small: false
        sit_height: -2
        step_height: 0.5
        hitbox:
          length: 3
          width: 1
          height: 1
        speed:
          drive: 2.2
          jump: 0.3
          fly: 0
        fuel:
          start: 350
          max: 900
          items:
            "vehicles:fuel_benzin": 200
        smoke:
          amount: 30
          offset:
            x: 0.0
            y: 0.0
            z: -4.5                                                             
  fuel_diesel:
    display_name: <#1A4899><bold>Diesel
    model_id: 3500020
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/diesel
  fuel_benzin:
    display_name: <#16777031><bold>Benzin
    model_id: 3500021
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/benzin
  fuel_battery_red:
    display_name: <red><bold>Batterie
    model_id: 3500022
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/battery_red
  fuel_battery_yellow:
    display_name: <yellow><bold>Batterie
    model_id: 3500023
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/battery_yellow
  fuel_battery_green:
    display_name: <green><bold>Batterie
    model_id: 3500024
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/battery_green
  fuel_battery_blue:
    display_name: <blue><bold>Batterie
    model_id: 3500025
    resource:
      material: golden_horse_armor
      generate: false
      model_path: fuel/battery_blue
recipes:
  crafting_table:
    fuel_diesel:
      enabled: true
      pattern:
      - KHD
      - RBR
      - KHD
      ingredients:
        K: COAL_BLOCK
        H: DARK_OAK_LOG
        D: DIRT
        R: REDSTONE_BLOCK
        B: BLACKSTONE
      result:
        item: vehicles:fuel_diesel
        amount: 1
    fuel_benzin:
      enabled: true
      pattern:
      - KHD
      - RCR
      - KHD
      ingredients:
        K: COAL_BLOCK
        H: DARK_OAK_LOG
        D: DIRT
        R: REDSTONE_BLOCK
        C: COBBLED_DEEPSLATE
      result:
        item: vehicles:fuel_benzin
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/832a9baa-101e-43c0-9f97-ef1dce8f17d2)
