### ISSUE TITLE
Fishing rod auto generating ingoring _cast texture

### ISSUE THREAD

**Issue by EagL3-GIT** [PluginBugs/Issues-ItemsAdder#4377]
### What happened?

When trying to make custom fishing rod texture, the cast part is being ignored and it shows only the main fishing rod.
[EDIT: And same for 3D textures]
It has to be a bug cause it works just fine for bows.

### Steps to reproduce the issue

```
  slime_fishing_rod:
    display_name: "Slime Fishing Rod"
    resource:
      material: FISHING_ROD
      model_id: 10011
      generate: true
      textures:
      - tools/slime_fishing_rod.png
```

![Image](https://github.com/user-attachments/assets/54547606-404f-4e36-b0c5-eeef00d1b968)

```
  ragnarok_fishing_rod:
    display_name: "Ragnarok Fishing Rod"
    permission: tools.ragnarok_fishing_rod
    resource:
      model_id: 10004
      material: FISHING_ROD
      generate: false
      model_path: not_generated/ragnarok_fishing_rod
```

![Image](https://github.com/user-attachments/assets/60c4ead5-2f55-4398-8988-d2af1a6d0255)
![Image](https://github.com/user-attachments/assets/bc942917-72d0-4b20-8e12-51253050dea5)

### Server version

This server is running Paper version 1.21.4-133-main@54b2e9d (2025-01-29T01:50:53Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.7

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-739

### LoneLibs Version

LoneLibs version 1.0.63

![Image](https://github.com/user-attachments/assets/07f23996-e1dd-4944-bc8c-0610464f2409)
