### ISSUE TITLE
cant reload

### ISSUE THREAD

**Issue by JuliusH1** [PluginBugs/Issues-ItemsAdder#4384]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

juliush_

### What happened?

if i reload or zip /iazip /iareload this happens 

[06:10:47 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String, boolean)" because "this.Py" is null
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.aen.k(SourceFile:153)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.lq.hS(SourceFile:89)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.ag.b(SourceFile:801)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.ag.c(SourceFile:647)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.afk.d(SourceFile:130)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.ag.a(SourceFile:641)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.ri.b(SourceFile:89)
[06:10:47 WARN]:        at ItemsAdder_4.0.7.jar//itemsadder.m.ri.onCommand(SourceFile:63)
[06:10:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:10:47 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[06:10:47 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[06:10:47 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[06:10:47 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[06:10:47 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[06:10:47 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[06:10:47 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[06:10:47 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451)
[06:10:47 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:358)
[06:10:47 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[06:10:47 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:340)
[06:10:47 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226)
[06:10:47 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200)
[06:10:47 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[06:10:47 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[06:10:47 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[06:10:47 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543)
[06:10:47 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354)
[06:10:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:10:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Steps to reproduce the issue

idk i just updated itemsadder and now it doesnt work i used to have beta-4 on the server and it worked but now it gets stuck at zipping items from fantasy_weapons which is the biggest folder

### Server version

[06:16:22 INFO]: Checking version, please wait...
[06:16:22 INFO]: Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
* You are running the latest version
Previous: 1.21.3-2358-16ce24a (MC: 1.21.3)

### ItemsAdder Version

ItemsAdder version 4.0.7

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-731

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/s5SRhQa

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
fantasy_weapons.yml:

info:
  namespace: fantasy_weapons

items:
  amethyst_greatsword:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/amethyst_greatsword
  phantomguard_greatsword:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/phantomguard_greatsword
  heavenly_partisan:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/heavenly_partisan
  valhakyra:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/valhakyra
  black_iron_greatsword:
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: item/black_iron_greatsword
  phantomguard_partisan:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/phantomguard_partisan
  talonbrand:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/talonbrand
  windreaper:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/windreaper
  crystal_frostblade:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/crystal_frostblade
  lycanbane:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/lycanbane
  grand_claymore:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/grand_claymore
  solstice:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/solstice
  gloomsteel_katana:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/gloomsteel_katana
  gloomsteel_knife:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/gloomsteel_knife
  vesper:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/vesper
  calamity_blade:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/calamity_blade
  ancient_greatslab:
    resource:
      material: MACE
      generate: false
      model_path: item/ancient_greatslab
  demons_blood_blade:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/demons_blood_blade
  demonslayers_greatsword:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/demonslayers_greatsword
  moonlight:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/moonlight
  vengeance_blade:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/vengeance_blade
  oculus:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/oculus
  azure_greatsword:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/azure_greatsword
  azure_dagger:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/azure_dagger
  azure_sabre:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/azure_sabre
  dragon_sabre:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/dragon_sabre
  spider_sword:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/spider_sword
  runic_piercer:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/runic_piercer
  demonic_sword:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/demonic_sword
  nature_sword:
    resource:
      material: STONE_SWORD
      generate: false
      model_path: item/nature_sword
  vindicator:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/vindicator
  black_iron_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/black_iron_greataxe
  viridian_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/viridian_greataxe
  crescent_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/crescent_greataxe 
  berserkers_greataxe:
  template: true
  resource: 
    material: IRON_AXE
    generate: false
    model_path: item/berserkers_greataxe
  berserkers_cleaver:
    resource:
      material: MACE
      generate: false
      model_path: item/berserkers_cleaver
  revenants_gravescepter:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/revenants_gravescepter
  crystal_frostscythe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/crystal_frostscythe
  black_iron_clobberer:
    resource:
      material: MACE
      generate: false
      model_path: item/black_iron_clobberer
  black_iron_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/black_iron_greataxe
  revenants_gravecleaver:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/revenants_gravecleaver
  gloomsteel_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/gloomsteel_greataxe
  emerald_greatcleaver:
    resource:
      material: MACE
      generate: false
      model_path: item/emerald_greatcleaver
  sacrificial_cleaver:
    resource:
      material: MACE
      generate: false
      model_path: item/sacrificial_cleaver
  crimson_cleaver:
    resource:
      material: MACE
      generate: false
      model_path: item/crimson_cleaver
  azure_greataxe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/azure_greataxe
  azure_scythe:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/azure_scythe
  treacherous_axe:
    resource:
      material: IRON_AXE
      generate: false
      model_path: item/treacherous_axe
  treacherous_cleaver:
    resource:
      material: DIAMOND_AXE
      generate: false
      model_path: item/treacherous_cleaver
  treacherous_bludgeon:
    resource:
      material: MACE
      generate: false
      model_path: item/treacherous_bludgeon
  zenith:
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/zenith
  wooden_bludgeon:
    resource:
      material: MACE
      generate: false
      model_path: item/wooden_bludgeon
  iron_mace:
    resource:
      material: MACE
      generate: false
      model_path: item/iron_mace
  wooden_tonfa:
    resource:
      material: WOODEN_SWORD
      generate: false
      model_path: item/wooden_tonfa
  iron_sai:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/iron_sai
  iron_dagger:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/iron_dagger
  iron_greataxe:
    resource:
      material: IRON_AXE
      generate: false
      model_path: item/iron_greataxe
  iron_polearm:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/iron_polearm
  iron_halberd:
    resource:
      material: IRON_AXE
      generate: false
      model_path: item/iron_halberd
  iron_broadsword:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/iron_broadsword
  iron_battle_axe:
    resource:
      material: IRON_AXE
      generate: false
      model_path: item/iron_battle_axe
  flamberge:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/flamberge
  claymore:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/claymore
  uchigatana:
    resource:
      material: IRON_SWORD
      generate: false
      model_path: item/uchigatana
  iron_hay_sickle:
    resource:
      material: IRON_HOE
      generate: false
      model_path: item/iron_hay_sickle

category_fantasy_weapons.yml

info:
  namespace: fantasy_weapons
categories:
  fantasy_weapons:
    enabled: true
    icon: "fantasy_weapons:heavenly_partisan"
    name: "Fantasy Weapons"
    permission: "ia.menu.fantasy_weapons"
    items:
      - "fantasy_weapons:phantomguard_greatsword"
      - "fantasy_weapons:heavenly_partisan"
      - "fantasy_weapons:amethyst_greatsword"
      - "fantasy_weapons:valhakyra"
      - "fantasy_weapons:black_iron_greatsword"
      - "fantasy_weapons:phantomguard_partisan"
      - "fantasy_weapons:talonbrand"
      - "fantasy_weapons:windreaper"
      - "fantasy_weapons:crystal_frostblade"
      - "fantasy_weapons:lycanbane"
      - "fantasy_weapons:grand_claymore"
      - "fantasy_weapons:solstice"
      - "fantasy_weapons:gloomsteel_katana"
      - "fantasy_weapons:gloomsteel_knife"
      - "fantasy_weapons:vesper"
      - "fantasy_weapons:calamity_blade"
      - "fantasy_weapons:ancient_greatslab"
      - "fantasy_weapons:demons_blood_blade"
      - "fantasy_weapons:demonslayers_greatsword"
      - "fantasy_weapons:moonlight"
      - "fantasy_weapons:vengeance_blade"
      - "fantasy_weapons:oculus"
      - "fantasy_weapons:azure_greatsword"
      - "fantasy_weapons:azure_dagger"
      - "fantasy_weapons:azure_sabre"
      - "fantasy_weapons:dragon_sabre"
      - "fantasy_weapons:spider_sword"
      - "fantasy_weapons:runic_piercer"
      - "fantasy_weapons:demonic_sword"
      - "fantasy_weapons:nature_sword"
      - "fantasy_weapons:vindicator"
      - "fantasy_weapons:black_iron_greataxe"
      - "fantasy_weapons:viridian_greataxe"
      - "fantasy_weapons:crescent_greataxe"
      - "fantasy_weapons:berserkers_greataxe"
      - "fantasy_weapons:berserkers_cleaver"
      - "fantasy_weapons:revenants_gravescepter"
      - "fantasy_weapons:crystal_frostscythe"
      - "fantasy_weapons:black_iron_clobberer"
      - "fantasy_weapons:revenants_gravecleaver"
      - "fantasy_weapons:gloomsteel_greataxe"
      - "fantasy_weapons:emerald_greatcleaver"
      - "fantasy_weapons:sacrificial_cleaver"
      - "fantasy_weapons:crimson_cleaver"
      - "fantasy_weapons:azure_greataxe"
      - "fantasy_weapons:azure_scythe"
      - "fantasy_weapons:treacherous_axe"
      - "fantasy_weapons:treacherous_cleaver"
      - "fantasy_weapons:wooden_bludgeon"
      - "fantasy_weapons:iron_mace"
      - "fantasy_weapons:wooden_tonfa"
      - "fantasy_weapons:iron_sai"
      - "fantasy_weapons:iron_dagger"
      - "fantasy_weapons:iron_greataxe"
      - "fantasy_weapons:iron_polearm"
      - "fantasy_weapons:iron_halberd"
      - "fantasy_weapons:iron_broadsword"
      - "fantasy_weapons:iron_battle_axe"
      - "fantasy_weapons:flamberge"
      - "fantasy_weapons:claymore"
      - "fantasy_weapons:uchigatana"
      - "fantasy_weapons:iron_hay_sickle"
```
