### ISSUE TITLE
Bug with 2 blocks hitbox Furnitures

### ISSUE THREAD

**Issue by Flouzl** [PluginBugs/Issues-ItemsAdder#4387]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

flouzi

### What happened?

I wanted to make a hitbox of the blocks for a furniture but when I do the configuration and I save the file and /iazip then /iareload /iatexture, the invisible block has a good hitbox on two axes on west and south but otherwise the invisible block is shifted to east and north see the video to better understand

### Steps to reproduce the issue

1. Make a furniture with 2 block hitbox
2. do /iazip
3. upload the folder on dropbox and modify the config and do /iareload /iatexture
4. then place the furniture on all the north/south/east/west axes

### Server version

This server is running Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 11 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

Itemsadder version 4.0.7

### ProtocolLib Version

ProtocolLib version 5.4.0-SHAPSHOT-739

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/V5pR4mO

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
shelf:
    display_name: "Shelf"
    resource:
      generate: false
      material: PAPER
      model_path: office_furniture/shelf
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        fixed_rotation: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
          length: 1
          width: 2
        sound:
          place:
            name: block.stone.place
          break:
            name: block.stone.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/a9342c04-8550-468b-988d-cb95bea75c01
