### ISSUE TITLE
Recipe registered, but dont work

### ISSUE THREAD

**Issue by Karma678** [PluginBugs/Issues-ItemsAdder#4396]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

I recently encountered this problem. I started creating crafting recipes for swords and got to the anvil. First, I registered repairs using diamonds, gold, etc., and got to the wooden tool. And here's the most interesting thing: I created several repair recipes using wood, all recipes are displayed in the menu as valid and working, there are no errors in the console, but only the very first craft with an oak board was registered, the rest are simply ignored. I also noticed that when trying to reproduce the repair, the desired craft appears for a split second, but for some reason it is immediately blocked.

### Steps to reproduce the issue

1. Create wood weapon
2. Create some recipes for anvil
3. Try first recipe in list and try others
4. In theory, except for the first one, the others do not work, but they will be shown in the menu as working.

### Server version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-132-b48403b (MC: 1.21.1)

### ItemsAdder Version

4.0.7

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/ORoBpMp

### Error (optional)

```shell
Nothing in logs
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: iasurvival
recipes:
  anvil_repair:
    diamond_tachi:
      enabled: true
      permission: iasurvival.swords.diamond_tachi
      ingredient: DIAMOND
      item: iasurvival:diamond_tachi
    golden_tachi:
      enabled: true
      permission: iasurvival.swords.golden_tachi
      ingredient: GOLD_INGOT
      item: iasurvival:golden_tachi
    iron_tachi:
      enabled: true
      permission: iasurvival.swords.iron_tachi
      ingredient: IRON_INGOT
      item: iasurvival:iron_tachi
    stone_tachi:
      enabled: true
      permission: iasurvival.swords.stone_tachi
      ingredient: COBBLESTONE
      item: iasurvival:stone_tachi
    netherite_tachi:
      enabled: true
      permission: iasurvival.swords.netherite_tachi
      ingredient: NETHERITE_INGOT
      item: iasurvival:netherite_tachi
    wooden_tachis1:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss1
      ingredient: OAK_PLANKS
      item: iasurvival:wooden_tachi
    wytdsad:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss1
      ingredient: SPRUCE_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis3:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss3
      ingredient: BIRCH_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis4:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss4
      ingredient: JUNGLE_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis5:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss5
      ingredient: ACACIA_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis6:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss6
      ingredient: DARK_OAK_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis7:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss7
      ingredient: MANGROVE_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis8:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss8
      ingredient: CHERRY_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis9:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss9
      ingredient: BAMBOO_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis10:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss10
      ingredient: CRIMSON_PLANKS
      item: iasurvival:wooden_tachi
    wooden_tachis11:
      enabled: true
      permission: iasurvival.swords.wooden_tachiss11
      ingredient: WARPED_PLANKS
      item: iasurvival:wooden_tachi
```
