### ISSUE TITLE
delay the emote's hiding player to match the changes from #4388

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#4405]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.

### What happened?

(Sorry if this is hard to understand, I tried my best in English)

when I use emotes with MythicMobs, sometimes I feel like the hiding emote part you implemented from #4388 is too long. = it makes me see player disappearing too long too.

even though the skills are running without delay.. I'm not even sure if this happens because MythicMobs (it always worked fine with IA emotes and I ran it with force-sync) 

sometimes it's short sometimes it's long..

So if it's not able to make it stably short as possible, I would think delaying the player hiding to match those hidden wrong bones location might look better.

please look at each video and it might be more understandable.

### Steps to reproduce the issue

1. these are all MythicMobs skills to test (each skills will run the emotes each 1,2,5,20 Ticks)
```
    no-1T:
      Skills:
      - command{sync=true;c="iaemote no <target.name>";repeat=19;repeatInterval=1} @Self      
    no-2T:
      Skills:
      - command{sync=true;c="iaemote no <target.name>";repeat=19;repeatInterval=2} @Self      
    no-5T:
      Skills:
      - command{sync=true;c="iaemote no <target.name>";repeat=19;repeatInterval=5} @Self      
    no-20T:
      Skills:
      - command{sync=true;c="iaemote no <target.name>";repeat=19;repeatInterval=20} @Self   
```
2. run commands ``/mm t cast no-1T`` /``/mm t cast no-2T``  ``/mm t cast no-5T`` etc. in game to test
3. the part where player is being hidden (real player and emotes are not being shown) is too long sometimes

### Server version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.3-2358-16ce24a (MC: 1.21.3)

### ItemsAdder Version

ItemsAdder version 4.0.8

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.64

### Full Server Log

https://mclo.gs/4ZvviFJ

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```

### Screenshots/Videos (you can drag and drop files or paste links)

**by "disappearing", I mean "real player and emotes are not being shown"

https://github.com/user-attachments/assets/703fe97d-b4f6-4bac-a2ad-97c833f8f4d2

use iaemote manually (disappearing is not too long) the emote bones delay aren't too long, so it looks ok.

https://github.com/user-attachments/assets/080eeca3-0aeb-47c9-a51f-20c281de3c6d

iaemote through MythicMobs (disappearing is too long) the emote bones are being delayed too long and now it looks bad.

https://github.com/user-attachments/assets/d4ab184e-b10e-4ae4-b3d0-0751b55d684f

iaemote through MythicMobs (disappearing is not too long)

I don't know if I should report this issue or not, but I will do it, because I think it would take long for anyone to notice these. I'm using iaemote for animation on my combat-based server, so if emotes hides player too long it's a big problem to me as well as bones spawning on wrong location.
