### ISSUE TITLE
Modern armor on iron armor as material runs achievements

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#4424]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

PSYCHEER

### What happened?

When you set in modern system armor or e.g. IRON_HELMET it runs "Build Up" achievement.
Some form of cancellation would be good

### Steps to reproduce the issue

```yml
info:
  namespace: test
equipments:
  my_modern_armor:
    type: armor
    layer_1: armor/copper_armor_layer1
    layer_2: armor/copper_armor_layer2
items:
  my_modern_armor_helmet:
    display_name: my_modern_armor_helmet
    resource:
      generate: true
      texture: items/armor/copper_helmet
      material: IRON_HELMET
    durability:
      max_durability: 165
    equipment:
      id: test:my_modern_armor
      slot_attribute_modifiers:
        armor: 2.5
      camer_overlay: []
      sound: "block.anvil.place" # Defaulted to the vanilla armor equip sound
      allowed_entities: []
      dispensable: true
      swappable: true
      damage_on_hurt: true
```

### Server version

This server is running Paper version 1.21.3-48-master@817550c (2024-11-22T12:02:23Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

### ItemsAdder Version

Version: 4.0.9-beta-4

### ProtocolLib Version

5.4.0-SNAPSHOT-739

### LoneLibs Version

No

### Full Server Log

https://mclo.gs/eIjGpxd

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```
