### ISSUE TITLE
Custom smithing table recipes not working on 1.21.4

### ISSUE THREAD

**Issue by gepao233** [PluginBugs/Issues-ItemsAdder#4434]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

 Custom smithing table recipes not working on 1.21.4

### Steps to reproduce the issue

.

### Server version

This server is running Paper version 1.21.4-147-main@3bd69f2 (2025-02-10T22:59:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[23:54:24 INFO]: ItemsAdder version 4.0.8
[23:54:24 INFO]: Customized Minecraft without client mods!
[23:54:24 INFO]: Website: devs.beer
[23:54:24 INFO]: Author: LoneDev

### ProtocolLib Version

[23:54:38 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[23:54:38 INFO]: Provides read/write access to the Minecraft protocol.
[23:54:38 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:54:51 INFO]: LoneLibs version 1.0.65
[23:54:51 INFO]: Collection of libs used by my plugins
[23:54:51 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/eeneGYn

### Error (optional)

```shell
[23:57:09 WARN]: [ItemsAdder] Can't find item '' to load some settings. File '/contents/custom_equipment/configs/emerald_equipment.yml'
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: custom_equipment
categories:
  emerald_equipment:
    enabled: true
    skip_if_already: false
    icon: custom_equipment:emerald_armor_helmet
    name: 绿宝石装备
    permission: ia.menu.buildplus
    items:
    - custom_equipment:emerald_armor_helmet
    - custom_equipment:emerald_armor_chestplate
    - custom_equipment:emerald_armor_leggings
    - custom_equipment:emerald_armor_boots
# 合成配方    
recipes:
  smithing:
    test_smithing:
      enabled: true
      base: DIAMOND_HELMET
      addition: EMERALD
      result:
        item: custom_equipment:emerald_armor_helmet
        amount: 1
  crafting_table:
    emerald_armor_helmet:
      enabled: true
      pattern:
      - AAA
      - AXA
      - XXX
      ingredients:
        A: EMERALD
      result:
        item: custom_equipment:emerald_armor_helmet
        amount: 1
    emerald_armor_chestplate:
      enabled: true
      pattern:
      - AXA
      - AAA
      - AAA
      ingredients:
        A: EMERALD
      result:
        item: custom_equipment:emerald_armor_chestplate
        amount: 1
    emerald_armor_leggings:
      enabled: true
      pattern:
      - AAA
      - AXA
      - AXA
      ingredients:
        A: EMERALD
      result:
        item: custom_equipment:emerald_armor_leggings
        amount: 1
    emerald_armor_boots:
      enabled: true
      pattern:
      - AXA
      - AXA
      - XXX
      ingredients:
        A: EMERALD
      result:
        item: custom_equipment:emerald_armor_boots
        amount: 1
armors_rendering:
  emerald_armor:
    color: '#d60003'
    layer_1: armor/emerald_equipment/layer_1
    layer_2: armor/emerald_equipment/layer_2
    animation:
      speed: 30
      interpolation: true
items:
  emerald_armor_helmet:
    display_name: 绿宝石头盔
    resource:
      generate: true
      textures:
      - item/emerald_equipment/helmet
    mmoitem:
      type: ARMOR
      id: EMERALD_ARMOR_HELMET
    specific_properties:
      armor:
        slot: head
        custom_armor: emerald_armor
  emerald_armor_chestplate:
    display_name: 绿宝石胸甲
    permission: my_armor
    resource:
      generate: true
      textures:
      - item/emerald_equipment/chestplate
    specific_properties:
      armor:
        slot: chest
        custom_armor: emerald_armor
    mmoitem:
      type: ARMOR
      id: EMERALD_ARMOR_CHESTPLATE
  emerald_armor_leggings:
    display_name: 绿宝石护腿
    permission: my_armor
    resource:
      generate: true
      textures:
      - item/emerald_equipment/leggings
    specific_properties:
      armor:
        slot: legs
        custom_armor: emerald_armor
    mmoitem:
      type: ARMOR
      id: EMERALD_ARMOR_LEGGINGS
  emerald_armor_boots:
    display_name: 绿宝石靴子
    permission: my_armor
    resource:
      generate: true
      textures:
      - item/emerald_equipment/boots
    specific_properties:
      armor:
        slot: FEET
        custom_armor: emerald_armor
    mmoitem:
      type: ARMOR
      id: EMERALD_ARMOR_BOOTS
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/e7c270d0-c4a5-42e6-801d-026584b329f7)
