### ISSUE TITLE
PLAYER_HEAD Error with custom_model_data - Error when setting a number

### ISSUE THREAD

**Issue by VictorAlonsoo** [PluginBugs/Issues-ItemsAdder#4435]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

When setting a custom “custom_model_data” in PLAYER_HEAD it was saved with another number not set!
- Yesterday I noticed it on my server and today I checked it with a test server.

It only affects PLAYER_HEAD for the other items I had it did not affect them.

### Steps to reproduce the issue

I have not tried with high numbers.
I have only put small numbers and when saving the changes the model did not appear, I checked with the command “iacustommodeldata” and I had another unassigned number.

### Server version

This server is running Paper version 1.21.4-164-main@8eb8e44 (2025-02-16T22:13:26Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.8

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

NONE

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: victoralonso

items:
  player_head_gui: #1x1
    show_in_ia_gui: false
    resource:
      material: PLAYER_HEAD
      custom_model_data: 1000
      generate: false
      model_path: player_head_gui
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/5497b0b4-3df2-4597-8315-9d812131a019)
