### ISSUE TITLE
The recipe that reduces durability like peeling potatoes in Wiki does not work properly

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#4436]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

neverlag

### What happened?

I imitated the recipe for peeling potatoes in the wiki and wrote a recipe for making eggplants one by one
When the durability of the frying pan is full, it can work normally
When the durability of the frying pan is not full, it cannot work.
 Please see the picture

![Image](https://github.com/user-attachments/assets/6aa938a0-9200-48f1-8096-78b6ada029ae)

![Image](https://github.com/user-attachments/assets/f4f76535-c687-4ba9-bb37-64470b17cba7)

### Steps to reproduce the issue

1.copy my config or use your peeled_potato recipe in the wiki
https://itemsadder.devs.beer/plugin-usage/adding-content/crafting

2. test in game like my picture show

### Server version

Current Purpur Version: 1.21.4-2381-5583a3f (MC: 1.21.4)*
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.4-2387-4f48185 (MC: 1.21.4)

### ItemsAdder Version

4.0.8

### ProtocolLib Version

5.4.0-SNAPSHOT-738

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/yNR6g85

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
skillet:
    display_name: skillet
    permission: skillet
    resource:
      material: IRON_SWORD
      generate: false
      model_path: combat/sword/skillet

  eggplant:
    display_name: "eggplant"
    lore:
    - '&f♤'
    resource:
      generate: false
      material: APPLE
      model_path: crops/eggplant/eggplant
    events:
      eat:
        feed:
          amount: 1

    stuffed_eggplant:
      permission: dripdrop.stuffed_eggplant
      enabled: true
      # pattern:
      pattern:
      - XXX
      - EME
      - XFX
      ingredients:
        E: dripdrop:eggplant
        M: PORKCHOP
        F: dripdrop:skillet
      result:
        item: dripdrop:stuffed_eggplant
        amount: 1
      return_items:
        decrement_durability:
          skillet:
            item: skillet
            amount: 1
        play_sound:
          name: dripdrop:item.skillet.use
          volume: 1
          pitch: 1
```
