### ISSUE TITLE
enable font_images.book in config.yml will cause book's title and author not show

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#4437]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

neverlag

### What happened?

enable
![Image](https://github.com/user-attachments/assets/bd568ba9-b869-478f-aed5-3eca3cf04c16)

dont enable 
![Image](https://github.com/user-attachments/assets/aedba341-3e29-4928-895c-28aaa8bf38a1)

### Steps to reproduce the issue

1.open the config.yml
2. change font_images.book.enabled: true
3. give yourself a writtable_book
4. write something and give it a title
5. this book don't show book name,don't show author but "written book" 

### Server version

Current Purpur Version: 1.21.4-2381-5583a3f (MC: 1.21.4)*
* You are 16 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.4-2387-4f48185 (MC: 1.21.4)

### ItemsAdder Version

4.0.8

### ProtocolLib Version

5.4.0-SNAPSHOT-738

### LoneLibs Version

1.0.63

### Full Server Log

https://mclo.gs/b4QUXxw

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
metrics: true
resource-pack:
  kick-player-on-decline: false
  kick-player-on-fail: false
  title:
    enabled: false
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    # use_separate_custom_font_file_EXPERIMENTAL: true
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      # 保护资源包
      protection_1: true
      protection_2: true
    compress-png-files: false
    compress-json-files: true # 压缩json
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
      vanilla: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - dripdrop
    - vanilla
    - _iainternal
    extract_internal_utility_assets: false
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    - CustomNameplates/ResourcePack
    compress-shader-files: true
  protect-player:
    lock-player: true
    hide-hud: true
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 42203
      append-port: true
      protection:
        block_non_game_requests: false
        rate_limit:
          enabled: false
          max_requests: 3
          period_seconds: 2
          cooldown:
            enabled: false
            duration_minutes: 30
            trigger_on_failed_times: 5
    external-host:
      enabled: false
      url: https://gitee.com/neverlag/dripdrop_pack/releases/download/v3.03/generated.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: true
    lobfile:
      enabled: false
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 1
      LEATHER_HORSE_ARMOR: 1000000
      DIAMOND: 11000
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  custom_blocks_sounds_patch:
    enabled: false
    step:
      enabled: true
      allow_non_player: true
    other: true
  expert_users: {}
  notify_other_plugins_resourcepacks: true
  allow_other_plugins_resourcepacks: false
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  atlas_support: true
  pre_1_21_2_shaders_fix:
    enabled: true
  auto_apply:
    enabled: false
    before_join: true
    delay_ticks: 1
blocks:
  fix-glitched-blocks:
    enabled: false
    only-new-chunks: false
    fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance: true
    seach-also-in-these-biomes: {}
  cancel-break-wrong-tool:
    enabled: false
    send-actionbar: false
    mining-fatigue:
      enabled: false
      duration: 20
      amplifier: 1
  campfire: {}
  fix-bugged-mushrooms:
    enabled: true
    only-new-chunks: false
  fix-liquids-flow: false
  fix-floating-blocks: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: false
    drop_when_broken: false
  custom:
    mushroom: false
    chorus: false
    note: false
    wire: true
    fire: false
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
items:
  fix-show-attack-and-damage-as-lore: false
  give_death_location_maps: false
  hide-custom-durability-lore: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 600
  update-legacy-items:
    enabled: true
    update_durability: true
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    add_hover_suggestion: true
    tab_autocompletion_1_19_1_plus: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: false
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
  customitem_name_and_lore:
    enabled: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
config_files:
  update-automatically: false
  lang: cn
  dictionaries-lang: zh_cn
  extract-default-resources: false
  force-sync-loading: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
    log-files-reloading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  blocks:
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-unusual-block-break: false
    log-save-load:
      enabled: false
      min-ms: 0
    log-fix-bugged-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-ia-gui-categories-loading: false
    log-ia-gui-categories-loading-skip: false
    log-ia-gui-categories-loading-overwrite: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  benchmark: false
  issues:
    log_font_image_replace_json_syntax_exception: true
  blocks-populators:
    log-generation: false
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  resourcepacks:
    log_player_install: false
    compression:
      files: false
      overlays: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  enabled: true
update-checker: false
entities:
  max-furniture-vehicles-per-chunk: 500
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false # 多个相同头颅会导致出错，禁用
    expert_users:
      delay_packets: false
      extract_emotes_shaders: true
  furniture:
    auto_convert_to_item_display: false
recipes:
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup: {}
      on-item-click: {}
      automatically: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
effects:
  hide-scoreboard-numbers: true
  hide-scoreboard-numbers-old-clients: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: true
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
text_effects:
  enabled: false
  chat:
    enabled: true
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  customitems-name-and-lore:
    enabled: true
  legacy_colors_compatibility: true
  customitem_name_and_lore:
    enabled: true
  hide_scoreboard_numbers: false
  hide_scoreboard_numbers_old_clients: false
cache_font_images_and_effects_replacements: true
```
