### ISSUE TITLE
ItemsAdder incorrectly detects resource.generate value (always sees it as “true”)

### ISSUE THREAD

**Issue by Marcoral** [PluginBugs/Issues-ItemsAdder#4439]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Marcoral

### What happened?

I have a problem with creating items, reusing minecraft resources. ItemsAdder persistently claims that I have set the `resource.generate: true` flag, even though it is set to `false`. Because of this, errors appear in the console regarding the lack of path to the model and texture.

### Steps to reproduce the issue

Use config
```
info:
  namespace: test
items:
  custom_iron_sword:
    display_name: "Custom Iron Sword"
    permission: "itemadder.customironsword"
    resource:
      material: IRON_SWORD
      generate: false # Note that it is set to "false"!
    lore:
      - "&cLooks like I made a mess in the console...."
      - "&cBut all I wanted to do was to use the existing Minecraft sword model! :("
```
When loading, you will see error message:
`test:custom_iron_sword'. No 'model_path' set with 'generate: true'.

### Server version

This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.8

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-738

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/TzHXedR

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: test
items:
  custom_iron_sword:
    display_name: "Custom Iron Sword"
    permission: "itemadder.customironsword"
    resource:
      material: IRON_SWORD
      generate: false # Note that it is set to "false"!
    lore:
      - "&cLooks like I made a mess in the console...."
      - "&cBut all I wanted to do was to use the existing Minecraft sword model! :("
```
