### ISSUE TITLE
Can't register cooking recipes if more than one machinery is specified

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4443]
```yml
info:
  namespace: parasite_weaponary
items:
  parasite_cell:
    display_name: Dead Cell
    resource:
      material: PAPER
      generate: false
      model_path: dead_cell
recipes:
  cooking:
    host_cell:
      machines:
        - FURNACE
        - BLAST_FURNACE
        - SMOKER
      ingredient:
        item: parasite_weaponary:parasite_cell
      exp: 10
      cook_time: 400
      result:
        item: CHARCOAL
        amount: 1
```

![Image](https://github.com/user-attachments/assets/3b44c3f8-8e18-4fdf-b9cb-d06803ff0dd4)
