### ISSUE TITLE
New behaviour `entity_summoner`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4452]
Allows to spawn a custom entity or a vanilla entity on the interacted location.
This can be used to create custom spawn eggs.
It supports vanilla and custom entities.

```yml
  custom_egg:
    name: Custom Egg
    resource:
      material: PAPER
      generate: true
      texture: item/custom_egg
    behaviours:
      entity_summoner:
        entity: ZOMBIE
```
