### ISSUE TITLE
Hud not showing up until itemsadder is reloaded with no-host enabled

### ISSUE THREAD

**Issue by Kenified** [PluginBugs/Issues-ItemsAdder#4459]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

kenified

### What happened?

I am having issue with my huds that i am upgrading from 1.20.1 to 1.21.4. The huds don't show up for the player until the plugin is reloaded after the player joins the server.

[huds.zip](https://github.com/user-attachments/files/18931964/huds.zip)

### Steps to reproduce the issue

1. Put the huds pack into content folder
2. Enable `no-host`
3. Restart and join server
4. Hud should not be visible
5. Hud should become visible after running `/iareload`
### Server version

Current Purpur Version: 1.21.4-DEV-e0350d4 (MC: 1.21.4)*
* Unknown version
Previous: 1.21.4-2398-196c176 (MC: 1.21.4)

(Purpur with custom patches, i also tested with latest purpur same issues present there)

### ItemsAdder Version

ItemsAdder version 4.0.8

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/bWqQGT3

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
#Energy Bar
info:
  namespace: minecubed
font_images:
  energy_full:
    suggest_in_command: false
    path: gui/huds/energy_full
    y_position: -6
  energy_half:
    suggest_in_command: false
    path: gui/huds/energy_half
    y_position: -6
  energy_empty:
    suggest_in_command: false
    path: gui/huds/energy_empty
    y_position: -6
huds:
  energy_bar:
    enabled: true
    show:
      auto: true
      creative: false
      underwater: true
      riding: true
    type: STATUS
    x_position_pixels: 11
    direction: LEFT
    value:
      player_stat_name: energy
      start: 10
      min: 0
      max: 10
    images:
      positive: minecubed:energy_full
      half: minecubed:energy_half
      negative: minecubed:energy_empty

#Thirst Bar
info:
  namespace: minecubed
font_images:
  thirst_full:
    suggest_in_command: false
    path: gui/huds/thirst_full
    y_position: -16
  thirst_half:
    suggest_in_command: false
    path: gui/huds/thirst_half
    y_position: -16
  thirst_empty:
    suggest_in_command: false
    path: gui/huds/thirst_empty
    y_position: -16
huds:
  thirst_bar:
    enabled: true
    show:
      auto: true
      creative: false
      underwater: false
      riding: false
    type: STATUS
    x_position_pixels: 11
    direction: LEFT
    value:
      player_stat_name: thirst
      start: 10
      min: 0
      max: 10
    images:
      positive: minecubed:thirst_full
      half: minecubed:thirst_half
      negative: minecubed:thirst_empty
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/34cbeae9-fcce-4e00-8fb7-1d476efaaae4)

![Image](https://github.com/user-attachments/assets/0d0f9ee6-b5aa-4f1d-88a7-42870b99d30d)
