### ISSUE TITLE
Ressource Pack won't load without error

### ISSUE THREAD

**Issue by Loutre-Chauve** [PluginBugs/Issues-ItemsAdder#4460]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

loutre_chauve

### What happened?

Hello !
ItemsAdder can't load my resource pack, and doesn't give me any information about the source of the problem.

I've tried to open my server only with these plugins, and it doesn't work.
- ItemsAdder, LoneLibs, LuckPerms, nightcore, ProtocolLib

The problems stem from the migration from version 1.21 to version 1.21.4.
Everything is up to date.

I've read a lot of documentation and the GitHub problem, and I still can't figure out where my misconfiguration is.

Thanks in advance !

### Steps to reproduce the issue

1. Enter to the server
2. See MC popup "Downloading resource Pack 1/1 ..."
3. See MC popup "Resource reload fail"
4. Repeat with /iazip & /iareload

### Server version

Current Purpur Version: 1.21.4-2398-196c176 (MC: 1.21.4)*
*You are running the latest version
Previous: 1.21.1-2329-803bf62 (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.8

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/6ATeQJr

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
metrics: true
update-checker: true
resource-pack:
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  auto_apply:
    enabled: true
    before_join: true
    delay_ticks: 10
  kick-player-on-decline: true
  kick-player-on-fail: true
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: mc303.boxtoplay.com
      pack-port: 30010
      append-port: true
      protection:
        block_non_game_requests: false
        rate_limit:
          enabled: true
          max_requests: 3
          period_seconds: 2
          cooldown:
            enabled: true
            duration_minutes: 30
            trigger_on_failed_times: 5
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  title:
    enabled: true
  atlas_support: true
  fix_force_unicode_font_images: true
  allow_other_plugins_resourcepacks: false
  notify_other_plugins_resourcepacks: true
  protect-player:
    lock-player: true
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    compress-shader-files: true
    generate-custom-armors-textures:
      vanilla: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - back2craft
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
  pre_1_21_2_shaders_fix:
    enabled: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  custom:
    note: true
    mushroom: true
    chorus: true
    wire: true
    fire: true
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  hide-custom-durability-lore: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  enabled: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
cache_font_images_and_effects_replacements: true
font_images:
  chat:
    enabled: true
    add_hover_suggestion: true
    tab_autocompletion_1_19_1_plus: true
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  customitem_name_and_lore:
    enabled: true
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
text_effects:
  enabled: true
  hide_scoreboard_numbers: false
  hide_scoreboard_numbers_old_clients: false
  legacy_colors_compatibility: true
  chat:
    enabled: true
  customitem_name_and_lore:
    enabled: true
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      delay_packets: false
      extract_emotes_shaders: true
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      automatically: true
      all-on-join: false
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
debug:
  benchmark: false
  resourcepacks:
    log_player_install: false
    compression:
      files: false
      overlays: true
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  blocks-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
effects:
  hide-scoreboard-numbers-old-clients: false
```

### Other files, you can drag and drop them here to upload. (optional)

# Client Log after a /iazip  

[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf822)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf80b)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf80a)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf801)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf825)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf82b)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf829)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf828)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf827)
[22:29:56] [Render thread/WARN]: Couldn't find glyph for character  (\uf802)
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Started generation
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Generated resourcepack assets.
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Saved into /26513/plugins/ItemsAdder/output/generated.zip
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Compressed in 3736ms
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Resourcepack URL (self-host): http://mc303.boxtoplay.com:30010/generated.zip
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Applying to every player... 
[22:30:08] [Render thread/INFO]: [System] [CHAT] [ItemsAdder] [Pack] Applied to 1 players
[22:30:08] [Download-28/WARN]: Existing file /home/purpul/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.21.4/minecraft/downloads/d69238f2-b7ce-30b0-8262-17cd9490f29d/3417851b0f3a2ed57c33234ff7e6853484e03111 not found or had mismatched hash
[22:30:09] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, axiom, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, sodium, server/0000000E/d69238f2-b7ce-30b0-8262-17cd9490f29d
[22:30:09] [Worker-Main-61/INFO]: Found unifont_all_no_pua-16.0.01.hex, loading
[22:30:09] [Worker-Main-68/WARN]: File back2craft:sounds/distributeur.ogg does not exist, cannot add it to event back2craft:distributeur
[22:30:09] [Worker-Main-61/INFO]: Found unifont_jp_patch-16.0.01.hex, loading
[22:30:10] [Worker-Main-59/WARN]: Missing sprite: minecraft:textures/joyau.png
[22:30:10] [Worker-Main-67/WARN]: Missing block model: 'minecraft:builtin/entity'
[22:30:10] [Worker-Main-67/WARN]: Missing block model: 'minecraft:carbon_dague'
[22:30:10] [Worker-Main-68/WARN]: Invalid frame index on sprite back2craft:cyberpunk/tv frame 1: 1
[22:30:10] [Worker-Main-68/WARN]: Invalid frame index on sprite back2craft:cyberpunk/tv frame 2: 2
[22:30:10] [Worker-Main-68/WARN]: Invalid frame index on sprite back2craft:cyberpunk/tv frame 3: 3
[22:30:10] [Worker-Main-59/WARN]: Texture painter:block/color_palettes/stripped_log_top_green with size 9x1 limits mip level from 4 to 0
[22:30:10] [Worker-Main-59/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
[22:30:10] [Worker-Main-59/WARN]: Missing textures in model minecraft:paper#inventory:
    minecraft:textures/atlas/blocks.png:minecraft:joyau
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:structure_void#:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:tripwire#attached=false,disarmed=false,east=false,north=false,powered=true,south=false,west=true:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:tripwire#attached=false,disarmed=true,east=false,north=false,powered=false,south=false,west=true:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:tripwire#attached=false,disarmed=true,east=false,north=false,powered=false,south=false,west=false:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:paper#inventory:
    #missing
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:chorus_plant#down=true,east=true,north=false,south=true,up=true,west=false:
    #missing
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:shears#inventory:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:tripwire#attached=false,disarmed=true,east=false,north=false,powered=true,south=false,west=true:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:chorus_plant#down=true,east=true,north=false,south=false,up=true,west=true:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:chorus_plant#down=true,east=true,north=false,south=false,up=true,west=false:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:tripwire#attached=false,disarmed=true,east=false,north=false,powered=true,south=false,west=false:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:chorus_plant#down=true,east=true,north=false,south=false,up=false,west=true:
    particle
[22:30:10] [Worker-Main-59/WARN]: Missing texture references in model minecraft:chorus_plant#down=true,east=false,north=true,south=true,up=true,west=true:
    particle
[22:30:10] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_gui_overlay (VertexFormat[Position, Color]): Could not find shader: minecraft:core/rendertype_gui_overlay (VERTEX)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:68) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1296) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:922) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_gui_overlay (VertexFormat[Position, Color]): Could not find shader: minecraft:core/rendertype_gui_overlay (VERTEX)
	at knot/net.minecraft.class_10151.method_62945(class_10151.java:182) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10151.method_18788(class_10151.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:14) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
[22:30:10] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, axiom, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, sodium
[22:30:10] [Worker-Main-61/INFO]: Found unifont_all_no_pua-16.0.01.hex, loading
[22:30:10] [Worker-Main-64/INFO]: Found unifont_jp_patch-16.0.01.hex, loading
[22:30:11] [Worker-Main-64/WARN]: Missing texture references in model minecraft:structure_void#:
    particle
[22:30:11] [Render thread/INFO]: OpenAL initialized on device Built-in Audio Stéréo analogique
[22:30:11] [Render thread/INFO]: Sound engine started
[22:30:11] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22:30:11] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:30:11] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[22:30:11] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[22:30:11] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:30:11] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[22:30:11] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:30:11] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:30:11] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/gui.png-atlas
[22:30:11] [Render thread/INFO]: Stopping worker threads
[22:30:11] [Render thread/INFO]: Started 6 worker threads
[22:30:13] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:internal.block.stone.step
Clipboard copy at: 23 Feb 2025 22:30:14 +0100

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/7a88f922-e359-4911-a4e6-d8ed40215f73)
