### ISSUE TITLE
Tile blocks 1.21.4, not showing model, only spawner

### ISSUE THREAD

**Issue by Flowflops** [PluginBugs/Issues-ItemsAdder#4464]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

flowflops

### What happened?

When i place a custom block, with the placed model type: TILE, It shows up as a spawner with a paper (the item, that's given in the config of the block). The custom model is not loading.

### Steps to reproduce the issue

Drop the newest: Itemsadder, Lonelibs and protocolibs in the plugins folder.
Start the newest Purpur/paper (both not working) 1.21.4 minecraft server

Create a custom block with the TILE type.
run: /iareload, /iazip

Give yourself the block and place it.

### Server version

Current Purpur Version: 1.21.4-2398-196c176 (MC: 1.21.4)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.4-177-e5a8ee8 (MC: 1.21.4)

### ItemsAdder Version

4.0.8

### ProtocolLib Version

5.4.0-SNAPSHOT-741

### LoneLibs Version

1.0.65

### Full Server Log

https://mclo.gs/du0ZLHL

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: chen

items:
  blocksectioncutoutclean:
    enabled: true
    display_name: "blocksectioncutoutclean"
    resource:
      material: PAPER
      generate: false
      model_path: "chen:block/blocksection_cutout_clean"
    specific_properties:
      block:
        placed_model:
          type: TILE
          model: "chen:block/blocksection_cutout_clean"
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/257f7e15-5e33-4d71-9781-5f0a6e6e2905)

**Comment by Andre601** [comment]
> [18:15:52] [Craft Scheduler Thread - 4 - ItemsAdder/INFO]: [ItemsAdder] READ HERE: 
You selected no-host so you will have to handle the pack upload and apply manually.
Probably you will use another plugin to apply the pack.

You have no-host enabled, so unless you host the pack through any other means is it not applied on join, which by the looks of the logs must be the case.

**Comment by Andre601** [comment]
Also, `model_path` does not require the namespace (`chen:`) if the model is the exact same namespace as the item you set it for, which is the case here.

**Comment by Flowflops** [comment]
> applied

Hello, i have found the problem in my main server, but for testing i made a new server. I hosted the pack myself, i downloaded the generated.zip and applyed it on my client.

**Comment by Flowflops** [comment]
> Also, `model_path` does not require the namespace (`chen:`) if the model is the exact same namespace as the item you set it for, which is the case here.

Okay, thank you for mentioning, i did not know that. But do i have to remove it know? Or can it also be there?

**Comment by Flowflops** [comment]
When im using REAL_NOTE or the REAL_TRANSPARENT it works like normal.

**Comment by PSYCHEER** [comment]
Proof
---
![Image](https://github.com/user-attachments/assets/6f3dff12-840d-493d-a74f-64fed5b4dc6d)

Configuration
---
```yaml
info:
  namespace: mypack
items:
  blocksectioncutoutclean:
    enabled: true
    display_name: "blocksectioncutoutclean"
    resource:
      material: PAPER
      generate: false
      model_path: "blocksection_cutout_clean"
    specific_properties:
      block:
        placed_model:
          type: TILE
        drop_when_mined: true       
```
Testing model
---
[blocksection_cutout_clean.json](https://github.com/user-attachments/files/19012655/blocksection_cutout_clean.json)

When `REAL_NOTE`
---
![Image](https://github.com/user-attachments/assets/523f8321-72df-4fd5-bd6c-f12da02f1ef9)
