### ISSUE TITLE
Refactor the `resource` section

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#4473]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

Hey there ItemsAdder developer!
I really like ItemsAdder for its extensive functions but can we make a config of items simpler?

I know why `generate` is called as is, but in same way in some things like armor pieces, excluding helmet, it is useless.

## SOLUTION
Rename `generate` >> `use_model` and when this variable will not be in config, it will be assigned as `false` to use texture instead.
It will simplify config files as we will not use useless config line in a lot of items.
Convertor to these may be useful too! And it will not be hard to implement as I believe you're skilled professional programmer.

### Is your feature request related to a problem?

Yes! I hate `generate`!

### Describe alternatives you've considered

Not suggesting it as I'm shy 🥺👉👈

### Additional context

Thank you! 💖

**Comment by Andre601** [comment]
I think a better name would be `generate_model`.
It would tell you its purpose: to generate models.

Also, to add to this: I cannot recall if this behaviour is present, but IA should force the generate option to false if a valid `model_path` is present.

**Comment by PSYCHEER** [comment]
Or this, yes, it's just not negating bool as I wanted to.
But still, this option should not be required as in some stuff it's really better to let IA handle this

**Comment by LoneDev6** [comment]
i too think that section needs a revamp.
the `resource` part always is related to the item render only.
so I could rename it to something like `model`, because it's always a model.

- `material` will be defaulted to `PAPER` if not specified.
- `parent` property will work only if `texture`/`s` is used.
- `custom_model_data` will still exist.

## Some examples

```yml
model:
  path: myitems:item/shit
```

```yml
model:
  path: myitems:item/shit
  custom_model_data 1337
```

```yml
model:
  texture: myitems:item/other_shit.png
```

```yml
model:
  texture: myitems:item/other_shit.png
  parent: minecraft:item/handheld
  custom_model_data 1337
```

```yml
model:
  textures:
    - myitems:item/other_shit_layer_1.png
    - myitems:item/other_shit_layer_2.png
    - myitems:item/other_shit_layer_3.png
```

**Comment by Andre601** [comment]
I agree. Not a good idea to call it model... especially since this one confuses me on what `model_path` would be...

Maybe `item` would be good? Since it's about the generated item.
Or would it conflict too much with `items`?

**Comment by PSYCHEER** [comment]
And which item model generation way you will take with it?

```yaml
items:
  my_item:
     resources:
       generate_model: true/false
       material: paper
       textures/model_path
```

This information will be nice to be a bit sooner than the release so we can prepare our knowledge for it.

Will you take only generate rename idea or the resource part change too?
