### ISSUE TITLE
Cooking registers recipe but does not produce result

### ISSUE THREAD

**Issue by SirNicholas433** [PluginBugs/Issues-ItemsAdder#4475]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

SirNicholas433

### What happened?

Recipe registers but does not produce resulting item

### Steps to reproduce the issue

attempt to cook the item as described in YML, goes through cooking but produces no item.

### Server version

1.21.4 purpur

### ItemsAdder Version

4.0.9 beta 12

### ProtocolLib Version

5.4.0 snap shot 739

### LoneLibs Version

1.0.65

### Full Server Log

https://mclo.gs/nqDStXE

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: items
items:
  aluminum_bar:
    permission: items.aluminum_bar
    display_name: "&x&0&0&f&f&0&0Aluminum Bar"
    resource:
      material: IRON_INGOT
      generate: true
      textures:
        - aluminum_bar
info:
  namespace: items
recipes:
  cooking:
    cooked_sausage:
      permission: items.aluminum_bar
      ingredient:
        item: items:bauxite_ingot
      machines:
        - FURNACE
        - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: items:aluminum_bar
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/5a61f1b2-9eba-4ad8-89b1-cc4b710360e5
