### ISSUE TITLE
Support for hand_animation_on_swap

### ISSUE THREAD

**Issue by duranaaron** [PluginBugs/Issues-ItemsAdder#4482]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I would like items to support the new hand_animation_on_swap field
https://www.minecraft.net/fr-fr/article/minecraft-java-edition-1-21-4

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Doing all the models myself

**Comment by Andre601** [comment]
This should already be doable by using the nbt option to apply additional NBT data.

**Comment by LoneDev6** [comment]
`hand_animation_on_swap` would be applied to the whole item.
Right now ItemsAdder is using CustomModelData to support legacy clients and because its internal logic works like that.
So this feature for now cannot be implemented without making all the items that use the same material apply`hand_animation_on_swap`.

This feature will be implemented once this will be implemented too:
- #4224

**Comment by LoneDev6** [comment]
Upcoming update

#4921

```yml
  # Automatically generate the modern item + model from a texture 
  modern_texture:
    name: Modern Texture
    material: paper
    graphics:
      texture: item/modern_texture
      hand_animation_on_swap: false # Optional property to disable animation
```


https://github.com/user-attachments/assets/b414fa0e-81ff-458f-abca-968df414d387
