### ISSUE TITLE
Easy sounds configuration

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4489]
Implement a configuration to easily add sounds instead of having to create the vanilla `sounds.json` file.

**Comment by 00Hrtz** [comment]
Nice idea but, it's already very easy? 

A simple wiki page on how to would suffice i.e.

```yaml
Free software that can edit and convert sound files to ogg format, i.e. Audacity:
https://www.audacityteam.org/

Tutorial on how to crop sound files using Audacity:
https://www.youtube.com/watch?v=0Upj8zHEH-8

Location to place sound file:
assets/minecraft/sounds/namespace

Location of sound.json file: (create it if not present)
assets/minecraft

Copy/Paste below code into  the sound.json file:

{
  "soundname": {
    "replace": false,
    "sounds": [
      "namespace/soundname"
    ]
  },
  "soundname": {
    "replace": false,
    "sounds": [
      "namespace/soundname"
    ]	
  }
}
```

**Comment by 00Hrtz** [comment]
If users are not learning how to edit json/yml files then they really have no place running server, just my opinion.

**Comment by LoneDev6** [comment]
## Showcase of the new feature

Download here: [test.zip](https://github.com/user-attachments/files/20287560/test.zip)

You can now create sounds directly in a `yml` file (exactly how you create items).
This allows you to avoid having to mess up JSON which is a very un-handy format to work with.

I wrote down some examples.
`bruh_1` has some variants that change pitch randomly each time you play it via `/playsound test:bruh_1`.

`bruh_2` is a simple sound that plays the `bruh.ogg` file each time.

`bruh_3` allows playing any of the listed `.ogg` files randomly (in this case I only have `bruh`, but each of them in the list should be different to make any sense.

Also as you can see I created a custom subtitle, for the ones playing with subtitles enabled.

![Image](https://github.com/user-attachments/assets/f2bce4fa-4558-4dd0-9fb5-08a6ed1df456)

```yml
info:
  namespace: test
minecraft_lang_overwrite:
  my_lang_overwrite:
    entries:
      sound.bruh: "BRUH"
    languages:
    - ALL
sounds:
  bruh_1:
    settings:
      subtitle: sound.bruh
    variant_1:
      path: bruh
    variant_2:
      path: bruh
      pitch: 0.9
    variant_3:
      path: bruh
      pitch: 0.85
    variant_4:
      path: bruh
      pitch: 0.8

  bruh_2:
    path: bruh

  bruh_3:
    paths:
    - bruh
    - bruh

  bruh_all_properties:
    settings:
      subtitle: sound.bruh
      replace: false
    variant_1:
      path: bruh
      volume: 0.8
      pitch: 1.0
      weight: 10
      attenuation_distance: 16
      stream: false
      preload: false

```
