### ISSUE TITLE
`execute_commands` only triggers when interacting with a block

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4500]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

andre601

### What happened?

When setting a `execute_commands` action for `events.interact.right` are the specified commands only executed when right-clicking a block. Right-clicking the air does not execute commands, but other actions such as `play_sounds` are.

### Steps to reproduce the issue

1. Setup an item
2. Add `events.interact.right` option
3. Set `execute_commands` with a valid command.
4. `/iazip`
5. Test the item by right-clicking with it

### Server version

[13:46:40 INFO]: This server is running Paper version 1.21.4-190-main@5538d24 (2025-03-05T12:40:02Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[13:46:57 INFO]: ItemsAdder version 4.0.9
[13:46:57 INFO]: Customized Minecraft without client mods!
[13:46:57 INFO]: Website: devs.beer
[13:46:57 INFO]: Author: LoneDev

### ProtocolLib Version

[13:47:10 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[13:47:10 INFO]: Provides read/write access to the Minecraft protocol.
[13:47:10 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

No longer required as of 4.0.9

### Full Server Log

https://mclo.gs/GxZ8jbb

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vanillaplus
items:
  recipe_book:
    name: "<lang_or:vanillaplus.item.recipe_book:'Recipe Book'/>"
    lore:
      - "<lang_or:vanillaplus.item.recipe_book_lore:'Lists all custom crafting recipes'/>"
    resource:
      material: BOOK
      generate: true
      texture: minecraft:item/knowledge_book.png
    events:
      interact:
        right:
          play_sound:
            name: minecraft:item.book.page_turn
            volume: 1
            pitch: 1
          execute_commands:
            open_recipes:
              command: recipes # Only executes on right-clicking blocks
```

**Comment by Andre601** [comment]
I've also tested with a variant that uses an actual vanilla command and same result:
```yaml
info:
  namespace: vanillaplus
items:
  recipe_book:
    name: "Recipe Book"
    resource:
      material: PAPER
      generate: true
      texture: minecraft:item/knowledge_book.png
    events:
      interact:
        right:
          play_sound:
            name: minecraft:item.book.page_turn # This sound plays on every interaction
            volume: 1
            pitch: 1
          execute_commands:
            my_command:
              command: say I executed this command!
```
Here is a video demonstrating the issue. You can notice the sound playing but command only executing while targeting a block.

https://github.com/user-attachments/assets/30117873-8560-4bca-bc8c-c05ba0af4183
