### ISSUE TITLE
Custom Drinks are displayed as only non-brewable potions

### ISSUE THREAD

**Issue by Leahcimkrob** [PluginBugs/Issues-ItemsAdder#4506]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

bloody_mind

### What happened?

The names of the custom potions are not taken from the config.
Names are available in Config. 
I also wrote a ticket in Discord, but so far there has been no response.
Itemsadder 4.0.9

### Steps to reproduce the issue

We've been using custom drinks since 4.0.2. We haven't had any issues with 4.0.8.

Since we were more focused on armor during the 4.0.9 beta, we didn't notice the potion issue.

### Server version

[08:25:06 INFO]: Checking version, please wait...
[08:25:06 INFO]: This server is running Paper version 1.21.4-207-main@1a7288a (2025-03-09T18:15:59Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[08:07:22 INFO]: ItemsAdder version 4.0.9
[08:07:22 INFO]: Customized Minecraft without client mods!
[08:07:22 INFO]: Website: devs.beer
[08:07:22 INFO]: Author: LoneDev

### ProtocolLib Version

[08:08:07 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[08:08:07 INFO]: Provides read/write access to the Minecraft protocol.
[08:08:07 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version lonelibs
[08:07:38 INFO]: LoneLibs version 1.0.64
[08:07:38 INFO]: Collection of libs used by my plugins
[08:07:38 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/4UHmVbC

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: drinks
font_images:
  caffeebar_left:
    suggest_in_command: false
    show_in_gui: false
    path: caffeebar/gui/caffeebar_left
    y_position: 12
  caffeebar_right:
    suggest_in_command: false
    show_in_gui: false
    path: caffeebar/gui/caffeebar_right
    y_position: 12
recipes:
  crafting_table:
    ethria_breu:
      enabled: true
      pattern:
      - KHD
      - RHR
      - RRR
      ingredients:
        K: HONEY_BOTTLE
        H: POTION
        D: WHEAT_SEEDS
        R: OAK_PLANKS
      result:
        item: drinks:ethria_breu
        amount: 1
    ethria_breu_alkoholfrei:
      enabled: true
      pattern:
      - KHD
      - RBR
      - RRR
      ingredients:
        K: HONEY_BOTTLE
        H: POTION
        D: WHEAT_SEEDS
        R: OAK_PLANKS
        B: COBWEB
      result:
        item: drinks:ethria_breu_alkoholfrei
        amount: 1
items:
  ethria_breu:
    display_name: <gradient:#5B71C8:#5BFFC8><bold>Ethria Bräu
    resource:
      material: POTION
      generate: false
      model_id: 1800000
      model_path: ethria_breu
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  ethria_breu_alkoholfrei:
    display_name: <gradient:#5B71C8:#5BFFC8><bold>Ethria Bräu <gradient:#FFE83D:#FFFDC1>(Alkoholfrei)
    resource:
      material: POTION
      generate: false
      model_id: 1800001
      model_path: ethria_breu
  blue_cura_ethria:
    display_name: <#0090D5><bold>Blue Cura-Ethria
    resource:
      material: POTION
      generate: false
      model_id: 1800002
      model_path: blue_cura_ethria
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  blue_mawaiian:
    display_name: <#0090D5><bold>Blue Mawaiian
    resource:
      material: POTION
      generate: false
      model_id: 1800003
      model_path: blue_mawaiian
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  blue_lagoon:
    display_name: <#0090D5><bold>Blue Lagoon
    resource:
      material: POTION
      generate: false
      model_id: 1800004
      model_path: blue_lagoon
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  moor_water:
    display_name: <#31907E><bold>Moor-Wasser
    resource:
      material: POTION
      generate: false
      model_id: 1800005
      model_path: moor_water
    events:
      drink:
        potion_effect:
          type: POISON
          amplifier: 1
          duration: 125
  white_rum:
    display_name: <#FFFFFF><bold>Weißer Rum
    resource:
      material: POTION
      generate: false
      model_id: 1800006
      model_path: white_rum
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  magic_dust:
    display_name: <#AFDB51><bold>Magic Dust
    resource:
      material: POTION
      generate: false
      model_id: 1800007
      model_path: magic_dust
    events:
      drink:
        potion_effect:
          type: LEVITATION
          amplifier: 1
          duration: 250
  batida_de_ethria:
    display_name: <#FFFFFF><bold>Batida de Ethria
    resource:
      material: POTION
      generate: false
      model_id: 1800008
      model_path: batida_de_ethria
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  kuestennebel:
    display_name: <#C54883><bold>Küstennebel
    resource:
      material: POTION
      generate: false
      model_id: 1800009
      model_path: kuestennebel
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 125
  met:
    display_name: <#F6880D><bold>Met
    resource:
      material: POTION
      generate: false
      model_id: 1800010
      model_path: met
    events:
      drink:
        potion_effect:
          type: STRENGTH
          amplifier: 1
          duration: 450
  martini:
    display_name: <#FFFFFF><bold>Martini
    resource:
      material: POTION
      generate: false
      model_id: 1800011
      model_path: martini
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  bloodymarry:
    display_name: <#D63B35><bold>BloodyMarry
    resource:
      material: POTION
      generate: false
      model_id: 1800012
      model_path: bloodymarry
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  chocolate_milk:
    display_name: <#5C322B><bold>Kakao
    resource:
      material: POTION
      generate: false
      model_id: 1800013
      model_path: chocolate_milk
    events:
      drink:
        potion_effect:
          type: LUCK
          amplifier: 1
          duration: 450
  whiskey_bottle:
    display_name: <#FBA800>Whiskey
    resource:
      material: POTION
      generate: false
      model_id: 1800014
      model_path: elitefurniture:luxury_restaurant_furniture_v1/whiskey_bottle
    lore:
    - '&6Ethria Single Malt'
    - '&412 years old'
    - '&6since 1804'
    - '&c58% Vol.'
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  wine_bottle:
    display_name: <#56070C>Wein
    resource:
      material: POTION
      generate: false
      model_id: 1800015
      model_path: elitefurniture:luxury_restaurant_furniture_v1/wine_bottle
    lore:
    - '&4Weingut Etrhia'
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 250
  vampire_soda:
    display_name: <rw Vampire Soda>
    resource:
      material: POTION
      generate: true
      model_id: 1800016
      textures:
      - xhalloween/vampire_soda.png
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  toxic_soda:
    display_name: <rw Toxic Soda>
    resource:
      material: POTION
      generate: true
      model_id: 1800017
      textures:
      - xhalloween/toxic_soda.png
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  zombie_virus:
    display_name: <rw Zombie Virus Soda>
    resource:
      material: POTION
      generate: true
      model_id: 1800018
      textures:
      - xhalloween/zombie_virus.png
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  scream_soda:
    display_name: <rw Scream Soda>
    resource:
      material: POTION
      generate: true
      model_id: 1800019
      textures:
      - xhalloween/scream_soda.png
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  halloween_shake:
    display_name: <rw Halloween Shake>
    resource:
      material: POTION
      generate: true
      model_id: 1800020
      textures:
      - xhalloween/halloween_shake.png
    events:
      drink:
        potion_effect:
          type: NAUSEA
          amplifier: 1
          duration: 500
  ghostly_tonic:
    display_name: <rw Ghostly Tonic>
    resource:
      material: POTION
      generate: true
      model_id: 1800021
      textures:
      - xhalloween/ghostly_tonic.png
    events:
      drink:
        potion_effect:
          type: INVISIBILITY
          amplifier: 1
          duration: 500
  caffeebar:
    display_name: <red>caffeebar
    lore:
    - <red>NICHT AUSGEBEN. FEHLER MIT PROTOCOLLIB
    - <red>ERST TESTEN UND IM LOG NACHSEHEN
    resource:
      material: PAPER
      generate: false
      model_id: 1800022
      model_path: caffeebar/caffeebar
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: false
      furniture_trade_machine:
        title: caffeebar
        gui_texture:
          left: caffeebar_left
          right: caffeebar_right
        trades_list:
          hamburger:
            ingredients:
              slot1:
                item: drinks:cialda
                amount: 1
              slot2:
                item: drinks:empty_cup
                amount: 1
            result:
              item: drinks:caffeebar_coffee
              amount: 1
  cialda:
    display_name: Cialda
    resource:
      material: PAPER
      generate: false
      model_id: 1800023
      model_path: caffeebar/cialda
  caffeebar_coffee:
    display_name: caffe
    resource:
      material: POTION
      generate: true
      model_id: 1800024
      textures:
      - caffeebar/item/coffee
    specific_properties:
      potion:
        type: WATER
        color: WHITE
    item_flags:
    - HIDE_POTION_EFFECTS
    events:
      drink:
        increment_player_stat:
          name: thirst
          amount: 2
        potion_effect:
          type: SPEED
          amplifier: 1
          duration: 100
  empty_cup:
    display_name: tazza vuota
    resource:
      material: STICK
      generate: true
      model_id: 1800025
      textures:
      - caffeebar/item/empty_cup
```
