### ISSUE TITLE
Blast furnrace baking is not working

### ISSUE THREAD

**Issue by pjindras** [PluginBugs/Issues-ItemsAdder#4514]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

detektiv_tank

### What happened?

When I put the item into Blast furnrace, its not working, in classic furnrace, it works, but with issues. (#4498)

### Steps to reproduce the issue

When I put the item into Blast furnrace, its not working, in classic furnrace, it works, but with issues. (#4498)

### Server version

Paper 1.21.1 v132

### ItemsAdder Version

4.0.9

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/5UUsJrg

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
jadeingot:
      ingredient:
        item: minerals_pack:raw_jade
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 3
      cook_time: 300
      result:
        item: minerals_pack:jade_ingot
        amount: 1
```
