### ISSUE TITLE
Entity Furniture issues

### ISSUE THREAD

**Issue by VergilPrime** [PluginBugs/Issues-ItemsAdder#4518]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

VergilPrime

### What happened?

- For one reason or another this didn't work unless I split entities out into it's own file. Not sure if that's intended behavior. Might have been an error on my part.

- If entity type under "entities" is armor_stand, bones get mildly randomized position and rotation, offsetting the mushroom from the base

- If entity type is "shulker" it snaps to 90 degrees but always faces the same direction. Placing while facing south or east results in the furniture occupying the same space as the block it's being placed against (wall placement).

- If the entity type is "item_display", then it throws an error trying to cast as living entity

- No way for color to be inherited from the item (which is dyable) to the furniture (afaik)

### Steps to reproduce the issue

Place the furniture

### Server version

This server is running Paper version 1.21.4-211-main@6ea4202 (2025-03-13T11:49:31Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

[06:29:01 INFO]: ItemsAdder version 4.0.9-hotfix-1
[06:29:01 INFO]: Customized Minecraft without client mods!
[06:29:01 INFO]: Website: devs.beer
[06:29:01 INFO]: Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.65
Collection of libs used by my plugins
Authors: LoneDev and others

### Full Server Log

https://mclo.gs/5eQM1J8

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
decorations.yml:
:
  namespace: angels_reach
categories:
  decorations:
    enabled: true
    icon: angels_reach:trophy
    name: Decorations
    items:
    - angels_reach:mushroom_sign
    
items:
  mushroom_sign:
    display_name: Mushroom Sign
    lore:
    - "Dyeable with regular dyes."
    resource:
      material: LEATHER_HORSE_ARMOR
      model_path: decorations/sign_mushroom
      model_id: 40000
      generate: false
    behaviours:
      complex_furniture:
        entity: sign_mushroom_spin
        light_level: 4
        drop_when_mined: true
        max_per_chunk: 16
        solid: false
        placeable_on:
          floor: false
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
    specific_properties:
      leather_horse_armor:
        color: MAROON

entities.yml:
:
  namespace: angels_reach
entities:
  sign_mushroom_spin:
    display_name: "Mushroom Sign"
    type: SHULKER
    gravity: false
    model_folder: entity/sign_mushroom_spin
    silent: true
    ai: false
    invulnerable: true
```

### Other files, you can drag and drop them here to upload. (optional)

[generated.zip](https://github.com/user-attachments/files/19340013/generated.zip)
