### ISSUE TITLE
Recipe Improvement!

### ISSUE THREAD

**Issue by 00Hrtz** [PluginBugs/Issues-ItemsAdder#4519]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

00_hrtz

### Describe the solution you'd like

```yaml
    comb:
      permission: bees_wax
      enabled: true
      pattern:
      - XXX
      - XGX
      - XHX
      ingredients:
        G: GLASS_BOTTLE
        H: HONEYCOMB
      result:
        item: customitems:comb
        amount: 1 
        item: customitems:honey_bottle
        amount: 1
```

Tried the above to no avail, looking to have multiple item results from one recipe.

### Is your feature request related to a problem?

Need to be able to reward multiple items, apologies if this has already been previously requested, i've checked and couldn't find anyone else who's requested it.

### Describe alternatives you've considered

alternatives would require adding more plugins and my servers drowned with plugins already.
