### ISSUE TITLE
Option for plugins to register custom function to execute via Item YAML event functions

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4520]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

andre601

### Describe the solution you'd like

An API feature that allows plugins to register their own custom event functions a user can execute via YAML `events` configuration.

As an example, assume the following is doable via the Java API:
```java
MyPlugin plugin = // Get plugin instance

CustomStack.registerCustomEvent(plugin, "myfunction", event -> {
    // Do stuff here.
    
    // event would be a an event class (i.e. CustomStackEvent?) that holds various
    // info such as the event type (interaction, ...), CustomStack used, etc.
    return event;
});
```

this would now allow a player to do this:
```yaml
info:
  namespace: mynamespace
items:
  my_item:
    // Your usual item stuff
    events:
      interact:
        right:
          custom: # Defines the custom function call.
            plugin: "MyPlugin"
            function: "myfunction"
```
The plugin instance is for avoiding possible conflicts where multiple plugins could define the same function, causing issues. By requiring a plugin instance this ambiguity can be avoided here.

### Is your feature request related to a problem?

Right now are plugins required to perform various checks themself, and also implement the event in question themself to perform necessary actions, which can be rather tedious to do.

With this solution would it be possible to support all the different Item Events in ItemsAdder without having to repeat too much of the (possibly) same code, while also having to do less checks as ItemsAdder would ensure this having been done already.

### Describe alternatives you've considered

Listening for all the events you may want to use and support with the CustomStack itself and perform all the checks there (is custom stack, is X event type, etc.)
