### ISSUE TITLE
Rename `permission` to `permission_suffix` in `font_images`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4524]
Rename the property `permission` into `permission_suffix` to enhance the font images permissions to create groups.
Right now it already acts as a permission suffix, but the property name is misleading.

For example set `permission_suffix: group_1.smile` will allow you to set `ia.user.image.use.group_1.*` to add all the emojis in a single line, instead of having to assign their permission one by one to the players.

Example:

You can now use
- `ia.user.image.use.mcemojis.*` to grant all the `mcemojis` to a player
- `ia.user.image.use.mcemojis.blocks` to grant all the `mcemojis` which are `blocks` to a player

```yml
info:
  namespace: "mcemojis"
font_images:
  mc_acacia_boat:
    permission_suffix: mcemojis.blocks.mc_acacia_boat
    show_in_gui: true
    path: "minecraft:item/acacia_boat"
    scale_ratio: 9
    y_position: 8
  mc_acacia_door:
    permission_suffix: mcemojis.blocks.mc_acacia_door
    show_in_gui: true
    path: "minecraft:item/acacia_door"
    scale_ratio: 9
  mc_arrow:
    permission_suffix: mcemojis.items.mc_arrow
    show_in_gui: true
    path: "minecraft:item/arrow"
    scale_ratio: 9
    y_position: 8
```
