### ISSUE TITLE
Lag Issue -> Chat?

### ISSUE THREAD

**Issue by bobhenl** [PluginBugs/Issues-ItemsAdder#4530]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

Hello, I'm not aware of using any chat feature by the ItemsAdder but it'S causing HUGE lags on my server. Even when I just thought that I loaded the pack and there it ends, the only feature I'm aware of using is the scoreboard one to remove numbers.

How can I disable this "chat" feature, and can it be fixed so it doesn't cause these huge lags please?

So, firstly, look at this Spark report please and on both of the spikes: https://spark.lucko.me/vd2uz9ZiGY
First one:

![Image](https://github.com/user-attachments/assets/b154dca0-d38b-4d7e-8514-3f30215e906f)
Second one:

![Image](https://github.com/user-attachments/assets/30228c2c-f7c9-4fd4-9cd5-fc88b2fd10bb)

I measured the protocollib timings and here are the results as well
```yml
Started: Sun Mar 23 14:23:16 UTC 2025
Stopped: Sun Mar 23 15:02:39 UTC 2025 (after 2362 seconds)

... (full log below, Itemsadder is consuming the most)

=== PLUGIN ItemsAdder ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           BLOCK_DIG                     59270        0.000030        2615.909628     0.077193        11.981248 
 PLAY           STEER_VEHICLE                 134590       0.000070        14.546913       0.001496        0.043553 
 PLAY           TR_SEL                        4            0.026650        0.937732        0.261078        0.451147 
 PLAY           UPDATE_SIGN                   2            0.012270        0.015280        0.013775        0.002128 
 SUM            -                             193866       0.000030        2615.909628     0.024644        6.624792 
 -------------------------------------------------------------------------------------------------------------------------------------------
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           OPEN_WINDOW_MERCHANT          3            0.008140        0.013510        0.011360        0.002840 
 PLAY           OPEN_WINDOW                   1890         0.007680        6.067000        0.117667        0.186408 
 PLAY           RECIPE_BOOK_ADD               1106         0.000060        0.290618        0.003019        0.017449 
 PLAY           SYSTEM_CHAT                   71333        0.000030        86.246313       0.230551        1.376714 
 CONFIGURATION  ADD_RESOURCE_PACK             45           0.140229        5.003349        0.340011        0.716760 
 SUM            -                             74377        0.000030        86.246313       0.224357        1.349084 
 => Time on main thread: 16686.967502 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

```

What is the: SYSTEM_CHAT?? I'm not aware of using it

Neither other functions like:
OPEN_WINDOW??
RECIPE_BOOK_ADD -> I don't need that neither?

STEER_VEHICLE ??
BLOCK_DIG ??

I provided full config as well, so you can check & share advice please what I can disable if I use only the generating pack & hiding numbers in scoreboard.

### Steps to reproduce the issue

1. I just measured the spark report
2. And the Protocollib timings /protocollib:protocol timings

### Server version

[15:06:20 INFO]: Checking version, please wait...
[15:06:20 INFO]: Current Purpur Version: 1.21.4-2408-5d1df70 (MC: 1.21.4)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

[15:06:35 INFO]: ItemsAdder version 4.0.8
[15:06:35 INFO]: Customized Minecraft without client mods!
[15:06:35 INFO]: Website: devs.beer
[15:06:35 INFO]: Author: LoneDev

### ProtocolLib Version

[15:06:48 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-739
[15:06:48 INFO]: Provides read/write access to the Minecraft protocol.
[15:06:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:06:56 INFO]: LoneLibs version 1.0.65
[15:06:56 INFO]: Collection of libs used by my plugins
[15:06:56 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/w1TWAri

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
Full config, so you can check where's the issue, or what I can disable, as I don't need anything else than generating the pack & hiding scoreboard numbers:

metrics: false
update-checker: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: XXXX(SECRET)
      pack-port: 41167
      append-port: true
      protection:
        block_non_game_requests: false
        rate_limit:
          enabled: false
          max_requests: 3
          period_seconds: 2
          cooldown:
            enabled: false
            duration_minutes: 30
            trigger_on_failed_times: 5
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
    lobfile:
      enabled: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    lock-player: false
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
      vanilla: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: false
    contents-folders-priority:
    - vanilla
    - deadly_disasters
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    compress-shader-files: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: false
    step:
      enabled: true
      allow_non_player: true
    other: true
  expert_users: {}
  atlas_support: false
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  allow_other_plugins_resourcepacks: false
  notify_other_plugins_resourcepacks: true
  pre_1_21_2_shaders_fix:
    enabled: true
  auto_apply:
    enabled: false
    before_join: true
    delay_ticks: 1
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: false
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: false
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
  custom:
    mushroom: true
    chorus: true
    note: true
    wire: false
    fire: true
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
  itemsadder_trade_machines: true
  vanilla_villagers: false
  other_plugins: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
liquids:
  enabled: true
huds:
  enabled: false
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  enabled: true
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
font_images:
  chat:
    enabled: true
    add_hover_suggestion: true
    tab_autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
  customitem_name_and_lore:
    enabled: true
effects:
  hide-scoreboard-numbers: true
  hide-scoreboard-numbers-old-clients: false
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: false
    interval-rendering-packets-ticks: 1
    expert_users:
      delay_packets: false
      extract_emotes_shaders: false
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup: {}
      on-item-click: {}
      automatically: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
    log-files-reloading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  resourcepacks:
    log_player_install: false
    compression:
      files: true
      overlays: true
  issues:
    log_font_image_replace_json_syntax_exception: true
  blocks-populators:
    log-generation: false
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
cooldown_bars:
  enabled: false
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
text_effects:
  enabled: true
  chat:
    enabled: true
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  legacy_colors_compatibility: true
  customitem_name_and_lore:
    enabled: true
  hide_scoreboard_numbers: false
  hide_scoreboard_numbers_old_clients: false
cache_font_images_and_effects_replacements: true
```

### Other files, you can drag and drop them here to upload. (optional)

Full timings from ProtocolLib:
```yml
Started: Sun Mar 23 14:23:16 UTC 2025
Stopped: Sun Mar 23 15:02:39 UTC 2025 (after 2362 seconds)

=== PLUGIN WorldGuardExtraFlags ===
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           REMOVE_ENTITY_EFFECT          882          0.000120        2.304087        0.017746        0.077654 
 => Time on main thread: 15.652083 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN ChatControl ===
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           WINDOW_ITEMS                  10280        0.002550        29.940220       0.147592        0.449396 
 PLAY           SET_SLOT                      98102        0.000060        15.328252       0.007503        0.060378 
 PLAY           OPEN_WINDOW_MERCHANT          3            0.081790        0.388957        0.264175        0.161482 
 SUM            -                             108385       0.000060        29.940220       0.020798        0.155370 
 => Time on main thread: 2254.142492 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN Citizens ===
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           REL_ENTITY_MOVE_LOOK          910497       0.000030        2.637414        0.000239        0.005372 
 PLAY           ENTITY_LOOK                   212492       0.000030        2.202967        0.000317        0.006170 
 PLAY           PLAYER_INFO                   72051        0.000070        1.473421        0.001180        0.011630 
 PLAY           ENTITY_HEAD_ROTATION          1556717      0.000029        29.661662       0.000193        0.025323 
 PLAY           ENTITY_METADATA               788079       0.000080        17.918056       0.002259        0.033664 
 PLAY           ENTITY_EQUIPMENT              75152        0.000080        1.370551        0.001583        0.007220 
 PLAY           ENTITY_TELEPORT               5307         0.000030        0.589286        0.000860        0.008557 
 SUM            -                             3620295      0.000029        29.661662       0.000711        0.023147 
 => Time on main thread: 2573.699258 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN VotingPlugin ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           UPDATE_SIGN                   2            0.009470        0.011460        0.010465        0.001407 
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN Images ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           USE_ENTITY                    6727         0.000090        1.380582        0.003204        0.017247 
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN LiteBans ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           CHAT_COMMAND                  448          0.003030        0.184479        0.011740        0.011097 
 PLAY           CHAT                          420          0.002310        0.144329        0.010631        0.008343 
 SUM            -                             868          0.002310        0.184479        0.011204        0.009871 
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN AdvancedReplay ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           POSITION                      477265       0.000020        2.245484        0.000466        0.007330 
 PLAY           POSITION_LOOK                 606180       0.000020        7.038823        0.000546        0.013765 
 PLAY           LOOK                          113535       0.000020        2.312505        0.000500        0.007206 
 PLAY           BLOCK_DIG                     46941        0.000020        1.074192        0.000507        0.006132 
 PLAY           ENTITY_ACTION                 41381        0.000020        0.708186        0.001119        0.006790 
 PLAY           ARM_ANIMATION                 116455       0.000020        1.074653        0.000309        0.003605 
 SUM            -                             1401757      0.000020        7.038823        0.000511        0.010399 
 -------------------------------------------------------------------------------------------------------------------------------------------
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           SPAWN_ENTITY                  246718       0.000010        4.404664        0.001074        0.014340 
 PLAY           EXPLOSION                     4610         0.000020        1.039563        0.008895        0.035902 
 PLAY           REL_ENTITY_MOVE               3881971      0.000010        21.057795       0.000133        0.011087 
 PLAY           REL_ENTITY_MOVE_LOOK          1520209      0.000010        10.492138       0.000170        0.011444 
 PLAY           ENTITY_LOOK                   345567       0.000010        3.107407        0.000099        0.005416 
 PLAY           POSITION                      5273         0.000020        0.117859        0.000329        0.001664 
 PLAY           ENTITY_DESTROY                291178       0.000010        1.731189        0.000401        0.004345 
 PLAY           ENTITY_VELOCITY               2809202      0.000010        7.124193        0.000172        0.006787 
 PLAY           ENTITY_TELEPORT               9490         0.000020        2.044038        0.000312        0.021026 
 SUM            -                             9114218      0.000010        21.057795       0.000189        0.009840 
 => Time on main thread: 1722.527597 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN InteractiveChat ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           CHAT_COMMAND                  448          0.000480        0.006300        0.002154        0.001168 
 PLAY           CHAT_COMMAND_SIGNED           109          0.001560        0.042379        0.013318        0.004368 
 PLAY           CHAT                          420          0.000150        0.062870        0.002036        0.003207 
 CONFIGURATION  CLIENT_INFORMATION            42           0.006530        0.037440        0.016458        0.006020 
 SUM            -                             1019         0.000150        0.062870        0.003889        0.005205 
 -------------------------------------------------------------------------------------------------------------------------------------------
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           TAB_COMPLETE                  1444         0.000240        0.128669        0.006086        0.006839 
 PLAY           SERVER_DATA                   44           0.006520        0.041720        0.017090        0.006137 
 PLAY           SET_ACTION_BAR_TEXT           348          0.000030        0.005250        0.001149        0.000922 
 PLAY           SET_SUBTITLE_TEXT             2506         0.000020        0.397307        0.000254        0.007938 
 PLAY           SET_TITLE_TEXT                2842         0.000020        0.148498        0.000540        0.003822 
 PLAY           SYSTEM_CHAT                   71333        0.000040        21.673469       0.026789        0.285499 
 SUM            -                             78517        0.000020        21.673469       0.024492        0.272229 
 => Time on main thread: 1923.022171 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN CMI ===
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           UNLOAD_CHUNK                  220423       0.000019        0.131319        0.000077        0.000618 
 => Time on main thread: 16.903650 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

=== PLUGIN ItemsAdder ===
 TYPE: SYNC_INBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           BLOCK_DIG                     59270        0.000030        2615.909628     0.077193        11.981248 
 PLAY           STEER_VEHICLE                 134590       0.000070        14.546913       0.001496        0.043553 
 PLAY           TR_SEL                        4            0.026650        0.937732        0.261078        0.451147 
 PLAY           UPDATE_SIGN                   2            0.012270        0.015280        0.013775        0.002128 
 SUM            -                             193866       0.000030        2615.909628     0.024644        6.624792 
 -------------------------------------------------------------------------------------------------------------------------------------------
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           OPEN_WINDOW_MERCHANT          3            0.008140        0.013510        0.011360        0.002840 
 PLAY           OPEN_WINDOW                   1890         0.007680        6.067000        0.117667        0.186408 
 PLAY           RECIPE_BOOK_ADD               1106         0.000060        0.290618        0.003019        0.017449 
 PLAY           SYSTEM_CHAT                   71333        0.000030        86.246313       0.230551        1.376714 
 CONFIGURATION  ADD_RESOURCE_PACK             45           0.140229        5.003349        0.340011        0.716760 
 SUM            -                             74377        0.000030        86.246313       0.224357        1.349084 
 => Time on main thread: 16686.967502 ms
 -------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by bobhenl** [comment]
Even when I probably disable it via 
```yml
font_images:
  chat:
    enabled: true
```

There are still some strange things that consume a bit even when I really don't know about any usage of ItemsAdder?

Like I use it only to generate pack, and the scoreboard, so why it's used continuously? How can I optimize it even more?

![Image](https://github.com/user-attachments/assets/8a5e7b40-285f-42e6-828e-371b94baac5f)
https://spark.lucko.me/ocSVNJlpdH

![Image](https://github.com/user-attachments/assets/c6ba1386-7791-447f-8041-5edc88883b2d)
