### ISSUE TITLE
Crop Generation(Strings) are no longer instant break and when item drops it does not show the name correct

### ISSUE THREAD

**Issue by iFranticman** [PluginBugs/Issues-ItemsAdder#4532]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

Not sure i can't figure out why the crops are not instant break anymore.

### Steps to reproduce the issue

break block they are no longer instant.

### Server version

1.20.6

### ItemsAdder Version

Latest i know you hate that but it's true i checked.

### ProtocolLib Version

741 5.4.0-snapshot 741

### LoneLibs Version

741 5.4.0-snapshot 741

### Full Server Log

https://mclo.gs/Df2JyB8

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
#███╗░░░███╗░█████╗░██╗░░██╗███████╗  ░██████╗██╗░░░██╗██████╗░███████╗  ████████╗░█████╗░ ░██████╗███████╗████████╗
#████╗░████║██╔══██╗██║░██╔╝██╔════╝  ██╔════╝██║░░░██║██╔══██╗██╔════╝  ╚══██╔══╝██╔══██╗ ██╔════╝██╔════╝╚══██╔══╝
#██╔████╔██║███████║█████═╝░█████╗░░  ╚█████╗░██║░░░██║██████╔╝█████╗░░  ░░░██║░░░██║░░██║ ╚█████╗░█████╗░░░░░██║░░░
#██║╚██╔╝██║██╔══██║██╔═██╗░██╔══╝░░  ░╚═══██╗██║░░░██║██╔══██╗██╔══╝░░  ░░░██║░░░██║░░██║ ░╚═══██╗██╔══╝░░░░░██║░░░
#██║░╚═╝░██║██║░░██║██║░╚██╗███████╗  ██████╔╝╚██████╔╝██║░░██║███████╗  ░░░██║░░░╚█████╔╝ ██████╔╝███████╗░░░██║░░░
#╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝  ╚═════╝░░╚═════╝░╚═╝░░╚═╝╚══════╝  ░░░╚═╝░░░░╚════╝░ ╚═════╝░╚══════╝░░░╚═╝░░░
#
#██████╗░██╗░██████╗░█████╗░██████╗░██╗░░░░░███████╗░░░░░░██████╗░███████╗░█████╗░██╗░░░░░░██╗░░░░░░░██╗██╗██████╗░███████╗██╗  ███████╗░█████╗░██╗░░░░░░██████╗███████╗
#██╔══██╗██║██╔════╝██╔══██╗██╔══██╗██║░░░░░██╔════╝░░░░░░██╔══██╗██╔════╝██╔══██╗██║░░░░░░██║░░██╗░░██║██║██╔══██╗██╔════╝╚═╝  ██╔════╝██╔══██╗██║░░░░░██╔════╝██╔════╝
#██║░░██║██║╚█████╗░███████║██████╦╝██║░░░░░█████╗░░█████╗██████╔╝█████╗░░███████║██║░░░░░░╚██╗████╗██╔╝██║██████╔╝█████╗░░░░░  █████╗░░███████║██║░░░░░╚█████╗░█████╗░░
#██║░░██║██║░╚═══██╗██╔══██║██╔══██╗██║░░░░░██╔══╝░░╚════╝██╔══██╗██╔══╝░░██╔══██║██║░░░░░░░████╔═████║░██║██╔══██╗██╔══╝░░░░░  ██╔══╝░░██╔══██║██║░░░░░░╚═══██╗██╔══╝░░
#██████╔╝██║██████╔╝██║░░██║██████╦╝███████╗███████╗░░░░░░██║░░██║███████╗██║░░██║███████╗░░╚██╔╝░╚██╔╝░██║██║░░██║███████╗██╗  ██╔══╝░░██╔══██║██║░░░░░░╚═══██╗██╔══╝░░
#╚═════╝░╚═╝╚═════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚══════╝░░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚═╝  ██║░░░░░██║░░██║███████╗██████╔╝███████╗
#
#██╗███╗░░██╗  ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░░░░██╗░░░██╗███╗░░░███╗██╗░░░░░
#██║████╗░██║  ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░░░░╚██╗░██╔╝████╗░████║██║░░░░░
#██║██╔██╗██║  ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░░░░░╚████╔╝░██╔████╔██║██║░░░░░
#██║██║╚████║  ██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗░░░░░╚██╔╝░░██║╚██╔╝██║██║░░░░░
#██║██║░╚███║  ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝██╗░░░██║░░░██║░╚═╝░██║███████╗
#╚═╝╚═╝░░╚══╝  ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝╚══════╝
info:
  namespace: munchies
recipes:
  crafting_table:
    cornstalk:
      enabled: true
      pattern:
        - XCX
        - XCX
        - CCC
      ingredients:
        C: munchies:corn
      result:
        item: munchies:cornstalk
        amount: 1
    cauliflowerplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - XCX
      ingredients:
        C: munchies:cauliflower
      result:
        item: munchies:cauliflowerplant
        amount: 1
    gingerplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - CCC
      ingredients:
        C: munchies:gingerroot
      result:
        item: munchies:gingerplant
        amount: 1
    garlicplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - CCC
      ingredients:
        C: munchies:garlic
      result:
        item: munchies:garlicplant
        amount: 1
    eggplantstalk:
      enabled: true
      pattern:
        - XXX
        - XCX
        - XCX
      ingredients:
        C: munchies:eggplant
      result:
        item: munchies:eggplantstalk
        amount: 1
    onionplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - XCX
      ingredients:
        C: munchies:onion
      result:
        item: munchies:onionplant
        amount: 1
    peanutplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - CCC
      ingredients:
        C: munchies:peanut
      result:
        item: munchies:peanutplant
        amount: 1
    squashplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - CCC
      ingredients:
        C: munchies:squash
      result:
        item: munchies:squashplant
        amount: 1
    tomatoplant:
      enabled: true
      pattern:
        - XXX
        - XCX
        - CCC
      ingredients:
        C: munchies:tomato
      result:
        item: munchies:tomatoplant
        amount: 1
    grapebush:
      enabled: true
      pattern:
        - XXX
        - CCC
        - CSC
      ingredients:
        C: munchies:grapes
        S: STICK
      result:
        item: munchies:grapebush
        amount: 1
items:
  cornstalk:
    enabled: true
    display_name: Corn Stalk
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/cornstalk
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  cauliflowerplant:
    enabled: true
    display_name: Cauliflower Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/cauliflowerplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  gingerplant:
    enabled: true
    display_name: Ginger Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/gingerplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  garlicplant:
    enabled: true
    display_name: Garlic Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/garlicplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  eggplantstalk:
    enabled: true
    display_name: Eggplant Stalk
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/eggplantstalk
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  onionplant:
    enabled: true
    display_name: Onion Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/onionplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          break_particles: ITEM
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  peanutplant:
    enabled: true
    display_name: Peanut Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/peanutplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  squashplant:
    enabled: true
    display_name: Squash Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/squashplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  tomatoplant:
    enabled: true
    display_name: Tomato Plant
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/tomatoplant
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  grapebush:
    enabled: true
    display_name: Grape Bush
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/grapebush
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
  crabcage:
    enabled: true
    display_name: Crab Trap
    resource:
      generate: false
      material: PAPER
      model_path: wilderness/crabcage
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          break_particles: ITEM
          placeable_on_water: true
        cancel_drop: true
        sound:
          place:
            name: block_chain_place
          break:
            name: block_chain_break
surface_decorators:
  cornstalk:
    block: cornstalk
    bottom_blocks:
    - GRASS_BLOCK
    - FARMLAND
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - BIRCH_FOREST
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - GIANT_TREE_TAIGA
    - JUNGLE
    - JUNGLE_EDGE
    - MODIFIED_JUNGLE
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  cauliflowerplant:
    block: cauliflowerplant
    bottom_blocks:
    - GRASS_BLOCK
    - FARMLAND
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  gingerplant:
    block: gingerplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  garlicplant:
    block: garlicplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  eggplantstalk:
    block: eggplantstalk
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  onionplant:
    block: onionplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  peanutplant:
    block: peanutplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  squashplant:
    block: squashplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  tomatoplant:
    block: tomatoplant
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  grapebush:
    block: grapebush
    bottom_blocks:
    - GRASS_BLOCK
    biomes:
    - PLAINS
    - TAIGA
    - GIANT_SPRUCE_TAIGA
    - FOREST
    - FLOWER_FOREST
    - DARK_FOREST
    worlds:
      - world
      - Survival
    chance: 15
    max_height: 255 
    min_height: 60
    amount: 1
  crabcage:
    block: crabcage
    bottom_blocks:
    - WATER
    biomes:
    - OCEAN
    - DEEP_OCEAN
    - WARM_OCEAN
    - COLD_OCEAN
    - BEACH
    worlds:
      - world
      - Survival
    chance: 1
    max_height: 100
    min_height: 50
    amount: 1
loots:
  blocks:
    cornstalk:
      enabled: true
      type: cornstalk
      items:
        corn:
          item: munchies:corn
          min_amount: 1
          max_amount: 3
          chance: 100
          ignore_fortune: true
    cauliflowerplant:
      enabled: true
      type: cauliflowerplant
      items:
        cauliflower:
          item: munchies:cauliflower
          min_amount: 1
          max_amount: 1
          chance: 100
          ignore_fortune: true
    gingerplant:
      enabled: true
      type: gingerplant
      items:
        gingerroot:
          item: munchies:gingerroot
          min_amount: 1
          max_amount: 3
          chance: 100
          ignore_fortune: true
    garlicplant:
      enabled: true
      type: garlicplant
      items:
        garlic:
          item: munchies:garlic
          min_amount: 1
          max_amount: 3
          chance: 100
          ignore_fortune: true
    eggplantstalk:
      enabled: true
      type: eggplantstalk
      items:
        eggplant:
          item: munchies:eggplant
          min_amount: 1
          max_amount: 3
          chance: 100
          ignore_fortune: true
    onionplant:
      enabled: true
      type: onionplant
      items:
        onion:
          item: munchies:onion
          min_amount: 1
          max_amount: 3
          chance: 100
          ignore_fortune: true
    peanutplant:
      enabled: true
      type: peanutplant
      items:
        peanut:
          item: munchies:peanut
          min_amount: 1
          max_amount: 4
          chance: 100
          ignore_fortune: true
    squashplant:
      enabled: true
      type: squashplant
      items:
        squash:
          item: munchies:squash
          min_amount: 1
          max_amount: 2
          chance: 100
          ignore_fortune: true
    tomatoplant:
      enabled: true
      type: tomatoplant
      items:
        tomato:
          item: munchies:tomato
          min_amount: 1
          max_amount: 4
          chance: 100
          ignore_fortune: true
    grapebush:
      enabled: true
      type: grapebush
      items:
        grapes:
          item: munchies:grapes
          min_amount: 1
          max_amount: 4
          chance: 100
          ignore_fortune: true
    crabcage:
      enabled: true
      type: crabcage
      items:
        planks:
          item: OAK_PLANKS
          min_amount: 3
          max_amount: 10
          chance: 5
          ignore_fortune: true
        stick:
          item: STICK
          min_amount: 3
          max_amount: 6
          chance: 100
          ignore_fortune: true
        clam:
          item: munchies:clam
          min_amount: 1
          max_amount: 1
          chance: 10
        crab:
          item: munchies:crab
          min_amount: 1
          max_amount: 1
          chance: 40
        seaweed:
          item: munchies:seaweed
          min_amount: 1
          max_amount: 1
          chance: 40
        rawshrimp:
          item: munchies:rawshrimp
          min_amount: 1
          max_amount: 1
          chance: 5
        caviar:
          item: munchies:caviar
          min_amount: 0
          max_amount: 1
          chance: 1
        rawanchovy:
          item: munchies:rawanchovy
          min_amount: 1
          max_amount: 1
          chance: 5
        rawlionfish:
          item: munchies:rawlionfish
          min_amount: 1
          max_amount: 1
          chance: 5
        rawoctopus:
          item: munchies:rawoctopus
          min_amount: 1
          max_amount: 1
          chance: 5
        rawtilapia:
          item: munchies:rawtilapia
          min_amount: 1
          max_amount: 1
          chance: 5
        rawtuna:
          item: munchies:rawtuna
          min_amount: 1
          max_amount: 1
          chance: 5
```
