### ISSUE TITLE
Crafting template option

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4535]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

andre601

### Describe the solution you'd like

A feature similar to an item template, but for crafting.
When set, you can re-use a pre-existing crafting recipe and either change the pattern or (more useful) the ingredients.

As an example, assume we want to make a crafting recipe to get ourself a hammer, which would be available as wood, stone, gold, iron or diamond tier.
With the template feature, we could setup the following:

```yaml
info:
  namespace: hammertime
recipes:
  crafting_table:
    #
    # Setup our template
    hammer_template_recipe:
      template: true
      pattern:
        - 'XAX'
        - 'ASX'
        - 'XXS'
      pattern_2:
        - 'XAX'
        - 'XSA'
        - 'SXX'
      ingredients:
        # Ingredient A will be defined later
        S: STICK
      #
      # No result, as that will be set in other recipes.
      #
    wooden_hammer:
      variant_of: hammer_template_recipe # Load in our recipe
      ingredients:
        A: OAK_PLANKS
      result:
        item: hammertime:wooden_hammer
    stone_hammer:
      variant_of: hammer_template_recipe # Load in our recipe
      ingredients:
        A: COBBLESTONE
      result:
        item: hammertime:stone_hammer
    gold_hammer:
      variant_of: hammer_template_recipe
      ingredients:
        A: GOLD_INGOT
      result:
        item: hammertime:gold_hammer
    iron_hammer:
      variant_of: hammer_template_recipe
      ingredients:
        A: IRON_INGOT
      result:
        item: hammertime:iron_hammer
    diamond_hammer:
      variant_of: hammer_template_recipe
      ingredients:
        A: DIAMOND
      result:
        item: hammertime:diamond_hammer
```
This would use the patterns and the `S` ingredient defined in the template, while also setting the `A` ingredient and the returned item.

To avoid conflicts and issues should a recipe that was defined as template NOT appear within the crafting table (not be an actual recipe usable ingame)

### Is your feature request related to a problem?

It can become tedious to setup recipes for an item available in different tiers/variants, as each tier/variant requires you to copy the recipe `n` times based on the pattern.
Allowing templating can reduce duplicate configuration and ease maintainability.

### Describe alternatives you've considered

Writing out every recipe for every item variant you want to have.
