### ISSUE TITLE
`CustomFurniture.getNamespacedIdsInRegistry()` only returns template and not any variant_of furnitures

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4538]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

andre601

### What happened?

When calling `CustomFurniture.getNamespacedIdsInRegistry()` to obtain a `Set<String>` while only having a Template furniture and furnitures inheriting from that template, is it only containing the template but none of the variants.

### Steps to reproduce the issue

1. Setup furniture using a template and variants using it (Attached Zip has such a setup)
2. Use the ItemsAdder API and obtain the furniture namespaced Ids using `CustomFurniture.getNamespacedIdsInRegistry()`
3. List the registered IDs.
4. Notice only the template is present but not the variants.

### Server version

[15:05:15 INFO]: This server is running Paper version 1.21.4-190-main@5538d24 (2025-03-05T12:40:02Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[15:05:28 INFO]: ItemsAdder version 4.0.9-hotfix-1
[15:05:28 INFO]: Customized Minecraft without client mods!
[15:05:28 INFO]: Website: devs.beer
[15:05:28 INFO]: Author: LoneDev

### ProtocolLib Version

[15:05:40 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[15:05:40 INFO]: Provides read/write access to the Minecraft protocol.
[15:05:40 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

https://mclo.gs/TZYMeYA

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vanillaplus
items:
  #
  # Furniture templates
  #
  chair_template:
    template: true
    name: ""
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/black_cherry_chair
    behaviours:
      furniture:
        entity: item_display
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.75
  #
  # Animated Chair
  #
  animated_chair:
    name: "Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/animated_chair
  #
  # Birch Chairs
  #
  black_birch_chair:
    variant_of: chair_template
    name: "Black Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/black_birch_chair
  blue_birch_chair:
    variant_of: chair_template
    name: "Blue Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/blue_birch_chair
  brown_birch_chair:
    variant_of: chair_template
    name: "Brown Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/brown_birch_chair
  cyan_birch_chair:
    variant_of: chair_template
    name: "Cyan Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/cyan_birch_chair
  gray_birch_chair:
    variant_of: chair_template
    name: "Gray Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/gray_birch_chair
  green_birch_chair:
    variant_of: chair_template
    name: "Green Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/green_birch_chair
  light_blue_birch_chair:
    variant_of: chair_template
    name: "Light Blue Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/light_blue_birch_chair
  light_gray_birch_chair:
    variant_of: chair_template
    name: "Light Gray Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/light_gray_birch_chair
  lime_birch_chair:
    variant_of: chair_template
    name: "Lime Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/lime_birch_chair
  magenta_birch_chair:
    variant_of: chair_template
    name: "Magenta Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/magenta_birch_chair
  orange_birch_chair:
    variant_of: chair_template
    name: "Orange Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/orange_birch_chair
  pink_birch_chair:
    variant_of: chair_template
    name: "Pink Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/pink_birch_chair
  purple_birch_chair:
    variant_of: chair_template
    name: "Purple Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/purple_birch_chair
  red_birch_chair:
    variant_of: chair_template
    name: "Red Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/red_birch_chair
  white_birch_chair:
    variant_of: chair_template
    name: "White Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/white_birch_chair
  yellow_birch_chair:
    variant_of: chair_template
    name: "Yellow Birch Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/birch/yellow_birch_chair
  #
  # Cherry Chairs
  #
  black_cherry_chair:
    variant_of: chair_template
    name: "Black Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/black_cherry_chair
  blue_cherry_chair:
    variant_of: chair_template
    name: "Blue Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/blue_cherry_chair
  brown_cherry_chair:
    variant_of: chair_template
    name: "Brown Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/brown_cherry_chair
  cyan_cherry_chair:
    variant_of: chair_template
    name: "Cyan Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/cyan_cherry_chair
  gray_cherry_chair:
    variant_of: chair_template
    name: "Gray Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/gray_cherry_chair
  green_cherry_chair:
    variant_of: chair_template
    name: "Green Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/green_cherry_chair
  light_blue_cherry_chair:
    variant_of: chair_template
    name: "Light Blue Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/light_blue_cherry_chair
  light_gray_cherry_chair:
    variant_of: chair_template
    name: "Light Gray Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/light_gray_cherry_chair
  lime_cherry_chair:
    variant_of: chair_template
    name: "Lime Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/lime_cherry_chair
  magenta_cherry_chair:
    variant_of: chair_template
    name: "Magenta Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/magenta_cherry_chair
  orange_cherry_chair:
    variant_of: chair_template
    name: "Orange Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/orange_cherry_chair
  pink_cherry_chair:
    variant_of: chair_template
    name: "Pink Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/pink_cherry_chair
  purple_cherry_chair:
    variant_of: chair_template
    name: "Purple Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/purple_cherry_chair
  red_cherry_chair:
    variant_of: chair_template
    name: "Red Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/red_cherry_chair
  white_cherry_chair:
    variant_of: chair_template
    name: "White Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/white_cherry_chair
  yellow_cherry_chair:
    variant_of: chair_template
    name: "Yellow Cherry Chair"
    resource:
      material: PAPER
      generate: false
      model_path: chairs/cherry/yellow_cherry_chair
```

### Other files, you can drag and drop them here to upload. (optional)

This zip contains the assets and models of my current server, including the above item models. Dragging and dropping them into the contents folder should be enough to get it working.
[vanillaplus.zip](https://github.com/user-attachments/files/19431132/vanillaplus.zip)
