### ISSUE TITLE
Remove_attributes not work on armor

### ISSUE THREAD

**Issue by MLeMeur** [PluginBugs/Issues-ItemsAdder#4541]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

devact_

### What happened?

When armor reaches a durability of 0, attributes are not cancelled.

Normally, armor attributes should be at 0.
But armor remains at 3.

### Steps to reproduce the issue

1. Create a file with my config
2. Take my armor
3. Spawn mob
4. Take dommage for make durability to 0
5. Look the attributes

### Server version

This server is running Paper version 1.21.1-127-master@14a48cd (2024-10-20T23:19:03Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.8
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.3.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.63
Collection of libs used by my plugins
Authors: LoneDev and others

### Full Server Log

https://mclo.gs/Zb0InTj

### Error (optional)

```shell
[21:57:15 ERROR]: [ItemsAdder] [Items] 'my_armor:myarmor'. Error: no 'model_path' set with 'generate: true'. File: /contents/my_armor/configs/myarmor.yml
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: my_armor
items:
  myarmor:
    display_name: My Armor
    resource:
      generate: false
      material: DIAMOND_CHESTPLATE
    durability:
      durability: 2
      max_custom_durability: 1561
      disappear_when_broken: false
    events:
      on_durability_zero:
        remove_attributes: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/3ed05759-f7fe-433f-aa01-fbe7033e4017)
