### ISSUE TITLE
world_populators ignores `replacable_blocks` option

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4544]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

andre601

### What happened?

The `replacable_blocks` option for the `world_populators` seems to be ignored, causing ItemsAdder to generate blocks in mid-air and water, even if set to only replace certain blocks.

### Steps to reproduce the issue

1. Setup a world populator based on the wiki info. See the shared configuration below for a setup.
2. Generate a new World (I used Multiverse-Core)
3. See blocks generating in mid-air/water

### Server version

[14:32:52 INFO]: This server is running Paper version 1.21.4-190-main@5538d24 (2025-03-05T12:40:02Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[14:32:56 INFO]: ItemsAdder version 4.0.9-hotfix-1
[14:32:56 INFO]: Customized Minecraft without client mods!
[14:32:56 INFO]: Website: devs.beer
[14:32:56 INFO]: Author: LoneDev

### ProtocolLib Version

[14:32:59 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[14:32:59 INFO]: Provides read/write access to the Minecraft protocol.
[14:32:59 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

https://mclo.gs/ELWjCUK

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vanillaplus
worlds_populators:
  bauxite_ore:
    block: "vanillaplus:bauxite_ore"
    worlds:
      - resources
    replacable_blocks:
      - ANDESITE
      - COBBLESTONE
      - DIRT
      - GRANITE
      - GRAVEL
      - STONE
    chunk_chance: 60.0
    max_height: 64
    min_height: 24
    vein_blocks: 4
    chunk_veins: 2
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/b1e8c127-5a3e-42e8-8e29-cac2bf1831c3)

![Image](https://github.com/user-attachments/assets/f9e408c2-5700-444e-b894-aec8af55c71a)
