### ISSUE TITLE
Add a way to define parent model for an item to use in auto generation

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4547]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

andre601

### Describe the solution you'd like

ItemsAdder uses the `parent` option when auto-generating the model of an item that has `generate: true`.

It would be great if there was a way for us to tell ItemsAdder to define a different `parent` for an item while auto-generating the model of it.

I can think of two possible implementations here that could work in some way.

#### Idea 1: Make `variant_of` use template as parent

When defining and using a template via the `variant_of` could ItemsAdder define the template's model as the parent to use.

Example:
```yaml
info:
  namespace: furniture
items:
  chair_template:
    template: true
    name: ""
    resource:
      material: PAPER
      generate: false
      model_path: chair
  #
  # This would inherit all the info from the template
  # and define the model of it as the parent, unless
  # specifically set via 'model_path'.
  #
  birch_chair:
    variant_of: chair_template
    name: "Birch Chair"
    resource:
      #
      # Sets the textures to override/set in the parent.
      # The list would generate colors with a "<number>": "<texture>" pattern
      # but maybe a pattern like this to allow setting named textures should
      # be considered?
      #
      # textures:
      #   planks: "minecraft:block/birch_planks" # Sets a texture "planks": "..."
      #
      textures:
        - "minecraft:block/birch_planks"
```

**Possible Issues:**

- How to deal with a template that itself auto-generates the model? Would ItemsAdder know what model path it would have in the end?
- How to handle models that don't use the default `"<number>": "<texture path>"` but have named textures? Would my proposed variant of the textures option work?

#### Idea 2: `parent` option to directly set the parent model

The second idea would be to provide a `parent` option in `resource` to directly define the parent ItemsAdder should use while generating the model.

Example:
```yaml
info:
  namespace: chairs
items:
  birch_chair:
    name: "Birch Chair"
    resource:
      material: PAPER
      generate: true
      parent: chair # Sets the parent model to use
      #
      # Sets the textures to override/set in the parent.
      # The list would generate colors with a "<number>": "<texture>" pattern
      # but maybe a pattern like this to allow setting named textures should
      # be considered?
      #
      # textures:
      #   planks: "minecraft:block/birch_planks" # Sets a texture "planks": "..."
      #
      textures:
        - "minecraft:block/birch_planks"
```

**Possible Issues:**
- How should `variant_of` be handled? Force a parent and inherit everything else, or not allow this combination?
- How to handle models that don't use the default `"<number>": "<texture path>"` but have named textures? Would my proposed variant of the textures option work?

### Is your feature request related to a problem?

There is an issue right now, which is that you either create duplicate models, or have to create the model files inheriting from parent yourself, which creates a lot of extra work and maintenance effort depending on how many items would use the parent model.

As a personal example: I've made a parent chair model and had to create $$16*12$$ model files - one model for each combination of wool color and wood type - that inherit from it and set the textures to use, so a total of 192 individual model files to have.

Thankfully did I had tools available to mass-replace stuff in multiple files, but for an inexperienced user not being aware of such features in their editor (or their editor simply not having such a feature) can this become extremely time consuming.

Not to mention, if you change the parent model by f.e. adding another texture, are you now required to edit `n` amounts of model files, just to add this new texture, rather than editing a single YAML file where you would add another texture to the items.

### Describe alternatives you've considered

Individually creating a JSON file for each item that should use the parent.

### Additional context

I was creating variants of a wooden chair for each wool and wood type combination, which was an extremely time consuming effort as it required me to copy-paste the same models multiple times and edit them.
This made me want to have this feature in ItemsAdder to begin with.
