### ISSUE TITLE
play_sound mechanics

### ISSUE THREAD

**Issue by 00Hrtz** [PluginBugs/Issues-ItemsAdder#4548]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

00_hrtz

### What happened?

As i'm only just starting to setup sounds for the first time, i'm unsure if this is a bug or not but.

When setting up an item that has durability due to it's material being for example `SHEARS`, also setting up a sound to play, in some cases the play_sound plays as well as the material items break sound. Also in some cases certain play_sound sounds fail to play, an example that refused to play was `minecraft:item.book.page_turn`

### Steps to reproduce the issue

Create an item that uses shears as its material and setup a play sound for it. 

See that the default sound plays and dependent on which sound you use, it either refuses to play or plays over the default break sound.

### Server version

This server is running Paper version 1.21.4-212-main@bb1beda (2025-03-17T10:10:58Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[13:35:49 INFO]: ItemsAdder version 4.0.9
[13:35:49 INFO]: Customized Minecraft without client mods!
[13:35:49 INFO]: Website: devs.beer
[13:35:49 INFO]: Author: LoneDev

### ProtocolLib Version

[13:36:08 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[13:36:08 INFO]: Provides read/write access to the Minecraft protocol.
[13:36:08 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

https://mclo.gs/GGeIiJF

### Error (optional)

```shell
no errors and nothing in console so log above is empty.
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: cheques_and_bottles
items:  
###################CHEQUES#########################    
  cheque_500:
    enabled: true
    display_name: "500 Coin"
    permission: custom.cheques
    lore:
    - '&a[ &eRight Click to deposit funds &a]'   
    resource:
      material: SHEARS
      generate: false
      model_path: item/cheque
    durability:  
      max_custom_durability: 1
      custom_durability: 1
      disappear_when_broken: true  
    blocked_enchants:  
      - ALL 
    events_cooldown: 10 ########### <-- EXAMPLE 4 seconds            
    events:
      interact:
        right:
          execute_commands:
            first_cmd:
              as_console: false
              command: 'eco give {player} 500'        
          decrement_durability:
            amount: 1
          play_sound:
            name: minecraft:item.bundle.insert
            volume: 1.5
            pitch: 1
            flow:
              stop_if_any_fail: true
```
