### ISSUE TITLE
Make trade machines their own thing not bound to blocks or furniture

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4559]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

andre601

### Describe the solution you'd like

trade machines should become their own thing and no longer be bound to a block or furniture.
This would allow us to assign it to any kind of trigger such as interacting with an NPC, interacting with a sign or just executing a command.

The way this could work is as follows:

1. Create a new entry in a YAML file that may look similar to this:
    ```yaml
    info:
      namespace: mytrade
    trades: # New!
      my_trades:
        #
        # Would support all the options of block|furniture_trade_machine
        #
        title: "My custom trades"
        trades_list:
          first_trade:
            ingredients:
              slot1:
                item: STONE
                amount: 64
            result:
              item: DIAMOND
              amount: 1:
          second_trade:
            ingredients:
              slot1:
                item: DIRT
                amount: 64
            result:
              item: STONE
              amount: 1
    ```
2. A player could now execute a new command `/iatrade mytrade:my_trades` to open the trade UI

### Is your feature request related to a problem?

Trade machines are currently bound to be a block or furniture behaviour, limiting them significantly in their use, as you can't make a NPC to have trades with (unless you create an (advanced) furniture that looks like an NPC.)

### Describe alternatives you've considered

Creating a (advanced) Furniture that looks like an NPC.
