### ISSUE TITLE
Placing furniture in WorldGuard Region triggers a second player right-click/interaction.

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4561]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

andre601

### What happened?

When placing a furniture with configured sit mechanic inside a WorldGuard region do you sit down instantly.

In addition, sneaking while placing the furniture dismounts you instantly and breaks the sit mechanic by making you unable to sit on any furniture until you break the one you dismounted from instantly.

### Steps to reproduce the issue

1. Create a furniture with sit mechanic
2. Create a WorldGuard region (I've denied passthrough in mine)
3. Place furniture in the WorldGuard region

### Server version

[19:10:35 INFO]: This server is running Paper version 1.21.4-190-main@5538d24 (2025-03-05T12:40:02Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[19:10:40 INFO]: ItemsAdder version 4.0.9-hotfix-1
[19:10:40 INFO]: Customized Minecraft without client mods!
[19:10:40 INFO]: Website: devs.beer
[19:10:40 INFO]: Author: LoneDev

### ProtocolLib Version

[19:10:50 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[19:10:50 INFO]: Provides read/write access to the Minecraft protocol.
[19:10:50 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

https://mclo.gs/n9pa4a6

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vanillaplus
items:
  #
  # Furniture templates
  #
  chair_template:
    template: true
    name: ""
    resource:
      material: PAPER
      generate: false
      model_path: furniture/chair
    behaviours:
      furniture:
        entity: item_display
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.75
  black_acacia_chair:
    variant_of: chair_template
    name: "Black Acacia Chair"
    resource:
      material: PAPER
      parent: vanillaplus:furniture/chair
      generate: true
      textures:
        - 'minecraft:block/black_wool'
        - 'minecraft:block/acacia_planks'
```

### Screenshots/Videos (you can drag and drop files or paste links)

(GitHub for whatever reason refuses to upload the mp4... Can't be too big now, can it?)
https://youtu.be/4HNoGXf_ENw
