### ISSUE TITLE
Refactor the `permission` field of `categories.<category>.icons` to use a new property `permission_suffix`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4572]
```yml
info:
  namespace: mcicons
categories:
  icons:
    enabled: true
    skip_if_already: false
    icon: mcicons:icon_web
    name: display-category-icons
    permission: ia.menu.seecategory.icons
    items:
      - mcicons:icon_left_grey
      # .....
```

Right now makes no sense to have to put the complete ItemsAdder permission there (`ia.menu.seecategory.icons`).
