### ISSUE TITLE
Setting `durability.usages` property only causes `Error: 'max_durability' must be > 0`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4573]
Setting `durability.usages` property only causes `Error: 'max_durability' must be > 0`.

Example item:
```yml
  cigar:
    enabled: true
    display_name: display-name-cigar
    permission: iawearables.cigar
    resource:
      material: FEATHER
      generate: false
      model_path: hat/cigar
    durability:
      usages: 5
```
