### ISSUE TITLE
Add a required plugin versions field to config files

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4580]
It would allow addon creators to specify versions or a version range for an addon that would make IA not load it if not supported.
```yml
info:
  namespace: lorem
  #
  # Sets the lowest supported version.
  min_version: 1.20.6
  #
  # Sets the latest supported version
  max_version: 1.21.5
  #
  # Sets specific versions
  versions: [1.20.6, 1.21.4, 1.21.5]
#
# Your other addon stuff
```

Maybe also add a `sennd_warning: true/false` because some might not need to send a warning at all, for example if you provide multiple configurations, one per-version.
