### ISSUE TITLE
Emotes background loop music

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-ItemsAdder#4588]
### Discord tag (optional)

mario638

### Describe the solution you'd like

What I mean is that the animation length is 3 seconds and the music length is more than the animation and the music doesn't repeat until it finish because right now the sound effect/music is repeatable every time that the animation is looped

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Adding a new part in the emotes.yml config
sound-on-play: "itemsadder/contents/folder/assets/music.ogg"
play-every: {SECONDS-IN-TICKS}/{SECONDS}

### Additional context

This is an example is a animation that only longs 4 seconds but the song is 80 seconds

![Image](https://github.com/user-attachments/assets/db2f3023-ebe2-4928-a99e-e65766714429)

https://github.com/user-attachments/assets/ff7e9fb9-616f-4da6-8739-ee4027d395a0

**Comment by LoneDev6** [comment]
Interesting scenario, I will try to come up with something.
Probably I will check if the sound is still playing (this is not automatic and it will require some deep thinking, I will also need to re-send the song to the players otherwise they won't hear it if they join or teleport.

**Comment by LoneDev6** [comment]
I think that a setting to specify a background looping music directly into the yml of the emote is better than putting it into the animation keyframes.
Thanks for the idea.

**Comment by LoneDev6** [comment]
The new update will introduce this feature:
```yml
info:
  namespace: test
emotes:
  fortinayt2:
    id: fortinayt2
    can_player_move: true
    background_music:
      sound:
        name: iaspecial_swords:item.guitar.play
      repeat_interval_seconds: 5
```
