### ISSUE TITLE
Cave Decorators: "Unknown type name: cave_decorator"

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#4596]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

@konfa

### What happened?

Hello,
I'm trying to create a "cave_decorators" configuration for my caves. The world in question is using my custom java plugin which generates it using a modified chunk generator (could this be the issue?)
EDIT: I've tested the Ore populator and it works with my custom generator, so the cave one must be a bug or a misconfiguration (but I barely even edited the default configuration from IA wiki).

I haven't been able to find anyone using cave decorators lately, seems like this option isn't very popular in the community, that's why I'm opening an issue.

This is the error:
[19:10:22 ERROR]: Unknown type name: cave_decorator

### Steps to reproduce the issue

use the configuration I provided

### Server version

Purpur 1.21.4-243-65b1288

### ItemsAdder Version

4.0.9-hotfix-1

### ProtocolLib Version

5.4.0-SNAPSHOT-742

### LoneLibs Version

1.0.65

### Full Server Log

Line 842

### Error (optional)

```shell
[19:10:22 ERROR]: Unknown type name: cave_decorator
```

### Problematic items yml configuration file (optional)

Note: all used blocks are REAL_WIRE.

```yaml
info:
  namespace: mystic
cave_decorators:
  small_rocks:
    block: kamen_2
    bottom_blocks:
    - STONE
    biomes:
    - WARM_OCEAN
    worlds:
      - isles
    chance: 10
    max_height: 0 
    min_height: -55
    amount: 1
    position: SURFACE
  small_rocks2:
    block: kamen_3
    bottom_blocks:
    - STONE
    biomes:
    - WARM_OCEAN
    worlds:
      - islands
    chance: 10
    max_height: 0 
    min_height: -55
    amount: 1
    position: SURFACE
```
