### ISSUE TITLE
CustomModelData bug

### ISSUE THREAD

**Issue by GreatGoal0** [PluginBugs/Issues-ItemsAdder#4598]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

im.jes.z

### What happened?

Hello, I have some configurations in which I define the Model Data so that they do not change, for example 

PAPER
Item 1 - 10
Item 2 -20
Item 3 -30
These are the same content, but I have other content in which I don't do it but when doing the iazip for some reason item 1 does put that model data,but you must continue with item 2 which is from the same content for some strange reason it gives the custom model data to another item from another content that is not defined

### Steps to reproduce the issue

Define a custom model in an item's configuration, use /iazip

### Server version

1.21.4-187-1a5e5a5

### ItemsAdder Version

4.0.9-hotfix-1

### ProtocolLib Version

5.4.0-SNAPSHOT-741

### LoneLibs Version

Not installed because it is not needed anymore

### Full Server Log

https://mclo.gs/s401TgJ

### Error (optional)

```shell
[Server thread/ERROR]: [ItemsAdder] [Item] 'rarities:legendary_icon'. Error: custom_model_data: 50' is already in use by [itemshopplus:magenta_shop_cover]

[Craft Scheduler Thread - 7 - ItemsAdder/ERROR]: [ItemsAdder] WTF? Negative custom model data found for material paper with custom model data -1. Skipping.
```

### Problematic items yml configuration file (optional)

```yaml
legendary_icon:
    display_name: '&fLegendary Icon'
    resource:
      generate: true
      material: PAPER
      texture: legendary/legendary_icon.png
      model_id: 50

magenta_shop_cover:
    display_name: "&dMagenta shop cover"
    permission: itemsadder.furnituresplus
    lore:
      - "&7Item Shop + by Yassou"
    resource:
      material: "PAPER"
      generate: false
      model_path: itemshopplus/magenta_shop_cover        
    behaviours:
      furniture:
        fixed_rotation: true      
        solid: false
        small: false
        placeable_on:
          walls: true
          ceiling: true
          floor: true
```

**Comment by GreatGoal0** [comment]
?

**Comment by LoneDev6** [comment]
You might need to delete the cache or update it manually.
It is in `ItemsAdder/storage/` folder.
Make sure to make a backup though.

**Comment by LoneDev6** [comment]
Will be tested, thank you

**Comment by GreatGoal0** [comment]
Has there been progress?

**Comment by LoneDev6** [comment]
YAML example:
```yml
info:
  namespace: test
items:
  test_cmd:
    name: test_cmd
    resource:
      material: EMERALD
      generate: true
      texture: block/my_custom_block
      custom_model_data: 49
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          hardness: 1
  test_cmd2:
    name: test_cmd
    resource:
      material: EMERALD
      generate: true
      texture: block/my_custom_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          hardness: 1
  test_cmd3:
    name: test_cmd
    resource:
      material: EMERALD
      generate: true
      texture: block/my_custom_block
      custom_model_data: 50
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          hardness: 1

```


Cache file before the fix:
```yml
EMERALD:
  test:test_cmd: 49
  test:test_cmd2: 50
```

Cache file after the fix:
```yml
EMERALD:
  test:test_cmd: 49
  test:test_cmd2: 10000
  test:test_cmd3: 50
```
