### ISSUE TITLE
Player punches IAEntity when dropping an item from an opened inventory with Q

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#4610]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

andre601

### What happened?

While standing in front of a summoned IAEntity, you can punch it by having your inventory open and dropping an item in front of it using the Q keybind.
This behaviour does not show with vanilla mobs

### Steps to reproduce the issue

1. Summon an IAEntity with `/iaentity summon <id>`
2. Stand in front of it
3. Open your inventory while facing the entity and drop an item using Q
4. The entity receives damage

### Server version

[14:11:28 INFO]: Checking version, please wait...
[14:11:28 INFO]: This server is running Paper version 1.21.4-190-main@5538d24 (2025-03-05T12:40:02Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[14:11:40 INFO]: ItemsAdder version 4.0.10-beta-6
[14:11:40 INFO]: Customized Minecraft without client mods!
[14:11:40 INFO]: Website: devs.beer
[14:11:40 INFO]: Author: LoneDev

### ProtocolLib Version

[14:11:45 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[14:11:45 INFO]: Provides read/write access to the Minecraft protocol.
[14:11:45 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

https://mclo.gs/bPFOQx9

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: vanillaplus
entities:
  spotlight:
    display_name: "Spotlight"
    type: ZOMBIE
    model_folder: entity/spotlight
    silent: true
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 0
items:
  spotlight:
    name: "Spotlight"
    resource:
      material: PAPER
      generate: true
      texture: "minecraft:item/light"
    behaviours:
      complex_furniture:
        entity: spotlight
        light_level: 15
        solid: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/lbK64BxLvGc
