### ISSUE TITLE
Commands on events doesn't work

### ISSUE THREAD

**Issue by TrookiGaming** [PluginBugs/Issues-ItemsAdder#4619]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Trooki

### What happened?

I'm using the command event on my items but they don't work, I've even tried some of the examples on the wiki and they don't work either.
I have tried this example, the play_sound does work but the commands part does not.

```
  chain_events:
    display_name: "%#FE5A00%chain_events"
    permission: test.chain_events
    resource:
      material: COAL
      generate: true
      textures:
      - "minecraft:item/diamond.png"
    events:
      interact:
        right:
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"Action 1","color":"gold"}'
              as_console: true
              delay: 0
            cmd2:
              command: 'tellraw {player} {"text":"Action 2","color":"gold"}'
              as_console: true
              delay: 20
            cmd3:
              command: 'tellraw {player} {"text":"Action 3","color":"gold"}'
              as_console: true
              delay: 40
          play_sound_1:
            name: minecraft:block.note_block.banjo
            delay: 0
          play_sound_2:
            name: minecraft:block.note_block.banjo
            pitch: 1.2
            delay: 20
          play_sound_3:
            name: minecraft:block.note_block.banjo
            pitch: 1.5
            delay: 40
```

### Steps to reproduce the issue

Just add the item code

### Server version

1.21.4-138-5395ae3 (MC: 1.21.4)

### ItemsAdder Version

4.0.9-hotfix-1

### ProtocolLib Version

5.4.0-SNAPSHOT-741

### LoneLibs Version

1.0.65

### Full Server Log

https://mclo.gs/AaKdI0e

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: hats
items:
    super_hat:
        display_name: '&f&nʙᴀɴᴅᴀɴᴀ&r &#fbee2a&lS&#fcf154&lu&#fcf47f&lp&#fcf7a9&le&#fdfad3&lr'
        permission: permission_model
        resource:
          material: PAPER
          generate: false
          model_path: super_hat
        behaviours:
          hat: true
        lore:
            - '&f&l----------------'
            - '&7[&#fbee2aEfecto de Particulas&7]'
        enchants:
            - PROTECTION_ENVIRONMENTAL:5 
        attribute_modifiers:
            head:
                armor: 3
        events:
            wear:
                execute_commands:
                    cmd1:
                        command: 'ppo {player} add entity_effect feet #fbee2a'
                        as_console: true
            unwear:
                execute_commands:
                    cmd1:
                        command: 'ppo {player} remove entity_effect feet #fbee2a'
                        as_console: true
```
