### ISSUE TITLE
Actions cannot be delayed on eat event

### ISSUE THREAD

**Issue by MattDeWeerd** [PluginBugs/Issues-ItemsAdder#4623]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Matt_ow

### What happened?

I attempted to add an item which would work like a voucher, but by making it a consumable and adding actions on the eat event.

I wanted the actions to have a delay, but the delays do not work for eat event.  

### Steps to reproduce the issue

1. Give yourself an item with the `Consumable` property along with `Eat` events with multiple `actions` with `delays`
2. Eat the item
3. Observe the actions all occur at the same time

### Server version

Current Purpur Version: 1.21.4-2407-a14011f (MC: 1.21.4)*

### ItemsAdder Version

ItemsAdder version 4.0.9-hotfix-1

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-741

### Full Server Log

https://mclo.gs/kPpvKo6

### Error (optional)

```shell
None occur in console
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: tokens
items:
  bonus_claims:
    name: '&c1 Bonus Claims &fVoucher'
    lore:
    - '&8&m━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    - '&4ᴅᴇѕᴄʀɪᴘᴛɪᴏɴ&7:'
    - ' &7Adds bonus claims to your'
    - ' &7current town for expanding'
    - ' &7your claims'
    - ''
    - '&4ᴀᴍᴏᴜɴᴛ&7:'
    - ' &71 Chunk &8(16x16)'
    - '&8&m━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    - ''
    - '&f &7ᴄʟɪᴄᴋ ᴛᴏ ʀᴇᴅᴇᴇᴍ'
    enchants:
    - UNBREAKING:1
    item_flags:
    - HIDE_ENCHANTS
    resource:
      generate: true
      material: RED_CANDLE
      textures:
      - items/bonus_claims
    consumable:
      nutrition: 0
      saturation: 0
      can_always_eat: true
      eat_seconds: 3
    events:
      eat:
        execute_commands:
          cmd1:
            command: 'tellraw {player} {"text":"Action 1","color":"gold"}'
            as_console: true
            delay: 60
          cmd2:
            command: 'tellraw {player} {"text":"Action 2","color":"gold"}'
            as_console: true
            delay: 80
          cmd3:
            command: 'tellraw {player} {"text":"Action 3","color":"gold"}'
            as_console: true
            delay: 100
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/rheGVWP
