### ISSUE TITLE
Weapon Reload feature

### ISSUE THREAD

**Issue by 00Hrtz** [PluginBugs/Issues-ItemsAdder#4624]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

simple reload event

```yaml

    events:
      interact:
        left:
          increment_durability:
            amount: 7
# if 1 item is present in player inventory
          item:
            name: itemsadder:energy_cell
# amount to remove
            amount: 1
          play_sound:
            name: minecraft:click
            volume: 1
            pitch: 1

# if item required is not in inventory, deny left click event.
# if durability is max, deny left click event
```

### Is your feature request related to a problem?

Solves the lack of ammo item reload event issue, at present the only way i see to reload a custom ranged weapon with an item is by using an anvil which is useless while fighting.

### Describe alternatives you've considered

no other solutions, many of us have been waiting patiently since 2023 for new range weapon system, i think this simple solution pretty much solves the whole problem. No need for a complete overhaul, guns are working fine, it's just the lack of good reload system.
