### ISSUE TITLE
Custom Recipe Smithing Table not working (1.21.4)

### ISSUE THREAD

**Issue by arturek1666** [PluginBugs/Issues-ItemsAdder#4626]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

artuditu

### What happened?

I had try to make custom Armor and items to be able to be upgraded in Smithing Table, however every time I do it while I can make it to show up that recipe works I can't actually take the item out of it, I will include video.

I had try different Minecraft engine like papermc and purpur but both don't work, I had also created test server from scratch and only included required files to run itemsadder, I had also noticed that LoneLibs was no longer required so I had also try with it and without but sadly same results. 
I had deleted all itemsadder files and regenerate them and then added only required items to test it and still same results. 

### Steps to reproduce the issue

1. Create some kind of item and add smithing to recipes so it can be smithed
2. reload the server 
3. Do /iareload /iazip to load the newest pack
4. Try to get the item with smithing table. 

Included the echoshards.yml file to recreate it. 

### Server version

This server is running Paper version 1.21.4-226-ver/1.21.4@a838a88 (2025-04-17T19:20:57Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

Newest 1.21.4 purpur was also tried. 

### ItemsAdder Version

[11:14:39 INFO]: ItemsAdder version 4.0.10-beta-11
[11:14:39 INFO]: Customized Minecraft without client mods!
[11:14:39 INFO]: Website: devs.beer
[11:14:39 INFO]: Author: LoneDev

### ProtocolLib Version

[11:14:56 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-742
[11:14:56 INFO]: Provides read/write access to the Minecraft protocol.
[11:14:56 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:15:15 INFO]: LoneLibs version 1.0.65
[11:15:15 INFO]: Collection of libs used by my plugins
[11:15:15 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/Hqc8rwD

### Error (optional)

```shell
No error was find
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: echoshards
equipments:
  echo:
    type: armor
    layer_1: armor/layer_1
    layer_2: armor/layer_2
items:
  echo_upgrade_smithing_template:
    display_name: '&eEchorytowe Ulepszenia'
    lore:
      - 'Szablon Kowalski'
      - ''
      - 'Nakladany na:'
      - '&9Echo Sprzęt'
      - ''
      - 'Skladniki:'
      - '&9Echorytowe Ingot'
    resource:
      material: PAPER
      generate: true
      textures:
      - echo_upgrade_smithing_template.png
      amount: 1
  echo_head:
    name: 'Echorytowy Hełm'
    resource:
      generate: true
      texture: echorytowe_head.png
      material: NETHERITE_HELMET
    durability:
      max_durability: 417
    equipment:
      id: echoshards:echo
      slot_attribute_modifiers:
        armor: 3.5
        armorToughness: 3.5
        knockback_resistance: 0.1
  echo_chestplate:
    name: 'Echorytowy Napierśnik'
    resource:
      generate: true
      texture: echorytowe_chest.png
      material: NETHERITE_CHESTPLATE
    durability:
      max_durability: 592
    equipment:
      id: echoshards:echo
      slot_attribute_modifiers:
        armor: 8.5
        armorToughness: 3.5
        knockback_resistance: 0.1
  echo_leggings:
    name: 'Echorytowe Nogawice'
    resource:
      generate: true
      texture: echorytowe_legs.png
      material: NETHERITE_LEGGINGS
    durability:
      max_durability: 555
    equipment:
      id: echoshards:echo
      slot_attribute_modifiers:
        armor: 6.5
        armorToughness: 3.5
        knockback_resistance: 0.1
  echo_boots:
    name: 'Echorytowe Buty'
    resource:
      generate: true
      texture: echorytowe_feet.png
      material: NETHERITE_BOOTS
    durability:
      max_durability: 481
    equipment:
      id: echoshards:echo
      slot_attribute_modifiers:
        armor: 3.5
        armorToughness: 3.5
        knockback_resistance: 0.1
  echo_sword:
    display_name: '&fEchorytowy Miecz'
    resource:
      material: NETHERITE_SWORD
      generate: true
      texture: echorytowe_sword.png
    attribute_modifiers:
      mainhand:
        attackDamage: 8.5
        attackSpeed: 1.6
  echo_axe:
    display_name: '&fEchorytowa Sikiera'
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - echorytowe_axe.png
    attribute_modifiers:
      mainhand:
        attackDamage: 10.5
        attackSpeed: 1.0
  echo_pickaxe:
    display_name: '&fEchorytowy Kilof'
    resource:
      material: NETHERITE_PICKAXE
      generate: true
      textures:
      - echorytowe_pickaxe.png
    attribute_modifiers:
      mainhand:
        attackDamage: 6.5
        attackSpeed: 1.2
  echo_shovel:
    display_name: '&fEchorytowa Łopata'
    resource:
      material: NETHERITE_SHOVEL
      generate: true
      textures:
      - echorytowe_shovel.png
    attribute_modifiers:
      mainhand:
        attackDamage: 7.0
        attackSpeed: 1
  echo_hoe:
    display_name: '&fEchorytowa Motyka'
    resource:
      material: NETHERITE_HOE
      generate: true
      textures:
      - echorytowe_hoe.png
    attribute_modifiers:
      mainhand:
        attackDamage: 1.5
        attackSpeed: 4
  echo_ingot:
    display_name: '&fSztabka Echorytu'
    resource:
      material: NETHERITE_INGOT
      generate: true
      textures:
      - echorytowe_ingot.png
      amount: 1
  echo_shard_block:
    display_name: '&fOdłamek Echorytowego Bloku'
    resource:
      generate: true
      material: PAPER
      textures:
      - block/echo_shard_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
  echorite_block:
    display_name: '&fEchorytowy blok'
    resource:
      generate: true
      material: PAPER
      textures:
      - block/echorytowe_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: ITEM
        hardness: 5
        break_tools_blacklist:
        - WOODEN_PICKAXE
        - HAND
recipes:
  crafting_table:
    echo_upgrade_smithing_template:
      permission: itemsadder.customcraftingpublic
      enabled: true
      pattern:
      - ABA
      - ACA
      - AAA
      ingredients:
        A: DIAMOND
        B: netherite_upgrade_smithing_template
        C: SCULK
      result:
        item: echoshards:echo_upgrade_smithing_template
        amount: 1
    echo_upgrade_smithing_template2:
      permission: itemsadder.customcraftingpublic
      enabled: true
      pattern:
      - ABA
      - ACA
      - AAA
      ingredients:
        A: DIAMOND
        B: echoshards:echo_upgrade_smithing_template
        C: SCULK
      result:
        item: echoshards:echo_upgrade_smithing_template
        amount: 2
    echo_ingot:
      permission: itemsadder.customcraftingpublic
      enabled: true
      pattern:
      - AAB
      - BCC
      - CCX
      ingredients:
        A: NETHERITE_SCRAP
        B: ECHO_SHARD
        C: DIAMOND
      result:
        item: echoshards:echo_ingot
        amount: 1
    echo_sword:
      permission: itemsadder.customcraftingpublic
      enabled: true
      shapeless: true
      ingredients:
        A: NETHERITE_SWORD
        B: echoshards:echo_ingot
      result:
        item: echoshards:echo_sword
        amount: 1
    echo_axe:
      permission: itemsadder.customcraftingpublic
      enabled: true
      shapeless: true
      ingredients:
        A: NETHERITE_AXE
        B: echoshards:echo_ingot
      result:
        item: echoshards:echo_axe
        amount: 1
    echo_pickaxe:
      permission: itemsadder.customcraftingpublic
      enabled: true
      shapeless: true
      ingredients:
        A: NETHERITE_PICKAXE
        B: echoshards:echo_ingot
      result:
        item: echoshards:echo_pickaxe
        amount: 1
    echo_shovel:
      permission: itemsadder.customcraftingpublic
      enabled: true
      shapeless: true
      ingredients:
        A: NETHERITE_SHOVEL
        B: echoshards:echo_ingot
      result:
        item: echoshards:echo_shovel
        amount: 1
    echo_hoe:
      permission: itemsadder.customcraftingpublic
      enabled: true
      shapeless: true
      ingredients:
        A: NETHERITE_HOE
        B: echoshards:echo_ingot
      result:
        item: echoshards:echo_hoe
        amount: 1
  smithing:
    echo_head:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_HELMET
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_head
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_chestplate:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_CHESTPLATE
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_chestplate
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_leggings:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_LEGGINGS
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_leggings
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_boots:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_BOOTS
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_boots
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_sword:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_SWORD
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_sword
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_axe:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_AXE
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_axe
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_pickaxe:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_PICKAXE
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_pickaxe
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_shovel:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_SHOVEL
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_shovel
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
    echo_hoe:
      permission: itemsadder.customcraftingpublic
      base: NETHERITE_HOE
      addition: echoshards:echo_ingot
      template: echoshards:echo_upgrade_smithing_template
      result:
        item: echoshards:echo_hoe
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
  anvil_repair:
    echo_sword:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_sword
    echo_axe:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_axe
    echo_pickaxe:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_pickaxe
    echo_shovel:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_shovel
    echo_hoe:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_hoe
    echo_head:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_head
    echo_chestplate:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_chestplate
    echo_leggings:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_leggings
    eecho_boots:
      permission: echoshards.ee.repair
      ingredient: ECHO_SHARD
      item: echoshards:echo_boots
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/84Ph245VcQU
