### ISSUE TITLE
Trouble with invisible item

### ISSUE THREAD

**Issue by dexcild** [PluginBugs/Issues-ItemsAdder#4629]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

dexcild

### What happened?

Hello, dear developers. There is a problem with the texture of an invisible object in your plugin. The bottom line is that the server is functioning on version 1.21.1, but the invisible object is displayed there with an incorrect texture (black and purple), and on version 1.16.5 everything is fine, the invisible object is displayed as needed. I'll attach the item's configuration below.

### Steps to reproduce the issue

1. Join the server
2. Open the menu

### Server version

Purpur 1.21.1

### ItemsAdder Version

ItemsAdder version 4.0.9-hotfix-1

### ProtocolLib Version

ProtocolLib version 5.3.0

### Full Server Log

https://mclo.gs/E7mUiZD

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: orioleskypvp
items:
  paper:
    display_name: ""
    resource:
      material: PAPER
      generate: true
      textures:
        - items/paper.png
```
