### ISSUE TITLE
Furniture execute actions doesn't work

### ISSUE THREAD

**Issue by slemmannen** [PluginBugs/Issues-ItemsAdder#4641]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

slemmannen

### What happened?

Furtniture can no longer execute actions on interact (atleast not console commands). Works as it should in 4.0.8 but not in 4.0.10 or 4.0.11-beta1
Tested on a fresh server with only ItemsAdder, Protocollib and Citizens installed.

### Steps to reproduce the issue

1. Create a furniture with a action that triggers on interact
2. Interact with furniture

### Server version

This server is running Paper version 1.21.5-13-main@7d5695d (2025-04-14T11:33:42Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)

Also tested:

This server is running Paper version 1.21.4-189-main@a866e36 (2025-03-05T09:48:36Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.11-beta-1

### ProtocolLib Version

5.4.0-SNAPSHOT-745

### Full Server Log

https://mclo.gs/lTBslwa

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: furniture
items:
  test_furniture:
    display_name: 'test furniture'
    permission: ia.furniture
    resource:
      material: PAPER
      generate: false
      model_path: furniture/arbetsbank
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
          length: 1
          width: 1
          height_offset: 0
          length_offset: 0
          width_offset: 0
    events:
      placed_armorstand:
        interact:
          execute_commands:
            openmenu:
              command: say test
              as_console: true
```
