### ISSUE TITLE
Option to remove or recolor shadow of specific font image

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4683]
(does not require regenerating the pack)

```yml
  smile:
    permission: twitteremojis.smile
    show_in_gui: true
    path: font/emoji/smile
    scale_ratio: 9
    y_position: 8
    shadow: # new property
      enabled: true
      color: AA4A44
```

```yml
  smile:
    permission: twitteremojis.smile
    show_in_gui: true
    path: font/emoji/smile
    scale_ratio: 9
    y_position: 8
    shadow: # new property
      enabled: false
```
