### ISSUE TITLE
Custom Hud not showing

### ISSUE THREAD

**Issue by dorori123** [PluginBugs/Issues-ItemsAdder#4684]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

I am using itemsadder, worldedit, and placeholder API plugins only.

I tried to create a custom hud named "bladder"
and I checked it's there by /iaplayerstats read playername bladder. (it shows the value successfully)

However over time the value doesn't decrease
and the bar image doesn't show on the screen.

Here are the paths and yml files.

contents/needs/resourcepack/needs/textures/hud/needs/0.png
(image path/ and I put 0-10 png images)

contents/needs/configs/huds/huds.yml
(hud config path)

contents/needs/configs/huds/huds_images.yml
(hud image setting path)

### Steps to reproduce the issue

I downloaded the itemsadder and the default add on.
And I copied the files in the default folder to make my own huds.
(I even recreated the path exactly the same with the default folder)
But when I enter the server, the hud image doesn't appear regardless of gamemodes,
and the hud value doesn't decrease over time.

### Server version

Spigot 1.21.4

### ItemsAdder Version

ItemsAdder_4.0.10-hotfix-1.jar

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-747

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/7fdZc52

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
-----
info:
  namespace: needs
huds:
  bladder:
    enabled: true
    show:
      auto: true
      creative: true
    type: FRAMES
    x_position_pixels: 100
    value:
      player_stat_name: bladder
      start: 10
      min: 0
      max: 10
      triggers:
        decrement:
          generic_over_time_10_minutes:
            every_ticks: 12000
            amount: 1
          biome_over_time_desert_10_minutes:
            biome: DESERT
            every_ticks: 12000
            amount: 0.5
          food_level_change:
            amount: 0.1
        increment:
          player_respawn:
            amount: 10
        on_min_value:
          damage_player:
            every_ticks: 100
            damage: 0.5
          potion_effect:
            every_ticks: 100
            type: SLOW
            amplifier: 1
            duration: 100
    images:
      frames:
        - needs:bladder_0
        - needs:bladder_1
        - needs:bladder_2
        - needs:bladder_3
        - needs:bladder_4
        - needs:bladder_5
        - needs:bladder_6
        - needs:bladder_7
        - needs:bladder_8
        - needs:bladder_9
        - needs:bladder_10
------
info:
  namespace: needs
font_images:
  bladder_0:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/0.png
    y_position: -15
    scale_ratio: 50
  bladder_1:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/1.png
    y_position: -15
    scale_ratio: 50
  bladder_2:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/2.png
    y_position: -15
    scale_ratio: 50
  bladder_3:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/3.png
    y_position: -15
    scale_ratio: 50
  bladder_4:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/4.png
    y_position: -15
    scale_ratio: 50
  bladder_5:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/5.png
    y_position: -15
    scale_ratio: 50
  bladder_6:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/6.png
    y_position: -15
    scale_ratio: 50
  bladder_7:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/7.png
    y_position: -15
    scale_ratio: 50
  bladder_8:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/8.png
    y_position: -15
    scale_ratio: 50
  bladder_9:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/9.png
    y_position: -15
    scale_ratio: 50
  bladder_10:
    suggest_in_command: false
    show_in_gui: false
    path: hud/needs/10.png
    y_position: -15
    scale_ratio: 50
```
