### ISSUE TITLE
extra playerstats doesn't work

### ISSUE THREAD

**Issue by dorori123** [PluginBugs/Issues-ItemsAdder#4685]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

So this is a very interesting bug.

I made a custom HD with a new player stat. I will call this Stat.1
Stat.1 works perfectly.
The hud image is shown clearly on the screen, the value goes up and down over time,
and console commands /iaplayerstat read, write, increase & decrease all work fine.

Now I tried a second HD & player stat.
I copied the config exactly from the Stat.1
for example, if the stat.1 is thirst then stat.2 is sweatiness.
Both values change over time, nothing complicated.
Also /iaplayerstat read for Stat.2 works perfectly,
the hud image is on the screen as programmed too.

However, when the stat.2 value reaches 0,
there's no way to put it back to the max 10.
/iaplayerstat increment and decrement doesn't work for Stat,2.
Which is weird, cus /iaplayerstat read still works!!!

I tried everything to fix this issue.
I deleted and remade Stat.2,
I changed the whole path orders, I tried different configs...
but nothing works.

I can't help feeling this is the plugin issue.

### Steps to reproduce the issue

I made two differents huds and player stats,
almost simiar condition and triggers.
But only one works and the other doesn't.

### Server version

1.21.5

### ItemsAdder Version

[ItemsAdder_4.0.10-hotfix-1.jar]

### ProtocolLib Version

5.4.0-SNAPSHOT-747

### LoneLibs Version

1.0.65

### Full Server Log

https://mclo.gs/H1ZqyUs

### Error (optional)

```shell
17.05 20:06:02 [Server] INFO Hotel_Kim issued server command: /version ProtocolLib
17.05 20:06:19 [Server] INFO Hotel_Kim issued server command: /version LoneLibs
17.05 20:07:30 [Server] INFO Hotel_Kim issued server command: /iaplayerstat write Hotel_Kim cleanliness 10
17.05 20:07:30 [Server] ERROR Command exception: /iaplayerstat write Hotel_Kim cleanliness 10
17.05 20:07:30 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'iaplayerstat' in plugin ItemsAdder v4.0.10-hotfix-1
17.05 20:07:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
17.05 20:07:30 [Server] INFO at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:105) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:449) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:357) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:347) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:341) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2269) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:2242) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1446) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:175) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1426) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1377) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1385) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-78-d683970]
17.05 20:07:30 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
17.05 20:07:30 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "itemsadder.m.bu.dJ()" is null
17.05 20:07:30 [Server] INFO at ItemsAdder_4.0.10-hotfix-1.jar/itemsadder.m.cn.al(SourceFile:168) ~[ItemsAdder_4.0.10-hotfix-1.jar:?]
17.05 20:07:30 [Server] INFO at ItemsAdder_4.0.10-hotfix-1.jar/itemsadder.m.ck.a(SourceFile:286) ~[ItemsAdder_4.0.10-hotfix-1.jar:?]
17.05 20:07:30 [Server] INFO at ItemsAdder_4.0.10-hotfix-1.jar/itemsadder.m.pb.onCommand(SourceFile:74) ~[ItemsAdder_4.0.10-hotfix-1.jar:?]
17.05 20:07:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
17.05 20:07:30 [Server] INFO ... 27 more

Clear log
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: cleanliness
huds:
  cleanliness_bar:
    enabled: true
    show:
      auto: true
      creative: true
      underwater: true
      riding: true
    type: FRAMES
    x_position_pixels: 113
    value:
      player_stat_name: cleanliness
      start: 10
      min: 0
      max: 10
      triggers:
        decrement:
          generic_over_time_5_minutes:
            every_ticks: 6000
            amount: 0.5
          biome_over_time_desert_5_minutes:
            biome: DESERT
            every_ticks: 6000
            amount: 1
          food_level_change:
            amount: 0.1
        increment:
          food_level_change:
            amount: 0.1
          player_respawn:
            amount: 10
    images:
      frames:
        - cleanliness:bar_0
        - cleanliness:bar_1
        - cleanliness:bar_2
        - cleanliness:bar_3
        - cleanliness:bar_4
        - cleanliness:bar_5
        - cleanliness:bar_6
        - cleanliness:bar_7
        - cleanliness:bar_8
        - cleanliness:bar_9
        - cleanliness:bar_10
```
