### ISSUE TITLE
Custom entity sounds

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4693]
A way to customize ambient sounds of the custom entity, for example custom ZOMBIE must play a custom ambient sounds when getting damaged and when idling (like the vanilla random sound).
Ambient sound has some more properties to customize its randomness.

Example:

```yml
entities:
  other_steve:
    model_folder: entity/other_steve
    type: ENDERMAN
    can_sun_burn: false
    sounds:
      ambient:
        sound: vanillaex:entity.other_steve.ambient
        chance_per_tick: 0.1
        cooldown_ticks: 80
      step: vanillaex:entity.other_steve.step
      hurt: vanillaex:entity.other_steve.hurt
      attack: vanillaex:entity.other_steve.attack
      death: vanillaex:entity.other_steve.death
```
