### ISSUE TITLE
no-host config option non-functional

### ISSUE THREAD

**Issue by Projecki** [PluginBugs/Issues-ItemsAdder#4695]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

projecki

### What happened?

A resource pack is being loaded/unloaded on my 1.21.4 paper server, despite have the config option "no-host" set to true.

This is because I use self-hosting to send players the resource pack in our hub server, then they don't have to load any more packs for the rest of the time they spend on our network.

However, on our new 1.21.4 realm, the pack is being loaded for a second time. This is unexpected.

### Steps to reproduce the issue

1) deleted generated.zip from the output folder
2) tried iazip after making no-host true and disabling all of the other settings
3) tried enabling no-host and rebooted the server and did /iareload before rebooting
4) enabled no-host and deleted the generated.zip from the output folder
this is what i tried

Nothing seems to work. the no-host config option is not functioning properly.

### Server version

[21:15:00 INFO]: This server is running UniverseSpigot version 1.21.4-ver/1.21.4-stable@4f6cdd2 (2025-04-29T22:16:01Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
Universe-1.21.4-4f6cdd2 (MC: 1.21.4)

### ItemsAdder Version

[21:15:14 INFO]: ItemsAdder version 4.0.10-hotfix-1
[21:15:14 INFO]: Customized Minecraft without client mods!
[21:15:14 INFO]: Website: devs.beer
[21:15:14 INFO]: Author: LoneDev

### ProtocolLib Version

[21:15:24 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-747
[21:15:24 INFO]: Provides read/write access to the Minecraft protocol.
[21:15:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:15:37 INFO]: LoneLibs version 1.0.65
[21:15:37 INFO]: Collection of libs used by my plugins
[21:15:37 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/gyx51gt

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
metrics: true
update-checker: true
resource-pack:
  hosting:
    no-host:
      enabled: true
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: google.com
      pack-port: 25565
      append-port: true
      protection:
        block_non_game_requests: false
        rate_limit:
          enabled: true
          max_requests: 3
          period_seconds: 2
          cooldown:
            enabled: true
            duration_minutes: 30
            trigger_on_failed_times: 5
    external-host:
      enabled: false
      url: https://google.com
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
    lobfile:
      enabled: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    lock-player: true
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: false
      protection_2: false
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla: true
      optifine_nbt: true
      overwrite_leather_armor_layers_textures: true
      1_21_5_plus_armors_shaders: true
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    compress-shader-files: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: false
    step:
      enabled: true
      allow_non_player: true
    other: true
  expert_users: {}
  notify_other_plugins_resourcepacks: true
  allow_other_plugins_resourcepacks: false
  auto_apply:
    enabled: false
    before_join: true
    delay_ticks: 1
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  atlas_support: true
  pre_1_21_2_shaders_fix:
    enabled: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  fix-liquids-flow: false
  fix-floating-blocks: false
  fix-glitched-blocks:
    enabled: false
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements: {}
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: false
  remove-unused-palettes-on-region-save: false
  custom:
    mushroom: false
    chorus: false
    note: false
    wire: false
    fire: false
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
  fix_unstackable_items_on_click: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
font_images:
  chat:
    enabled: true
    add_hover_suggestion: true
    tab_autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
  customitem_name_and_lore:
    enabled: false
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
entities:
  max-furniture-vehicles-per-chunk: 30
  custom_entities:
    enabled: true
    emotes: false
    interval-rendering-packets-ticks: 1
    expert_users:
      delay_packets: false
      extract_emotes_shaders: true
    max_per_chunk: 5
  max_furniture_per_chunk: 20
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup: {}
      on-item-click: {}
      automatically: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
    log-files-reloading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
  blocks-populators:
    log-generation: false
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
  resourcepacks:
    log_player_install: false
    compression:
      files: false
      overlays: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
text_effects:
  enabled: false
  chat:
    enabled: true
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  customitems-name-and-lore:
    enabled: true
  customitem_name_and_lore:
    enabled: true
  hide_scoreboard_numbers: false
  hide_scoreboard_numbers_old_clients: false
  legacy_colors_compatibility: true
cache_font_images_and_effects_replacements: true
show_plugin_logo_on_enable: true
advanced:
  legacy_shader_armor_conversion:
    append_new_equipment_tag:
      enabled: false
    completely_convert_to_new_equipment_tag:
      enabled: false
      new_armor_material: IRON
```
