### ISSUE TITLE
Furniture lore/name is not refreshed when dropped

### ISSUE THREAD

**Issue by TheLaoming** [PluginBugs/Issues-ItemsAdder#4715]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

So i've updated to 1.21.4 and furnitures like this

```
test:
    display_name: "&#9513fbTest"
    lore:
    - '&ftest'
   resource:
      material: PAPER
      generate: false
      textures:
        - item/gamerealms/crates/hall22_chest
      model_path: "item/gamerealms/crates/hall22_chest"
      model_id: 502
    events:
      placed_armorstand:
        right:
          play_particle:
            name: CRIT_MAGIC
          execute_commands:
            cmd1:
              command: ec
              as_console: false
      #placed_armorstand:
      #  interact:
      #    execute_commands:
      #      the_first_command:
      #        command: ec
      #        as_console: false
    behaviours:
      furniture:
        solid: true
        fixed_rotation: false
        opposite_direction: false
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        sound:
            place:
              name: minecraft:block.sculk_shrieker.place
            break:
              name: minecraft:block.sculk_shrieker.break
```
Doesn't execute command, only if I remove `solid: true` option. On 1.21.1 with Itemsadder 4.0.8 it works fine, so don't know if it's a problem with IA or version (ig IA).

### Steps to reproduce the issue

1. Place this furniture
2. Put any command
3. It's not executed until you remove the barrier or click above it

### Server version

This server is running UniverseSpigot version 1.21.4-ver/1.21.4-stable@4f6cdd2 (2025-04-29T22:16:01Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
Universe-1.21.4-4f6cdd2 (MC: 1.21.4)

(Tried paper too)

### ItemsAdder Version

ItemsAdder version 4.0.10-hotfix-1
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-742

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/RQZkROF

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```
