### ISSUE TITLE
Use minimessage format in the plugin translation files

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4720]
Example:
```yml
ia-button-search: <gray>Search…</gray>
ia-button-back: <white>← Back</white>
ia-button-next-page: <white>Next Page »</white>
ia-button-previous-page: <white>« Previous Page</white>
ia-button-next-recipe: <white>Next Recipe »</white>
ia-button-previous-recipe: <white>« Previous Recipe</white>
ia-button-get-item: <white>Get Item</white>
ia-button-loot-blocks: <white>Drop from Block</white>
ia-button-loot-mobs: <white>Drop from Mob</white>
ia-button-loot-fishing: <white>Drop from Fishing</white>
ia-button-vehicle-fuel-items: <yellow>Fuel Items</yellow>
ia-button-seed-result: <white>From Seeds</white>
ia-button-blocks-populators: <white>Block Spawn Info</white>
ia-button-surface-decorators: <white>Spawn Info</white>
ia-button-trees-populators: <white>Spawn Info</white>
```
