### ISSUE TITLE
Allow ItemsAdder blockstates support multimodelling

### ISSUE THREAD

**Issue by Gu57-git** [PluginBugs/Issues-ItemsAdder#4723]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)
gust1337

### Describe the solution you'd like
**_Tried to find information about this in wiki/git, but can't find anything, if IA already have this feature - sorry, I'm stoopid_**

Under "Allow ItemsAdder blockstates support multimodelling" I mean this minecraft feature:

![Image](https://github.com/user-attachments/assets/d8b8b799-014e-4379-b5d3-2b776938b809)
![Image](https://github.com/user-attachments/assets/360bba84-2a4e-4fb5-9878-1db38398c717)

As you can see, this feature allow you to see random variations (random rotation or even random model) of same block in same state.

Right now it's not possible to use blockstates in this way, only if you edit pack manually (each /iazip will kill it), so, for example, it's not possible (actually possible, but it's big REAL_WIRE slots loss) to do something like this (ignore blocks glitch, it's my fault):
https://youtu.be/Hf-RwbZy5yA

### Is your feature request related to a problem?
Sadly, yes this time

### How could this be configured:
1. Allow to use CUSTOMBLOCK.json in blockstates folder of namespace, ItemsAdder should add new properties inside "minecraft/blockstate/..." automatically.
2. Possibility to specify more than 1 model in **model_path** in item configuration, first model should be "main" (for be displayed in hands/head/etc), works only if item have **placed_model** attribute.

**Comment by LoneDev6** [comment]
you can using the `custom_variants` property of itemsadder blocks
https://itemsadder.devs.beer/plugin-usage/adding-content/block#custom_variants

https://www.spigotmc.org/resources/deco-worlddeco-add-autogenerating-decorations-on-your-world-surface-for-itemsadder.95207/

```yml
  mossy_small_rocks:
    enabled: true
    display_name: display-name-mossy_small_rocks
    resource:
      generate: false
      material: PAPER
      model_path: mossy_small_rocks
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          custom_variants:
            variant_1:
              model: mossy_small_rocks
              y: 90
            variant_2:
              model: mossy_small_rocks
              y: 180
            variant_3:
              model: mossy_small_rocks
              y: 270
        sound:
          place:
            name: block.stone.place
          break:
            name: block.stone.break
```

![Image](https://github.com/user-attachments/assets/e6842cc7-014c-44a2-89f3-557609bf7071)
