### ISSUE TITLE
Custom entities specify animations in the yaml file

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4729]
Allow setting animations in the yaml file too, for easier swapping without using the Blockbench extension that requires an export each time.

```yml
    animations:
      idle: idle # obtained by default, not mandatory
      walk: walk # obtained by default, not mandatory
      attack: attack # obtained by default, not mandatory
      death: death # obtained by default, not mandatory
      sneak: sneak # obtained by default, not mandatory
      sneak_walk: sneak_walk # obtained by default, not mandatory
      idle_angry: idle_angry
      walk_angry: walk_angry
```

<details>
<summary>Click to open the full configuration example</summary>

```yml
info:
  namespace: vanillaex
entities:
  other_steve:
    model_folder: entity/other_steve
    type: ENDERMAN
    can_sun_burn: false
    sounds:
      ambient:
        sound: vanillaex:entity.other_steve.ambient
        chance_per_tick: 0.1
        cooldown_ticks: 80
      step: vanillaex:entity.other_steve.step
      hurt: vanillaex:entity.other_steve.hurt
      attack: vanillaex:entity.other_steve.attack
      death: vanillaex:entity.other_steve.death
    animations:
      idle: idle # obtained by default, not mandatory
      walk: walk # obtained by default, not mandatory
      attack: attack # obtained by default, not mandatory
      death: death # obtained by default, not mandatory
      sneak: sneak # obtained by default, not mandatory
      sneak_walk: sneak_walk # obtained by default, not mandatory
      idle_angry: idle_angry
      walk_angry: walk_angry
```
</details>
