### ISSUE TITLE
Allow creating sounds with dots in their key

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4730]
Example
```yml
sounds:
  "entity.other_steve.ambient":
    variant_1:
      path: entity/other_steve/ambient1
      pitch: 1
    variant_2:
      path: entity/other_steve/ambient1
      pitch: 1.1
    variant_3:
      path: entity/other_steve/ambient1
      pitch: 0.9
```
