### ISSUE TITLE
Better External Host improvements

### ISSUE THREAD

**Issue by arturek1666** [PluginBugs/Issues-ItemsAdder#4734]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

artuditu

### Describe the solution you'd like

I would love the external-host to work similar to lobfile where the generated.zip file automatically is moved to another server where file is hosted, but for external-host to use FTP to automatically transfer the file when doing /iazip

They way I see the config:
config.yml:
```
    external-host:
      enabled: true
      url: https://fanimc.pl/Resourcepack/generated.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
      ftp-autotransfer:
        enabled: false/true
        host-name: (hostname)
        User_name: (hostname)
        password: (password)
        port: (port)
```
This would make things easer if server owners want to use external-host with they have access to it with FTP.

### Is your feature request related to a problem?

At this moment of time the way resource pack works on my server is I use external-host, and I have the generated.zip file where my site is located, and each time I do /iareload + /iazip I move generated.zip file from my mc server manually to my website server using FTP and do /iareload again to make it work. Out of the 3 options at the moment I like the external-host but the negative about is I have to manually move the file from mc server to ftp server, so if it could be automated would really be nice. 

### Describe alternatives you've considered

I had try to consider using ftp to ftp sync but there are not quick to sync so after doing /iareload and /iazip it takes some time for pack to sync with each other, so I have to do /iareload.

I had also try use my raspberry pi to automate sync between 2 ftp but failed.
