### ISSUE TITLE
Make /iaentity summon <mob> using console

### ISSUE THREAD

**Issue by AlmostPanda** [PluginBugs/Issues-ItemsAdder#4735]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Pandicka

### Describe the solution you'd like

Hello,
just like the title says, I would like to be able to execute the `/iaentity summon <mob>` on players thought console. I haven't found anything about it on wiki, I even tried using placeholders  `%player%, %PLAYER%, etc`

If I made any mistake let me know, have a good day.

Server version: 
Paper version 1.21.4-225-main@0767902 (Implementing API version 1.21.4-R0.1-SNAPSHOT)

Plugin's version:
ItemsAdder: 4.0.10-hotfix-1
LoneLibs: 1.0.65
LibsDisguises: 11.0.6 (Free version, not premium)

### Is your feature request related to a problem?

Yes, haven't found any other way to make the command work in console to summon the mob on players.

### Describe alternatives you've considered

I thought of creating CustomAlias using CMI, but that didn't work either.
I mean yes it works, if player executes the command, but if I execute the coomand via console it doesn't work.

```
CustomAlias:
  crabspawn: # <player>
    Cmds:
      - "check:$1==Null~! msg! [playerName] &e&lError | &cUse: /crabspawn <player>"
      - iaentity summon mobs:crab
    CustomTabs:
      - "[allPlayername]"
    Perm: true
```
