### ISSUE TITLE
Cave / surface decorators doesn't work in nether dimension

### ISSUE THREAD

**Issue by Gu57-git** [PluginBugs/Issues-ItemsAdder#4736]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

gust1337

### What happened?

Cave / surface decorators doesn't work in nether.

tests:
Surface decorators:
Overworld - ✅
Nether - ❌(cause top layer)
End - ✅

Cave decorators:
Overworld - ✅
Nether - ❌(nether is not a cave, nether caves (space with cave_air) also empty by the way)
End - didn't tried, but it's not really need there, surface is enough for this dimension

### Steps to reproduce the issue

1. Make REAL_WIRE block and populator cfg
2. Select some chunks with WE
3. //replace tripwire 0
4. 0 blocks replaced

### Server version

1.21.4

### ItemsAdder Version

4.0.10 hotfix 1

### ProtocolLib Version

5.4.0 - 745

### Full Server Log

-

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: world_additions
items:
  netherrack_pebbles:
    enabled: true
    display_name: display-name-netherrack_pebbles
    permission: world_additions.user
    resource:
      material: PAPER
      generate: false
      model_path: netherrack/netherrack_pebbles
    specific_properties:
      block:
        drop_when_mined: false
        drop_on_silk_touch: true
        hardness: -1      
        blast_resistance: 0        
        placed_model:
          type: REAL_WIRE
          break_particles_material: NETHERRACK
        sound:
          place:
            name: block.netherrack.place
            pitch: 1.2
          break:
            name: block.netherrack.break    
            pitch: 1.2   

surface_decorators:
  netherrack_pebbles:
    block: netherrack_pebbles
    bottom_blocks:
    - NETHERRACK
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - GLOWSTONE
    - MAGMA_BLOCK
    - GRAVEL
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - SOUL_SAND
    - BASALT
    worlds:
      - world_nether
    chance: 100
    max_height: 124
    min_height: 5
    amount: 1
    position: SURFACE
```
