### ISSUE TITLE
Allow custom entities in `type` of mobs loots and rename to `entities`

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4759]
```yml
  entities:
    my_loot:
      type: vanillaex:redstone_bug
      items:
        redstone:
          item: REDSTONE
          min_amount: 1
          max_amount: 2
          chance: 99.9
          ignore_fortune: false
```

Instead of 
```yml
  mobs:
    my_loot:
      type: SILVERFISH
      metadata:
        ItemsAdderEntity:
          name: ItemsAdderEntity
          value: vanillaex:redstone_bug
          type: string
      items:
        redstone:
          item: REDSTONE
          min_amount: 1
          max_amount: 2
          chance: 99.9
          ignore_fortune: false

```
