### ISSUE TITLE
Custom Entities - `events` `script` action similar to items

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4762]
Related to #4756

Allows running scripts on custom entities.

### Example

The script code:
This script changes the current animation of the interacted entity with `test` (assuming it exists on your model).
```js
log("Hello!");
$player.sendMessage("yo");

$customEntity.playAnimation("test");
```

Configuration

```yml
info:
  namespace: vanillaex
entities:
  redstone_bug:
    model_folder: entity/redstone_bug
    type: SILVERFISH
    can_sun_burn: false
    speed:
      movement: 0.15
    events:
      interact:
        execute_command:
          command: tell {player} interact
        script:
          name: vanillaex:test # Run the script
scripts:
  test:
    path: test.jspp # Script file declaration

```
