### ISSUE TITLE
Native 2D icons (1.21.2+ client only)

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4784]
Use the new 1.21.2 properties to show a different model (for example the 2D variant) in inventory.
A new `icon` property will be added and accepts a texture namespaced path.

Example custom model and icon.
```yml
info:
  namespace: test
items:
  test_block:
    name: test_block
    resource:
      material: PAPER
      generate: false
      model_path: test:block/test_block
      icon: test:item/test_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
```

Example using vanilla textures
```yml
info:
  namespace: test
items:
  test_block:
    name: test_block
    resource:
      material: PAPER
      generate: false
      model_path: minecraft:block/diamond_block
      icon: minecraft:item/diamond
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
```
