### ISSUE TITLE
`cancel: true` not working for `eat`

### ISSUE THREAD

**Issue by ZzPowerTech** [PluginBugs/Issues-ItemsAdder#4786]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

ZzPowerTechzZ

### What happened?

I'm trying to create an item with a cooldown to use, I tried using the cooldown, but it doesn't stop the player from consuming the item, the item is consumed, but the command events are not executed, but I tried to set a permission to block the player from consuming the item, but the item is still consumed.

### Steps to reproduce the issue

The item...
evento_buildbattle:
      enable: true
      permission: 'test'
      display_name: '<#B87537>Impulso de Construção'
      lore:
        - '<gray>Consuma o item para iniciar um evento'
        - '<gray>BuildBattle especial no servidor.'
        - ''
        - '<#FFD700><bold>❖ Evento limitado!'
      resource:
        material: GOLDEN_APPLE
        model_id: 6
        generate: true
        textures:
          - item/perks/buildbattle
      events_settings:
        cooldown:
          indicator: BOSSBAR
          ticks: 12000
      events:
        eat:
          cancel: true
          execute_commands:
            remove_perm:
              command: 'lp group default permission settemp austv.itemsadder0buildbattleitem false 600s'
            aviso:
              command: 'broadcast &f⨖ &e{player} &#F9C91Biniciou o evento &lBUILD BATTLE! &#F9C91BDigite &e/entrarbuild &#F9C91Bpara participar!'
              as_console: true
            permissao:
              command: 'lp group default permission settemp mycommand.cmd.entrar_build true 300s'
              as_console: true
            start:
              command: 'buildavisos'
              as_console: true
          play_sound:
            name: minecraft:entity.ender_dragon.growl
            delay: 0
            volume: 1.0
            pitch: 1.0        

### Server version

version
[21:10:55 INFO]: Checking version, please wait...
[21:10:56 INFO]: Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.1-2305-fdfc12e (MC: 1.21.1)

### ItemsAdder Version

[21:12:02 INFO]: ItemsAdder version 4.0.8
[21:12:02 INFO]: Customized Minecraft without client mods!
[21:12:02 INFO]: Website: devs.beer
[21:12:02 INFO]: Author: LoneDev

### ProtocolLib Version

[21:12:19 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-739
[21:12:19 INFO]: Provides read/write access to the Minecraft protocol.
[21:12:19 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:13:37 INFO]: LoneLibs version 1.0.63
[21:13:37 INFO]: Collection of libs used by my plugins
[21:13:37 INFO]: Authors: LoneDev and others

### Full Server Log

no errors in console

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: austv_itens
items:
  perk_tempo_recarga:
    enable: true
    display_name: '<#B87537>Impulso de Recarga de Habilidade'
    lore:
    - '<gray>Consuma o item para diminuir'
    - '<gray>a recarga das suas habilidades'
    - '<gray>ativas em <#FFB066>50%<gray>.'
    - ''
    - '<aqua> ❖ Dura 12 horas'
    resource:
      material: GOLDEN_APPLE
      model_id: 1
      generate: true
      textures:
      - item/perks/tempoderecarga
    events:
      eat:
        execute_commands:
          permissao:
            command: 'lp user {player} permission settemp mcmmo.perks.cooldowns.halved true 12h accumulate server=henesys'
            as_console: true
          cmd1:
            command: 'ap sendtitle {player} 2 5 2 "<green><bold>Perk Ativado!" "<white>Utilize <aqua>/perks <white>para ver o tempo restante."'
            as_console: true
        play_sound:
          name: minecraft:block.note_block.banjo
          delay: 0
  perk_sorte:
    enable: true
    display_name: '<#B87537>Impulso de Sorte em Habilidade'
    lore:
    - '<gray>Consuma o item para aumentar'
    - '<gray>a sorte das suas habilidades'
    - '<gray>passivas em <#FFB066>33%<gray>.'
    - ''
    - '<aqua> ❖ Dura 2 dias'
    resource:
      material: GOLDEN_APPLE
      model_id: 2
      generate: true
      textures:
      - item/perks/sorte
    events:
      eat:
        execute_commands:
          permissao:
            command: 'lp user {player} permission settemp mcmmo.perks.lucky.all true 2d accumulate server=henesys'
            as_console: true
          cmd1:
            command: 'ap sendtitle {player} 2 5 2 "<green><bold>Perk Ativado!" "<white>Utilize <aqua>/perks <white>para ver o tempo restante."'
            as_console: true
        play_sound:
          name: minecraft:block.note_block.banjo
          delay: 0
  perk_habilidade_ativa:
    enable: true
    display_name: '<#B87537>Impulso de Habilidade Ativa'
    lore:
    - '<gray>Consuma o item para aumentar'
    - '<gray>a duração das suas habilidades'
    - '<gray>ativas em <#FFB066>8 segundos<gray>.'
    - ''
    - '<aqua> ❖ Dura 12 horas'
    resource:
      material: GOLDEN_APPLE
      model_id: 3
      generate: true
      textures:
      - item/perks/habilidadeativa
    events:
      eat:
        execute_commands:
          permissao:
            command: 'lp user {player} permission settemp mcmmo.perks.activationtime.eightseconds true 12h accumulate server=henesys'
            as_console: true
          cmd1:
            command: 'ap sendtitle {player} 2 5 2 "<green><bold>Perk Ativado!" "<white>Utilize <aqua>/perks <white>para ver o tempo restante."'
            as_console: true
        play_sound:
          name: minecraft:block.note_block.banjo
          delay: 0
  perk_dobro_xp:
    enable: true
    display_name: '<#B87537>Impulso de Experiência em Habilidade'
    lore:
    - '<gray>Consuma o item para aumentar'
    - '<gray>o ganho de experiência na prática'
    - '<gray>das habilidades em <#FFB066>2x<gray>.'
    - ''
    - '<aqua> ❖ Dura 60 minutos'
    resource:
      material: GOLDEN_APPLE
      model_id: 4
      generate: true
      textures:
      - item/perks/dobroxp
    events:
      eat:
        execute_commands:
          permissao_1:
            command: 'dobromcmmoindividual {player} 1'
            as_console: true
          cmd1:
            command: 'ap sendtitle {player} 2 5 2 "<green><bold>Perk Ativado!" "<white>Utilize <aqua>/perks <white>para ver o tempo restante."'
            as_console: true
        play_sound:
          name: minecraft:block.note_block.banjo
          delay: 0
  perk_alma:
    enable: true
    display_name: '<#B87537>Impulso de Alma Infinita'
    lore:
    - '<gray>Consuma o item para os seus super'
    - '<gray>encantamentos <#FFB066>não gastarem<gray> almas'
    - '<gray>guardadas nos itens.'
    - ''
    - '<aqua> ❖ Dura 20 minutos'
    resource:
      material: GOLDEN_APPLE
      model_id: 5
      generate: true
      textures:
      - item/perks/alma
    events:
      eat:
        execute_commands:
          permissao:
            command: 'lp user {player} permission settemp ae.bypass.souls true 20m accumulate server=henesys'
            as_console: true
          cmd1:
            command: 'ap sendtitle {player} 2 5 2 "<green><bold>Perk Ativado!" "<white>Utilize <aqua>/perks <white>para ver o tempo restante."'
            as_console: true
        play_sound:
          name: minecraft:block.note_block.banjo
          delay: 0
  evento_buildbattle:
      enable: true
      permission: 'test'
      display_name: '<#B87537>Impulso de Construção'
      lore:
        - '<gray>Consuma o item para iniciar um evento'
        - '<gray>BuildBattle especial no servidor.'
        - ''
        - '<#FFD700><bold>❖ Evento limitado!'
      resource:
        material: GOLDEN_APPLE
        model_id: 6
        generate: true
        textures:
          - item/perks/buildbattle
      events_settings:
        cooldown:
          indicator: BOSSBAR
          ticks: 12000
      events:
        eat:
          cancel: true
          execute_commands:
            remove_perm:
              command: 'lp group default permission settemp austv.itemsadder0buildbattleitem false 600s'
            aviso:
              command: 'broadcast &f⨖ &e{player} &#F9C91Biniciou o evento &lBUILD BATTLE! &#F9C91BDigite &e/entrarbuild &#F9C91Bpara participar!'
              as_console: true
            permissao:
              command: 'lp group default permission settemp mycommand.cmd.entrar_build true 300s'
              as_console: true
            start:
              command: 'buildavisos'
              as_console: true
          play_sound:
            name: minecraft:entity.ender_dragon.growl
            delay: 0
            volume: 1.0
            pitch: 1.0
```
