### ISSUE TITLE
Fix `fix_unstackable_items_on_click` issues

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4787]
https://discord.com/channels/533407895010803753/1382020769755697173

Books and some other items are merged by mistake.

To fix that I will implement some more checks and also add new properties to the item configuration, and also in the `config.yml` as global property: `fix_unstackable_items_on_click`.

Previously implemented by #4497 and gets improved in this task.

The new structure in `config.yml`:
```yml
items:
# ....
  auto_update:
    fix_unstackable_items_on_click: true
```

New properties in the item file:
```yml
  test_item:
    name: Test Item
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: PAPER
    max_stack_size: 16
    lore:
    - bro1
    enchants:
    - AQUA_AFFINITY
    auto_update:
      fix_unstackable_items_on_click: true # <-- here
```
