### ISSUE TITLE
Custom Item/Recipes Bug

### ISSUE THREAD

**Issue by dorori123** [PluginBugs/Issues-ItemsAdder#4800]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

Hello, I already fixed the bug on my end,
I thought maybe I needed to report some incorrect info on the official IA wiki.

1. "Potion" crashes Server
When you make a custom consumable item and set the material to "POTION"
It crashes the server until you remove the configuration and the entire player data.
I changed the material to "HONEY_BOTTLE" and now it works perfectly.
(It give potion effects too with special property so no complain lol)

2) minecraft: grammer doesn't work
On the official wiki, when making a custom recipe,
it says you should write like minecraft:water_bucket.
But somehow it doesn't work like that.
You need to use "WATER_BUCKET" instead then it works.

### Steps to reproduce the issue

Make a custom drink or potion and write the material "POTION".
-> disconnection with the server instantly.

Use the namespace "minecraft:"
-> It should be without the namespace and written in upper cases when a vanilla item.

Thanks.

### Server version

Paper 1.21.5

### ItemsAdder Version

ItemsAdder_4.0.11

### ProtocolLib Version

5.4.0

### LoneLibs Version

1.0.65

### Full Server Log

https://mclo.gs/abLg66q

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```

**Comment by Andre601** [comment]
This can be partially blamed on Spigot and paper.
Items there are stored as uppercased values due to them being an enum in the past.
Also, some item names may not match the ones in mc itself.

**Comment by dorori123** [comment]
> This can be partially blamed on Spigot and paper. Items there are stored as uppercased values due to them being an enum in the past. Also, some item names may not match the ones in mc itself.

Ahhh that makes sense. Damn spigor and paper lol
I still appreciate the plugin greatly.
It's enabling me to make everything I want haha

**Comment by Andre601** [comment]
If you ever need to know what names are used can you check the `Material` javadoc of Spigot for info: https://helpch.at/docs/1.21.5/org/bukkit/Material.html

Note that items with `LEGACY_` prefix shouldn't be used. They only exists because Spigot still wants to support plugins from before 1.13 for no good reason...

**Comment by LoneDev6** [comment]
I did some testing and it works just fine.
If you still encounter the issue please share your configuration so that I can test

```yml
info:
  namespace: my_items
items:
  my_drink:
    enabled: true
    display_name: My Drink
    resource:
      material: PAPER
      generate: true
      textures:
        - item/my_drink
    consumable:
      nutrition: 1
      saturation: 0
```

```yml
info:
  namespace: my_items
items:
  my_drink:
    enabled: true
    display_name: My Drink
    resource:
      material: POTION
      generate: true
      textures:
      - item/my_drink
    consumable:
      nutrition: 1
      saturation: 0
```
