### ISSUE TITLE
1.21.1 - REAL_WIRE blocks glitching – Custom Crops

### ISSUE THREAD

**Issue by galileoba** [PluginBugs/Issues-ItemsAdder#4815]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

@gaalileo

### What happened?

A few days ago, I changed item frame furniture items with REAL_WIRE blocks to improve performance, as they are used frequently and in large quantities by players. However, after making this change, I started experiencing serious issues. especially in combination with the Custom Crops plugin.

**Here’s what’s happening:**

- The pot (used as a planting container) completely loses its original block appearance and turns into a glitched item, sometimes even dropping the seed of the planted crop.

- In cases where there was previously a pot before switching from item frame to REAL_WIRE, it gets totally messed up and turns directly into a planted crop.

- I’ve also noticed that some REAL_WIRE blocks around spawn have randomly changed (e.g., a flower pot block now appears as a completely unrelated radnom REAL_WIRE block).

- On areas where nothing was previously planted, the crops mostly work, but there's still a big issue, walking over them causes the crops to change growth stages or even turn into a different crop entirely.

I reached out to the developers of Custom Crops, and they confirmed that the issue is not on their end, but rather a bug in ItemsAdder.

**What I’ve Tried:**

- Updated Custom Crops plugin to the latest version, including all configuration and asset files.

- Updated ItemsAdder to the latest available version.

- Fully updated the server to Paper 1.21.1.

### Steps to reproduce the issue

https://www.youtube.com/watch?v=zQilR62KuOk
https://www.youtube.com/watch?v=rY7lcPKLopY

### Server version

[01:11:06 INFO]: This server is running Paper version 1.21.1-133-ver/1.21.1@3cb8529 (2025-03-28T16:14:36Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

You are running the latest version
Previous version: 1.21-130-b1b5d4c (MC: 1.21)

### ItemsAdder Version

ItemsAdder version 4.0.11

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-739

### LoneLibs Version

LoneLibs version 1.0.65

### Full Server Log

https://mclo.gs/IVphgUz

### Error (optional)

```shell
logs
```

### Problematic items yml configuration file (optional)

```yaml
dry_pot:
    display_name: "Pot"
    resource:
      material: PAPER
      generate: false
      model_path: 'item/customcrops/item/basics/dry_pot'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
        break_tools_whitelist:
        - AXE
  wet_pot:
    display_name: "Wet Pot"
    resource:
      material: PAPER
      generate: false
      model_path: 'item/customcrops/item/basics/wet_pot'
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
        break_tools_whitelist:
        - AXE

  cabbage_stage_1:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/customcrops/cabbage/stage_1
    specific_properties:
      block:
        hardness: -1
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
  cabbage_stage_2:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/customcrops/cabbage/stage_2
    specific_properties:
      block:
        hardness: -1
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
  cabbage_stage_3:
    display_name: ""
    resource:
      generate: false...


  cabbage_seeds:
    display_name: "Cabbage Seeds"
    resource:
      generate: false
      material: PAPER
      model_path: item/customcrops/cabbage/cabbage_seeds
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=zQilR62KuOk
https://www.youtube.com/watch?v=rY7lcPKLopY
