### ISSUE TITLE
Additional loots conditions

### ISSUE THREAD

**Issue by Gu57-git** [PluginBugs/Issues-ItemsAdder#4817]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

gust1337

### Describe the solution you'd like

Possibility to use next conditions for loots:
- **min_height** and **max_height** (for entities and fishing)
- **min_time** and **max_time** (in ticks)

Optional:
Advanced conditions with PlaceholderAPI placeholders support

Example: 
``` 
loots:
  fishing:
    item_example:
      advanced_conditions:
        condition_1: %player_exp% < 500
        condition_2: %player_saturation% > 10
      items:
        item_1:
          item: ia:item_example
          min_amount: 1
          max_amount: 1
          chance: 100
```
Condition return true and drop **ia:item_example** only when player exp value is lower than 500 and saturation value bigger than 10

### Is your feature request related to a problem?

d

### Describe alternatives you've considered

d

### Additional context

d

**Comment by LoneDev6** [comment]
I prefer to avoid using some pseudo codice conditions and instead implement some configurations for them, because I can optimize the lookup internally.

Which features do you need exactly? Loots based on stats?

**Comment by Gu57-git** [comment]
> Which features do you need exactly? Loots based on stats?

Made some examples of stats and where it can be used:


- player_min_hp and player_max_hp - Can be useful for dropping healing potions/other healing stuff when it's really needed to player (same mechanic used in Terraria game, for example) [FISHING, MOBS, BLOCKS]:
```
loots:
  blocks:
    example:
      type: example:example
      statistic_condition:
        player_min_hp: 6
        player_max_hp: 15
      items:
        apple:
          item: GOLDEN_APPLE
          min_amount: 1
          max_amount: 1
          chance: 100
```
- player_min_hunger and player_max_hunger - Can be useful for dropping food when it's really needed to player [FISHING, MOBS, BLOCKS]:
```
loots:
  blocks:
    example:
      type: example:example
      statistic_condition:
        player_min_hunger: 6
        player_max_hunger: 15
      items:
        apple:
          item: APPLE
          min_amount: 1
          max_amount: 1
          chance: 100
```
- player_entity_kills  - Can be useful for dropping trophies once/looped (every 100 in example) when player killed enough of specific entities/players/all entities (but requre to add possibility to specify ALL type in mob type option) [MOBS]:
```
loots:
  mobs:
    example:
      type: ZOMBIE
      statistic_condition:
        player_entity_kills: 
          type: ZOMBIE   #<- option can be useful, when you need to count specific entity, but drop item from other
          value: 100
          looped: true
      items:
        zombie_head:
          item: ZOMBIE_HEAD
          min_amount: 1
          max_amount: 1
          chance: 100
loots:
  mobs:
    example:
      type: ALL 
      statistic_condition:
        player_entity_kills: 
          type: ALL
          value: 100
          looped: true
      items:
        diamond:
          item: DIAMOND
          min_amount: 1
          max_amount: 1
          chance: 100
loots:
  mobs:
    example:
      type: PLAYER
      statistic_condition:
        player_entity_kills: 
          type: PLAYER
          value: 100
          looped: true
      items:
        iron_sword:
          item: IRON_SWORD
          min_amount: 1
          max_amount: 1
          chance: 100
```
- player_mined_block -  Can be useful for dropping trophies once/looped (every 500 in example) when player break specific or any block enough times [BLOCKS]:
```
loots:
  blocks:
    example:
      type: STONE
      statistic_condition:
        player_mined_block: 
          type: STONE
          value: 500
          looped: true
      items:
        DIAMOND:
          item: DIAMOND
          min_amount: 1
          max_amount: 1
          chance: 100
```
