### ISSUE TITLE
Display name custom colors

### ISSUE THREAD

**Issue by Envqu** [PluginBugs/Issues-ItemsAdder#4825]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

Envqu

### What happened?

Custom display_name adds &f at the beginning when custom HEX color are used.
I tried 3 formats: MiniMessage, § and &#. 

### Steps to reproduce the issue

```
  zegar_powrotu:
    display_name: "&#FAD64A&lT&#C99068&le&#984987&ls&#6703A5&lt"
    lore:
      - "&8Lore"
    permission: icon
    resource:
      material: IRON_HORSE_ARMOR
      generate: true
      textures:
      - item/special/zegar_powrotu.png
```

/itemname shows "&f" at the beginning so its "&f&#FAD64A&lT&#C99068&le&#984987&ls&#6703A5&lt"

### Server version

Current Purpur Version: 1.21.4-2416-51aafbc (MC: 1.21.4)*

### ItemsAdder Version

4.0.12-beta-6

### ProtocolLib Version

5.4.0-747

### LoneLibs Version

1.0.65

### Full Server Log

.

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```
