### ISSUE TITLE
Implement Smithing Table recipes

### ISSUE THREAD

**Issue by VulkanoTG** [PluginBugs/Issues-ItemsAdder#524]
**Is your feature request related to a problem? Please describe.**
i miss using other crafting stations in the plugin, for example the brewing stand to make potions and etc.

**Describe the solution you'd like**
Add the option to create craftings by Smithing Table and brewing stand so you can create more things

**Describe alternatives you've considered**
install other plugins that allow this, but I believe it would be possible to do by Itemsadder

**Additional context**
an example would be the potion that marks the diamonds, it might be possible to craft by brewing stand. or an upgrade that only spent one item just to convert let's say the diamond hammer be converted pro from netherite

**Comment by ElMoha943** [comment]
I would also like smithing table as a valid crafting station, i tried to workaround it using blocktradding machines but they dont keep enchantments 
![image](https://user-images.githubusercontent.com/25410859/125140535-218fb500-e0e9-11eb-9fc4-3a827107b273.png)

**Comment by purejosh** [comment]
Bump. This feature would be immensely valuable to weaponsmith players.

**Comment by LoneDev6** [comment]
This is planned in the future updated

**Comment by LoneDev6** [comment]
Will be added on 3.2.5
```yml
info:
  namespace: test
recipes:
  smithing:
    test1:
      base: ruby_sword
      addition: ruby_block
      result:
        item: end_sword
        amount: 1
        move_attributes:
          enchants: true
          durability: false
          custom_model_data: false
          material: false
          other_nbt: false
```
