### ISSUE TITLE
[Suggestion] Add an option to disable automatic show all categories

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#534]
> [<img alt="R-Josef" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/R-Josef) **Authored by [R-Josef](https://github.com/R-Josef)**
_<time datetime="2020-11-19T23:01:53Z" title="Friday, November 20th 2020, 12:01:53 am +01:00">Nov 20, 2020</time>_
_Closed <time datetime="2020-12-04T14:16:21Z" title="Friday, December 4th 2020, 3:16:21 pm +01:00">Dec 4, 2020</time>_
---

**Is your feature request related to a problem? Please describe.**
I have localized the ia_gui.yml file, i found that the latest version will show all categories automatic, but it makes me can not custom category names, i want translate them to chinese.

**Describe the solution you'd like**
Add an option to disable automatic show all categories.
Example:
```yaml
categories:
  show_all_categories: true
  all:
    enabled: true
    icon: "itemsadder:ruby_block"
    name: display-category-all
    show_all_items: true
    hide_items:
      - "......"
```

**Describe alternatives you've considered**
Add all of default category names to language file.
