### ISSUE TITLE
[Suggestion] Option to Disable ActionBar Message

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#581]
> [<img alt="Xuwznln" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Xuwznln) **Authored by [Xuwznln](https://github.com/Xuwznln)**
_<time datetime="2020-12-26T02:14:04Z" title="Saturday, December 26th 2020, 3:14:04 am +01:00">Dec 26, 2020</time>_
_Closed <time datetime="2021-01-11T12:37:32Z" title="Monday, January 11th 2021, 1:37:32 pm +01:00">Jan 11, 2021</time>_
---

**Is your feature request related to a problem? Please describe.**
I use an addon called betterhud. This shows thirsty and health info with bossbar instead of actionbar. So if I want to enable built-in thirsty function, action bar will still show something invisible and sometimes show a word "null". I only want thirsty function but dont want to show the action-bar  message.

**Describe the solution you'd like**
Provide an option like:
```
  thirst:
    enabled: true
    show:
      **disable: true**
      auto: false
      creative: false    
      underwater: false
      riding: false
```
**Describe alternatives you've considered**
Maybe No.
