### ISSUE TITLE
[BUG] ItemsAdder blocks are desynced and mushrooms bugged

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#583]
> [<img alt="imparium-de" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/imparium-de) **Authored by [imparium-de](https://github.com/imparium-de)**
_<time datetime="2021-01-03T15:09:42Z" title="Sunday, January 3rd 2021, 4:09:42 pm +01:00">Jan 3, 2021</time>_
_Closed <time datetime="2021-01-12T15:38:00Z" title="Tuesday, January 12th 2021, 4:38:00 pm +01:00">Jan 12, 2021</time>_
---

**Describe the bug**
When placing an ItemsAdder block and breaking it again, it's still there for other players

**To Reproduce**
1. Place a block
2. Break the block
3. See that it's still there and solid

**Expected behavior**
It should disappear for both players

**Screenshots**
https://streamable.com/0ep3ec

EDIT: It's not only with mushrooms https://streamable.com/cc92d1

**Info (please complete the following information):**
 - Server version: git-Paper-306 (MC: 1.16.4)
 - Client version: 1.16.4 with OptiFine HD_U_G5
 - Plugin version: 2.1.23

**Additional context**
It happens with all mushroom blocks. Naturally spawned brown mushrooms are also bugged that they show ItemsAdder blocks. 
The config should be right:

```
blocks:
  light-api: true
  fix-bugged-mushrooms:
    enabled: true
    only-new-chunks: true
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
    mining-fatigue:
      enabled: true
      duration: 20
      amplifier: 1
  campfire:
    unlit-on-place: true
    allow-any-item: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance: false
    seach-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  disable-REAL-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  disable-REAL_TRANSPARENT-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  ```
