### ISSUE TITLE
[BUG] Enchantments are not working !

### ISSUE THREAD

**Issue by ValouProjet** [PluginBugs/Issues-ItemsAdder#584]
**Describe the bug**
With the last update, the "enchantments" in the config files on : armor, swords & tools are not working anymore.

**To Reproduce**
Juste create a sword, tool or piece of armor with an enchant on it, example with my armor file :

bottes_rubis:
    display_name: '&rBottes en rubis'
    permission: armures
    enchants:
    - PROTECTION_ENVIRONMENTAL:2
    lore:
    - '&e&oKit Seigneur'
    - ''
    resource:
      generate: true
    durability:
      max_custom_durability: 458
    specific_properties:
      armor:
        slot: FEET
        color: b02e26
    attribute_modifiers:
      feet:
        armor: 3.5
        armorToughness: 2

**Expected behavior**
In the last versions of IA, it was working fine, i had my armor with the enchantment (protection II there) on it.
Since the last update, it gives me the item without the enchantment. (and it's the same for the swords, armors & tools)

And it stopped working juste after i uptaded IA to the last version. So pretty sure it comes with the last update.

So expected behavior : it should be enchanted..

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: Minecraft 1.15.2
 - Plugin version: 2.1.23

**Comment by LoneDev6** [comment]
Please attach a correctly formatted configuration, use pastebin or similar websites, I cannot check if there is an error as everything is aligned at the same level.
Also I suggest you to use [this free tool](https://ide.plugin.ga/itemsadder/) to create your items to avoid mistakes (as explained in the tutorials)

Thanks

**Comment by ValouProjet** [comment]
I don't think there is a problem in my config files, it was working super well without any errors in the console. I just uptaded IA to the new version and the thing is that is still working, i still receive the item with the lome, the correct data (all is working) but WITHOUT the enchantment.

For the Pastebin :
https://pastebin.com/TfikUimR

You should try yourself pretty sure it will not work.
Thanks for your answer and have a nice day !

**Comment by LoneDev6** [comment]
Using latest itemadder and it works, I have no idea sincerly, maybe it's another plugin interfering

![image](https://user-images.githubusercontent.com/27242001/104335256-816b2180-54f3-11eb-9025-39be12b8bfdf.png)

**Comment by ValouProjet** [comment]
i searched where was the problem and i found something : the enchantment is working WHEN i remove the attribute_mofidiers, this :

attribute_modifiers:
feet:
armor: 3.5
armorToughness: 2

Weird... so i suppose it comes from another plugin :/ ?

**Comment by ValouProjet** [comment]
and it's why it's working on bow but not swords, armors & tools.
Because bow doesn't have that attribute_modifier section

**Comment by LoneDev6** [comment]
I just copied and pasted your text when I send you the screenshot
![image](https://user-images.githubusercontent.com/27242001/104342104-c5adf000-54fa-11eb-90b3-762b16ada176.png)

```yml
  bottes_rubis:
    display_name: '&rBottes en rubis'
    permission: armures
    enchants:
    - PROTECTION_ENVIRONMENTAL:2
    lore:
    - '&e&oKit Seigneur'
    - ''
    resource:
      generate: true
    durability:
      max_custom_durability: 458
    specific_properties:
      armor:
        slot: FEET
        color: b02e26
    attribute_modifiers:
      feet:
        armor: 3.5
        armorToughness: 2
```
