### ISSUE TITLE
[BUG] Resource Pack download

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ItemsAdder#593]
Ciao Matteo, volevo segnalarti che ogni volta che effettuo il login su minecraft, mi da sempre e lo da a tutti gli utenti un errore riguardo alla texture pack

![image](https://user-images.githubusercontent.com/20026629/104842905-1db47000-58c8-11eb-9b92-26fd6ccf3bb0.png)

Il fatto è che come puoi vedere in realtà alla fine questo errore non è reale... cioé lui tenta di fare il download della resource pack più volte appena entrato, ma poi alla fine ci riesce tranquillamente.

Te lo volevo segnalare perché c'è qualche cosa che comunque non va nel sistema di download e magari gli potresti dare un occhiata.

Inoltre ci tenevo anche a dirti che il kick-player-on-fail: false è completamente buggato praticamente banna i players... e forse è legato all'errore che viene dato all'inizio

```
metrics: true
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 20
  self-host:
    enabled: false
    server-ip: 127.0.0.1
    pack-port: 8163
  external-host:
    enabled: true
    url: http://www.survivalla.fun/respack/pack55.zip
  custom-font:
    enabled: false
    name: font.ttf
  thin-font:
    enabled: true
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: false
  title:
    enabled: true
    ```

**Comment by LoneDev6** [comment]
we

Prova ad incrementare delay-ticks a 100.
Controlla anche di non aver nessun resourcepack impostato in server.properties e non aver nessun altro plugin che tenta di applicare resourcepack. Questi son gli unici due casi in cui ho riscontrato un problema simile, altrimenti non ne ho idea sinceramente

**Comment by LoneDev6** [comment]
Chiudo per inattività, nel caso ci siano notizie scrivi pure qui che riapro

**Comment by Fargus5** [comment]
Ho una brutta notizia per te @LoneDev6 
Ho provato a mettere i valori cosi:
```
resource-pack:
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
```  
proprio per vedere se entrando ci fossero altre resourcepack che si mettevano a scaricarsi automaticamente.
e la risposta è no.

quindi sostanzialmente ci sta solo itemsadder che si mette a scaricare la texture.

sistematicamente ed a tutti i giocatori, appena fai il login, fa un primo tentativo che fallisce e poi dopo
  delay-ticks: 100
  ritenta di scaricarla e ci riesce senza problemi.
