### ISSUE TITLE
[BUG] Resource Pack download

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#603]
> [<img alt="Fargus5" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Fargus5) **Authored by [Fargus5](https://github.com/Fargus5)**
_<time datetime="2021-01-17T12:36:15Z" title="Sunday, January 17th 2021, 1:36:15 pm +01:00">Jan 17, 2021</time>_

---

Ciao Matteo, volevo segnalarti che ogni volta che effettuo il login su minecraft, mi da sempre e lo da a tutti gli utenti un errore riguardo alla texture pack

![image](https://user-images.githubusercontent.com/20026629/104842905-1db47000-58c8-11eb-9b92-26fd6ccf3bb0.png)

Il fatto è che come puoi vedere in realtà alla fine questo errore non è reale... cioé lui tenta di fare il download della resource pack più volte appena entrato, ma poi alla fine ci riesce tranquillamente.

Te lo volevo segnalare perché c'è qualche cosa che comunque non va nel sistema di download e magari gli potresti dare un occhiata.

Inoltre ci tenevo anche a dirti che il kick-player-on-fail: false è completamente buggato praticamente banna i players... e forse è legato all'errore che viene dato all'inizio

```
metrics: true
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 20
  self-host:
    enabled: false
    server-ip: 127.0.0.1
    pack-port: 8163
  external-host:
    enabled: true
    url: http://www.survivalla.fun/respack/pack55.zip
  custom-font:
    enabled: false
    name: font.ttf
  thin-font:
    enabled: true
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: false
  title:
    enabled: true
    ```
