### ISSUE TITLE
[Suggestion] The ability to create crafting recipes in the 2x2 crafting field

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#612]
**Is your feature request related to a problem? Please describe.**
We created a custom recipe for charcoal -> charcoal block and vice versa. The problem is that in your inventory, you're unable to craft the block back to charcoal, because the config doesn't seem to support that. In the wiki at https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/recipes it says "In this example I created a `crafting_table` recipe called `deadmau5_hat`", and I could find anything to replace `crafting_table`.

**Describe the solution you'd like**
Another option like `inventory` where you can create 2x2 crafting recipes

**Describe alternatives you've considered**
An alternative would be to use something like the bottom part of the 3x3 option, where IA would recognize it as an 2x2 recipe. 
Example:
```
pattern:
      - AAA
      - ACC
      - ACC
      ingredients:
        C: CHARCOAL
        A: AIR
```

**Comment by ArgonGaming** [comment]
Good idea!

**Comment by LoneDev6** [comment]
Thanks, I added this feature in the new update.
Please let me know if anything recipes related broke, but I did all the tests I could and everything seems to work fine.

Recipes must be like this:
(bottom right, first line all XXX)
```yml
    taco:
      permission: itemsadder.taco
      enabled: true
      pattern:
      - XXX
      - XSC
      - XPB
      ingredients:
        B: itemsadder:baguette
        C: itemsadder:sliced_roast_beef
        P: itemsadder:potato_sticks
        S: itemsadder:lettuce
```
Check here for more info https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/recipes
