### ISSUE TITLE
[Suggestion] Options for adding experience to mob, block and fishing drops

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#627]
The vanilla Ore_ Block can drop experience
I think this option can be added to improve the drop...

**Comment by LoneDev6** [comment]
already possible, for example

```yml
loots:
  fishing:
    fishing_1:
      biomes:
        - BEACH
      exp:
        exp_1:
          min_amount: 1
          max_amount: 5
          chance: 99.9
  mobs:
    cat:
      enabled: true
      type: CAT
      exp:
        exp_1:
          min_amount: 1
          max_amount: 5
          chance: 99.9
```
