### ISSUE TITLE
[Suggestion] Add saturation for IA food (overfeed / yellow bar from modpacks)

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#630]
**Is your feature request related to a problem? Please describe.**
When eating ItemsAdder food, it doesn't add saturation like normal vanilla food. This makes stuff like pizzas pretty useless to eat unless you're already about to starve. 

**Describe the solution you'd like**
I'd love to see a new config option where you can define a fixed amount of saturation for each food item.
Example:
```
    events:
      eat:
        feed:
          amount: 9
        saturation:
          amount: 12
```

**Describe alternatives you've considered**
And alternative would be to continue to eat even though your hunger is full, so ItemsAdder checks for the saturation value (yellow bars) instead of the hunger of a player and adds the "overflowing" food bars as saturation.

**Additional context**
A small video that should explain it better: https://s.imparium.de/niho0/QAkuGoLu58.mp4

**Comment by LoneDev6** [comment]
Thanks for the suggestion!
I decided to add it like that since they are handled the same event in vanilla Minecraft, seems more intuitive to me:
```yml
        feed:
          amount: 9
          saturation: 12
```
You can also set a negative value if you want to make a some sort of poisoned food.

Here you can get the list of vanilla saturation values: https://minecraft.gamepedia.com/Hunger#Food_level_and_saturation_level_restoration


This will be available in the next update
