### ISSUE TITLE
[Suggestion]  Removal of Pink Potion Effect when

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#636]
All my Beverages use POTION as it's host, because of this they all gain the Pink Hue when i try to sell them in a Shop Plugin, I need to be able to remove this shimmer effect of potions from my Beverages.

**Comment by SirCraftypants** [comment]
![2021-02-02](https://user-images.githubusercontent.com/66942713/106775308-e7eae780-663a-11eb-88e2-f42affb4a524.png)

**Comment by SirCraftypants** [comment]
I've requested help from the shop plugin dev but they are one of the worst ever for support so though i'd see if you have any idea if it's possible to get rid of.

**Comment by SirCraftypants** [comment]
Thing is, Itemsadder doesn't show my custom drinks using POTION to host with the potion shimmer effect, so why can't it do the same in my shop plugin, if you have any info on this subject you can let me know please.

**Comment by SirCraftypants** [comment]
My question is, how did you prevent the shimmer from loading over our drinks textures when using potion as the host.

**Comment by LoneDev6** [comment]
```yml
  cola:
    display_name: display-name-cola
    permission: cola
    resource:
      material: POTION
      generate: true
      textures:
      - item/cola.png
    specific_properties:
      potion:
        type: WATER
        color: WHITE
    item_flags:
    - HIDE_POTION_EFFECTS
    events:
      drink:
        increment_player_stat:
          name: thirst
          amount: 5
```

for example all itemsadder drinks use the potion as base, you can see I set color to WHITE
