### ISSUE TITLE
[Suggestion] Replace_block action for blocks not just items

### ISSUE THREAD

**Issue by JustJP2K** [PluginBugs/Issues-ItemsAdder#672]
Im trying to change the block type of a custom log into a stripped log when right clicking on it with any type of normal axe.
This isnt currently possible since you can only put the action replace_near_blocks on items but not the custom block itself.
Meaning you would need a custom tool to make this change possible

So having an action like replace_block for custom blocks would be a lifesaver :)

**Comment by LoneDev6** [comment]
Thanks.
In the new update you will be able to do something like that:

```yml
  custom_log:
    display_name: "Custom Log"
    permission: custom_log
    resource:
      material: ACACIA_LOG
      generate: true
      textures:
      - block/custom_log.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
        break_tools_whitelist:
        - _AXE
        - _axe
        events_tools_whitelist:
        - _AXE
        - _axe
        hardness: 0.5
    events:
      placed_block:
        interact:
          replace_block:
            decrement_durability:
              amount: 1
            from: custom_log
            to: stripped_custom_log
          play_sound:
            name: item.axe.strip
            volume: 1
            pitch: 0.8
          play_sound_2:
            name: item.log.break
            volume: 1
            pitch: 0.8
  stripped_custom_log:
    display_name: "Stripped Custom Log"
    permission: stripped_custom_log
    resource:
      material: STRIPPED_ACACIA_LOG
      generate: true
      textures:
      - block/stripped_custom_log.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
        break_tools_whitelist:
        - _AXE
        - _axe
        hardness: 0.5
```
