### ISSUE TITLE
[Suggestion] new events, Interact Right/Left Block -> replace item customitems

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#685]
I want to make Thaumcraft on 1.16.5, and I need to take a lot of functions, for example, using Salis Mundus, if I click on the bookshelf with the right mouse button, I should get a Taumonomicon, I need to make this function, please

**Comment by LoneDev6** [comment]
answered on discord

```yml
  custom_bookshelf:
    display_name: "Custom Bookshelf"
    permission: custom_bookshelf
    resource:
      material: BOOKSHELF
      generate: true
      textures:
      - block/custom_bookshelf.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
        break_tools_whitelist:
        - _AXE
        - _axe
        hardness: 0.5
    events:
      placed_block:
        interact:
          replace_block:
            decrement_durability: 1
            from: custom_bookshelf
            to: AIR
          give_item:
            item: DIAMOND
            amount: 1
```
