### ISSUE TITLE
repopulate grass as pebbles | worlds_populators 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#718]
Can't replace grass to be pebbles because it's furniture , 
- it should be not solid , that's why I did not use Blocks 
I tried to to make some thing like this but did not work with me 
```
worlds_populators:
  pebbles:
    block: halloweenie:pebbles
    worlds:
    - world
    replaceable_blocks:
    - GRASS
    chance: 100
    max_height: 200
    min_height: 0
    amount: 50
    iterations: 1
```

![Screenshot 2021-03-02 000232](https://user-images.githubusercontent.com/68678154/109565085-a3902180-7aea-11eb-8f5e-dcd59600896d.png)

**Describe the solution you'd like**
the solution is to be able to use worlds_populators on furniture or add new properties that makes blocks not solid
