### ISSUE TITLE
[Suggestion] Hex colors in lang file

### ISSUE THREAD

**Issue by MrmaximoExcssum** [PluginBugs/Issues-ItemsAdder#721]
Hey, could you add HEX support for the lang file and "\n" to make new lines?

Itemsadder > lang > en.yml

**Comment by 100petr** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/320

**Comment by LoneDev6** [comment]
Will be added in the next update, example:
```yml
  iron_arrow:
    display_name: "%#FE5A00%Iron Arrow"
    permission: arrows.iron_arrow
    resource:
      material: ARROW
      generate: true
      textures:
      - "minecraft:item/spectral_arrow.png"
    events:
      item_hit_entity:
          damage_entity:
            damage: 1
```

Special character is %%
