### ISSUE TITLE
[Suggestion] Spawners Drops custom items {EntityID control spawners drop}

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#723]
Make it so that my custom item can drop out of the desired spawner of a mob, for example, spawner {EntityId: Zombie} - drop my custom elements, and so on..

**Comment by MrJorman** [comment]
UP PLS man Priority 100/100

**Comment by LoneDev6** [comment]
Will be added in the next update.
```yml
loots:
  blocks:
    change_me:
      enabled: true
      type: SPAWNER
      nbt:
        spawner_type:
          path: SpawnData.id
          value: minecraft:zombie
          type: string
      items:
        change_me:
          item: ACACIA_BOAT
          min_amount: 1
          max_amount: 1
          chance: 100
          ignore_fortune: false
```
