### ISSUE TITLE
[BUG] Netherite tools burn in lava!!!

### ISSUE THREAD

**Issue by samodyr** [PluginBugs/Issues-ItemsAdder#726]
Custom items with my texture,
which are tied to netherite tools and logically should not burn - ignore this fact and calmly burn...

Server: Yatopia, 1.16.5
ItemsAdder: 2.1.38

**Comment by LoneDev6** [comment]
Tested creating this item and works fine on IA 2.1.42
```yml
  test:
    display_name: test
    permission: test
    resource:
      material: NETHERITE_SWORD
      generate: true
      textures:
      - item/example_item.png
    durability:
      max_custom_durability: 1324
```
