### ISSUE TITLE
[BUG] events target_potion_effect does not work correctly

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#747]
https://pastebin.com/fEigd7Lj

events: target_potion_effect no working, point to action at any time and it won't work. FIX PLS.

**Comment by LoneDev6** [comment]
As always, please DO NOT ERASE THE ISSUE TEXT.
Provide all the info asked.
I'm not asking them randomly, I need all the info requested to find the issue.


Here is a video of the working item: https://youtu.be/huo-YLt3NSg

Here is the code
```yml
  gandalf_stick:
    display_name: '&dПосох Гендальфа'
    permission: gandalf_stick
    resource:
      material: WOODEN_SWORD
      generate: false
      model_path: item/gandalf_stick
    durability:
      max_custom_durability: 850
      unbreakable: true
    attribute_modifiers:
      mainhand:
        attackDamage: 1.0
        attackSpeed: 1.2
    events_cooldown: 400
    events:
      interact:
        entity:
          target_potion_effect:
            type: LEVITATION
            duration: 300
            amplifier: 1
        right:
          play_particle:
            name: ENCHANTMENT_TABLE
          play_sound:
            name: minecraft:entity.ender_dragon.shoot
            volume: 1
            pitch: 1
      attack:
        play_particle:
          name: ENCHANTMENT_TABLE
          ```
