### ISSUE TITLE
Furniture No sound Material: PAPER 

### ISSUE THREAD

**Issue by WizardGtG** [PluginBugs/Issues-ItemsAdder#784]
i have problem, when i place any chair with material, paper it doesn't make any sound also no animation when you place it, i tried to use sounds but it's only working on blocks.

```
sound: #customizable sounds of the block

          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9

```
### GIF: It's not a sound but you will understand. https://imgur.com/a/C99NmN1
PaperSpigot 1.16.5
ItemsAdder 2.2.6
