### ISSUE TITLE
[Suggestion] Full #HEX color support and..

### ISSUE THREAD

**Issue by MrmaximoExcssum** [PluginBugs/Issues-ItemsAdder#786]
I want full #HEX color support, and the option to do \n for new lines.

I primarly want \n for new lines in ItemAdder > Lang > en.yml > "resourcepack-error:" and "resourcepack-kick-declined:"

**Comment by 100petr** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/721

**Comment by LoneDev6** [comment]
will be added in the future, thanks

duplicate of #721

**Comment by LoneDev6** [comment]
Will be added in the next update, example:
```yml
  iron_arrow:
    display_name: "%#FE5A00%Iron Arrow"
    permission: arrows.iron_arrow
    resource:
      material: ARROW
      generate: true
      textures:
      - "minecraft:item/spectral_arrow.png"
    events:
      item_hit_entity:
          damage_entity:
            damage: 1
```

Special character is %%
