### ISSUE TITLE
[Suggestion] No drops for spawner mobs

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#791]
**Describe alternatives you've considered**
I would like some option to turn off drops for mobs spawned by the spawner.

**Additional context**
We set up various IA drops for the mobs on the server, but the players made farms for this via spawners, and thus the items lose value.

**Comment by 100petr** [comment]
No. Players use spawners to farm drops that we have set up for mobs. So if mob drops coins with which you can get something on the server, players will use spawners. Because they have it lighter and more effective than killing natural mobs.so I imagine a solution so that the mobs from the spawner do not give the set drops.

**Comment by LoneDev6** [comment]
But how did you set these drops? with which plugin?
I don't understand

**Comment by 100petr** [comment]
Normally via ItemsAdder. Ex.:
```
loots:
  mobs:
    villager:
      type: VILLAGER
      items:
        item_1:
          item: ananasomanie:commonmoneybag
          min_amount: 1
          max_amount: 1
          chance: 5
        item_2:
          item: ananasomanie:uncommonmoneybag
          min_amount: 1
          max_amount: 1
          chance: 2
```
And I just don't want these drops from the mobs from the spawner.

**Comment by LoneDev6** [comment]
> 
> 
> Normally via ItemsAdder. Ex.:
> 
> ```
> loots:
>   mobs:
>     villager:
>       type: VILLAGER
>       items:
>         item_1:
>           item: ananasomanie:commonmoneybag
>           min_amount: 1
>           max_amount: 1
>           chance: 5
>         item_2:
>           item: ananasomanie:uncommonmoneybag
>           min_amount: 1
>           max_amount: 1
>           chance: 2
> ```
> 
> And I just don't want these drops from the mobs from the spawner.

OHHH so basically the request is:
allow an option to disable dropping if mobs are spawned from SPAWNER block and not naturally?

**Comment by 100petr** [comment]
Yes.

**Comment by LoneDev6** [comment]
Will be added in next update and will be true by default, so your rules will now ignore mobs spawned by spawners, no need to add `ignore_spawner: true` to each of your configs
```yml
loots:
  mobs:
    change_me:
      type: PIG
      ignore_spawner: true
      items:
        change_me:
          item: ACACIA_BOAT
          min_amount: 2
          max_amount: 2
          chance: 100
```
