### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alvid98** [PluginBugs/Issues-ItemsAdder#807]
**Describe the bug**
The commands in an action doesnt do in order.

**To Reproduce**
1. put execute_command on config
2. Put severals commands
3. The commands doent do in order

**Expected behavior**
When i put 3 commands in the config in order to give a permission to certain command. It doesnt do the requested way, it does first the as_console: true commands and then the as_console: false commands

**Screenshots**
i tried several things like this:
```
          execute_commands
            first_command_first:
              command: 'lp user {player} permission set mycommand.cmd.particulafuego'
              as_console: true
            second_command_second:
              command: 'particulafuego'
              as_console: false
            third_command_third:
              command: 'lp user {player} permission unset mycommand.cmd.particulafuego'
              as_console: true
```
```
          execute_commands
            first:
              command: 'lp user {player} permission set mycommand.cmd.particulafuego'
              as_console: true
            second:
              command: 'particulafuego'
              as_console: false
            third:
              command: 'lp user {player} permission unset mycommand.cmd.particulafuego'
              as_console: true
```
```
          execute_commands_first:
            first:
              command: 'lp user {player} permission set mycommand.cmd.particulafuego'
              as_console: true
          execute_commands_second:
            second:
              command: 'particulafuego'
              as_console: false
          execute_commands_third:
            third:
              command: 'lp user {player} permission unset mycommand.cmd.particulafuego'
              as_console: true
```

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: forge 1.16.5
 - Plugin version: 2.2.9
