### ISSUE TITLE
[Suggestion] Ability to use loot_table

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#823]
Loot table give a lot of flexibility to drop from blocks, mob kill or fishing with the use of predicate. I was creating treasure chest and i would like to have the contain one of multiple loot pool instead of mix matching multiple items type or having to create a tons of different chest with loot that isn't exactly what I'm expecting.
It would make it easier in a way to set drop from blocks or even furniture with the use of loot table table. In the loot section, instead of adding the path of items, we could set the path to custom loot_table.

Something that would look like this:
```
loots:
  blocks:
    ruby_ore:
      type: itemsadder:ruby_ore
      items:
        ruby:
          item: itemsadder:ruby
          min_amount: 1
          max_amount: 2
          chance: 100
 
loots:
  blocks:
    ruby_ore:
      type: itemsadder:ruby_ore
      items:
        ruby:
          loot: minecraft:gameplay/custom_loot/...
```
