### ISSUE TITLE
Customise Title Loading Text

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#825]
**Be able to edit the Title when loading a resource pack**
Currently there is a title between downloading the resource pack and the loading screen so it would be nice to be able to change and text. One of the main reasons is because some of the grammar isn't correct.

**The grammar could be corrected**
Correct the grammar so its grammatically correct

**Format Idea**
resource-pack:
  title:
    enabled: false
    custom-message: "Hello"

Thanks!

**Comment by LoneDev6** [comment]
please specify which message you're referring to and which grammar is not correct, i'm sure it's already customizable

**Comment by Fantom250YT** [comment]
Here you go, and its not customisable

"Please be patient, it will take only some seconds"
Should be -> "Please be patient, it will only take a few seconds"

<img width="2560" alt="Screenshot 2021-04-12 at 17 30 17" src="https://user-images.githubusercontent.com/73852683/114429090-e3036080-9bb4-11eb-8255-4c64983d58ad.png">

**Comment by LoneDev6** [comment]
thanks
you can already customize it in the language file inside lang folder

```yml
resourcepack-error: "&4An error occurred when enabling the resourcepack. Please contact admins or disable resourcepacks."
resourcepack-kick-declined: "&4You must accept the resourcepack! Also make sure you set them to 'Prompt' or 'Enabled' in server properties."
resourcepack-apply-title: "&a&lApplying resourcepack..."
resourcepack-apply-subtitle: "&6Please be patient, it will take only some seconds!"
```
