### ISSUE TITLE
[Suggestion] module management, default block particles

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#829]
**Is your feature request related to a problem? Please describe.**
About this issues #768 
so i think you should make the **module management** features
to disabled custom block module or etc.

that mean, it's will won't simulate the particle anymore
but it's can't create custom block too when i disabled module

**Describe the solution you'd like**
making **module settings** or can change particle default Noteblock and Muchroom to other thing like `AIR` in `config.yml`

**Additional context**
Example `config.yml`:

```yml
default-custom_blocks-particle:
  NOTE_BLOCK: NOTE_BLOCK
  MUSHROOM_BLOCK: MUSHROOM_BLOCK
modules:
  custom_blocks: true
  furniture: true
  font: true
  ...
```
