### ISSUE TITLE
[Suggestion] Add option to execute command on right click a furniture

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#833]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem, only a feature that i think would be useful.

**Describe the solution you'd like**
Add a behaviour option to execute commands on right click a furniture, it can be "furniture_command" like the other behaviours (furniture_sit, furniture_trade_machine)
Example:

>     behaviours:
>       furniture_command:
>         command: 'give {player} diamond 32'
>         as_console: true/false

**Additional context**
I think this feature would be useful to link furnitures with other plugins, like "/fuel shop" command from VehiclesPlus plugin, to execute that command on right click on a gas pump furniture, hope we can have this feature soon if it's possible, thanks.

**Comment by LoneDev6** [comment]
Hello, good suggestion but it's already possible
```yml
    events:
      placed_armorstand:
        interact:
          execute_commands:
            givecmd:
              command: 'give {player} diamond 32'
              as_console: true
              
```


use the online tool for easier configuration: https://ide.plugin.ga/itemsadder/
