### ISSUE TITLE
[Suggestion] Separate /ia menu background/text for every item

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#836]
Add posibility to add your own background for every item in itemsadder (/ia) menu as specific_propertie. 
You can configurate background manually as specific_properties like this:

```
specific_properties:
  ia_menu_background: 
  - ":offset_N::background_icon:"
```

**Comment by LoneDev6** [comment]
Will be added in the next update.
Example:
```yml
info:
  namespace: ia_various_configs
categories:
  armors:
    enabled: true
    skip_if_already: false
    icon: itemsadder:ruby_head
    name: display-category-armors
    permission: ia.menu.armors
    font_image:
      name: "mcguis:blank_menu"
      x_position_pixels: -16
    title_position_pixels: 0
    items:
      - itemsadder:ruby_sword
      - itemsadder:ruby_head
      - itemsadder:ruby_chest
      - itemsadder:ruby_legs
```
