### ISSUE TITLE
[Suggestion] Add held_offhand and unheld_offhand Events

### ISSUE THREAD

**Issue by alejandro0256** [PluginBugs/Issues-ItemsAdder#857]
Add events for the second hand. For example held_offhand and unheld_offhand

**Comment by LoneDev6** [comment]
why is this needed?

**Comment by alejandro0256** [comment]
I want to equip a full costume to the player while he is holding the item in the second hand.
I was thinking to execute a command that equips the costume when you hold the item on the second hand and another command to remove it when you unhold that item.
In my case I want it for something very specific, but also maybe it can be useful to create more interesting shields or other type of items used like passive skills, or more complex items, etc...

**Comment by LoneDev6** [comment]
i understand but it's a bit complex to implement, I don't think I will add this in the next update, sorry

**Comment by TenReeez** [comment]
I agree.

I want to add a potion effect to a shield when in offhand. Shield slot.

But nothing works

**Comment by LoneDev6** [comment]
Example of the upcoming feature:
```yml
info:
  namespace: test
items:
  test_held:
    display_name: test held
    resource:
      generate: false
      model_path: minecraft:item/diamond
      material: STONE_SWORD
    events:
      held:
        execute_commands:
          change_me_1:
            command: tell {player} &6held - {debug-event-name}
            as_console: true
      unheld:
        execute_commands:
          change_me_1:
            command: tell {player} &cunheld - {debug-event-name}
            as_console: true
      held_offhand:
        execute_commands:
          change_me_1:
            command: tell {player} &6held offhand - {debug-event-name}
            as_console: true
      unheld_offhand:
        execute_commands:
          change_me_1:
            command: tell {player} &cunheld offhand - {debug-event-name}
            as_console: true
```
