### ISSUE TITLE
add way to be able to use events For furniture

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#861]
![image](https://user-images.githubusercontent.com/68678154/115950656-e237cc00-a4dc-11eb-8c1f-46cdda18a004.png)
We need to be able to use events for furniture Example |  I Need to make a bin (trash) with a command and sound but I can't because it's furniture

```
  bin_2:
    display_name: Bin
    lore:
    - 'Decorative Item'
    resource:
      material: DARK_OAK_WOOD
      generate: false
      model_path: item/bin_2
    behaviours:
      furniture:
        small_hitbox: true
        solid: true
        fixed_rotation: true
    events:
      placed_block:
        interact:
          execute_commands:
            1_cmd:
              as_console: false
              command: 'trash'
            2_cmd:
              as_console: false
              command: 'playsound minecraft:item.book.page_turn neutral {player} ~ ~ ~ 10000000000 0.8'  
```
