### ISSUE TITLE
[Suggestion] Add option to disable fuel use on vehicles

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#879]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem, it's a feature that i think would be useful

**Describe the solution you'd like**
Add a config option to disable fuel on vehicles, like "enable: false", i already tried adding minus values on max and start options on the fuel section, but not working.
Example:
```
  wheelchair:
    display_name: '&fWheelchair'
    permission: wheelchair
    resource:
      material: IRON_NUGGET
      generate: false
      model_path: vehicles/wheelchair
    behaviours:
      vehicle:
        fuel:
          enable: false
```
**Additional context**
I think it would be useful to make vehicles that doesn't require fuel, like a bike, a wheelchair, tricycle, etc. Like in real life
