### ISSUE TITLE
[Suggestion] 2D textures of blocks

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#881]
version 1: New thing for blocks
Request description:
This function would make it possible to have a different model in the inventory (Or a flat 2D texture), and if we laid this block, it would have a different model than in the inventory. This function would be just below either (model_path or texture) And of course the REAL_STRING function (tripwire, but I won't confuse it here, even if it was a very great option.)

Screenshot:
In the picture we can notice one plant (tripwire).
It has a flat 2D texture in its inventory, but when I put it on the ground, it has its own model and that's what it's all about.
![2021-04-28 (4)](https://user-images.githubusercontent.com/62265168/117447076-4e82e880-af3d-11eb-967c-edcf71ceaac7.png)

version 2: new event and events
Or it could be done differently with items / events / actions.
new event for item: place_block.
I would create an item and a block. For the item, I would put the event place_block and choose which block I would like to place on the ground using the right button.

**Comment by MinecollYT** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/741

**Comment by TeiBri** [comment]
> #741

Have you read my entire suggestion? I know about 741, but this suggestion has nothing to do with it.

**Comment by MinecollYT** [comment]
So you want something like a "custom turtle egg", because that has exactly the function. Showing a spawn egg as an item and showing something differnt when placed

**Comment by TeiBri** [comment]
> Chcete tedy něco jako „vlastní želví vejce“, protože to má přesně tu funkci. Zobrazovat spawn vejce jako předmět a při umístění ukazovat něco jiného

Yes. In the inventory 2D texture and when I right click on the ground, it will have its own model.

**Comment by LoneDev6** [comment]
This may be added in the future, it would be a bit complicated as to make this you have to create two items: one for the placed model and one for the inventory model.
Basically placed model won't be able to be obtained ingame but only spawned as block or furniture.

This will require a rewrite of a lot of the code of ItemsAdder, so I have to delay this feature release for now.
I hope you understand.

**Comment by TeiBri** [comment]
> This may be added in the future, it would be a bit complicated as to make this you have to create two items: one for the placed model and one for the inventory model.
> Basically placed model won't be able to be obtained ingame but only spawned as block or furniture.
> 
> This will require a rewrite of a lot of the code of ItemsAdder, so I have to delay this feature release for now.
> I hope you understand.

Of course I understand. Your plugin is already great (I would actually increase the price of that plugin above 30Euro :D). I'll wait for both tripwire and this update. Good luck. :-)

**Comment by TeiBri** [comment]
> This may be added in the future, it would be a bit complicated as to make this you have to create two items: one for the placed model and one for the inventory model.
> Basically placed model won't be able to be obtained ingame but only spawned as block or furniture.
> 
> This will require a rewrite of a lot of the code of ItemsAdder, so I have to delay this feature release for now.
> I hope you understand.

To conclude this suggestion. I know you closed everything about tripwire 5 hours ago, but this proposal doesn't apply to tripwire (Tripwire is just only mentioned) This proposal concerns a new system of 2D block textures in inventory, so I guess you didn't confuse it?

**Comment by LoneDev6** [comment]
Yep I closed it by mistake

**Comment by TeiBri** [comment]
> Ano, omylem jsem to zavřel

I definitely don't want to ruin your plans and nothing like that, you have your plan to add, but I'll just say (You don't have to listen to it) This suggestion is useful now after adding REAL_WIRE. We both know that the decorations that use this type of block literally need 2D textures in the GUI. (But that's just my idea, of course you don't have to follow it.)

**Comment by LoneDev6** [comment]
> 
> 
> > Ano, omylem jsem to zavřel
> 
> I definitely don't want to ruin your plans and nothing like that, you have your plan to add, but I'll just say (You don't have to listen to it) This suggestion is useful now after adding REAL_WIRE. We both know that the decorations that use this type of block literally need 2D textures in the GUI. (But that's just my idea, of course you don't have to follow it.)

This feature is definitely needed and I already added the "Complex to implement" tag because I still have to find a clean way to implement this since right now the blocks stuff is a bit misleading.
I have to separate blocks resource setting from the item itself.

Probably the model/textures settings for blocks will be moved into specific_properties.block.

An example of how it could be implemented:
```yml
items:
  ruby_block:
    display_name: display-name-ruby_block
    permission: ruby_block
    resource:
      material: PAPER
      generate: true
      textures:
      - block/ruby_block_2D.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: REDSTONE_BLOCK
          resource: # <-------
            generate: true
            textures:
            - block/ruby_block.png
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  crystal_block:
    display_name: display-name-crystal_block
    permission: crystal_block
    resource:
      material: PAPER
      generate: true
      textures:
      - block/crystal_block_2D.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles_material: PRISMARINE_BRICKS
          resource: # <-------
            generate: false
            model_path: block/crystal_block
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
 ```
