### ISSUE TITLE
[BUG - CRITICAL] With throwables and tools that apply effects

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#897]
**Describe the bug**

**To Reproduce**
1. Create a sword(or other item) that uses the "attack" event
```
    events:
      attack:
        target_potion_effect:
          type: WITHER
          duration: 80
          amplifier: 4
```
2. Create a throwable
3. Throw it at a player and then switch back to the sword before the throwable arrvies
4. Watch the opponent suffer from wither(or other effects)

**Expected behavior**
Better check if player really got hit by that tool

**Screenshots**
-

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: LabyMod 1.16.5
 - Plugin version: 2.3.7

**Additional context**
x
