### ISSUE TITLE
Events: actions Not Working | HATS --> EventWEAR 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#906]
i have a problem that i Can't use right_click events or WEar Event with behaviours hat 

**First try**
```
info:
  namespace: newhats
items:
  animal_ears:
    display_name: display-name-animal_ears
    permission: hats
    lore:
    - 'paintable'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: newhats/animal_ears
    behaviours:
      hat: true
    events:
        right_click:
             play_sound:
             name: itemsadder:item.shotgun.shot
```
 **second try** Also did not work
```
 info:
  namespace: newhats
items:
  animal_ears:
    display_name: display-name-animal_ears
    permission: hats
    lore:
    - 'paintable'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: newhats/animal_ears
    behaviours:
      hat: true
    events:
        wear:
             play_sound:
             name: itemsadder:item.shotgun.shot
              
```

**The third** Also did not work 🤔

```
  animal_ears:
    display_name: display-name-animal_ears
    permission: hats
    lore:
    - 'paintable'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: newhats/animal_ears
    behaviours:
      hat: true
    events:
      wear:
        interact:
          execute_commands:
            1_cmd:
              as_console: true
              command: 'playsound minecraft:block.iron_trapdoor.open neutral {player} ~ ~ ~ 10000000000 0.1'  
```

**Comment by LoneDev6** [comment]
events wear interact has no sense.
it's "wear"

anyway this indentation is totally wrong.. i suspect you're not using the items editor. https://ide.plugin.ga/itemsadder/
![immagine](https://user-images.githubusercontent.com/27242001/119357818-47333d00-bca8-11eb-9641-dfc8fef963b1.png)


here is a fixed version:
```yml
info:
  namespace: newhats
items:
  animal_ears:
    display_name: display-name-animal_ears
    permission: hats
    lore:
    - 'paintable'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: newhats/animal_ears
    behaviours:
      hat: true
    events:
      wear:
        play_sound:
          name: itemsadder:item.shotgun.shot
          volume: 1
          pitch: 1
```
