### ISSUE TITLE
[Suggestion] Add functionality!

### ISSUE THREAD

**Issue by TheKlimoT** [PluginBugs/Issues-ItemsAdder#910]
Add functionality, the sound of breaking the block, that is, in time for the very process of breaking the block.

```
sound:
  break:
    name: BLOCK_STONE_BREAK
    volume: 1
    pitch: 0.9
  place:
    name: BLOCK_STONE_PLACE
    volume: 1
    pitch: 0.9
  breaking:
    name: BLOCK_STONE_HIT
    volume: 1
    pitch: 0.9 
```
