### ISSUE TITLE
[BUG] Thirst bar disappear when the user sits

### ISSUE THREAD

**Issue by NessunoMC** [PluginBugs/Issues-ItemsAdder#946]
![image](https://user-images.githubusercontent.com/67857828/121571602-880ab000-ca23-11eb-864d-a1600d443a24.png)

**Comment by LoneDev6** [comment]
I just checked, it's working as intended.
Vehicles have health bar, thirst would overlap it.
When a player is on a vehicle it gets hidden because of this setting:
```yml
    show:
      auto: true
      creative: false
      underwater: false
      riding: false  # <---- this
```
