### ISSUE TITLE
[Suggestion] Add option to enable default minecraft craftings for specific items

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#950]
**Is your feature request related to a problem? Please describe.**
It's not related with a problem, only a feature that can be useful for leather armor based items.

**Describe the solution you'd like**
Add a config option to enable default vanilla crafting for specific ItemsAdder item, this would be useful to easily paint leather armor based items, like furnitures, if we can enable the default vanilla crafting, we're able to mix colors and etc for leather based items.

**Describe alternatives you've considered**
Maybe a config option like this:
```
  oak_chair:
    display_name: '&fOak chair'
    permission: furnitures
    resource:
      material: IRON_NUGGET
      generate: false
      model_path: furnitures/oak_chair
    behaviours:
      default_vanilla_crafting:            <--- This
       enable: true/false
      furniture:
        gravity: false
        small: true
        solid: false
      furniture_sit:
        sit_height: 0.5
```
Or like this
```
recipes:
  crafting_table:
    oak_chair:
      permission: furnitures
      enabled: true
      default_vanilla_crafting:            <--- This
        enable: true/false
        item: ia:oak_chair
```

**Additional context**
![image](https://user-images.githubusercontent.com/77519944/121802548-f067b600-cc0a-11eb-8290-da5185318a3f.png)
