### ISSUE TITLE
[BUG] Attributes, operators, specific_properties and lore replacement.

### ISSUE THREAD

**Issue by GuazP** [PluginBugs/Issues-ItemsAdder#962]
**Describe the bug**
There are few chained problems with attributes:
1. Armour with modifier for attackDamage have automatic flag `HIDE_ATTRIBUTES` and displaying lore like weapon, even if not there isn't main-hand affected, what obstruct other attributes, obstruct real slot when attackDamage is increased and increase attackDamage to incorrect value.
2. Specific property `bow` and `crossbow` for arrow_damage aren't working on armor like attribute does attackDamage work.
3. I didn't found anywhere in wiki if I can somehow decide which operator for attribute I want to use, might be a bug but doesn't seems so.
4. AttackDamage attribute doesn't seems to be fixxed from +1 to +2.

**To Reproduce**
1. Make following item:
```
  platinum_boots:
    display_name: :ks:&2Platinum Chausses
    permission: bcequipment
    resource:
      generate: true
    durability:
      max_custom_durability: 531
    specific_properties:
      crossbow:
        glow_arrows: false
        fire_arrows: false
        arrow_damage: 2 # it should be 2 times of normal damage? WebIDE says 1 is default value.
        multishot: false
        firework: false
      bow:
        glow_arrows: false
        fire_arrows: false
        arrow_damage: 50 # that wasn't affect bow damage either
      armor:
        slot: FEET
        color: cccccc
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        attackDamage: 0.5
        maxHealth: 1
        movementSpeed: 0.04
```
2. get it via itemsadder: /iagive <nick> <namespace>:platinum_boots
3. Hover over item to see invalid lore replacement.
4. Execute /iatag while holding item in hand to check attributes are there, and works correctly when worn on feet, but are automatically converted poorly.

**Expected behavior**
1. Only if attackDamage is specified to main-hand slot plugin should rewrite it with lore replacement. 
2. arrow_damage should work for every item in slot maintained by attributes like attackDamage.
3. Operator should be accessible, because for example, when you using movementSpeed, it creates not understandable description for player, where add_factor is a lot better written by default mc mechanics, and scale correctly either player walks or sprints:
With operation ADD, it won't scale correctly for sprinting.

Base movementSpeed is 0.1 and 0.15 when sprinting.
With ADD movementSpeed: 0.04 it will increase to 0.14 walking and 0.19 when sprinting.
Instead with ADD_FACTOR movementSpeed: 0.4 it will increase to 0.14 walking and 0.21 when sprinting, it's 40% speed increase instead of flat.
And it means much more for players, because most of them don't know how movementSpeed works. % are much cleaner for them then + 0.04 Speed

Additional benefit from ADD_FACTOR instead of MULTIPLY, because I belive many item creators isn't strong with math so far I realized, and order of execution overgrowing them. Then they would be confused why for example two items with +100% speed boost, giving player 400% basic speed.

But in the best case, operators for attributes should be managable.

4. That's self explaining from `Describe a bug` section.

I would expect/suggest form like:
```
  platinum_boots:
    display_name: :ks:&2Platinum Chausses
    permission: bcequipment
    resource:
      generate: true
    durability:
      max_custom_durability: 531
    specific_properties:
      armor:
        slot: FEET
        color: cccccc
    attribute_modifiers:
      feet:
        #Old form could stay, just extension gives possibility to more control, by default stay with 'ADD':
        armor: 3
        armorToughness: 3
        attackDamage: 0.5
        maxHealth: 1
        attackSpeed:
          value: 0.2
          operator: MULTIPLY
        movementSpeed: 
          value: 0.1
          operator: ADD_FACTOR
        #It could be some additional attribute if that will work as one, of course for bow/crossbow old handler is great because of additional options.
        IA_arrow_damage: 
          value: 0.4 #Which means +40% of base damage only when boots are worn on feets
          operator: ADD_FACTOR
```

**Screenshots**
![](https://cdn.discordapp.com/attachments/855219992065081405/855700589719191562/unknown.png)

**Info (please complete the following information):**
- Server version: Purpur
- Client doesn't matter.
- Plugin version: 2.3.9

**Additional context**
More additional explainations etc. at ticket: #armor-attributes

**Comment by LoneDev6** [comment]
Update the plugin when reporting problems

**Comment by GuazP** [comment]
Updated, bug: 
4. AttackDamage attribute doesn't seems to be fixxed from +1 to +2.
Is indeed fixxed, probably update was backwarded with rollup backup. Other ones still seems to persist.

**Comment by GuazP** [comment]
Bump

What about remaining bugs?

**Comment by LoneDev6** [comment]
As announced on Discord I was taking a break.


1. This is an ItemsAdder limitation.
config.yml has this option `fix-show-attack-and-damage-as-lore: true`, which makes ItemsAdder hide attributes and show "fake" ones using the item lore.
This option is used to make IA handle the attributes stuff manually adding a lore to the item not using vanilla behaviour, this was introduced to avoid showing a misleading counter for the attribute modifiers (removing base value).
IA wasn't coded to take into account the fact that someone would set `attackDamage` to an armor other than to weapons, so that's why you see "when in main hand".
What you can do is to set HIDE_ATTRIBUTES and write your own custom lore for that.
```yml
    item_flags:
    - HIDE_ATTRIBUTES
```
I may in the future take also this case into account but I'd need to add a lot of code to the plugin to handle all the different cases, so it's easier to write your own lore for that.

2. specific properties are.. specific for the item material itself, in this case for `bow` and `crossbow`. 
The `specific_properties` are referred to the material itself, you can't set a bow specific property to be applied to armors and to be taken into account ingame while holding a bow and wearing the armor, that's not how this feature is meant to be used.

3. There is no way to set a custom operator for attribute modifiers other than `0` (add), do you need this feature?

**Comment by GuazP** [comment]
1. Okay, that's fine by me. Isn't that just match which item attributes are set? I think simple handler to replace with lore only at main-hand slot would be simple solution :)

2. I see, understandable.

3. Generally like i said as example: operator ADD isn't scale correctly for changing attributes like movementSpeed or any other controlled by (for example - even if these shouldnt be used generally) datapacks which could set new base value for attribute.
 Keeping long story short, ADD 0.04 is equal to ADD_FACTOR 0.4 when player is not sprinting. But when player sprints, add will just give lower result, and Movement Speed + 0.04 is less understandable for players then: Movement Speed +40%.
 
 Same with equipment, minecraft balance is awful where enchants came to game, when someone have full protection enchantments and cap for both armor and armor toughness are both really low (30 and 20 but these values provide ridicolous protection itself) some +20% attack damage (for example, to scale armor to damage way instead) which is depend what you wield, could shorten fight a little, because so far now with high supply of golden apples it is nearly impossible to kill enemy which I want to prevent, to force players for more strategic playing when engage and when run for your life. Generally MULTIPLY operator in this case is a lot more handy then ADD operator.
 
 Despite these cases it's just lightweight and already coded way to customize equipment, not having such thing is just coming below vanilla customizability in matter of raw equipment power :)

**Comment by LoneDev6** [comment]
the `3th` feature request will be implemented in the next update. Old format will still be accepted as valid to avoid breaking old configurations.
![immagine](https://user-images.githubusercontent.com/27242001/123660435-f200c300-d833-11eb-8b0e-f1fbd7c90176.png)

**Comment by LoneDev6** [comment]
The next update will address your request.
Armors will accept attack damage/speed attribute and will correctly handle the lore replacement.
![image](https://user-images.githubusercontent.com/27242001/123962712-09fe5100-d9b2-11eb-87d9-aa6914a1e892.png)

```yml
  ruby_legs:
    display_name: display-name-ruby_legs
    permission: rubyarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 375
    specific_properties:
      armor:
        slot: legs
        color: ff0000
    attribute_modifiers:
      legs:
        armor: 5
        armorToughness: 1
        attackDamage: 8.0
        attackSpeed: 1.2
```
