### ISSUE TITLE
[Suggestion] Important missing feature - Override or turn off vanilla recipies.

### ISSUE THREAD

**Issue by GuazP** [PluginBugs/Issues-ItemsAdder#967]
**Is your feature request related to a problem? Please describe.**
I'm always terrible annoyed with minecraft balance when after iron (15 armor) comes diamond (20 armor + 8 armor toughness) and this generally turn upside down whole fluent balance between equipments, try to kill someone with diamond gear when you have iron and a lot more skills... Without enchantments, it's possible, but there is abyss between armours, where weapons go smoothly between iron and diamond...
Generally like with villager economy, Mojang didn't know what the hell they're doing, I belive no one of them are so much to math =,=

**Describe the solution you'd like**
I would like to have possibility, to disable such ugly items crafting and replace them with itemsAdder. Or just replace vanilla recipies with specific item.
Same when comes to smithing table.

Generally the most important for me is about armors, but I belive there are a lot more usages I didn't get idea yet.

**Describe alternatives you've considered**
Example how could it look:
```
    leather_boots:
      permission: example.exampleoverride
      enabled: true
      override_vanilla_recipe: true  <====
      pattern:
      - XXX
      - pXp
      - pXp
      ingredients:
        p: LEATHER
      result:
        item: example:leather_boots
        amount: 1
```

Or:
```
recipes:
  crafting_table:
    disabled_craftings:
      - IRON_INGOT:IRON_NUGGET
      - IRON_INGOT:IRON_BLOCK
      # - Item : from recipe with (optional if meant specific one, there are not so many of them)
```
or:
```
    air:
      permission: example.exampleoverride
      enabled: true
      override_vanilla_recipe: true  <====
      pattern:
      - XXX
      - pXp
      - pXp
      ingredients:
        p: LEATHER
      result:
        item: air
        amount: 1
```

**Additional context**

I am aware of scenario where villagers have these armors for sell and these armors unchanged could come to player from loot chests, but this could be future update? Not so important, because there are many ways to deal with it, like make own script to replace them (if someone is willing to, or just keep them as 'crafted by better armorsmith, whatever)

**Comment by ElMoha943** [comment]
+1

**Comment by LoneDev6** [comment]
This will be added in the next update, in config.yml

```yml
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      "DIAMOND_SWORD": true
      "IRON_INGOT": true
```
