### ISSUE TITLE
[Suggestion] Add a way to swivel seat on furniture

### ISSUE THREAD

**Issue by Wondaaaah** [PluginBugs/Issues-ItemsAdder#994]
**Is your feature request related to a problem? Please describe.** 
Yes, my request is related to a problem generated wehen I sit on a chair oriented to another direction different to north ([Screenshot](https://imgur.com/a/xNJeIU9)) (server v, 2.4.1)

**Describe the solution you'd like**
I'd like a correct sitting on the chairs directioned to another direction different to nord

Here is a screen of the error that I described: https://imgur.com/a/xNJeIU9

- Thanks, Wonder
P.s. I apologize if the format of the request is incorrect or does not conform to the template

**Comment by LoneDev6** [comment]
I sincerely don't understand the question, ItemsAdder makes the player sit corretly on the model orienting the player to make it face the front of the chair.
Example chair:
```yml
  computer_chair:
    display_name: display-name-computer_chair
    permission: computer_chair
    lore:
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/computer_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
```
