### ISSUE TITLE
font\default.json does not change

### ISSUE THREAD

**Issue by Johnnnn278** [PluginBugs/Issues-ItemsAdder#997]
When I want to change the default.json for its own parameters after restarting ItemsAdder replaces my settings with its own. 
![image](https://user-images.githubusercontent.com/29003149/124142110-9d0eb800-da92-11eb-8eb9-0f4ecfe5e99e.png)

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/cant-edit-minecraft-default-files

**Comment by Johnnnn278** [comment]
I did this a long time ago, but it didn't solve my problem

![image](https://user-images.githubusercontent.com/29003149/124151079-d8ad8000-da9a-11eb-8c2c-22a5cf918163.png)

**Comment by Johnnnn278** [comment]
> https://itemsadder.devs.beer/faq/cant-edit-minecraft-default-files

I did this a long time ago, but it didn't solve my problem

**Comment by LoneDev6** [comment]
I misunderstood.
You can't change the default.json file manually, this is to avoid confusion and conflicts with ItemsAdder font images feature.
If you want to use a custom font you can use these settings:
```yml
  custom-font:
    enabled: false
    name: "ipaexg.ttf"
    shift: "[0,0]"
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
```

If you want to use a PNG custom font you can just add the files in the folder `assets\minecraft\textures\font`
